#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 2023 个人总结
#+DATE: 2023-12-30 22:23:43

* 家庭

今年 5 份家里新添一员，很开心。看着他一点点的长大，是个很有趣的过程。有了孩子以后：一家人的心态变化挺大，有了一种真正意义上属于自己的家的感觉，也有了归属感；
还有一个感觉是当了父母才能明白，养大一个孩子有多不容易。另外，从怀孕、生娃、养娃对于女性的身体和心理上伤害都挺大的，母亲伟大。

有了孩子以后，除了快乐，也倍感身上的责任在变大。今年在杭州换租了房子、换了车，加上养娃，手头也不宽裕了。当然除了钱上的压力，对于小孩的教育也有一点忧虑，仅“以身作则”一项就不容易。

2024 年，要继续多花时间陪伴家人，做好自己。

* 工作

去年的12月5日加入字节，已经一年了，过程曲折，但真过的挺快。当前所在的团队，无论在做管理、做平台、做技术方方面面都于我这么多年的认知格格不入，
曾经总结的方法论在字节都不咋适用。所以我相当于从 0 开始。至于做的事情，更是刚毕业就可以干的一些 CURD 工作，一年几乎没有任何的成长。
一句话总结：我不喜欢这家公司的价值观和工作方法，也并不适合。如果放到几年前，我可能在在这家公司待不到试用期结束，但是在这样一个年龄段、所面临的家庭状况，
是不允许有更多的选择。所以坚持了下来。

尽管如此，不喜欢不代表不好好做事，在字节职责范围内的事，该做还是做了的，只不过不如前几年工作时候，那么的有开拓进取精神。

2024 年，积极的把该做的事情最好，如果没有很好的选择，就踏踏实实的干下去。

* 读书

微信读书统计一共阅读了 527 个小时，339 天。时长上至少有 1/3 的时间是听书（微信读书没做区分）。
每天平均阅读时间在 30-60 分钟（前半年少，后半年多）。在工作繁忙和带娃的双重时间积压下，每天能有一点自己的时间来看看书是不容易的，
我基本上放弃了一切电子化的娱乐手段（看剧，看直播），当然主要要感谢老婆大人承担了带娃的重任。

一共读完了 17 本书（多册算一本），大都是历史：

- 历史：
  1. [[https://book.douban.com/subject/35627881/][五代十国全史.Ⅳ,大唐末路]]
  2. [[https://book.douban.com/subject/35817714/][五代十国全史. Ⅴ, 后梁帝国]]
  3. [[https://book.douban.com/subject/4000908/][金瓯缺（全四册）]]
  4. [[https://book.douban.com/subject/36157153/][三国争霸（上、中、下）]]
  5. [[https://book.douban.com/subject/33443912/][细说宋朝：黎东方讲史之续]]
  6. [[https://book.douban.com/subject/35477048/][文治帝国：大宋300年的世运与人物]]
  7. [[https://book.douban.com/subject/34950734/][大宋国士·北宋卷]]
  8. [[https://book.douban.com/subject/34950735/][大宋国士·南宋卷]]
  9. [[https://book.douban.com/subject/27127895/][明朝那些事儿(增补版)(套装共9册)]]
  10. [[https://book.douban.com/subject/1463256/][大明王朝的七张面孔]]
  11. [[https://book.douban.com/subject/6533042/][南明史]]
  12. [[https://book.douban.com/subject/27028223/][永乐大帝]]
  13. [[https://book.douban.com/subject/26925171/][大明王朝1566]]
  14. [[https://book.douban.com/subject/4162705/][康熙大帝（全四册）]]
  15. [[https://book.douban.com/subject/1016595/][乾隆皇帝（全三册）]]
- 其他
  1. [[https://book.douban.com/subject/4124876/][易经的奥秘]]
  2. [[https://book.douban.com/subject/36328704][太白金星有点烦]]

从 2019 年下半年开始有了通读中国历史的计划，今年集中在五代十国、南北宋、明、清（未完成）。也没有读很细，每个朝代找了几本评价还不错书看看，能够把历史人物、事件串起来是第一阶段的目标。
经过四年多的坚持，终于在今年明显感觉到对于读书这件事，不需要再刻意的要求自己，已经养成了每天阅读的习惯。

在阅读中国历史的过程中，学到了很多知识，增长了一丢丢智慧，但大部分不成体系，我还不具备落成观点分享出来的能力。但对于怎么样去读历史书，有了一点感悟是：
“读历史不能以当代人的视角、旁观者的视角来看；而是要有代入感，假设你是某个历史人物，面对他当时的局势和困难，会说什么样的话，做什么样的事，做什么的判断。
这时就会特别佩服古人的智慧，读起来也就不枯燥了”。

另外，我读书一开始只读纸质书，觉得这样更有仪式感，更像是在读书。但是在快节奏的生活下，找个成块的时间看看书、喝喝茶不太现实。
于是 2022 年开始读电子书，午休前、睡觉前、高铁上等任何有空的时候都可以拿出阅读器看上十几二十分钟，尽管阅读质量比不上捧着纸质书看，但读总比不读要好，不知不觉就读了很读书。
今年开始尝试在上下班的时间用微信听书，听易经、道德经、菜根谭、史记，感觉也挺好的，更好的利用碎片化的时间，学一点是一点。也让我接触到了国学、儒释道，大开眼界。

总结下来，2023 年读书这一环节，收获颇丰，挺满意。2024 年阅读的主线依旧是中国历史：把清史、近代史、周读完以后，开始读中国通史。此外，继续用好碎片化听儒释道经典。

* 复盘

今年继续坚持一周一次的复盘，以及一天一次的打卡（坦白说，不是这种方式每天激励着自己，我恐怕在字节熬不了一年）。

有段时间很苦恼，感觉自己在同一个错误上一次又一次的犯错，所以觉得这么多年坚持复盘失去了意义，很沮丧。当时在听的菜根谭，结合自己的思考，让我想明白了几件事情：

1. 从小养成的性格，其中的缺陷不是一朝一夕才能改变的，可能需要 10 年或者更长的时间坚持需修正，才能解决掉（这不是我的观点，但是很有道理）；
2. 时刻告诉自己，我就是一个普通的不能再普通的人，不是天才、更不是圣人。因此，对自己要求不能太高，学会原谅自己；
3. 对于让自己变的越来越好这件事，要放长周期来看，要积极，要有信心；
4. 过程要比结果重要的多，过程中要积极的面对，坚持的去做。过程尽人事，结果听天命。

总结：不要过分纠结，要重视践行的过程。2024 也要这样。

* 历年总结

- [[file:../2023/2022-personal-review.org][2021-2022 个人总结]]
- [[file:../2021/2020-personal-review.org][2020 个人总结]]
- [[file:../2019/2017-2019-personal-review.org][2017-2019 个人总结]]
- [[file:../2019/2018-personal-review.org][2018 个人总结]]
- [[file:../2016/2016-personal-review.org][2016 个人总结]]
- [[file:../2016/2015-personal-review.org][2015 个人总结]]
- [[file:../2015/2014-personal-review.org][2014 个人总结]]
- [[file:../2014/2013-personal-review.org][2013 个人总结]]
