#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 在合肥-S9: 生活
#+DATE: 2016-12-19 00:00:00

看了一会视频，写了一会文档，又饿了！是的，又，而且突然特别想吃烤红薯。印象中，周边晚上有一个老大爷有的时候会卖红薯。那还想什么呢，下床，穿鞋，下楼觅食。

到楼下，有些懵逼，下雨了，没伞，家里也没有。

烤红薯肯定是没有了，但是我想试试。于是淋着雨兜了一圈，试图找回那么一丝丝的希望。结果很显然，不止没有烤红薯，一家有亮的商店、餐馆都没有了。

雨逐渐打湿了羽绒服，我走的急促了一些。不会有人像我一样会在这个点去买烤红薯，更不会有人像我一样在这个点去卖烤红薯。好像我面对的很多事情都是这样，明明知道不可能，但就是想试一试。大部分时候，我不喜欢做这些事产生的结果，但是会喜欢这尝试的过程。

找了一个雨淋不到的地方，让自己缓一缓。

停下来之后，再去观察这一条街道。和以前一样，一如既往的寂静，冷清，形色匆匆的人们。与平时不同的是，淅沥的雨点将这夜晚变的更加萧索。

如此夜晚，不继续走走简直就是浪费，我决定兜到小区的另外一侧去买点吃的，那里有个商店，关门一般比较晚。

我走的比平时更慢了，仔细的观察周边的建筑物，以及偶尔路过的一两个人，有的打伞、有的没打伞，这个时间点、又淋着雨，他们心里想必是苦的吧？还是为了快回到家而喜悦呢？那么孤身一人在外漂泊无家可言的人呢，他们是苦还是甜？我不知道。

终于到了小卖铺。我原本以为一个人都没有的地方，竟然有三个大汉在和老板娘调侃，我进去看看有什么可以吃的，尽管饿，但也不知道吃什么好。

上下打量了那个三个人才发现，这三个人喝多了，身材略显魁梧，看着装应该是某机关部门员工(有点像城管)，买了些喝的，不断的调侃老板娘，老板娘只能赔笑。

我有些反感，一反感喝多了的人，二则是对政府部门的人从来没有好印象。我不想靠近他们，就多看了看有什么东西可以吃。

没几分钟，三个人中有一个人就拖着另外两个人走了，可能他也觉得行为不太妥。

在挑吃的时候，我隐约听到了鼾声与小孩的哭泣声。他们走了时候，我善意的提醒老板娘小孩在哭。她回去看了看，对我一笑并表示感谢，笑意让我感觉到一丝温暖，又夹杂着一些凄凉。

我经常晚上回去他们家买吃的，应该是四口人的家庭，老板、老板娘、一个三四岁的小姑娘，还有一个老太太带孩子，估计是老板娘的母亲。老板和老板娘人非常和气，
这边只有这么一家商店，所以不下雨的时候，12 点或者凌晨也有人会去买东西，老板娘总是和和气气，不紧不慢的样子。

小孩醒了，一边哭一边从内堂里走了出来，老板娘柔声的安慰女儿让我非常感动。换位思考一下，这种天气，这种时间，碰到一些醉汉，家里还有小孩闹腾，我早就崩溃了。

我付了钱，离开了商店，与来的时候心思不同，陷入了深深的思考。

我想起了我的父母。07 年的时候，转学到陕西，我爸妈为了有个营生，就开了一个饭店。我记得很清楚，晚自习结束 10
点左右到家，有一帮人在喝酒抽烟在大声的嚷嚷，我妈已经睡了，我爸还有一个亲戚在陪着他们喝酒。不知道他们什么时候结束的，第二天早上烟头，酒瓶满地都是。
后来才知道，是有关部门的领导，不请客吃饭，饭店不好开。令我不解的是，我妈没有太多的抱怨，而且显得那么「理所应当」。

在我的印象中，我爸妈几乎很少抱怨社会、环境给他们带来的麻烦。很少抱怨工资的高低，住房条件，吃穿。他们只是尽力的去工作，赚钱，让生活变得比以前更好一些。
对于我，上了高中以后，他们也没怎么在学习上施加压力，上大学，毕业工作就不再关心我的挣的多少，只是偶尔会担心我的衣食住行。每当我跟我妈抱怨工作、工资的时候，她觉得够吃够花就行。

我有的时候琢磨，像我的父母他们这一代人，他们是否想过真正自由的生活：不必求别人，不必依赖国家政府，全凭本事赚钱，然后做一些自己喜欢做的事情。只是不断的适应社会所带来无可奈何，只是默默的忍受，然后逐渐的习惯，最后泰然处之。

是应该向他们一样习惯于面对现状，豁达的处理所遭遇的一切？还是应该像知识分子、伪文艺青年一样去指责，会愤怒，然后试图去改变一些东西？我不知道。

总之，这生活赋予我的，我仍旧难以明白。
