#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 在合肥-S5
#+DATE: 2016-01-30 00:00:00

明天离开合肥，年前（阴历）最后一篇「在合肥」了。10月初到合肥，4个月了，真快。昨天下午整理一下这几个月做的事情，顺便写了份 2016 TODOList。

整体来看，算是做了很多事情，可能比在北京一年时间接触的东西、写的代码都要多（不和上海比了，上海第一年也是做了很多事情）。
但是还有一些事情没做好，远没达到自己的期望，说到底还是心急、浮躁。

** 1

12 月下旬，我开始写「绝版青春」系列文章，当时信誓旦旦的说一天一篇，可是到一月份就断了，真不是我懒。

刚到合肥没多久，[[/blog/in-hefei-s2][日子难熬]]。我一直喜欢猫，就预定了一直小猫，怕一个人不好养，就怂恿武师傅也买了一只。有段时间我一直在知乎上搜各种养猫的攻略，12月底的时候，该准备的都准备好了。
期间去养猫姑娘哪里看猫，都觉得萌萌哒，爱不释手。还让热血的小伙伴们给起名，在微信群里热闹了两个小时左右。奶妈说，我火锅都吃完了，你们名字还没起完。

从厦门团建回来以后的一个下午把猫领回家了。开始一直躲着我，熟了以后一直跟着我打转。

第二天、第三天安好。

第四天回家我感觉他似乎很虚弱，怕是病了，就赶紧喊武师傅带我去宠物医院，医生说不行了。我那个时候虽然害怕，但是还存有希望，就把猫带回卖猫的地方。刚到没多久就死了。

期间不过两个小时时间，两个小时之前还能跑来跑去。

送去的路上，我不知道怎么就哭了，这可能是这几年第一次流泪，我以前说:「可以迷茫、可以彷徨，但是不可以绝望」。这次彻底绝望了，不知道到底发生了什么，不知道自己到底做错了什么。就觉得，这一年，怎么所有的事情都发生在了我身上。

以前看到一篇文章，那时候我还不明白: http://www.jianshu.com/p/f6b9307520be ，内容比较短，全文引用了:

#+BEGIN_QUOTE
*那个时候我还不明白*

  一九七六年，金庸的长子查传侠在美国自缢身亡。

  次年，金庸将十七年前连载完毕的《倚天屠龙记》重新修订，并补上了一段后记。在后记中有这样两句话：

  然而，张三丰见到张翠山自刎时的悲痛，谢逊听到张无忌死讯时的伤心，书中写得太也肤浅了，真实人生中不是这样的。

  因为那时候我还不明白。

  是啊，那时候我也不明白。.

  初中上学时最讨厌的事情莫过于看到「背诵」二字。需要背诵的课文中，朱自清的散文最是让我恨之入骨，一曰《荷塘月色》，二曰《背影》，一整段全是一小句一小句的白描，文字平白简素，毫无美感可言，当时看得我可是叫苦连天，心中暗想，不就是父亲到车站送别我上火车吗，何必絮絮叨叨地写出这么长的一番话。

  大学报到那天，父亲搬起我的行李，气喘吁吁地走在楼梯上。望着那一晃一晃的背影，脑海中又浮现出曾经死记硬背到滚瓜烂熟的那段话：

  我看见他戴着黑布小帽，穿着黑布大马褂，深青布棉袍，蹒跚地走到铁道边，慢慢探身下去，尚不大难。可是他穿过铁道，要爬上那边月台，就不容易了。他用两手攀着上面，两脚再向上缩；他肥胖的身子向左微倾，显出努力的样子。这时我看见他的背影，我的泪很快地流下来了。

  滚烫的眼泪划过脸颊。

  是啊，那时候我也不明白。

  念过太多太多的诗词，读过太多太多的故事，哪怕已经深深地刻在脑海中了，可依旧是不明白。

  不明白同叔为何要望尽天涯路，不明白稼轩为何会道天凉好个秋。

  不明白幽梦里相对无言唯有泪千行的思忆之痛，不明白僧庐下夜听细雨点滴到天明的黍离之悲。

  不明白项脊轩中亭亭如盖的枇杷树，不明白姑苏城外独对愁眠的渔火钟声。

  课本的注释写得再清晰，老师的讲解说得再透彻，也只懂得词中意，奈何悟不透话中情。

  是啊，年少之时，又怎么会懂丧子亡妻，怎么会懂国破家亡，怎么会懂人鬼殊途，怎么会懂名落孙山。

  直到某天，书中故事变成了人生，莫名的悲痛涌上心头，不能自已，才大彻大悟，醍醐灌顶，仿似大梦初醒。如梦幻泡影，如露亦如电。

  「是啊，那时候我还不明白。」

  可有些事，等你明白了，已经太晚。

  对不起。
#+END_QUOTE

我自责过自己怎么可以这么冷血。很多事情，别人都觉得感动的稀里哇啦的，我一点感觉都没有。原来，只是这是些事情没有发生自己的身上。

在之后的一段时间里，下班回去之后什么都不想干，感觉做什么事都没有意义，更别提写文章了。

我似乎总是这样一个人，经历的类似的事情，承受外部环境带来的、自身存在的各种问题，纠结着，思考着。走进阴影，走出（而不是逃避）阴影。

几年前生病痊愈之后，让我觉得生命很短，我要在有限的时间的做更多事情，工作也好，打游戏也罢，总之不能闲着。于是，我变得越来越急。
在合肥以后，我才逐渐的意识到太在意反而会适得其反，与其每天都琢磨着半年、一年、五年以后自己要做到什么程度，不如做好眼前应该做的事。*少说，少想，多做*。

** 2


在我写的东西里，有碎碎念，有吐槽，有偏激的观点，也有些可能是"负能量"。真实的东西，有些是美好的，更多的是"残酷的"。

我特别喜欢的两篇关于摇滚的文章中各有一句话送给大家:

#+BEGIN_QUOTE
*白日梦蓝 【豆瓣乐评摘抄】*

大白菜才是生活，燕京和青岛才是生活，京酱肉丝和拍黄瓜才是生活。没碴过架没飞过叶子没割过腕上过吊没退过学，这难道就不是青春了么？正视自己的青春吧，把拯救世界的任务还给超人，把启迪人类的任务交给艺术家，我们只不过是些忧郁青年而已。

*这是一个亡命徒死绝的时代，不知道这是不是谈中国摇滚*

曾经我想做个亡命徒，做个像他们一样的疯子，时间让我发现我们其实都是一样的俗人而已。早就剪短了头发，把专门磨破洞的牛仔裤扔进垃圾箱，人模狗样的穿着衬衫开始日复一日的上班，等死。

只有一件事，我们拒绝否认我们曾经的信仰，因为麻木的心灵最深处还有着一小块无比柔软的地方。这就是为什么我们会在小孩子们问"为什么王菲会和窦唯结婚啊他一点都不帅"
的时候露出无奈的笑容，为什么在穿水手衫的时候忍不住想系条红领巾，以及在看到苍老的张楚多年后再次站在台上唱"上帝保佑吃饱了饭的人民"的时候，会忍不住泪流满面。
#+END_QUOTE

也曾和杨溪在操场上哼唱着未卜乐队的：好 B 都让狗日了。

也曾听阴三儿唱的，老师您好：

#+BEGIN_QUOTE
  想让我尊重你 你得先学会尊重别人

  冤枉我的事我TM永远不能承认

  没收我的东西我TM都不要了

  跟别人都没事 我跟你只有仇恨
#+END_QUOTE

迷茫的时候，也曾唱着扭机的《理想的背后》：

#+BEGIN_QUOTE
  长久以来都是我一个人 怀揣着梦想走在街上

  我最喜欢的颜色是蓝色的 我天生是个忧郁的孩子

  一如既往的努力换回的只是那一如既往的扭曲

  我不愿再这样默默等待 也不愿再被这一切伤害

  明天将会怎样已不再重要 我在这虚幻中佯装疯狂
#+END_QUOTE

迷茫过后，也曾大声吼着：再见杰克，再见我的凯鲁亚克。

想要的回忆的时候，也曾唱的：

#+BEGIN_QUOTE
  我第一次恋爱在那里

  不知她现在怎么样

  我家门前的湖边

  这时谁还在流连
#+END_QUOTE

略感忧郁的时候，也曾唱着：

#+BEGIN_QUOTE
  时间过得飞快

  转眼这些已成回忆

  每天都有新的问题

  不知何时又会再忆起
#+END_QUOTE

···

面对那些可以装 B 的过往，面对那些反学校、反制度、反社会的愤青思想。如今还是一个人开心的编织着代码，按时上班下班，看个电影，听个音乐，打个 Dota。

看着那些傻逼们做着傻逼的事情，心里默默的骂一句傻逼，然后继续过自己的日子。

那你是不是不再"愤青"了？不再"事B"了？ 只是我逐渐选择不说了，我选择不浪费时间了。

** 3

写文章的人更像是剑客或者侠客，拥有一柄利剑，让看到的人会痛，会不爽，会反感；而不是一个谋略家，站在道德的制高点上，指点江山，摇旗呐喊，天朝从来不缺这样的"人才"。

最后，不要相信我说的，我只是在瞎扯淡。
