#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 在合肥-S4
#+DATE: 2015-12-22 00:00:00

人生中的很多事情，还没开始就已经结束了，不是缺少能力，而是缺少迈出第一步的勇气。

人们总是站在今天去想昨天为什么不那么做，而不去想明天要做什么。你说早知道现在这熊样，当初就不打酱油了；你说你有严重的拖延症，所以没有去做；你说我今天陪朋友了把一些事情耽搁了，明天一定去做；你说你不喜欢XX技术，所以这些问题不会，没弄好......
好像你总有不开始去做的理由。

在风行，我讨厌网络，所以即便是从一个搞 P2P
的公司出身，都从没认真的看过TCP/IP协议；

在江游，我讨厌数据库，所以即便对于服务器开发数据库是刚需。高数据分析，广宇说，试一下用一条
MySQL 语句做个表级联把结果搞出来，我说我讨厌 SQL，所以宁愿用 Python
多写几行代码，也不愿意稍微研究一下 SQL ；

常用 Linux，但一直都是双系统，从来不装虚拟机，是因为不想配置 WMware
网卡，尽管那个东西真的很简单；

......

发生在我身上的例子太多了，我总是在逃避自己讨厌和不擅长的东西，直到最后真的成了问题。于是，我几乎每天都在填以前的挖的坑，好在我现在已经不会向以前那样怨天尤人，因为所有的问题都是自己造成的，与人无关。

在江游听过一个老师的讲座，后来我逐渐想明白了一个道理：我们每个人，贫穷也好，富贵也罢，最后的终点都是一样，都要面对死亡。也可以想象成，每个人出生到死亡，要达到的高度是一样的，时间也是一样的，每过一天都画一个点。前面累的，爬快的，后面就可以轻松一点。别人花了10分力气去拼，而你只花了3分，你觉得自己天赋高，不需要那么努力，说不定还在心里骂别人傻。而事实通常是，当别人花
20
分的力气去做另外一件事情的时候，你确在弥补当时欠缺的7分。基本上就是这个道理。今天与昨天欠的，明天总会补回来的。

总会有人说，我不需要那样的生活方式，我志不在此，甚至说我家里有钱，我不需要那么拼。但是每个人都会
20岁，30岁，40岁，50岁，60岁......，你有想过在七八十岁的时候往回看自己的样子吗，你曾经想拥有的真的有那么重要吗？
到底什么才是重要的呢？

每个人都是孤独的，真正能陪伴到最后的只有你自己。所以，对自己好一点，活的开心一点（首先你得想明白什么是真正的开心）。

共勉。

张杰 2015/12/22
