#+SETUPFILE: ~/site/tpl/youth-tpl.org
#+TITLE: 在合肥-S6
#+DATE: 2016-03-27 00:00:00

周末两天，昨天打了一天游戏，今天写了一天代码。现在折腾一天，即便是工作也不再会有以前那种充实的感觉了，唯一的感觉就是累，特别累。上周本来应该是写这篇文章的，打了两天游戏，搁浅了，今天实在避不了了，就随便絮叨几句吧。
现在是晚上8:50，争取一个小时写完，洗澡睡觉。

--------------

最近翻了翻在12、13年写的文章，才发现写东西还有另外一个好处：「它可以准确的记录当时的你当时心境，不像回忆，它总是会自动筛选那些特别开心的日子，和曾经刺痛你的事情，时间再久一些，可能什么都不记得了」。之前在 博客停更，转做公众号 里说过:
并非每个技术人都应该有一个博客，但是每个技术人都应该写作。现在想想，可能每个人都应该适当的写一点东西，记录自己的过往。

上次在写 在西农-S13: WXYZ 之前，回忆以前的事情，整理素材，突然觉得好想哭，趴在桌子上哭了好久，再后来的几篇勉强写完了。我一直觉得自己是一个理性远大于感性的人，后来发现在生活和感情上，恰恰相反，感性的一塌糊涂。
从过年到现在上班一个半月左右，日子忽慢忽快。只是上班，没看书，没折腾新的东西，生活没有什么节奏，比较好的一点是晚上睡觉睡的早了，以前基本上不到 12 点不上床睡觉。现在九点半十点就躺床上睡觉了。

--------------

上周末的时候跟一个朋友聊一些技术相关的话题，扯到了「职业生涯规划」上。他问我说："你觉得工作的几年里，是在你的职业规划里吗？"。

我回想了一下，过去的几年里，我一直在各种完善自己的职业生涯规划，但是几乎没有一件事情是发生在意料之内的，更不可能符合职业生涯规划。只要你去折腾，未知远大于已知。

尽管这样，我依旧每个人应该有自己的职业生涯规划。

职业生涯规划是非常泛的一件事情，近到明后天，远到四五年以后或者更远，不是一两个小时坐着慢慢想就可以想的明白的，要不断的去更正完善，也是不断成长和了解自己的过程。
拿我来说吧，第一年，规划里全都是技术相关的，看书也只看纯技术相关的；第二年，规划里大部分都是技术相关的，看了很多技术周边的书；第三年，规划技术占的层面非常少了，更多的是要做什么样的事情，养成什么样的习惯。

总结下来，逐渐越贴近每一天的生活了，趋向于做事情的规划，而是不是技术和书，越来越模糊，给自己足够的空间，可实施性变的高了。对于一年、三年以后只是偶尔想想，不要求自己必须成为什么样，有个念想就好。
最近文章一些重复表达的一个观点，不管你多牛逼，有多崇高的理想，你还是要和普通人面临相同的问题，吃喝拉撒睡。对于未来，按着大方向努力就是了。

规划和理想是一样的，很有可能你永远都达不到，但是你要努力的去做。虽然我过去在发生的事情都在意料之外，但是到现在我很少像以前那样迷茫，至少今天睡觉之前知道明天睡醒之后自己应该干些什么。

--------------

我们公司有几款工具类的应用，之前大家时间都还充裕，在闲暇时间，我顺便做其他几款应用的服务器，还给公司搭了一个数据平台和放代码片段的网站。

从去年 10 月份到公司和肖峰、赵总一起做一款产品，两个月之后发了第一个版本，现在在线上已经跑了两个多月了，我一个人兼
Web前后端。随着业务的逐渐复杂化，技术上到还好，测试变的越来越难了。快速搭建产品原型，不像长线运营产品，前期不可能把精力投放在自动化测试这一块。
加上赵总和肖峰又要做开发，又要做管业务，管公司（创业公司真是把一个人当是十个人来用），所以公司决定招人，一个测试，一个iOS，一个Android。

在来七行之前没有面试别人的经历，前几周和肖峰一起面试了几个人。真的是不招不知道啊，小公司招人好难。一份 C 语言的笔试题，
我大二、大三的时候就可以做了，几个来面试的，没有一道题能完全做对，看的我心都碎了！也有毕业一两年的，我都不敢问，啥都不会。单从技术角度上讲，基础才是一个程序员的核心竞争力，会几门语言，几个框架，几个组件真的什么都不算的。

说了这么多，就想说明一点：我公司在招人......

喜欢折腾的，有全栈追求的可以来我公司试试，小公司比大公司爽太多了，能够真正把精力放在做事上。

--------------

我从去年年底的时候开始写「回首」，虽然代码量不大，但是值得思考的东西还是挺多的。今年来了之后一直忙着项目开发，导致回首的开发节奏很慢，只能放到周末来写。
这几天闲了下来，写了几天代码，把 UI 换了一层皮，预计在四月初，能够出第一个正式版本，到时候欢迎大家测试使用。

下周末应该会更新一篇短文章，写一写自己从单纯喜欢技术到现在喜欢产品的转变过程，敬请期待吧。
