#+SETUPFILE: ~/site/tpl/youth-tpl.org
#+TITLE: 在合肥-S11: 聊聊
#+DATE: 2017-06-18 00:00:00

最近从得到上看到一句话：「业余人士才讲灵感，我们专业人士只是每天早上准时开始干活」，基于过往的一些经历，让我非常的认可。

年前看了村上春树新书的《我的职业是小说家》，有一段是讲他小说是怎么写出来的：每天都会在固定的时间，写固定的页数，完全量化的来实现一本小说的撰写。这让我非常的诧异，因为在我的想象中，像写小说这种创造性的行为，都是非常需要「灵感」，在某天某时因为某件某个事件触动下，突然文思如泉，抑制不住的文字从笔尖流淌出来，于是便成了小说或者其它艺术品。

看完这篇文章之后，我才知道原来创造的过程也是机械式，即便是像村上君这样的小说家也只不过是每天像工作一样，逼着自己去写固定限制的文章，他与常人的区别只是他坚持了
30 年之久。

之所以有那样的误区，因为我在 15
年之后的文章都是靠着「灵感」写出来的，写文章一度成为我「打发时间」和「倾诉」的途径。《在西农》系列只不过是为了打发难熬的时光，而现在写的《在合肥》系列大多都是伴随着很重的倾诉情绪，或者失眠或者工作、生活不顺利。所以我的文章更新非常不固定，更为重要的是，我自己几乎不会回看自己非技术类的文章，不喜欢，甚至不喜欢到了每次写完发表之后就有删掉的冲动。这是一种扭曲的心里状态，原本我以为只有自己是这样的。几年前，从我的一个大学同学
Youmengbo 的 QQ
空间中看到他写的东西，他自己也坦言自己不喜欢自己写的东西，有种希望更多人的看到、但是又心里上又不希望别人看到而删除的纠结心里。

毕业之后，我一个人来到大城市生活，谈不上辛苦，但是总有莫名的孤独。起初在北京生活给我最大的感触是：当你一个人坐在公交车上望着窗外，你会发现外面这么多人，这么繁华，但却和你无关，你不属于这里。再之后，我遇到了更多的人，才发现我并不是一个个体。这个社会给年轻人太多的压力，又或者说一个学校教会了太多无用的东西，让你难以面对社会的种种。以至于步入社会之后，一旦开始了个体生活，有太多的感触没有一个正常的渠道可以表达和发泄。

目前来讲，写文章对我越来越难了。写东西写了快七八年了吧，最初是为了技术积累，后来为了让写作成为一项技能，再后来就是粗糙的观念输出了。把一件事情准确的用文字表达出来这项技能，在两三年前对我都已经不是问题了，而工作之后，锻炼的机会也非常多。像之前一样「倾诉」式的文章，不能说是不对的，至少是不好的，负能量比正能量更容易得到共鸣，所以我不再会写这样的文章。

我偶尔会思考这样一个问题：自己要成为一个什么样性格的人。在写上篇文章的时候，我遇到了一个姑娘，现在是我女朋友，发展算是很快很顺利了，可能是缘分吧。但在之后的相处过程中遇到了一些问题，让我再次思考「我要成为一个什么样性格的人」。凡事得过且过，还是要在一些问题上讲讲道理、较较真？是要做一个性格随和的人（随和意味着你要忍受时间上的极度浪费），还是成为一个高效的人？

有一点是可以确定的，我不自觉的养成一个随意表达负面情绪的习惯，其实我只是习惯了把负面的东西发泄出去，然后很正面的去面对问题。时间长了自己感觉不到这个问题，在公司也觉得无所谓，我只需要做好自己该做的事情就行了。但是有个角色我并没有转变过来，我把自己定位成一个按着想法做事的「软件工程师」，公司的其它员工可能会把我当成一个工作经验丰富的工程师，不懂技术的人会把我当成万能的技术的大神，而对于新人来讲，我可能是一个公司「元老级的人物」。不自觉我可能成了公司某种角色的代表，所以如果我随意的表达消极的东西，换位思考一下，可想而知。这是我最近一个月才开始思考的问题，已经在改了。

人到了一定阶段之后，一些曾经执着的问题，就失去了再执着的意义。

--------------

6月14号的时候，磊磊写了一篇流水式的文章《黄山行》，之后私聊表示写文章不易，balabala
。当时我一时冲动就夸下海口，以后大家一周写一篇文章，谁不完成任务，发 100
红包。大家信誓旦旦的表示如果对方没问题自己也没问题，可以想像磊神在杭州雄赳赳气昂昂的立下重誓。但是我觉得不够刺激，就把
Tanky 拉到群里，因为以我对 Tanky 的了解，就他的拖延症，100 块是稳收了。

剩下的是就是我和磊磊一顿言辞激励，「逼迫」Tanky
收下战帖，然后稳赚红包，一切都在计划中。

第一周的周末，也就是今天，我实在是不想写文章。就偷偷的私聊磊磊，要不不玩了吧。从磊神扭捏的言辞中，我觉得欧了，磊磊也不想写！这特么要赶上磊磊自己写了，其它人没写，还不上天了？！

可是万万没想到，就在今晚的九点零三分，Tanky
发布了文章，重要的是他还分享到群里，说出了「本周任务完成，敢不敢说到做到」，这特么就很尴尬了啊！虽然写的挫吧，但真的是文章啊~

逼的我我赶紧跑到公司，临时「构思」，然后就有了现在的这篇文章，从来没有感觉写文章是这么难啊！

--------------

既然有了开始，以后就一周一篇吧，后面看看写个什么系列或者专题什么的。如果大家有好的建议，可以以回复的形式发给我~

「业余人士才讲灵感，我们专业人士只是每天早上准时开始干活！」，持之以恒的去做事，各位共勉。
