#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 在西农-S9：摇滚（1）

上大学、工作以后遇到很多人，我会把遇到的人进行分类。对我来讲，最重要的两类是：兄弟和朋友。我觉得他们的区别在于，兄弟是没有距离的，朋友是有一些距离的。举个例子，当你让他们帮忙做事情的的时候，他们都会尽力帮你。
当遇到不愿意的时候，兄弟会一边骂你，一边帮你，朋友会可能不会说出来；兄弟就是你在任何时候都愿意去打扰的人，而朋友你要顾及他的感受与生活。杨溪、峰子属于前者，邬明、X、胖子、张超等属于后者。

我交朋友的唯一的准则是：坦诚。脾气好坏，个性与否都不重要。我最讨厌人前一套、背后一套的人，我也不会做这种事情。比如吴磊吧，我们在群里，动不动就怼起来了，怼的不可开交，这时候得靠 Tanky 出来逗B一下缓解尴尬的氛围。
不过，我在背后还是经常拿吴磊出来吹牛逼的：「我认识一个朋友，多年运维经验，在运维、系统、工具方面，屌！学习和动手能力，强！前两天我 xxx 问题搞不定，人家分分钟就搞定了······」。
以前经常跟广宇吹：「磊磊在文档化方面做的还是很好的，你看楼上的运维文档，基本上都靠他做起来的······江游的服务器集群，他搭的······上次我的服务器也是被他删的······」。我相信他也是这样的人。有的时候你会发现，替朋友吹牛逼的感觉比给自己吹牛逼还要舒坦。

在我的很多文章中，都会出现杨溪这样一个人。还别说，杨溪和 Tanky 虽然性格上差距很大（他们相互不认识的），但是在有些方面真的很像，比如他们都是很重感情的人，他们是都是存在感爆棚的人（如果可以出现在别人的文章里，可以得到别人的夸奖，开心的屁颠屁颠的）。

前面写了 10 篇了，一直没开始都没开始写摇滚，主要是我没想明白怎么写，好像这个摇滚这个概念以及它所表达的含义，已经深深的印入我的生活中，无法用言词表达。我写技术方面的文章，感觉总有的写，大多数时候写着写着就刹不住车了，
因为它是在明面上的东西，我写出来愿意看的人就能看明白。反过来，写音乐、生活方面的文章，总是写完了擦，每次都抑制不住自己心里的悸动开始写，写到一半又删了。

这次还是一样的，我不知道自己会写出几篇、也不知道会写成什么样，随便写写吧。所有的故事都有一个开始，关于摇滚，杨溪就是开始。

-----

#+begin_quote
我好像是一个从很小开始就会想很多的人。

记忆中从起码初中起最常就会躺在床上想的事就是，宇宙好大，而我们又是渺小，这种对比，反差，令我感觉非常可怕，非常恐惧。还有人会死，我死了，这个世界上的所有事都不知道了，好可怕。
这可能注定了我一直都不会是一个很天真，很开心的人。高中时开始，我爸妈就会常说人家孩子都看起来青春阳光的，你怎么天天都是愁眉苦脸，唉声叹气。

其实我从高中开始就有了彷徨、迷茫的感觉，感觉很少有东西能刺激到我，能我打起精神，提起兴趣。那时候每天我会听很多许巍的歌，那时候的许巍，每首歌好像都会击进我的内心的最深处，我能感觉到一种完全的沉浸感，听着许巍的歌，会哭，会笑，会轻盈，会沉重。

我记忆中最深的是，在高考之后，要填志愿，我跟我爸发生了很大的争执，不是因为报什么志愿，而是估分，他让我仔细的再估几遍然后综合一下，而我觉得我已经估过了，不需要在估，可能看起来不算什么事，但是在我们家，在当时的环境下，我们吵得不可开交。

于是，我选择出去走走，我下了楼，感觉自己就是个行尸走肉，呆呆的走，呆呆的看着周围的景象，但是脑子没有任何感觉，没有任何想法，没有任何人可以交流，非常孤独，非常痛苦。

我想起了我的秋天，我唱着我的秋天，流着泪孤独的走在大街上：

那些无助的夜

我漫无目的地走

那些无助的夜

你牵着我的手

幸福如此遥远

我无法看见
#+end_quote

在大一第一次全班聚会的时候，杨溪唱的就是这首歌：许巍的《我的秋天》，他唱的很认真，但是我没听懂（估计没人能听懂）。

「用我长长的头发，遮住我迷茫的双眼」，这句话用来形容杨溪再合适不过，那个时候还有一把木吉他。你可能觉得：卧槽，这不是一个典型的文艺范么，你错了，他不是文艺，而是抑郁。
大一一年里，他都是孤独的，除了自己本身的压抑的性格原因；还有一个原因是：上大学他就是有女朋友的，他不是一个人，这样他离班级这个群体的的距离就更远了。

大一的时候，我很讨厌三个人：杨溪、邬明、X（跟我正确发音：「叉」）。

杨溪，他总是唉声叹气，无论是上自习、吃饭还是上课······，总是会把氛围带的无比压抑；呜明呢，他对所有事情的态度都是一样的：无所谓，表现的特别彻底；X呢，因为他X啊。（然而，世事无常，造化弄人······ 最让我讨厌的几个人却给了我大学生生活中最多的记忆。）

前面文章说过，我大一下学期的时候谈恋爱了，也不是一个人了，也快被宿舍孤立了。大二课比较多，食堂饭基本上抢不到什么好的了。中午，我和 zq 就经常东门吃饭，经常能碰到杨溪他们两个。
一个班的同学，也没多大仇多大怨，年轻人，反正经常能碰到一起，下课一起过去吃完一起走回去。

就这样，吃着吃着，四个人就熟悉了。印象中，后面还是接着吃······过个节啦，过生日啦，周六日啦，今天开心啦，今天不开心啦······ 大学里大家手头都没什么钱，四个人下馆子两个人要划算的多，所以动不动就出去炒个菜，吃个火锅什么的。

大学生活真的很简单，可以做的事情就那么多，朋友感情也就是这么那么来的。我和呜明和 X 的感情是打篮球、扯淡、吃饭喝啤酒搞出来的，和峰子胖子他们是打游戏、扯淡、吃饭喝啤酒搞出来的。和杨溪就单纯的很多，一起听歌聊音乐。
我们一起讨论摇滚，分享摇滚，一起愤青，一起摇，一起吼。

我的听歌经历基本上可以分为下面几个阶段：

1. 流行
2. 轻度国内摇滚
3. 重度国内摇滚（90年代的中国摇滚）
4. 地下摇滚
5. 国外摇滚
6. 国内小众音乐
7. 后摇，纯音

这两年基本上都是什么好听听什么。不再标榜自己是一个听摇滚的怎么怎么样的，有人可能觉得不愤青了、不摇滚了，我恰好以为这才是真摇滚。要说真正偏执和痴迷的摇滚的阶段应该是从 11 年到 13 年这三年的时间，听的特别多，各式各样的摇滚都听，研究摇滚风格和摇滚文化。

** 启蒙

「没有什么能够阻挡 ，你对自由的向往 。天马行空的生涯，你的心了无牵挂」。

在军训的时候为这个班带来了许巍，而我也仅仅知道蓝莲花。后来大家都开始蓝莲花了，杨溪似乎对蓝莲花有了抵触感。后来他跟我讲，许巍有很多好听的歌，我并没有在意。

直到某个秋天的傍晚，夕阳西下，晚霞烧红了整个西边的天空，我们走在从小东门通往西区宿舍的路上，杨溪突然唱了几句：

「天边夕阳再次映上我的脸庞 ，再次映着我那不安的心 ，这是什么地方依然是如此的荒凉 ，那无尽的旅程如此漫长」。

此情此景，伴随着沧桑的歌声，以及每个人对未来的悸动与迷茫。突然间，我被触动到了，决定去听一听许巍。也有可能我也要这种装深沉，装 B 的感觉。

听了之后，许巍的音乐有两个方面让我深深折服，并且欲罢不能。

一个原因是电吉他、木吉他前奏，架子鼓，不信你可以听一下：

+ 吉他前奏代表歌曲：故乡、漫步、像风一样自由、彩虹、旅行、完美生活、礼物
+ 架子鼓前奏代表歌曲：闪亮的瞬间、浮躁、今夜、我的秋天（从头到尾的 deng,deng,da,da,deng,deng da 鼓点）

另一个原因是歌词：

+ 曾梦想仗剑走天涯，看一看世界的繁华，年少的心总有些轻狂，如今你四海为家。—— 《曾经的你》
+ 青春的岁月，我们身不由己。只因这胸中，燃烧的梦想 ——《完美生活》
+ 谁画出这天地，又画下我和你，让我们的世界绚丽多彩。谁让我们哭泣，又给我们惊喜，让我们就这样相爱相遇。总是要说再见，相聚又分离，总是走在漫长的路上。——《旅行》
+ 走不完的路，望不尽的天涯。在燃烧的岁月，是漫长的等待。当心中的欢乐，在一瞬间开启。我想拥你在身边，与你一起分享。——《礼物》
+ 我不停的弹着不停的唱着，直到所有的弦都断了。我不停的弹着不停的唱着，直到所有的力量尽了。有一种力量有一种力量，依然在我心中流淌。——《浮躁》
+ 过去没有开始，未来没有终点。这是希望的旅程，是谁在风中奔跑。自由穿行梦想，向着幸福的远方。——《风行》
+ 我给你自由，记忆的长久。我给你所有，但不能停留。我像风一样自由。——《像风一样自由》
+ ······

我曾经想过用「时间已过去多少年，如今的你们在哪里。经历着什么样的故事，什么样的幸福伤痛。今天我依然还能够感到，那理想飞扬在春天里。——《少年》」 用来作为在西农的结尾（我第一次向 GF 发短信隐式表白用的是：「很多事来不及思考，就这样自然发生了」。
也不知道她当时懂了没······。擦，原来我以前就这么文艺）。

对于杨溪、对于我，换个阶段，早几年或者晚几年再听到许巍，可能就不会有这么喜欢了。

大二的时候，我受峰子和胖子的影响开始看古龙的小说，后来古龙的小说基本上都被我看遍了。能突然对许巍有感觉，和当时看古龙小说有很大的关系。古龙小说的主人公，总是在流浪、总有自己兄弟朋友、总是嗜酒如命。
有的人很颓废，比如李寻欢；有的人很隐忍压抑，比如傅红雪；有的人执拗，比如阿飞；有的人很洒脱不羁，比如叶开······ 但是都有一个共性，就是他们眸子很亮（眸子意味着希望）。这和许巍的歌词表达的东西是一样，这是他们教会我的：

*可以流浪、可以迷茫、可以彷徨，但任何时候从不放弃希望。*

张杰

2015/12/24
