#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 在西农-S12：陈东坡

前面文章说，这些年，我所遇到的人中佩服的人有两个: TankyWoo 和 陈东坡。Tanky 的事前面已经写过很多了，在以后的文章中也会出现很多次，就不单独写篇文章了。

有一次和郑媛聊天，我说你的戏份比较少，她说：「没事，你才是主角」。其实在时间面前，我们都是配角。

在「在西农」这一系列的文章中，我打算只写事，谈谈自己的经历，以及看法，顺便写写这些朋友们。陈东坡是个例外，与我相关的事不多也不多，但是很值得单独写篇文章。我非常不擅长写人，写的不好，见谅。

----

** 0

陈东坡。

确切来讲，我们不算同学，没一起做过事，聊的也不多。

但是他是我的朋友，老朋友。

做事务实、生活简单、说话耐人寻味。

** 1

大一入学，同学们都心高气傲，但是出彩的总是那几个人。一些人因能歌善舞而出彩，比如小宝；一些人因孤单压抑而出彩，比如杨溪；一些人因身宽体胖而出彩，比如二班的 XXX ；一些人因高调行事而出彩，比如陈东坡。

他是我们班的班长，他是最早和辅导员搞好关系的人，也是最早和学生会混熟的人。

他是在学校不允许带电脑的情况下，班里第一个带电脑的人，也是第一个跟着蔡老师混的人（前面的文章里讲过，他是最早开始「写代码」的一批人）。

他在开学的几月时间里只有一个被子，没有褥子。光板床睡了近半个学期，一个爷们儿。

他给很多人的第一印象是「强势」。我不喜欢行事高调的人，所以，我不喜欢他。

** 2

我大一的时候是生活委员，他是班长，我也在学生会混过一段时间。可能是「工作」上的交集，不知道什么时候，我们逐渐成了朋友。

学校举办辩论赛，一个班必须出一个队伍，陈东坡、cy、ly 和我四人一队参加了学院的辩论赛。

时至今日，我依旧觉得我非常不适合「
一对多」的沟通。东坡不然，很多人开始佩服东坡是辩论赛，我也是。从学院开始到学校，十几场辩论赛，一路高歌猛进，几乎场场都是最佳辩手。一个理科学生，文学功底深厚，尤其在历史方面，更是望尘莫及。

** 3

大二，他要退学。父母、老师纷纷表示不理解并进行阻拦，几方协商之下，由退学改成了休学一年。临走之前，聊了几句，他说「学校不适合我」，我也没说什么反对或者不理解的话（这几年，我对大学教育的厌恶从未改变过）。

我们总是谈着说走就走，但是有的人真的走了。对于休学，很多人都投以羡慕、崇拜的眼神。而我却明白，对于他这个决定是艰难的，而为这个决定付出的势必是更难的。

有句话说：「生命中曾经有过的灿烂，原来终究，都需要寂寞来偿还」。除了大自然以外，所有看起来美好的东西，背后都需要付出更多，从无例外。

** 4

大三的暑假快结束的时候，东坡回来了。我说你回来我请你吃饭，他说不用好的，一碗面条就好。结果，我在小东门请他吃了一碗面条。

回来之后，由同班同学变成了学弟，哈哈。我大学四年暑假都没回去，他暑假住在我宿舍。

我偶尔看看东西，大部分时间都在打游戏，他白天在蔡老师办公室，晚上回来折腾。他偶尔也打游戏，看电影，有几天时间他都在尝试各种 Linux 发行版，所以天天都在装系统。

我晚上2点睡，他比我睡的更晚，早上六七点就不见人了，总是这样。我根本想象不到一个人每天睡四五个小时，白天居然可以保持 12 分的精神。

大三上学期，我的团队参加软件设计大赛，他也参加了。在上台演讲的时候，我发现了他变了，讲话变的磕磕绊绊，完全没有当年最佳辩手的风采。是他厌恶这种比赛的形式，还是别的什么原因，我不确定。但是有一点我确定是，他这一年出去一定经历了很多事情。

大三的事情突然变的多了起来，当我再次想起他的时候，在 QQ 上找他，他说他已经离开学校了，这次是退学。理由是: 「学校还是不适合我」。

** 5

13 年初我在风行正式上班（在北京），通过几次电话。

第一次电话，问了问近况，他说在一家小公司，那个时候他应该已经工作 2年+ 了。

第二次通话，说他在咖啡厅遇到美团的一个主管聊了聊感觉还好，但是他觉得现在的公司发展的不错，不愿意离职。

通话第二天，他跟我说，他已经在美团上班了。

** 6

15 年入夏，天已经很热了。

他说他要来上海工作了，我说来吧，来了先住我这里。我没问公司，没有问缘由，我不是多嘴的人，别人不说的我永远不会问。

在我那里住了一周左右吧。我说你女朋友呢？他说他马上都要当爹了。我说还是以前那个（女朋友）吗？他说早就不是了。

再之后，他朋友圈晒娃，我点赞。

** 未结束的结束

他是我见过的人中执行力最强的一个人。

看他的朋友圈就会发现，他对很多产品理解都很「原始」，一针见血。

他务实，「低头做事，莫问前程」。

他热爱生活，吃一碗面条，可以写一首诗，偶尔还赏自己一根棒棒糖吃。

前路艰辛但势必美好，深蓝色的梦想，祝好。

张杰

2015/01/13
