#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 在西农-S4: 胖子的音乐

#+begin_quote
时来运到 天下无敌 天生有种总有用 无论场地软硬 长与短途 同样向前冲 -- 郑中基《有种》
#+end_quote

这首歌是建国的手机铃声，宿舍几个被听了四年，现在前奏响起来的时候，恍若当年，总有要站起来战斗的欲望。08、09年的时候，大部分人拿的都是非智能机，建国的 诺基亚N81 算的上是高端机了，声音洪亮，且无杂音。所以大一上学期的时候，我基本上都是听建国的音乐过来的。

_属于大一的的音乐_

在 建国 的个人档案里我说 建国 对音乐的追求还是蛮高的，那是我最近几年的的感觉。当时可没觉得，反正没的听就瞎听呗，等到后来我逐渐接触地下乐队的时候还鄙视他听的"主流"音乐呢。

昨天整理大学时候听的音乐的时候，才发现建国听的很多音乐都是值得听一辈子的，都是经典。在前面说过，我曾经做个中国摇滚编年史，详细介绍 90年代中国的摇滚乐与摇滚人，但是能听和能品的差距太大了，我尽量在不影响文章主线的情况下穿插一些。
下面列一下我和建国能回忆到的一些歌手（乐队）和歌曲，我已经整理成网易云专辑，附在最后，以后文章中出现的所有音乐我都会整理成专辑。

国外歌手（乐队）：

+ 邦乔维（Bon Jovi），美国老牌摇滚乐队。歌曲：It's My Life, You Give Love  a Bad Name, Have A Nice Day
+ 枪花（Guns N’ Roses），美国老牌乐队。歌曲：Don't Cry, Knockin' On Heaven's Door，Sweet Child O' Mine（超喜欢这首歌的前奏），Civil War
+ 披头士（The Beatles），不解释，要是没听过这个乐队，去面壁。歌曲：Hey Jude，Let It Be，Yesterday
+ 皇后（Queen），英国摇滚乐乐队。歌曲：We will Rock U,
+ 迈克尔·杰克逊（Michael Jackson），不解释。歌曲：You Are Not Alone， Beat It
+ 迈克尔·波顿（Michael Bolton），性感的老男人，成熟的声音。歌曲：When a Man Loves a Women。这个是建国补的，我听的比较少。现在去听他的声音，感觉太有味道了。
+ 老鹰乐队（Eagles）。歌曲：Hotel California
+ 威猛乐队（Wham!） 。我听的比较少，就不推荐了。
+ 滚石（The Rolling Stones）。我听的比较少，就不推荐了。
+ 西城男孩（Westlife）。歌曲：You Raise Me Up，Seasons In The Sun（我更喜欢Nirvana的版本），My Love
+ 后街男孩（Backstreet Boys），高中听的比较多吧。歌曲：As Long as You Love Me（听烂了，不喜欢听），I Want It That Way，Show Me the Meaning of Being Lonely，Everybody（胖子……，你还记得这首歌吗，Everybody呀~yeah~ 我也是听醉了）

国内歌手（乐队）：

+ 谭咏麟 歌曲：讲不出再见，一生中最爱，朋友 （这三首歌堪称经典），爱情陷阱 （忘了是那个演唱会的Live版，吵的我都骂人了）
+ 郑中基 歌曲：无赖（最爱），英雄寞，有种
+ 张宇 这几个人里面我做喜欢张宇了，自私一点，按照我喜欢的歌排序：一言难尽，心术，曲终人散，男人的好，给你们，趁早，单恋一枝花和大女人并列，走样……
+ 王杰 歌曲：谁明浪子心，安妮，伤心1999（万万没想到，多年以后，这居然成了峰子在KTV的必点之歌）
+ 伍佰 歌曲：白鸽（前奏想起来的时候，这首歌唱不唱都不重要了），泪桥，浪人情歌
+ 范玮琪 歌曲：最初的梦想，是非题，黑白配

https://music.163.com/#/playlist?id=140886935


建国比较喜欢谭咏麟和郑中基，他曾经信誓旦旦的说，将来一定要把 “一生中最爱” 这首歌唱给他老婆听。如今建国结婚了，如果小丹看到这篇文章，记得让他唱啊~！

----------------

一听歌就不太想写东西了，这期故事就不讲了，我们来聊点别的吧。

这一系列的文章我本来不打算发公众号的，只想发到博客，一个人偷偷的写，这一系列的文章的受众一是自己，另外就是大学的朋友们。但是喜欢公众号这种连载方式也好，自己有那么一点虚荣心也好，最终还是同步到了公众号了。

公众号的朋友（粉丝）大多都是从技术博客过来的，所以我再次要给大家道个歉，这里暂时不会发任何技术相关的东西，并且这个系列既然连载了就会一直连载下去，去留自便吧~

算上这篇的话，一共发了五篇了，本意是一天写两个小时，一天更新一篇，能写多少算多少。等实施的时候才发现 2 个小时真的太短了，每天至少需要 3个小时+ 的时间，今天我从晚上8点左右开始写的，这篇文章其实什么都没写，只是整理了一些音乐，等写完差不多 11 点半。
前几天有点事，开始写的晚，基本上都是凌晨才开始准备睡觉，还真是挺累的。

但是，让我没有想到的是，我得到了很多朋友的授权和支持。杨溪、郑媛自然不用说，他们从来都是支持我的。当我找建国的时候，建国二话不说关注了我的公众号，还说要素材灵感啥的直接找他。
当我找呜明的时候，他在出差，说没问题，随便写。连一向高冷的峰子，也表示可以写…… 。今天，问了一下陈东坡，得到了陈东坡的授权，可以写他的故事。说实在的，他们感动到我了，毕竟这是我个人的事。

后面的更新还是一天一篇，每天晚上 11 点左右，公众号评论要拿到原创资格，所以暂时不能评论。要评论的话，可以点击原文链接，跳转到我的博客。

如果有建议，或者有那些想听的，可以在公众号后台直接回复。

张杰

2015/12/17
