#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 在西农-S2：宿舍

#+begin_quote
没有什么能够阻挡 ，你对自由的向往，天马星空的生涯，我的心了无牵挂  ——许巍《蓝莲花》
#+end_quote

/杨溪（暂且不管杨溪是谁）说，这些人真他妈烦，一说许巍就一定会说蓝莲花，许巍还有那么多好听的歌呢。我也烦，不过作为真正意义上的开篇，放蓝莲花再好不过了。/

下大巴以后，一路按照「新手引导」办完各种手续顺利到达宿舍。

敲门以后，一个胖胖的少年开门。

“你好，我叫孙建国（建国，是我在西农的第一个朋友）。”

面对如此成熟客套的打招呼的方式，我有些不知所措（毕竟，村里人），愣了一下，笑道：

“额，我叫张杰。”

“你住这边，”  他用手指了一下，“住我上铺”。

我是一个偏于冷漠的人，尤其是对一个新的环境。我放下行李，环顾了一下四周，宿舍 4 个人，4 张配套座椅，4 个放行李的柜子，一个阳台……  看床铺，我是最后一个来的。

虽然我知道他们已经来了，但是还是愚蠢的问了一个问题：“他们，还没来吗？”

“你是最后一个了，我第二个来的，对面上铺那哥们来的最早，不过我没见过正脸，偶尔回来睡个觉，没怎么说过话；下铺的那哥们比你早一天，应该去洗衣服了吧。”

话说途中，一个年轻的小伙子，后脑勺有几根头发炸着，端着脸盆，从门口一颠一颠地走了进来。我的第一反应是，好小，初中生？后来得知，这个孩子（噢，不! 应该叫同学）叫汪进祥，是我们宿舍年龄最小的。

当前晚上，他上铺的另外一个哥们没有回来，第二天早上不知道几点回来的直奔床上，睡到大中午。哦，原来这几天他一直在网吧通宵打魔兽世界。

刚到学校的那段日子，无非就是相互认识，辅导员带我们认学校，讲一讲学校的历史啦。后面的军训就更没什么可讲的。总之，大家都很开心，总是面对一些新的人，新的物，不亦乐乎。

只有一个人是例外，就是我们宿舍的那个哥们，他总是那么冷漠，好像学校的任何事情他都不感兴趣。因为经常抽烟，也是辅导员的重点关注对象。我很不理解，怎么会有这样的人，直到有一次喝酒喝开了，他讲听了他的故事（5分吹B成分，5分真实性吧），才逐渐地理解。
如果要是我，我可能也不感兴趣。对于这个神一样的男人，我会单拉一篇来讲，前提是要通过他老人家的授权。

我们宿舍是 113，后来因为宿舍单面靠墙冬天太冷了，没过多久（一年左右）就换了一个宿舍，搬到 103。我想对于很多人大学宿舍的编号总有一种莫名的自豪与荣誉感，他是这个团队的代号。
为达统一，以后都用 103（穿插一个梗，我们宿舍一直比较乱，大二的时候，有大三同学经过门口，会留意看看，然后说：“你看这就是他们的大四的宿舍，真乱，我们可能也会这样……”）。

分别介绍一下宿舍成员，额外信息在后面的故事中慢慢穿插，按年龄顺序：

_黄营峰的个人档案_

- 姓名：黄营峰
- 职位：宿舍长
- 性格：性情不好捉摸
- 出生年月：198X.XX.XX （说出来，这个系列怕是写不下去了）
- 通用绰号：峰子（这个绰号应该是建国给起得，印象中除了女生和老师会叫全名，其他人都是峰子，从无例外）
- 非通用绰号：屌丝峰，峰峰（这两个应该都是我起的），峰哥（很多其他宿舍的人在喝酒恭维的时候会叫；要烟抽的时候，也会叫；当然他要打我的时候，我也会叫……）
- 喜好：抽烟，看小说，打游戏（魔兽世界、刀剑online、WAR3）
- 口头禅：祥子，滚开，信不信我弄死你

_孙建国的个人档案_

+ 姓名：孙建国
+ 出生年月：1989.XX.XX
+ 性格：随和
+ 绰号： 胖子（峰子给起的，我在大学里面很少叫这个绰号），建国（我起的？这两个绰号都比较常用）
+ 喜好：听歌（建国对音乐的追求还是蛮高的，粤语歌和老牌的国外摇滚乐队他听的都比较多），看小说，打游戏（仙剑系列，轩辕剑系列，日本很多单机游戏），看电视剧（不谈了，哎……），给女朋友打电话（不谈了，哎……）
+ 口头禅：哥们儿~

_张杰的个人档案_

+ 姓名：张杰
+ 出生年月：1990.XX.XX
+ 性格：偏激
+ 绰号：没有（只有X偶尔会叫“阿杰”，其他没人叫过）
+ 喜好：听歌，看小说，打游戏
+ 口头禅：艹，卧槽

_汪进祥的个人档案_

+ 姓名：汪进祥
+ 出生年月：1991.XX.XX
+ 性格：略
+ 绰号：祥子（峰子给起的吧，所有的人都非常统一）
+ 喜好：一边看我们打游戏一边 BB
+ 口头禅：没发现

103 是年龄差最大的一个宿舍，年龄最小的是班里最小的，年龄最大是班里最大的。性格差距也比较大，经常有人说，你们宿舍四个奇葩，只有建国可能正常一些。
很奇怪的是这样的四个人的关系处的还都不错，一起开黑通宵打游戏，每学期开始、结束会出去喝一杯；逢年过节的，出去喝一杯；峰子把游戏号卖了赚个一两百的，出去喝一杯···

一个班 30 个人，22 个男的，8 个女的，听说这还算很不错的配备了。就在军训的时候，有那么一瞬间，我发现班里的有个姑娘，长的还不错，于是我就慢慢地留意，后来好像就演变成了暗恋...

张杰

2015/12/15
