#+SETUPFILE: ~/site/tpl/youth-tpl.org
#+TITLE: 在西农-S11：摇滚(3)

时隔两个月，再开始有些茫然了，随便写了。继续摇滚小结，接上文介绍一些我所了解的摇滚和我到现在依旧喜欢的歌曲。

** 崔健

#+begin_quote
你问我要去向何方，我指着大海的方向。

花房姑娘
#+end_quote

要谈国内摇滚，第一个想到就是应该就是号称「中国摇滚教父」的崔健。他不是中国第一个搞摇滚的，但绝对是最具代表性的一个。

每个时代的年轻人所面对的问题都是不一样，也许是这个原因，我对他的歌并没有多少共鸣也就听的少。对于音乐理念以及表达的艺术高度，我还没有资格评判，把崔健放到第一个的位置是对这位摇滚老大哥的尊重，因为我明白 从 0 到1 是很难的。

对于「一无所有」和「新长征路上的摇滚」这样传唱度高的作品，在小学初中就已经听过了，但是并不知道是崔健唱的，更不知道崔健是谁。有段时间特别喜欢 扭曲(扭曲的机器)，到处找视频，听到一首 [[https://www.youtube.com/watch?v=sg_bS-XMKMc][盒子]]，感觉爽歪歪。
后来查了一下才知道是扭曲翻唱崔健的，也是那个时候才知道崔健的。

喜爱的歌曲(按顺序，后面不在赘述)：[[http://music.163.com/#/song?id=63633][盒子]] [[http://music.163.com/#/song?id=63612][假行僧]]。

** 黑豹乐队

#+begin_quote
曾感到过寂寞 也曾被别人冷落

却从未有感觉 我无地自容

无地自容
#+end_quote

这是我特别喜欢的一句歌词，也是很具摇滚味道的一句话，出自黑豹。

1992 年发表第一张同名专辑《黑豹》，发行量 150 万，取得辉煌成绩。这是一张中国摇滚史上不能避过的专辑，不单是因为其正版加盗版创下了惊人的销售记录，让黑豹成了当时“中国人世界销售量最高的摇滚乐队”，并奠定了中国第一摇滚专辑的地位。

对了，黑豹的主唱是「窦唯」。

喜爱的歌曲：Don't Break My Heart、无地自容、别再纠缠我

** 唐朝乐队

#+begin_quote
风 吹不散长恨

花 染不透乡愁

雪 映不出山河

月 圆不了古梦

梦回唐朝
#+end_quote

有一次在 KTV 唱歌，杨溪鬼吼了一首梦回唐朝，那个时候班里应该没有人听过这首歌，跟别说这个乐队。当唱到「忆昔开元全盛日, 天下朋友结交情, 眼界无穷世界宽, 安得广厦千万万间」的时候，小伙伴们都惊呆了，当时想法不外乎三种：

1. 妈的，这个B唱的对不对啊
2. 哇擦，歌还可以唱
3. 这特么也叫歌

我相信大部分都是第一个想法，杨溪唱错了。我心里默默的把这首歌记到了小本子上，打算回去查查。从那之后，我就开始听唐朝了。有段时间，出去唱歌《梦回唐朝》和《国际歌》基本上是必点的。

关于唐朝，除了记住他们的歌以外，还有一句话需要知道。那就是：他们中国第一支重金属风格摇滚乐队。也是难得的国内摇滚风格鲜明的一只乐队。

喜爱的歌曲：梦回唐朝、国际歌、浪漫骑士、封禅祭、送别

** 张楚

#+begin_quote
我喜欢鲜花

城市里应该有鲜花

即使被人摘掉

鲜花也应该长出来

孤独的人是可耻的
#+end_quote

张楚，「魔岩三杰」之一。

喜爱的歌曲：孤独的人是可耻的、姐姐

** 高旗&超载乐队

#+begin_quote
梦 缠绕的时候

在我眼中

昨日的痛楚如音符

静静地飘过心中

梦缠绕的地方
#+end_quote

这是我接触的第一个摇滚乐队，高旗和超载在上篇文章中已经说过了，不再赘述。

喜爱的歌曲: 梦缠绕的地方、每次都想拥抱你、如果我现在死去、祖先的阴影

** 地下婴儿

了解不多，只听过几首。尤其喜欢 [[http://music.163.com/#/song?id=350957][觉醒]] 从 1:40 开始的那段旋律。

喜爱的歌曲：觉醒、[[http://music.163.com/#/song?id=5278187][都一样]]

** 瘦人乐队

15 年才知道的一个乐队，推荐一首：[[http://music.163.com/#/song?id=376978][第七天]]，单曲循环了至少一周。

** 达达乐队

#+begin_quote
孤独的流星滑过

这无声夜空

记忆也从此带上

永久的黑白

等待
#+end_quote

大四寒假，杨溪在他的QQ 空间写了这么一条说说: 「不是非要飘扬，我的梦想没有翅膀，不愿让所有的最后总结束的忧伤」。看完之后，我瞬间觉得这个逼格太足了。问了之后才知道这是达达乐队《等待》的一句歌词，从那之后达达变成了我最喜爱的乐队之一，也是影响我最深的乐队。

喜爱的歌曲：南方、Song F、等待、收音机之恋

** 反光镜乐队

#+begin_quote
是谁改变了属于我的模样

是谁吹灭那传说中的神话

我愿换上那最动人的衣裳

只为等待那最善良的出发

长大
#+end_quote

在北京的时候常听。

喜爱的歌曲: 晚安北京、长大、释你、嘿!姑娘、只有音乐才是我的解药

** 谢天笑与冷血动物

#+begin_quote
向阳花! 如果你只生长在黑暗下

向阳花,会不会害怕

向阳花
#+end_quote

记得很久以前杨溪就跟我念叨谢天笑了，但是一直没听，直到在家养病的那一段时间才开始听的。可以说「在错误的时间，遇到的错误的歌」。谢天笑的很多歌太过压抑，尽管确实有些歌很好听，但是我不推荐别人去听。

喜爱的歌曲: 向阳花、风是外衣

** 痛苦的信仰

#+begin_quote
再见杰克，再见我的凯鲁亚克
#+end_quote

北京的时候听的比较多，我接触的痛仰已经是「晚期的痛仰」了，满怀希望，没那么躁动了。

喜爱的歌曲：再见杰克、生命中最美丽的一天、公路之歌

** AK-47

号称国内的「战车」，实际上还是有很大的差距。

喜爱的歌曲：残酷青春、黄金时间、47公路

** 万能青年旅店

#+begin_quote
河北师大附中 乒乓少年背向我

沉默的注视 无法离开的教室

杀死那个石家庄人
#+end_quote

如果有人问我，你觉得国内那个乐队最「摇滚」，我的答案会是万青。

喜欢的歌曲: 杀死那个石家庄人、十万嘻皮、揪心的玩笑与漫长的白日梦、不万能的喜剧

** 刺猬

#+begin_quote
故事开始没有画面

伙伴们紧闭双眼

醒来时却发现朋友早已不见

留下陌生的世界待我们去冒险

身后的灯火熄灭

前方已漆黑一片

纵然不顾一切也还需要时间

还有更多的秘密待我们去挖掘

故事最后留下悬念

青年们睁大双眼

耳畔响起音乐留下沸腾画卷

这里并不只有音乐

这里有梦也有鲜血

电影
#+end_quote

有段时间看DOTA视频，阿川的视频开头有一段背景旋律，听的久了被洗脑了，找了一下才知道是刺猬的《白日梦蓝》。之前转了两篇文章，一篇就是关于刺猬的，写的很好，值得一看：白日梦蓝 【豆瓣乐评摘抄】

对于刺猬，我只能说，歌词、旋律一级棒。

喜爱的歌曲：白日梦蓝、最后，我们会一起去海边、金色年华，无限伤感、树、电影

** 逃跑计划

喜爱的歌曲：一万次悲伤、再见，再见、阳光照进回忆里

** 扭曲的机器

#+begin_quote
注视着那镜中的自己

慢慢将这眼泪擦去

不知什么还能让我留下回忆

留下回忆

我的心中有无限感慨

我在期待美好的未来

镜子中
#+end_quote

镜子中，第一首地下摇滚的歌，这首歌基本上贯穿了整个大学生涯。

喜爱的歌曲: 镜子中、理想的背后、三十

还有些乐队，就不挨个介绍了：

+ 指南针
+ 春秋乐队
+ 轮回乐队
+ 麦田里的守望者
+ GALA
+ 木马
+ 相对论
+ 渡鸦乐队
+ 声音碎片
+ 指人儿
+ 木星3号
+ 果味VC

不打算再单独花篇幅去讲摇滚了，在以后的文章一带而过吧，太枯燥了。

张杰

2015/01/12
