#+SETUPFILE: ~/site/tpl/youth-tpl.org
#+TITLE: 在西农-S3：迷茫的大一

#+begin_quote
如果骄傲没被现实大海冷冷拍下 ，又怎会懂得要多努力 ，才走得到远方 —— 范玮琪《最初的梦想》
#+end_quote

刚开始每篇的开头和 BGM 总是最难选的，我有很多可以用来装B的歌词以及BGM，可惜不符合现阶段的内容。于是我问胖子：“你还记得我们大一的时候听的什么歌吗？”
 他说：“必须是最初的梦想啊，哈哈”，我一想，操，还真是。用这首歌来形容当时很贴切。

大一上学期的很多事情记不清了，不是因为时间久了，而是因为那个时候真的什么都不想，像个傻子，成天开心的不行，也不知道开心什么。一次吃饭的时候（应该已经到大三了吧），忘了是谁说：“你看，小孩子多好，无忧无忧，玩的多开心，我们现在……”
，X说：“可是他们并不知道自己过的很开心”。没想到，像X这样X的孩子，居然能说出这么有哲理的话。当我们开心的时候，其实并不知道应该去享受一下开心的阶段，只有回首过去的时候，才会突然间追悔莫及。

大一上学期似乎离很多事情很远，从来没有想过自己以后要干什么，能干什么。从小学到高中算是憋坏了，突然放开了，觉得好爽、好自由。可是，所有的事情总会有一个度，再好的东西，时间长了也会疲倦。

上高中的时候老师说，等上了大学就幸福了，不用考试……

等上了大学之后才知道，早上 8:00 要上课，课很多，要点名，要考试，要交作业算平时分。MLGB，分低了，要补考，补考不过还要重修，重修不过毕不了业。简直没天理。

当我觉得大家应该接受不了这个设定的时候，其实不然，国产教育下的学子们忍受和适应能力还真是挺强的。人与人之间的差距就逐渐拉开了。大体分为这么几种：

1) 第一种、学霸！继承了高中时候的学风，任劳任怨，三点一线的生活：图书馆、自习室、宿舍。毫无疑问，他们包揽了各种奖学金，他们是老师眼里的好学生、最有希望的学生。代表人物：dtq, ymb, 祥子（没错，就是咱们宿舍的祥子，真争气！）
2) 第二种、一边骂着娘，一边上着自习写着作业。说不上有多拼，成绩也还算好。代表人物：杨溪
3) 第三种、哥们儿以后不干这个，只要一个毕业证。该上课上课，交作业的时候抄一份，考试之前突击一下，不求高分，但求不挂。代表人物：胖子
4) 第四种、学渣，逃课打游戏，爱咋地咋地，考试能过自然最好了，过不了那也是没办法的事啊。代表人物：峰子
5) 第五种、个性较劲性，爱学就多学一点，不爱学、老师讲的不好，就不去了，作业要么自己写，要么不写，反正不抄。代表人物：我

现在你明白我为什么说我们四个人四种性格了吧。不过谁也没有想到的是，一两年之后，我们都逐渐向峰子靠拢了，大家一起逃课，一起打游戏。自豪地当了一个学渣，我和胖子是最早沦陷的，
等到了大三的时候，祥子！我们宿舍唯一的标兵也沦陷了。现在看来峰子真是有先见之明，站对了队以后就没变过。

大一下学期的时候，我确实很迷茫（那是我上大学的第一次迷茫）。迷茫的点在于：没目标，不知道自己以后要干什么，不知道自己现在该干什么（我之前的文章应该写过这些，不过没这么详细，侧重点不一样）。

这个问题困绕了 6、7 年的样子，从来没有真正的解决过。当时发生了 2 件事情，让我暂时有的方向。

_疯狂的程序员_

09年，CSDN有个系列连载叫 「疯狂的程序员」，相信很多人应该都看过这部小说吧（毕竟CSDN是众多菜鸟的聚集地）。看的我心潮澎湃，热血沸腾。也是那个时候，第一次接触「程序员」这个词。

不得不说这本书确实写的很好，虽然没涉及到什么技术（还好没涉及，不然也看不下去），但是人物感觉很真实，绝影不算高手，也算不上一个菜鸟，他有追求，他谈恋爱（后来分手了），他也曾迷茫和失落，还富有幽默细胞（也就是程序员的呆萌）。摘几句话：

#+begin_quote
我要做个病毒，就藏在电源里面。电源总不会断电吧，哈哈。就一直藏在那里面。（逗比……）

人无非通过两种方法提高自己，一是真的提高自己，二是通过打击别人抬高自己。（我也经常说这句话，原来是从这学的）

能进别人系统偷东西，那就是小偷；能进别人系统又不偷东西，那就是黑客。

你比他好一点，他不会承认你，反而会嫉妒你；只有你比他好很多，他才会承认你，然后还会很崇拜你。所以要做，就一定要比别人做得好很多。

...
#+end_quote

看完之后，觉得挺有意思的，就决定做一个「程序员」。等我真正接触这个行当以后，看到很多程序员自黑，自我嘲讽的时候，觉的加班是很自豪的一件事情的时候，喜欢叫自己码农、码畜的时候。
我心想，傻B，去你妈的，老子不当程序员了，老子是 「软件工程师」。所以，你很少在我写的文章的任何地方见能到 程序员 这三个字，大部分都是 程序 或者 工程师。当然，这一切都是后话。

_找工作_

大一下学期的时候，是上一届大四找工作的热潮，找到工作的人 学院还会办一些分享会，其实就是 装B 会啦。在大部分人眼里，当你成功的时候，你拉屎放屁的姿势都是值得学习的。

大家都在讨论谁谁去了哪家公司，月薪多少，年薪多少。当时有个学长拿了 5K 的工资，大家都好崇拜。其实对当时的我们而言，5K工资到底算高还是算低没几个人知道，谁知道行业行情是什么啊，反正大家都觉得牛逼，可能就牛逼吧。

当时我突然想明白了，嗯，等我毕业的时候，我也要拿 5K+ 工资。

这两件事情让我找到了自己的定位：一、我要当个程序员；二、我要拿5K+的工资。

当时还发生了另外一件事情：大一下学期，大约在春季运动会的时候，我谈恋爱了。用许巍的一句话来形容其过程：「很多事来不及思考 ，就这样自然发生了」。没有追求的过程，很自然就到一起了，其实到现在我也想不明白原因···

张杰

2015/12/16
