#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 在西农-S1: 第一个选择

“喂，别睡了，下车了！”

一个乘务员（中年男性）操着浓重的杨凌话对我喊，这是我在杨凌听到的第一句话，对于大学，对于身后这座即将生活的四年的地方并没有特殊的感觉，只是困，想找个地方好好的睡一觉。


**三个月前**

出高考考场的那一瞬间，我的第一反应是完了，最擅长的理综物理好几道大题都不会。估分之后，我更加肯定完了！我妈说不行的话复读一年，我拒绝了。我早就不想念书了，念够了。

有多少人“寒窗苦读”的目的不是为了前途，而是为了大学之后不用再考试了的目的在读书。我算一个！一个大学乃至硕士博士毕业的人，都可能不知道出路在哪儿，让一个高中生为了不知道为了什么的目的去读书，真是一个莫大的悲哀。更可笑的是，还有一些人把这个悲哀带到了硕士，带到了博士，甚至带给了自己的孩子。

这可能就是中国式的教育，告诉你是什么，你该怎么做，却从来没有耐心去启发、去解释给你听为什么要这么做。小学、初中、高中、大学……不外如是。我们缺的东西太多，但是最缺的是去独立思考、去选择的权利。

既然估分很不理想，我的一个老师就跟我说，如果对其他一本没信心的话，就报 西北农林科技大学 大学吧。这学校一般只要能过本科线，就能被录取。那好吧，选什么专业呢？班主任说，土木工程吧，这专业不错。第二志愿呢？那就随便填吧。在高三快结束的时候，我特别喜欢打游戏，经常上下午都模拟考试的时候，中午随便吃点东西，几个人就奔去网吧打CS了。第二志愿，我找了好久，终于找到一个可能喜欢的专业：信息工程学院——计算机科学与技术。

我心理上更喜欢能选中这个专业，因为这样以后就可以名正言顺的打游戏了。嘿！录取通知书下来的时候，还真他妈是计算机专业。我的老师就跟我爸妈说，哎，你家孩子可惜了，这专业不行，没前途。这句话他们讨论了四年，甚至最后我妈都质疑了，严重怀疑我大学是不是白念了。直到毕业以后，他们再也没有说过这样的话……

我想，关于报考志愿选择计算机这件事情，可能是我人生中自己独立的、偷偷做的第一个选择，现在想来多么正确而又有远见。像我这样一个手无缚鸡之力的人，除了敲敲键盘之外，其它的可能还真干不了。

想起某次宿舍几个喝得正嗨的时候，峰子用极为自豪兼具鄙视的语气跟我们说：“像你们这样的弱渣去给人家搬砖，一天估计都抗不下去，想当年，我……”。我只能承认，他的前半段说的很有道理，我们这一代人，大部分人基本上都是出生于88~90之间，没有太好的成长环境，也没怎么受过苦，不好也不坏。当然，峰子不是这个年龄段的，要说峰子的故事，我可以写上万字了……

**一天前**

很多人第一次上大学，都是父母亲自送的，我后来还听说回家还有的父母去车站去迎接。我从小父母在外打工，我跟他们一起在异地念书，8年左右的时间算的上是一直在流浪。所以，不管是他们还是我，对于这些接送的事情从来都在我们的世界观里。在很长的一段时间里，到家、离家并没有很开心、或者很伤感，都已经习惯了。我在外面，他们也放心。

在高考结束那个暑假的那段时间，父母在天津，我一个人呆不住，就到河北（我在河北廊坊念的小学、初中、高中，高三转学回家）转了一圈，和一堆小伙伴打牌、打游戏，嗨了一段时间。那个时候，我在谈恋爱，记得很清楚，一天5块的短信费（当时算是很奢侈了）。快要去上学的时候，坐火车回到延安。

听人说有趟大巴，从县里直达西安，就提前去买了一张票。现在想想，是有那么一点可怜，一个人跑来跑去，早上晚上做大巴到西安，从西安汽车站（忘了是东站还是西站了，反正我从来都搞不清楚）到另外一个汽车站，再到杨凌。

这里要插一句，从我第一次到西安，就对这座城市没有任何好的印象，火车站很凌乱，周围全是黑车。基本上每次去都要被司机宰。记得有次寒假结束去上学的时候，有个师傅开着三蹦子把我从汽车站到火车站:

“师傅，近吗”

“近，坐我这个比出租车快！”

“那多少钱啊？”

“50 !”

“啊？这么贵啊”

“那你想多少吧，从这边过去都这个价位。”

“30？……”

“上车吧”

“哦……（操，我是不是说高了）”

快，也确实快，你能想象零下几度，坐着三蹦子在西安城里狂奔吗？！我他妈都快冻成小鸡子了。

扯回来，晚上坐大巴 12 个小时早上 8 点左右到西安，再折腾一顿，终于上了到杨凌的杨凌的大巴，心想着老子这回可以踏实睡一觉了。所以，你就能明白，为什么我会那么的困。

被乘务员叫醒之后，揉了揉眼睛，晃晃悠悠的拉着箱子走出了车外……

张杰

2015/12/14
