#+SETUPFILE: ~/site/tpl/link-tpl.org
#+TITLE: 曾经发表在 ONCE 上的一些话

** 2016-01-10 20:09:28
   :PROPERTIES:
   :CUSTOM_ID: section
   :END:

要是有些事我没说，你别以为是我忘了，我什么也没忘，但是有些事只适合收藏。不能说，也不能想，却又不能忘。

------史铁生

** 2016-01-10 23:02:18
   :PROPERTIES:
   :CUSTOM_ID: section-1
   :END:

如果一个人肯坦然面对真实的自我，他最终会发现所有的尴尬或多或少都有自己的责任。

** 2016-01-10 23:02:45
   :PROPERTIES:
   :CUSTOM_ID: section-2
   :END:

我们所面临的今天很大程度上取决于我们的过去。

** 2016-01-10 23:03:03
   :PROPERTIES:
   :CUSTOM_ID: section-3
   :END:

知无不言，言无不尽，在大部分情况下是最浪费时间和精力的做法。

** 2016-01-10 23:05:09
   :PROPERTIES:
   :CUSTOM_ID: section-4
   :END:

这些公认为优秀的人，往往并不"低调"，也不"平易近人"。他们不是故意这样做的。他们无意去惹恼身边那些他们看来"平庸"的人，只不过他们无形中有这样的体会：与这些人交流，沟通成本太高。这些人当中不多见的那些心态平和者，一般都是经历了波折，才终于意识到应该保护自己。他们发现，有些误解根本没机会解释。于是，他们开始"谦虚"，他们学会"低调"，他们显得"平易近人"。

一个人的心智一旦开启，他就会发现，自己在这个信息唾手可得的世界里，只要正常的努力，并且有耐心和时间做朋友，就很容易就能成为至少成为一个领域的专家。努力并不像传说中的那么辛苦，说出来只不过是，每天至少专心学习、工作六小时。可是，努力需要耐心，却远比多数人想象的巨大。短则五
年，长则二十年。

李笑来《把时间当作朋友》

** 2016-01-10 23:05:34
   :PROPERTIES:
   :CUSTOM_ID: section-5
   :END:

在最常见的品味这个问题上，如果你做一个偏好调查，你会发现大多数人根本就不知道该怎么选择，他们只好选择自己熟悉的答案。

** 2016-01-10 23:06:02
   :PROPERTIES:
   :CUSTOM_ID: section-6
   :END:

管理的技巧就是通过其他人的工作实现自己的目标。写作的技巧就是创造一个能够激发其他人进行思考的环境。

** 2016-01-10 23:06:29
   :PROPERTIES:
   :CUSTOM_ID: section-7
   :END:

不要低估社交的力量。社交不是勾心斗角，或是操纵别人，它是通过建立起人与人之间的关系来吧事情做成功，而且这种关系延续时间肯定比项目本身更长。

** 2016-01-10 23:06:42
   :PROPERTIES:
   :CUSTOM_ID: section-8
   :END:

计算机科学领域的任何问题都可以通过增加一个间接的中间层来解决。

** 2016-01-10 23:07:16
   :PROPERTIES:
   :CUSTOM_ID: section-9
   :END:

创业公司的ceo不应该计算成功的概率。创建公司时，你必须坚信，任何问题都有一个解决的办法，而你的任务就是找出解决办法，无论这一概率是十分之九还是千分之一，你的任务始终不变。

** 2016-01-10 23:07:29
   :PROPERTIES:
   :CUSTOM_ID: section-10
   :END:

逃避问题和痛苦是一切心理问题的根源。你不解决问题，你就会成为问题。

** 2016-01-10 23:07:53
   :PROPERTIES:
   :CUSTOM_ID: section-11
   :END:

多年来我头一次意识到，这园中不单是处处都有过我的车辙，有过我的车辙的地方也都有过母亲的脚印。

------史铁生《我与地坛》

** 2016-01-10 23:08:02
   :PROPERTIES:
   :CUSTOM_ID: section-12
   :END:

生活就是这样，

在你最糟的时候，会遇到最好的人。

知乎@萌面高圆圆

** 2016-01-10 23:08:16
   :PROPERTIES:
   :CUSTOM_ID: section-13
   :END:

永远年轻，永远热泪盈眶。

杰克 凯鲁亚克

** 2016-01-10 23:08:37
   :PROPERTIES:
   :CUSTOM_ID: section-14
   :END:

孩子，我要求你读书用功，不是因为我要你跟别人比成绩，而是因为，我希望你将来会拥有选择的权利，选择有意义、有时间的工作，而不是被迫谋生。

龙应台

** 2016-01-10 23:08:50
   :PROPERTIES:
   :CUSTOM_ID: section-15
   :END:

长大后也会哭泣，回忆越多，那些泪水就越抑制不住。

------矮子画廊

** 2016-01-10 23:09:12
   :PROPERTIES:
   :CUSTOM_ID: section-16
   :END:

我们都会遇到那个人吧，陪你走过一段路，影影绰绰似乎开始了模糊的恋情，事后想来却仿佛停止于尚未开始的爱。

或许是多年再见，各自安静生活数年。

在某个人潮拥挤的街头，透过公车的玻璃窗突然看见你，想叫让司机马上停车，想用力拍打窗户来引起你的注意，想从车上跳下来，想奔跑，想大喊大叫，想把整个阻隔在你我之间的世界撕裂。呼吸急促，面额潮红，手指颤抖，在激烈的想象中把自己感动的快哭了。

而事实总是一动不动的坐着，安静的看你远去。你的脸，从开始到现在，我原来从未曾看清楚过。我知道我只能陪你走这一段路。

------豆瓣《萤火之森》影评

** 2016-01-10 23:11:23
   :PROPERTIES:
   :CUSTOM_ID: section-17
   :END:

但愿你已经睡着了，一觉醒来的时候是飒爽的早晨，而不是四下无人的夜。

知乎@易燃先生

** 2016-01-10 23:11:53
   :PROPERTIES:
   :CUSTOM_ID: section-18
   :END:

有很大一部分确实非常优秀的人，是风险厌恶型的，他们完全没兴趣参与任何创业公司------在他们看来，他们在任何地方都可以获得足够好的收入，根本用不着冒险。

这也是为什么寻找共同创业的优秀人才那么难的重要原因。

很多人之所以有冒险精神，并不是因为他们优秀，而是因为他们其实一无所有。

** 2016-01-10 23:12:14
   :PROPERTIES:
   :CUSTOM_ID: section-19
   :END:

生命的真谛不在于你呼吸的次数，而在于那些令你屏住呼吸的时刻。

** 2016-01-10 23:12:36
   :PROPERTIES:
   :CUSTOM_ID: section-20
   :END:

我一直梦想着可以写出很好的文章，可惜从小到大作文老师最好的评价是：朴实无华。

我一直不太明白这个词为什么会是个褒义词。

现在才逐渐明白了，不管是什么样的文章，讲清楚文章要表达的主旨才是最重要的。

华丽的文字，通常需要很强的驾驭能力，如果用的不好就会喧宾夺主。

** 2016-01-10 23:14:46
   :PROPERTIES:
   :CUSTOM_ID: section-21
   :END:

[十二年]

2015年10月20日 朴树

不记得从什么时候开始被叫朴老师了。可怕的是有时我还答应了。96 年签下第 1
张合约，算下来，的确是个老艺人了。

从一开始，就厌恶这个行业，并以之为耻。电视上的明星们令人作呕，我毫不怀疑我会与他们不同。后来，与这行业若即若离的那些年，被裹挟着，半推半就着往前走，边抗拒边享受着它给予我的恩惠。钱，名声。一度沾沾自喜，而且颇有些年迷失其中，沉湎于享乐，无力自拔。直到老天爷收走了赋予我的所有的才华和热情。

09
年合约了断的时候，我真的松了口气。够了。我不要再过那种生活。我需要一整段时间来搞清楚，我到底想要什么，要干嘛。

我不否认我心存偏见。在我眼中，明星这个词昂贵而无趣。而这个行业，保守，短视，贪婪，僵死，象涂脂抹粉的尸体。甚至比起二十年前更加无耻。

我赞同人们该各行其是，互不相扰，没有你死我活。但就我而言，我只希望做自己真正想做的事，心安理得的，让它们尽可能有趣。这一点愈发清楚。它对我很重要。

7
月，我看到了木星的单曲封面，看到了这个行业标准模式的宣传通稿。我被告知，这是这个行业的规律，不如此就没有人看没有人听。我怒不可遏。我想说，你们就是用这方法让你们的行业每况愈下奄奄一息的。

这是我写这些文章的原因。

我希望有更多的人来听我的歌，甚至了解我这个人。但与其做那些断章取义驴唇马嘴的采访，还不如自己把它们说出来。

关于这十二年，我真的很厌烦那个说法，"某人十年磨一剑，十一年，十二年"。一而再而三，我觉得好愚蠢。我不是用
12 年来做 1 张唱片。不是。如果一张唱片做了 12
年，可以预见，那该有多糟糕。

在英国时，听朋友讲起prince录音的故事。话说，prince为了一首歌能录出他想要的鼓的音色，从美国录到英国，一直不得。两年后的一天，录音师正在整理素材，躺在沙发上的prince一跃而起，"嘿，就是刚才的那个声音，它就是我要的那个。"录音师回过头，看着他，缓缓说道，"是吗。好吧。谢谢你。这是两年前我们录下的第一条。"

各位，这并不可笑。当你足够爱一件事，你就会知道，这有多正常。当你长久地专注于它，它便会无限放大，以至于你的听觉视觉所有感官开始变形，失去判断，最终陷入疯狂。

这也是我9月刚刚经历过的。心有余悸。

岔回来。是老天爷让我等了12年才等到可以做唱片的状态。

它真不短。

它很残酷。

在这12年间，爸爸妈妈变得很老了，我和我身边的一切都老了。连我的狗也老了。它曾经那样精力旺盛，充满好奇地整天玩耍。而现在，他开始越来越久地睡觉。他的鼻子不再那么黑亮，湿润。他脸上的毛开始发白。他会时常把头放在我的膝盖上，长久地望着我，就象知道他不能永远这样陪伴我。

我的情况则是，不再热衷于漂亮衣服，终日的party，卖弄炫耀。越来越沉默。我的眼睛渐渐失去神采，看起来越来越疲惫，头发越来越白，越来越少。

它们慢慢的发生。它们就像凌迟。漫长的侮辱。让你充满了疑惑和恐惧。

后来，不知不觉地，你开始接受发生在你身上的一切减法，并乐于见到自己变得越来越少。有一天，你居然发现，在心里的某个地方，你比最年轻的时候还要年轻。以至于认为，一切才刚刚开始。时间变得不再有意义。

各位，时间哪儿都没有去。它是你的幻觉。它并不存在。

前几天读到这样的故事。某人善画竹，名满天下。可他的老师对他说，你尚未入门。问：如何得入。答：要在心里觉得你就是竹子。其人乃去，终日站在竹林中。风起。竹摇。其人亦摇。如此十年过去。一日，师往探之，见其在竹林中闭目凝神，随风摇摆。师视良久说，好了，可这还不够，你要忘掉你是竹子这件事。又三年。师复探之，曰，汝成矣。

我喜欢这种对待时间的态度。

我们是不是非要那么急迫不可？

** 2016-01-10 23:15:24
   :PROPERTIES:
   :CUSTOM_ID: section-22
   :END:

如果天空总是黑暗，那就摸黑生存；如果发出声音是危险的，那就保持沉默。

如果自觉无力发光，那就蜷伏于墙角。

但不要习惯了黑暗就为黑暗辩护；不要为自己的苟且而得意；不要嘲讽那些比自己更勇敢热情的人们。

我们可以卑微如尘土，不可扭曲如蛆虫。

** 2016-01-10 23:15:53
   :PROPERTIES:
   :CUSTOM_ID: section-23
   :END:

I thought I knew the feeling but I didn't.

我曾以为我知道那种感觉，但我其实并不知道。

** 2016-01-10 23:16:05
   :PROPERTIES:
   :CUSTOM_ID: section-24
   :END:

某天，你无端想起一个人，她曾让你对明天有所期许，但是却完全没有出现在你的明天里......

这是个喧嚣的世界

我从未觉得安静过

他的繁荣 他的昌盛

带给人们却只是更多的疲惫

更多的抱怨

于是我捂住双耳

不去听他的疲惫

不去听他的昌盛

不去听他的繁荣

也不去听他的抱怨

于是我以为我的世界安静了

只是这世上总有那么一人哪怕她不曾对我讲过一言一语

但我却听得到她的声音。

** 2016-01-10 23:17:22
   :PROPERTIES:
   :CUSTOM_ID: section-25
   :END:

我们年轻的时候，总是把创作的冲动误以为是创作的才华；总是把对孤独的恐惧误以为是对爱情的向往。

网易云音乐@桥域往事

** 2016-01-10 23:17:49
   :PROPERTIES:
   :CUSTOM_ID: section-26
   :END:

对一个人的未来最具决定意义的是一个人的出身，其次是运气，个人努力相比之下则是最不重要的。

** 2016-01-10 23:18:01
   :PROPERTIES:
   :CUSTOM_ID: section-27
   :END:

可是，明显有一些人，尽管数量上不是大多数，在用另外一种状态生活。他们从容，他们优雅。他们善于化解各种压力，安静地去做他们认为应该做的事，并总是有所成就。他们最终甚至可以达到常人无法想象的境界------不以物喜，不以己悲。

《把时间当做朋友》

** 2016-01-10 23:18:23
   :PROPERTIES:
   :CUSTOM_ID: section-28
   :END:

产品经理最重要的能力不是某一项技能，而是「让正确的事情相继发生」。

** 2016-01-10 23:18:37
   :PROPERTIES:
   :CUSTOM_ID: section-29
   :END:

拼命的把所有事情搞清楚，然后认真的去做。

** 2016-01-10 23:18:57
   :PROPERTIES:
   :CUSTOM_ID: section-30
   :END:

我所有的自负皆来自我的自卑，所有的英雄气概都来自于我的软弱。嘴里振振有词是因为心里满是怀疑，深情是因为痛恨自己无情。这世界没有一件事情是虚空而生的，站在光里，背后就会有阴影，这深夜里一片寂静，是因为你还没有听见声音。

------马良《坦白书》

** 2016-01-10 23:19:12
   :PROPERTIES:
   :CUSTOM_ID: section-31
   :END:

这世上真话本就不多，一位女子的脸红胜过一大段对白。

老舍

** 2016-01-10 23:19:26
   :PROPERTIES:
   :CUSTOM_ID: section-32
   :END:

坏程序员总是担心他们的代码，而优秀的程序员则会担心数据结构和他们之间的关系。

林纳斯

** 2016-01-10 23:19:39
   :PROPERTIES:
   :CUSTOM_ID: section-33
   :END:

一个人能做他想做的，但是不能要他想要的。

叔本华

** 2016-01-10 23:20:02
   :PROPERTIES:
   :CUSTOM_ID: section-34
   :END:

「后来我终于知道，它并不是我的花，我只是恰好途径了它的盛放。」和「年少时不能遇到太惊艳的人」似乎表达的含义是一致的。

后面这句话来形容郭襄的一生再好不过了。

如果郭襄在杨过的任何年龄段遇到杨过估计都不会喜欢他的，也就不会成为悲剧了。

最后，郭襄当了尼姑，张君宝当了道士，虽然都成了一代宗师，可谁不是悲剧呢？一见杨过误郭襄终生，一见郭襄误了张君宝百年啊！

而杨过，却再也没出现过。

金庸小说的主角最讨厌两个人，一个是杨过，他自卑，他又自负，最受不了的是他自私。另外一个是张无忌，要不是他做事优柔寡断，也不会造成周芷若的悲剧。

最喜欢的是令狐冲，他放荡不羁，却始终能保持一颗赤子之心。

** 2016-01-10 23:20:37
   :PROPERTIES:
   :CUSTOM_ID: section-35
   :END:

以前我以为那句话很重要，因为我觉得有些话说出来就是一生一世，现在想一想，说不说也没有什么分别，有些事会变的。

------电影《东邪西毒》

** 2016-01-10 23:20:56
   :PROPERTIES:
   :CUSTOM_ID: section-36
   :END:

他教我收余恨、免娇嗔、 且自新、改性情、休恋逝水、苦海回身、早悟兰因。

------京剧《锁麟囊》

** 2016-01-10 23:21:09
   :PROPERTIES:
   :CUSTOM_ID: section-37
   :END:

一直以为我跟他不一样，原来寂寞的时候，所有的人都一样。

电影《春光乍泻》

** 2016-01-10 23:22:41
   :PROPERTIES:
   :CUSTOM_ID: section-38
   :END:

总之岁月漫长，然而值得等待。 ------村上春树《如果我们的语言是威士忌》

** 2016-01-10 23:22:54
   :PROPERTIES:
   :CUSTOM_ID: section-39
   :END:

每个人都会经历这个阶段：
看见一座山，就想知道山后面是什么。我很想告诉他，
可能翻过去山后面，你会发觉没有什么特别。 回头看，会觉得这一边更好。
但我知道他不会听， 以他的性格，自己不试过，又怎么会甘心？

** 2016-01-10 23:23:17
   :PROPERTIES:
   :CUSTOM_ID: section-40
   :END:

- 所谓承诺，都要分了手才承认是枷锁
- 所谓辜负，都是浪漫的蹉跎

** 2016-01-10 23:23:28
   :PROPERTIES:
   :CUSTOM_ID: section-41
   :END:

哪里会有人喜欢孤独，不过是不喜欢失望罢了。 ------《挪威的森林》

** 2016-01-10 23:23:37
   :PROPERTIES:
   :CUSTOM_ID: section-42
   :END:

丢失的日子如融化在人群里的好姑娘，我看着她沿途美丽下去，嫁给别人。

叶三《九万字》

** 2016-01-14 09:03:56
   :PROPERTIES:
   :CUSTOM_ID: section-43
   :END:

万物之中，希望至美；至美之物，永不凋零。

** 2016-01-14 09:06:48
   :PROPERTIES:
   :CUSTOM_ID: section-44
   :END:

聪明是一种天赋，而善良是一种选择。

Jeff Bezos

** 2016-01-15 08:53:26
   :PROPERTIES:
   :CUSTOM_ID: section-45
   :END:

百度控制着普通人接触信息时代的入口，却把路标指向邪恶欺骗的世界。它让人们对互联网世界失去信任、对技术失去尊总、在使用这个时代最先进的知识/信息获取方式时感到恐惧。加剧了信息占有乃至知识上的不平等。这种对弱势群体对普通大众的经年累月的作恶，是最深的恶。

西乔

** 2016-01-20 15:29:00
   :PROPERTIES:
   :CUSTOM_ID: section-46
   :END:

那一天我二十一岁，在我一生的黄金时代，我有好多奢望。
我想爱，想吃，还想在一瞬间变成天上半明半暗的云。后来我才知道，生活就是个缓慢受锤的过程，人一天天老下去，奢望也一天天消失，最后变得像挨了锤的牛一样。
可是我过二十一岁生日时没有预见到这一点。我觉得自己会永远生猛下去，什么也锤不了我。

王小波 《黄金时代》

** 2016-01-20 15:36:34
   :PROPERTIES:
   :CUSTOM_ID: section-47
   :END:

你没有如期归来，而这正是离别的意义。

北岛

--------------

我希望生命几经摔打，能够因此变得柔韧。我希望下次流泪，不再是因为失去。世界小得像一条街的布景，我们相遇了，你点点头，省略了所有的往事，省略了问候。
也许欢乐只是一个过程，一切都已经结束。

北岛

--------------

那时我们有梦，关于文学，关于爱情，关于穿越世界的旅行。如今我们深夜饮酒，杯子碰到一起，都是梦破碎的声音。

北岛

** 2016-01-20 15:44:32
   :PROPERTIES:
   :CUSTOM_ID: section-48
   :END:

钱以外的东西，永远都还不清。比如难以启齿的歉意，比如无地自容的倔强，比如无法化解却可以忍让的温柔，比如一起经历过羞耻和仇恨之后才会出现的脆弱的朝露一般的同盟。

@笛安

** 2016-01-20 15:50:00
   :PROPERTIES:
   :CUSTOM_ID: section-49
   :END:

我慢慢地、慢慢地了解到，所谓父女母子一场，只不过意味着，你和他的缘分就是今生今世不断地在目送他的背影渐行渐远。你站在小路的这一端，看着他渐渐消失在小路转弯的地方，而且，他用背影告诉你：不必追。

龙应台 目送

** 2016-01-20 15:51:54
   :PROPERTIES:
   :CUSTOM_ID: section-50
   :END:

人在无端微笑时，不是百无聊赖，就是痛苦难当。

王小波

** 2016-01-20 15:55:04
   :PROPERTIES:
   :CUSTOM_ID: section-51
   :END:

生命中曾经有过的灿烂， 原来终究， 都需要寂寞来偿还。

《百年孤独》

** 2016-01-29 15:42:50
   :PROPERTIES:
   :CUSTOM_ID: section-52
   :END:

Dota 有个民间解说 "阿川"
。他有三个代表性的ID：屠夫阿川、拆黑之王、一条大菜狗。我想我可以诠释这三个
ID 的含义：

1. 在初出江湖的时候，我希望自己能有一技之长，在自己的刻苦训练之下终于可以崭露头角，我的屠夫是最屌哒！
2. 终于有一天我认为这个ID已经不能代表我的水平了，我应该有一个更好的平台，于是我将自己的ID改为："拆黑之王"，誓要拆尽天下黑店，让对手闻风丧胆。就这样我坚持去做了，但是随着我的技术水平越来越屌，遇到的对手也越来越屌，我才发现世界很大，玩法很多，我还有很多东西要去学习。
3. 于是，我变成了"一条大菜狗"，就像一个真正的鼓手不是要力量足够大，而是要学会控制力量一样，让对手感觉到害怕的不是自己的ID带来的荣誉，而是能力的收敛与不断的变强，让他看不懂你。

** 2016-01-29 15:53:12
   :PROPERTIES:
   :CUSTOM_ID: section-53
   :END:

[一万小时定律]

人们眼中的天才之所以卓越非凡，并非天资超人一等，而是付出了持续不断的努力。只要经过
1 万小时的锤炼，任何人都能从平凡变成超凡。

阅读: 天赋 VS 勤奋，"一万小时定律" 没你想得那么简单

马太效应：凡是有的，还要加给他，叫他有余；没有的，连他所有的也要夺过来。换句话说，获得特殊机遇的人，他们最终取得更大的进步；富有的因为减税而更富有，成绩优异的因为获得更多老师指导而更优异；冰球队孩子中年纪稍大者因获得更多指导和训练而变得更优秀。这在社会学领域叫做”优势积累”。

昨天晚上把这本书读完了，整本书读的很快，很多细节没有去扣，但是收获颇丰。

个人的成功依赖的因素颇多，主要包括：大环境、时运、努力程度（一万小时定律）等；反而、而智商、天才之说也没必然的关系。

看完之后能让自己更加平静下来，坚持去做事情。

[也谈成熟]

最近和 x 聊的比较多，x
是公司新人，因为公司的一些政治原因被离职后更换部门，作为一个"老人"，我不自觉地唠叨了几句，虽然真实的世界每个人都是要经历的，但是说出来难免有些残酷和悲观，之后很快的意识到自己说的是不是现实了一些。她说："其实你这说的这些我都明白，只不过不愿意面对而已......"。

我才发现我的唠叨似乎是多余的。原来每个人的成长都差不多，大家都不笨，很快的就可以明白其中的道理，只不过有人选择面对，有人选择逃避。

这可能就是人变成熟的真谛，面对以前自己不愿意面对的事物，解决它。自己想想自己以前的想法和做法，也基本上都都是这样的。

今年我基本上很少谈成熟的话题了，也可能自己潜意识里意识到这个问题，走向成熟是每个人必须经历的，也没什么坏处，自己以前的叛逆无非也就是给逃避现实找各种借口罢了。

想说明什么？

1. 不要在用各种理由逃避自己成熟、成长
2. 和人沟通的时候少讲一些大道理，多听听别人的想法，然后帮助别人

** 2016-01-29 16:37:53
   :PROPERTIES:
   :CUSTOM_ID: section-54
   :END:

几年前踏上火车那一刻都还没有意识到，从此故乡只有冬夏，再无春秋.

** 2016-01-29 16:38:41
   :PROPERTIES:
   :CUSTOM_ID: section-55
   :END:

关于联系你这件事 躲得过对酒当歌的夜 躲不过四下无人的街。

** 2016-01-29 16:48:04
   :PROPERTIES:
   :CUSTOM_ID: section-56
   :END:

我淋過最大的雨，是你在烈日中的不回頭。

** 2016-01-29 16:48:28
   :PROPERTIES:
   :CUSTOM_ID: section-57
   :END:

"我希望自己老了的时候，变得更加开阔，能接纳一切人。对身份，对地位，都没有偏见，对世界还很好奇，有正义感，而且能够很勇敢。"

李健

** 2016-01-29 16:58:37
   :PROPERTIES:
   :CUSTOM_ID: section-58
   :END:

此刻时光匆匆消逝化作神奇的往昔，从此以后，它就留在我们的记忆里，照射出不朽之光芒。在将来，尤其到了糟糕恶劣的日子，我们的记忆就会拉起帷幕：此刻时光已经变成了我们内心眷恋和思念的对象。

叔本华《人生的智慧》

** 2016-01-29 16:59:12
   :PROPERTIES:
   :CUSTOM_ID: section-59
   :END:

Fate, however, seems to be not so much unexpected as unavoidable.

命里的事，好像并不那么意想不到，而是在劫难逃。

** 2016-01-29 17:00:40
   :PROPERTIES:
   :CUSTOM_ID: section-60
   :END:

有生之年，每个人都会成为孤儿，只不过，或早或晚而已。

** 2016-01-29 17:07:12
   :PROPERTIES:
   :CUSTOM_ID: section-61
   :END:

"年少时不能遇到太惊艳的人。"

真的，没经历过的人看这句话，永远不会有那种心头一揪、眼前浮现出一个身影、一段回忆、兀自望着发呆的感受。

** 2016-01-29 17:08:00
   :PROPERTIES:
   :CUSTOM_ID: section-62
   :END:

身为企鹅最可悲的一点也许是，

一场激烈的争吵后，

你迈着坚毅的步伐愤然离开，

而在别人眼中却是一个摇摇摆摆卖萌的小可爱。

** 2016-01-29 17:13:27
   :PROPERTIES:
   :CUSTOM_ID: section-63
   :END:

我知道我只能陪你走这一段路，再见之后，各自安静生活数年。

@李豆豆

** 2016-01-29 17:16:20
   :PROPERTIES:
   :CUSTOM_ID: section-64
   :END:

很久之后遇到你，提起你曾经每天早晨7点35准时出现在食堂门口，十分钟之后喝着豆浆出来，脚步轻松背影颀长。

那时我只能悄悄趴在寝室阳台偷看你，想变成你手中的那杯豆浆让你每天醒来都会惦念。

你茫然的告诉我，你很少早上能起来吃早餐，而且你豆类过敏，更不可能喝豆浆。

我忘了怎么跟你告别，连回忆都出了错，何况是你我。

@李狗蛋

** 2016-01-29 17:16:52
   :PROPERTIES:
   :CUSTOM_ID: section-65
   :END:

我知道我只能陪你走这一段路，再见之后，各自安静生活数年。

然后在某个人潮拥挤的街头，透过公车的玻璃窗突然看见你。

我想叫让司机马上停车，想用力拍打窗户来引起你的注意，想从车上跳下来，想奔跑，想大喊大叫，想把整个阻隔在你我之间的世界撕裂。

我呼吸急促，面额潮红，手指颤抖。

我在激烈的想象中把自己感动得快哭了。

而事实总是，我一动不动的坐着，安静的看你远去。

你的脸，从开始到现在，我原来从未曾看清楚过。

@何初夏

** 2016-01-29 17:17:37
   :PROPERTIES:
   :CUSTOM_ID: section-66
   :END:

当一个人不能拥有的时候，他唯一能做的便是不要忘记。

普鲁斯特

** 2016-01-29 17:18:13
   :PROPERTIES:
   :CUSTOM_ID: section-67
   :END:

我去旅行，是因为我决定了要去，并不是因为对风景的兴趣。

加西亚·马尔克斯

** 2016-01-29 17:20:40
   :PROPERTIES:
   :CUSTOM_ID: section-68
   :END:

如果你认识从前的我，那么你就会原谅现在的我。

张爱玲

** 2016-01-29 17:22:12
   :PROPERTIES:
   :CUSTOM_ID: section-69
   :END:

每一个不曾起舞的日子，都是对生命的辜负。

尼采

** 2016-01-29 17:22:32
   :PROPERTIES:
   :CUSTOM_ID: section-70
   :END:

这一生，我为女子，你为公子，倾城相遇，不诉离殇。以诗为鉴，以词为盟，以月为媒，以星为证，今生愿为你费尽思量，共谱一曲莫失莫忘。
终于为那一身江南烟雨覆了天下，容华谢后，不过一场，山河永寂。

** 2016-01-29 17:22:46
   :PROPERTIES:
   :CUSTOM_ID: section-71
   :END:

情不敢至深，恐大梦一场；卦不可算尽，畏天道无常

** 2016-01-29 17:22:54
   :PROPERTIES:
   :CUSTOM_ID: section-72
   :END:

有些人只适合走进你的生活，却走不进你的心里。

** 2016-01-29 17:24:55
   :PROPERTIES:
   :CUSTOM_ID: section-73
   :END:

我是你路上最后的一个过客，最后的一个春天，最后的一场雪，最后的一次求生的战争。

（很纯粹的诗人，这是他写给前妻的诗。）

保尔·艾吕雅

** 2016-01-29 17:27:24
   :PROPERTIES:
   :CUSTOM_ID: section-74
   :END:

你知道吗？风往哪个方向吹，草就要往那个方向倒。年轻的时候，我也曾经以为自己是风，可是最后遍体鳞伤，我才知道，原来我们都是草。

艋舺

** 2016-01-29 17:28:46
   :PROPERTIES:
   :CUSTOM_ID: section-75
   :END:

我们一路奋战，不是为了改变世界，而是为了不让世界改变我们。

《熔炉》

** 2016-01-29 17:30:43
   :PROPERTIES:
   :CUSTOM_ID: section-76
   :END:

世界上最廉价的东西就是男人一事无成时的温柔。

** 2016-02-03 11:24:28
   :PROPERTIES:
   :CUSTOM_ID: section-77
   :END:

今天发朋友圈说：「消失半年，不发朋友圈」，其实半年只是一个随意时间值，我想表达的是，除非
ONCE 上线可以分享到朋友圈，否则我会等。

算是给自己一个要求或者说念想吧。

** 2016-02-03 11:32:07
   :PROPERTIES:
   :CUSTOM_ID: section-78
   :END:

[那个时候我还不明白]

原文：[[http://www.jianshu.com/p/f6b9307520be]]

一九七六年，金庸的长子查传侠在美国自缢身亡。

次年，金庸将十七年前连载完毕的《倚天屠龙记》重新修订，并补上了一段后记。在后记中有这样两句话：

然而，张三丰见到张翠山自刎时的悲痛，谢逊听到张无忌死讯时的伤心，书中写得太也肤浅了，真实人生中不是这样的。

因为那时候我还不明白。 是啊，那时候我也不明白。
初中上学时最讨厌的事情莫过于看到「背诵」二字。需要背诵的课文中，朱自清的散文最是让我恨之入骨，一曰《荷塘月色》，二曰《背影》，一整段全是一小句一小句的白描，文字平白简素，毫无美感可言，当时看得我可是叫苦连天，心中暗想，不就是父亲到车站送别我上火车吗，何必絮絮叨叨地写出这么长的一番话。

大学报到那天，父亲搬起我的行李，气喘吁吁地走在楼梯上。望着那一晃一晃的背影，脑海中又浮现出曾经死记硬背到滚瓜烂熟的那段话：
我看见他戴着黑布小帽，穿着黑布大马褂，深青布棉袍，蹒跚地走到铁道边，慢慢探身下去，尚不大难。可是他穿过铁道，要爬上那边月台，就不容易了。他用两手攀着上面，两脚再向上缩；他肥胖的身子向左微倾，显出努力的样子。这时我看见他的背影，我的泪很快地流下来了。

滚烫的眼泪划过脸颊。

是啊，那时候我也不明白。

念过太多太多的诗词，读过太多太多的故事，哪怕已经深深地刻在脑海中了，可依旧是不明白。

不明白同叔为何要望尽天涯路，不明白稼轩为何会道天凉好个秋。

不明白幽梦里相对无言唯有泪千行的思忆之痛，不明白僧庐下夜听细雨点滴到天明的黍离之悲。

不明白项脊轩中亭亭如盖的枇杷树，不明白姑苏城外独对愁眠的渔火钟声。

课本的注释写得再清晰，老师的讲解说得再透彻，也只懂得词中意，奈何悟不透话中情。

是啊，年少之时，又怎么会懂丧子亡妻，怎么会懂国破家亡，怎么会懂人鬼殊途，怎么会懂名落孙山。

直到某天，书中故事变成了人生，莫名的悲痛涌上心头，不能自已，才大彻大悟，醍醐灌顶，仿似大梦初醒。如梦幻泡影，如露亦如电。

「是啊，那时候我还不明白。」

可有些事，等你明白了，已经太晚。

对不起。

** 2016-02-11 09:48:33
   :PROPERTIES:
   :CUSTOM_ID: section-79
   :END:

作者：Daniel FC

链接：https://www.zhihu.com/question/38426540/answer/77124514

你从来不曾对任何人说出，你经历过的那一段感情；

就好像，你从来未曾爱过她，未曾爱上她一样。

你好像什么都不记得了，不记得那一天，她低着头，不敢直视你的眼睛，却盯着那杯因长久的沉默------

而寒冷的咖啡，如同盯着一个深不可测的湖。

你偶尔会想起那天她扎起了小小的马尾，戴着粉色的耳钉，像一只初生的松鼠；
但你当然不会想起那天，她嗫嚅着说了什么。

「我想我们还是先分开一段时间比较好......」

她嗫嚅地说，似乎带着征询；但语声低微，几不可闻。你知道说些什么，可以把她挽留下来；

你也知道，无论说什么，什么都无可挽留了。你听着秒针滴答。

你甚至不知道她什么时候离开，只知道你终究喝完了那杯早已凉透的红茶拿铁。暮色四合。你如常生活、如常工作。只是偶尔，觉得与周围，如同隔着一层滞重的雾。

只是偶尔。

你终究忘记了她。忘记了她的调皮或无理取闹。

忘记了她喜欢眯起眼睛笑，脸红的时候像个半熟的苹果。

但还是不对劲，就像经历了一场大手术，麻醉未退。整个人昏昏沉沉、麻麻木木。

你觉得身体里缺失了什么东西。或许是淋透一场大雨、或许是又一个彻夜不眠------很久以后，你才想起，那一天，你的感受：

一只无形的怪手，伸进腔子里，把身体掏空。

以一种挖掘砂石的方式。

粗暴无情地。猛烈。难受，

说不出话。四周沉默得听见秒针滴答。那种被麻痹了数月的难以忍受的痛。袭来（混杂着迟来了4320个小时的酸楚）你久违地，有流泪的冲动。

（大哭一场，就可以得救了。）

而你笑笑，对身边的人说：

「我有点累了......」

这就是想通。

** 2016-02-11 09:50:28
   :PROPERTIES:
   :CUSTOM_ID: section-80
   :END:

夕阳最美时，也总是将近黄昏。

世上有很多事都是这样子的，尤其是一些特别辉煌美好的事。

所以你不必伤感，也不用惋惜，纵然到江湖去赶上了春，也不必留住它。

因为这就是人生，有些事你留也留不住。

你一定要先学会忍受它的无情，才会懂得享受它的温柔。

古龙《白玉老虎》

** 2016-02-11 09:56:20
   :PROPERTIES:
   :CUSTOM_ID: section-81
   :END:

我不再装模作样地拥有很多友人，而是回到了孤单之中，以真正的我开始了独自的生活，有时我也会因为寂寞而难以忍受空虚的折磨，但我宁愿以这样的方式来维护自己的自尊，也不愿以耻辱为代价去换取那些表面的朋友。

余华《在细雨中呼喊》

** 2016-02-13 16:01:48
   :PROPERTIES:
   :CUSTOM_ID: section-82
   :END:

影响人生命运的选择，不是在某个重要的关头，某些很大的事上，而是在一些很无谓的事情上。

《一个字头的诞生》

** 2016-02-17 10:04:29
   :PROPERTIES:
   :CUSTOM_ID: section-83
   :END:

[豆瓣对你来说意味着什么？]

http://www.douban.com/note/539797398/

我们的精神角落。

除了一个小秘密，我只是一个极其平凡的人。

最懂你的人，不一定认识你。

对这个现实世界，再现实的人，也有自己的狂想。

曾循环最久的歌单，是妈妈的心跳。

有人驱逐我，就有人欢迎我。

你追求的，正是你不想再失去的。

** 2016-02-18 09:07:04
   :PROPERTIES:
   :CUSTOM_ID: section-84
   :END:

回首应该加一个音乐分享功能。

** 2016-02-18 15:24:20
   :PROPERTIES:
   :CUSTOM_ID: section-85
   :END:

这世上有许多人每天做的事就是不断将一只脚放到另一只脚前面，日子久了，生活便显得平淡无奇。

一个人的朝圣

** 2016-02-26 14:13:38
   :PROPERTIES:
   :CUSTOM_ID: section-86
   :END:

每个人心里都有一团火，路过的人只看到烟。但总有一个人，总有那么一个人能看到这团火，然后走过来，陪我一起。我带着我的热情，我的冷漠，我的狂暴，我的温和，以及对爱情毫无理由的相信，走的上气不接下气。我结结巴巴对她说：你叫什么名字。从你叫什么名字开始，后来，有了一切。

------梵高

** 2016-02-27 13:06:27
   :PROPERTIES:
   :CUSTOM_ID: section-87
   :END:

年前开始读小李飞刀系列（多情剑客无情剑，边城浪子，九月鹰飞，天涯明月刀，飞刀又见飞刀），一两个月吧，今天读完了。

年少的时候，总有仗剑江湖的梦想，有大块喝酒，大碗吃肉的豪爽，有相逢一笑泯恩仇的胸怀。甚至想象过：秋风萧瑟，月半，一人，一剑，一壶烈酒，宿醉。

大学的时候喜欢许巍的歌，喜欢古龙的江湖，向往着那种简单，洒脱的生活，向往着无根浪子无止境的流浪，以为自己能够理解哪种孤独。所以，那个时候，唯独喜欢叶开，讨厌李寻欢。

然后，当向往的生活逐渐成了现实的时候，当开始流浪的时候，当自己逐渐能够理解那种深深的孤独的时候，才发现不是那样的。

不想再读古龙，也许可能开始懂了。

所有，未达到，想达到的。可能，都不是你想要的。

** 2016-03-01 09:23:42
   :PROPERTIES:
   :CUSTOM_ID: section-88
   :END:

微信又加了一些同事，越来越工作化了，基本上已经逐渐告别朋友圈了。

以后朋友圈只能偶尔发发「好的」，「坏的」还是继续发到这里吧。

** 2016-03-01 09:25:57
   :PROPERTIES:
   :CUSTOM_ID: section-89
   :END:

网易云音乐的分享功能做的真棒，以后 ONCE 得向他们学习。

话说，有生之年能做一款不为满足大众眼光，情怀式的小众产品，也是很不错的一件事情。

** 2016-03-12 22:41:32
   :PROPERTIES:
   :CUSTOM_ID: section-90
   :END:

没成功之前，不要轻易向别人谈及自己的想法。

** 2016-03-12 22:43:57
   :PROPERTIES:
   :CUSTOM_ID: section-91
   :END:

要么庸俗，要么孤独。------叔本华

** 2016-03-14 08:58:39
   :PROPERTIES:
   :CUSTOM_ID: section-92
   :END:

你是什么时候爱上我的？

属于它的时间是边界模糊的土壤，并没有一块界碑分明，写定，我对你的爱情，在这一线从无到有。它无非是某一时刻砰然心动，某一时刻情根深种，某些时刻辗转反侧，某些时刻静海深流。只是它一经存在就寸土不让，直到令我在所有的时刻，所有的时刻，对你念念不忘。

------月褪《错过你为遇见谁》

** 2016-03-14 08:59:20
   :PROPERTIES:
   :CUSTOM_ID: section-93
   :END:

[why once, 1]

当社交软件真的干起社交的事以后，它可能就只能干社交的事了。

QQ空间其实是挺好的写东西的地方，QQ说说也是挺好的分享心情的地方。上了大学以后，「朋友」多了，就不怎么写了，总觉得矫情，也是那个时候有了写了删的习惯。

人都是这样，对于过去，总想把辉煌的方面留下来，令人讨厌的抹去。甚至当时很骄傲的地方，现在看来也是不值一提。

毕业以后，QQ上有了很多工作上的朋友，以前的东西不愿意让别人看见，就索性把空间关了。

刚开始，微信的出现，一大程度上拯救了QQ的非社交部分。让真正的朋友有了朋友圈，可以像以前一样小群体嗨。

然而，很不幸，微信也开始逐渐取代了QQ，成为工作上的通讯手段。

朋友圈里可能有了你的上司，你的同事，甚至你由于工作的关系不得已加了一些你很讨厌的人。

我是一个很喜欢碎碎念的人，喜欢把自己看到的，想到的记录下来，写给我的「朋友们」看。从去年不知道什么时候开始讨厌自己发的东西，就全删了。后来实在抑制不住自己碎碎念的冲动，就写一条删一条。

社交工具越发达，我们越孤独。是因为他们仅仅解决了语言上的沟通问题，却没有解决一些隐形感情的的沟通问题。比如，我的开心想给一部分人看，我的失落要给另外一部分人看。如果做不到的话，那结局就是我不给任何人看。

我要做一个可以自嗨的平台。

** 2016-03-17 12:01:03
   :PROPERTIES:
   :CUSTOM_ID: section-94
   :END:

面试别人之后才知道，原来自己挺值钱的。

** 2016-03-30 13:42:10
   :PROPERTIES:
   :CUSTOM_ID: section-95
   :END:

谨言慎行，少说话，多做事

** 2016-04-04 21:16:42
   :PROPERTIES:
   :CUSTOM_ID: section-96
   :END:

折腾一天，回去吃饭，睡觉。

** 2016-04-05 10:47:50
   :PROPERTIES:
   :CUSTOM_ID: section-97
   :END:

著作权归作者所有。 商业转载请联系作者获得授权，非商业转载请注明出处。
作者：木易 链接：http://zhuanlan.zhihu.com/p/20474215 来源：知乎

如果我问你艺术,你可能会提出艺术书籍中的粗浅论调。

有关米开朗基罗,你知道很多，他的满腔政治热情，与教皇相交莫逆，耽于性爱，你对他很清楚吧？但你连西斯汀教堂的气味也不曾嗅到？你未曾站在那儿，昂首眺望天花板上的名画吧？可是我见过。

如果我问关于女人的事，你大可以向我如数家珍，你可能上过几次床。但你没法说出当自己在女人身旁醒来时，那份涌自内心真正的喜悦。

你年轻彪悍，我如果和你谈论战争，你会向我大抛莎士比亚，朗诵"共赴战场，亲爱的朋友"但你从未亲临战阵，未试过把挚友的头拥入怀里，看着他吸着最后一口气，凝望着你，垂死向你求助。

我问你何为爱情，你可能只会吟风弄月，但你未曾试过全情投入真心倾倒。

四目交投时彼此了解对方的心，好比上帝安排天使下凡只献给你，把你从地狱深渊拯救出来对她百般关怀的感受你也从未体会，你从未对她情深款款矢志厮守，明知她患了绝症也在所不惜，你从未尝试过痛失挚爱的感受。

你也从未经历过在她的病床前坚定不移地陪伴，紧握着她的纤手，因为医生知道你根本就不在乎"探访时间"的明文约束。

你不了解真正的失去，唯有爱别人胜于自己才能体会。

我怀疑你从未付出过这样的爱。

现在我看着你，眼前所见并非一位聪敏、自信的男人，而是一个无耻狂妄、内心恐惧的孩子。但是你是个天才，威尔。

这是毋庸置疑的。没人可以完全认识到你的深度。

但是你在我的油画上瞥过一眼、就以为了解了我的一切？你的狂言糟蹋了我的人生！你是个孤儿吧？但你认为我能看穿你的悲惨生活、认识你的全部，仅仅因为我读过《雾都孤儿》？莫非它能简化你的人生？

个人而言，我对此莫不关心。因为你知道吗？我无法通过一些破书来认识你的一点一滴。

除非你先谈论自己，告诉我你到底是谁。

于是我对此着迷，我愿意来帮助你。

但是你并不想这么做，是吗？你甚至还怕你会被说出来的话吓到。

** 2016-04-06 10:44:39
   :PROPERTIES:
   :CUSTOM_ID: section-98
   :END:

戴荃·悟空

叫一声佛祖 回头无岸 跪一人为师 生死无关

@944黄小刀: 今天去看了大圣归来。 我旁边有个小孩儿问他妈妈
"这个不是动画片么？为什么有这么多大人来看？" 他妈妈回答：
"因为他们一直在等大圣归来啊，等啊等啊，就长大了." ------泪目~

@古乙丁三雨_:
曾经我以为如来老儿是世上最烦的人，毕竟他压了我五百年。直到我遇见江流儿，他念了我一辈子。

** 2016-04-10 11:43:52
   :PROPERTIES:
   :CUSTOM_ID: section-99
   :END:

早起的第一反应是没有迟到，第二反应是今天是不是工作日。

作为一个职场人，我感到一些悲哀。

** 2016-04-12 09:07:26
   :PROPERTIES:
   :CUSTOM_ID: section-100
   :END:

@默默:
为什么想要不断尝试新的东西，不断重新推翻自己。因为我逐渐意识到，当你停止创造，你得才能就不再重要，剩下的只有品味，品味会排斥其他人，让你变得更狭隘，所以，要创造。

来自饭否每日精选

** 2016-04-13 17:37:17
   :PROPERTIES:
   :CUSTOM_ID: section-101
   :END:

你千万别和任何人谈起任何事情，只要你谈起，就会想念起每一个人来。

为了这一句话，买了《麦田里的守望者》，可惜看了一半就放弃了，实在看不下去。

** 2016-04-16 11:29:29
   :PROPERTIES:
   :CUSTOM_ID: section-102
   :END:

域名买了，备案也过了，不容易啊。

** 2016-04-16 14:59:35
   :PROPERTIES:
   :CUSTOM_ID: section-103
   :END:

以前觉得 Windows 挺好的，看惯了 Mac 屏幕以后，现在总感觉 Windows
的屏幕是糊的。

** 2016-04-17 21:38:15
   :PROPERTIES:
   :CUSTOM_ID: section-104
   :END:

[写文字的那些事儿]

虽然是个理科生，但是我从小就特别喜欢语文，见到一些美好的、有趣的文字，总会收藏下来。在朋友圈故作深沉和忧伤，这些文字可算是立了大功了。

自从逐渐开始写一写零零碎碎的事情之后，发现写技术文章毫无乐趣，而且没什么写作技巧而言。技术文章的核心点在于把问题描述清楚，思路清晰、直截了当通常是评判一篇技术文章是否合格的第一要素，解决用户的痛点嘛。

而非技术类的文章是有些不同的，如果要直截了当的描述问题，几百字的文章，几句话就说清楚了。所以，我以为这种碎碎念性质的文章，看似简单，实际很难。技术文章，需要技术功底，做一番调研和验证即可；闲扯类的文章需要你对周遭的事物有自己的理解，并且需要一定的社会经历。

有了写东西的习惯以后，发现在一段时间内不写东西总感觉少了点什么，一些新的想法总想一吐为快。

时间长了，我很快就发现了另外一个问题：自己对自己的行文表达手法越来越厌恶。记得在写在西农系列的时候，很多精力都用在如何把前后两句话连接起来，比如：「其实」、「也许」、「可能」、「说真的」、「发现」、「感觉」
... 类似的词汇都用烂了，自己也不想用，但是想不出更好的表达手段。

古龙，应该是我看过的最多的书的作者了，有些东西已经深深的成为自己的性格的一部分。比如，快意恩仇的江湖、以酒为伴的流浪、生而为人，那种深深的孤独。在写
在西农-S12: 陈东坡(http://blog.zhangjiee.com/in-xinong-s12.html)
这篇文章的时候，我刻意的模仿了一下古龙的写作手法，比如下面这一段：

#+BEGIN_QUOTE
  陈东坡。 确切来讲，我们不算同学，没一起做过事，聊的也不多。
  但是他是我的朋友，老朋友。
#+END_QUOTE

现在看看也挺好玩的，但是我发现写这样一篇文章太难了。对我来讲，偶尔矫揉造作一两句还可以，毕竟，装逼这种事情，我个人还是很擅长的。通篇这样玩，自己看了也会恶心。

我平常看的公众号，MacTalk 和 小道消息 应该是最多的了。MacTalk
早期文章写作风格，我还是挺喜欢的，最近一年左右的的技术周边类的文章，我越来越不喜欢了。文字过于华丽，让我感觉很多地方都在套字，看完之后文章到底说了一件什么样的事，反倒没啥印象了。相比，Fenng
的文章则不同，始终如一，言辞犀利，恰到好处。

我认为，每个文章的写作者都应该有自己的风格，我所追求是真实厚重的文字，宁愿爆粗口也不愿隐晦婉转，更不愿意哗众取宠，逗众人一笑。

路还很长啊~

** 2016-04-19 09:46:36
   :PROPERTIES:
   :CUSTOM_ID: section-105
   :END:

它类似一种少年时代的憧憬，一种从来不曾实现而且永远不能实现的憧憬。这种直欲燃烧般的天真烂漫的憧憬，我在很早前就已遗忘在什么地方了，甚至很长时间里我连它曾在我心中存在过都没有记起。

挪威的森林

** 2016-04-20 09:08:44
   :PROPERTIES:
   :CUSTOM_ID: section-106
   :END:

人生，其实像一条从宽阔的平原走进森林的路。

在平原上同伴可以结伙而行，欢乐地前推后挤、相濡以沫；一旦进入森林，草丛和荆棘挡路，情形就变了，各人专心走各人的路，寻找各人的方向。

那推推挤挤同唱同乐的群体情感，那无忧无虑无猜忌的同僚深情，在人的一生之中也只有少年期有。

龙应台

** 2016-04-20 17:09:08
   :PROPERTIES:
   :CUSTOM_ID: section-107
   :END:

我想起自己在过去的人生旅途中失却的许多东西------蹉跎的岁月，死去或离去的人们，无可追回的懊悔。

挪威的森林

** 2016-04-20 17:10:42
   :PROPERTIES:
   :CUSTOM_ID: section-108
   :END:

我想，文章这种不完整容器所能容纳的，只能是不完整的记忆和不完整的意念。

并且发觉，关于直子的记忆愈是模糊，我才能更深入地理解她。时至今日，我才恍然领悟到直子之所以求我别忘掉她的原因。

直子当然知道，知道她在我心目中的记忆迟早要被冲淡。也惟其如此，她才强调说：希望你能记住我，

记住我曾这样存在过。

挪威的森林

** 2016-04-26 09:10:12
   :PROPERTIES:
   :CUSTOM_ID: section-109
   :END:

昨天晚上做梦梦见 once 被攻击了，满屏幕都是图片，今天一看并没有，好失望~

** 2016-04-26 11:45:14
   :PROPERTIES:
   :CUSTOM_ID: section-110
   :END:

刚开始用框架的时候，觉得框架能做的事情不够多；用的时间长了，觉得框架做的事情不够少。

** 2016-04-29 10:10:09
   :PROPERTIES:
   :CUSTOM_ID: section-111
   :END:

常与同好争高下，不与傻瓜论断长

** 2016-05-03 11:04:44
   :PROPERTIES:
   :CUSTOM_ID: section-112
   :END:

都说时间可以冲淡一切，

其实，不会。

人是非常现实的动物，只有感觉被彻底替代以后才会出现所谓的冲淡。

** 2016-05-04 15:35:11
   :PROPERTIES:
   :CUSTOM_ID: section-113
   :END:

长时间不和别人交流，表达能力越来越弱了。

怎么办呐！！

** 2016-05-06 10:19:36
   :PROPERTIES:
   :CUSTOM_ID: section-114
   :END:

朱哥语录：

1. 从此之后遇到的姑娘一个比一个差
2. 看不懂不要说人装逼，对不理解的事情保持敬畏

** 2016-05-12 14:10:34
   :PROPERTIES:
   :CUSTOM_ID: section-115
   :END:

在你有一个好的想法，说给被人听的时候；

在你完成了一件巨牛逼的任务，说给被人听的时候；

在你有一些想法不确定需要跟被人商讨的时候；

在你肚子摸索一些从来没有接触过的平台和技术的时候；

没有一个人能够与你沟通，这就是创业公司。

写代码写着写着各种焦躁不安，有的时候能让自己发疯，但是当我想停下来的时候，总是被自己当初的选择惊醒。

我常常慰自己：「如果这种日子，我都能熬的下去，还有什么事情做不到呢」。问题是什么时候才是个头。

** 2016-05-18 17:47:38
   :PROPERTIES:
   :CUSTOM_ID: section-116
   :END:

自认惊叹的桥段终沦为老生常谈。

** 2016-05-19 11:46:04
   :PROPERTIES:
   :CUSTOM_ID: section-117
   :END:

社交，是迄今为止，我做过最累的一件事。

** 2016-05-21 11:11:59
   :PROPERTIES:
   :CUSTOM_ID: section-118
   :END:

现在为啥没有静下心学一门技术的心呢。

** 2016-05-26 10:12:13
   :PROPERTIES:
   :CUSTOM_ID: section-119
   :END:

与其抱怨，不如改变。

** 2016-05-27 16:28:08
   :PROPERTIES:
   :CUSTOM_ID: section-120
   :END:

重复性的代码写的人真想骂娘！

** 2016-05-27 16:32:32
   :PROPERTIES:
   :CUSTOM_ID: section-121
   :END:

按照现在的开发节奏，ONCE 的下个版本要等到明年或者后年了......

** 2016-05-31 10:16:26
   :PROPERTIES:
   :CUSTOM_ID: section-122
   :END:

你以为有很多人在陪着你， 其实，你永远只是一个人。

** 2016-05-31 16:37:24
   :PROPERTIES:
   :CUSTOM_ID: section-123
   :END:

万里长征第一步啊。

** 2016-06-01 08:55:25
   :PROPERTIES:
   :CUSTOM_ID: section-124
   :END:

微信朋友圈应该增加「允许点赞」、「允许评论」、「是否公开」等功能。

** 2016-06-03 16:07:41
   :PROPERTIES:
   :CUSTOM_ID: section-125
   :END:

好的设计方案，原来真的是越做越简单，赞。

** 2016-06-16 16:44:52
   :PROPERTIES:
   :CUSTOM_ID: section-126
   :END:

小时候刮奖刮出"谢"字还不扔，非要把"谢谢惠顾"都刮的干干净净才舍得放手，和后来太多的事一模一样。

知乎@Catalina

** 2016-06-27 09:49:40
   :PROPERTIES:
   :CUSTOM_ID: section-127
   :END:

当初选择 Python 本身就是一个错误。

** 2016-06-29 09:19:40
   :PROPERTIES:
   :CUSTOM_ID: section-128
   :END:

要开始写东西了！

** 2016-06-30 08:45:10
   :PROPERTIES:
   :CUSTOM_ID: section-129
   :END:

在合肥，最让我不能理解的是，这些姑娘竟然在电梯里吃鸡蛋！

** 2016-07-01 10:07:22
   :PROPERTIES:
   :CUSTOM_ID: section-130
   :END:

跌跌撞撞，全都是小坑。

要开始整理印象笔记，写技术文章和wiki了。

** 2016-07-03 14:21:38
   :PROPERTIES:
   :CUSTOM_ID: section-131
   :END:

比搜索更靠谱的是官方文档，比官方文档更靠谱的是源代码。

** 2016-09-17 17:34:47
   :PROPERTIES:
   :CUSTOM_ID: section-132
   :END:

生病之后才会发现三件事情的重要性：女朋友，健康，钱。

** 2016-09-21 09:13:31
   :PROPERTIES:
   :CUSTOM_ID: section-133
   :END:

优秀的软件系统，应该是越做越合理，越做越简单。

** 2016-09-27 16:08:00
   :PROPERTIES:
   :CUSTOM_ID: section-134
   :END:

崩溃。

** 2016-09-27 19:19:29
   :PROPERTIES:
   :CUSTOM_ID: section-135
   :END:

从业时间长了，发现这样个简单地道理：很多很艰难很复杂的技术，找一本基础书籍或者文档，就可以找到答案。

技术上的「野路子」看起来似乎很美好，实际上并非如此。

** 2016-09-29 09:39:54
   :PROPERTIES:
   :CUSTOM_ID: section-136
   :END:

等微信小程序正式上线以后，就可以我自己做客户端了，哈哈哈

** 2016-09-30 10:00:18
   :PROPERTIES:
   :CUSTOM_ID: section-137
   :END:

自从换了耳机以后，就不想听家里的音响了，感觉同一首歌放出来都是两个味道。

** 2016-10-02 10:48:03
   :PROPERTIES:
   :CUSTOM_ID: section-138
   :END:

不要告诉别人，别人应该做什么；更不要告诉别人自己要去做什么。

这都是极大的时间浪费。

** 2016-10-02 11:50:25
   :PROPERTIES:
   :CUSTOM_ID: section-139
   :END:

在季节的车上，如果你要提前下车，请别推醒装睡的我，这样我可以沉睡到终点，假装不知道你已经离开。------张嘉佳
从你的全世界路过

** 2016-10-03 17:05:24
   :PROPERTIES:
   :CUSTOM_ID: section-140
   :END:

1. 湄公河行动 看完了，国产电影拍出了美国大片的感觉，很赞，值得一看；
2. 看了几次电影了，每次都有人从头 BB
   到尾，吃东西的，带小孩的，菜市场即视感。为省会城市的国民素质感到担忧，为自己感到悲哀；
3. iOS系统升级到 10
   以后，感觉系统慢了好多，但是锁屏的声音和按键声音比以前好听多了。

** 2016-10-04 12:25:02
   :PROPERTIES:
   :CUSTOM_ID: section-141
   :END:

我现在想明白了，做任何事情之前都要琢磨清楚这件事情的「利润」有多少。

如果「利润」为或者很小就别做了吧；如果是必须要做的，比如需要写几天业务代码，而这些业务代码，你闭着眼睛都可以写完；那么要做的就是找一个高效的时间段，把事情累积到一起，一次性搞定，再也不去碰了。

如果「利润」很大但是暂时的，比如帮别人做一个网站，给你报酬，但是这件事情本身没什么技术含量。这个时候，就要考虑了，我是不是有更重要的事情去做，如果实在没事情可以做了，才可以考虑去做。

如果「利润」一般，但是是长期的，一周、一个月、一年、五年、十年、一辈子。以五年或三年为中轴线，画一个正太分布曲线，来区分重要等级。重要等级越高，越应该不假思索的投入大量的精力去做。

对一周、一个月有意义的事情，比如收拾房子，买菜，洗衣服，看电影等，这些事情耗费较少的时间，但是却可以极高的提高生活质量。

对一年、三年有意义的事情，一般都是针对职场，比如学习基础知识、看文档，学一两门新技术，大量的阅读等等，这些事情应该是对当前最重要的事情。

对五年+有意义的事情，比如培养一个爱好，听音乐，写作，锻炼身体，看非技术类书籍等等，这些事情应该培养成个人习惯。

** 2016-10-09 17:04:46
   :PROPERTIES:
   :CUSTOM_ID: section-142
   :END:

有 bug，删除记录无法还原......

沃日哦。

** 2016-10-17 18:03:19
   :PROPERTIES:
   :CUSTOM_ID: section-143
   :END:

我以前觉得每个函数都应该写到最优，现在觉得得分时候，框架层面的改优化则优化，业务层面的如果没什么重用性丑一点也没关系。

开始重构之前，要权衡一下时间投入和实际的产出比。

** 2017-01-17 15:49:59
   :PROPERTIES:
   :CUSTOM_ID: section-144
   :END:

不知道要忍受多少孤独，才能真的变的牛逼起来。

** 2017-02-08 18:24:36
   :PROPERTIES:
   :CUSTOM_ID: section-145
   :END:

1. 理论基础 vs 身体四肢
2. 思维 vs 内功
3. 技术、工具 vs 招式

** 2017-10-12 10:54:48
   :PROPERTIES:
   :CUSTOM_ID: section-146
   :END:

总会越来越好的。

** 2018-12-11 21:58:56
   :PROPERTIES:
   :CUSTOM_ID: section-147
   :END:

还好有 ONCE 数据备份，就把 2016 年在 ONCE
发表的将近两百条记录手动迁移到了网站上，关闭 ONCE
的时候，只想着备份，也没想过有一天还可以再次贴出来留作纪念。

ONCE 像我众多小产品一样，上线了两三年就下线了。对我来讲，它承载的是 2016
年的心境，时而干劲十足，时而焦躁不安，时而又迷茫万分，然而，过去的始终就过去了，不想再去探究和追悔什么，毕竟未来还有更长的路要走下路。

最后，用 ONCE
最初的那句话来做为结束：「当所有等待都变成曾经，我会说好多精彩的故事给你听」。

*但是我不会讲给你听了。*
