#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 写写最近
#+DATE: 2013-03-30 15:24:40

好久不写东西了，突然间不知道怎么下手。写写最近这一个月吧，算是一种总结。

月初（3月份）公司 HR
召唤我，我几经波折终于去医院成功的开了一个证明，终于结束了我长达 7
个月之余的"休假"生活。公司的变化还是挺大的，不过我们部门的人还都没变化，这个挺好。

现在做的事情，我也不太好定位，不知道别的公司研发人员所干的事情是不是和我一样。刚来公司，还是挺适应的，毕竟去年实习了一两个月，导致大家都不当我是新人了。至于公司内部我个人的一些想法，就不说了吧，感觉不太好。

选择风行，其实很简单，比较适合我的性格。我们部门的人也都比较和谐，沟通上也没什么障碍。我需要的条件不高，软件或者硬件都可以忍受。唯一一个要求就是人文，这一点上我们部门做的不错，整个公司的话，不评价，没有调研就没有发言权。

这一个月算是比较累吧，感觉很充实。日子过的比较凌乱，需要定期的整理一下生活，我一般周末找个时段总结一下做了那些事情，包括工作/个人两个部分。

每周末都会去找祥子聊一聊，没什么变化，和大学一样。不过给祥子带了不少的经济负担，等我发工资就好了。

来的第二周和 [[http://www.wutianqi.com][TankyWoo]]、胖子、啪啪啪
在北邮聚了一次，聊了聊。Tanky
我比较熟了，其他两个不太熟，不过还好，技术型男在一起总是有一些东西可以聊的。Tanky
第一印象挺好的，我们第一次见吧（嗯，我们是"网恋"），说话上直截了当，没什么做作，符合我性格。在他们身上还是可以学到很多东西的，也顺便见识一下"高富帅"。

连续几周周五晚上去网吧通宵打
Dota，很爽，但是很累，身体有些扛不住。需要多锻炼。

前段时间收到 chen huimin
同学的一封邮件，素不相识，交互了几次，聊的很投机。最后一封邮件是我今天回复的，抽不开时间。其实不是那么忙，只是假如你认真的去做一件事情的时候，总需要静下来想一想。很多时候，我在说没时间也都是这个缘故。如果随随便便的就可以搞定一件事情，那那件事情需要做的必要性就不是很强了。

有一种人，当你第一次跟他/她聊的时候，就感觉认识了很久了。说出来的话，很真心、很实在。感觉不到任何的做作，balabalabala
跟你说一堆。我喜欢和那种人做朋友，少了很多麻烦。我是那种人，但是很多人似乎不喜欢这种人，这一点我已经验证了太多次了。

实在不喜欢北京这个城市，环境污染太严重。我刚过来那段嗓子一直难受，总感觉理不清。都
4 月份了，气温还是相当不稳定，能 TM 冻死我。

--------------

*2009 伍声*
说："......我心里清楚，在你没有做出成绩之前，这个世界不会在乎你的自尊......"，感触挺多的，引发了我的很多思考，先做点东西再扯淡吧，要不然都是废话。

越来越感觉，我们需要感恩，感谢父母，感谢朋友，感谢这个世界提供给我们的东西，而不是去抱怨。一旦你的想法发生了改变，很多事情都彻底的变了。
