#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 从我是歌手所想到的
#+DATE: 2013-04-13 14:29:06

在家的时候，湖南卫视在做《我是歌手》的宣传，力度很大，视觉冲击也很大。后来上班了，就再也没有关注这方面的东西。偶然一天周末，扫了几眼就沉溺了，不得不说很棒。

我看到了他/她们的真实和真诚。

没有很仔细的看过所有的比赛，只是简短性的扫完了所有的自己觉得很好听的片段，所以断断续续的听，那我就断断续续的写吧。

时代不一样的，很多好听的歌曲不再为人所知，齐秦就是一个很明显的例子。他的退出，我想是一种无奈，这无奈之中更多的是年华和时代吧。多好的曾经也抵不过岁月，这是多么残酷的现实。

尚雯婕的歌，我以前没听过什么，但是我听过有这个人。我对超级女声这种节目从没有什么好印象。我看过她的演唱之后，逐渐的开始喜欢这个舞台上的女王。她的舞台表现力太强了，给人感觉很潮很兴奋。对于她的淘汰，我只能说是里面的规则而不是她的实力，她完全可以留在最后的。我记得最后她说过的话，她曾经提过一些自己的大胆的想法（对于Super
Star的改变），可是（别人考虑）保住位置的问题，只能选择保守。在我想，她心里有一百种、一千种不服。可是又能怎么样呢？

周晓鸥的加入，并且坚持到最后，我觉得非常不容易。不容易的因素有很多，其中最大的是因素就是流行音乐和摇滚乐之间的隔阂，摇滚乐对于大众来说太陌生了，大部分无法感受到周晓鸥所展现出来音乐的好或者坏。《无地自容》因为大众耳熟能详，所以得到了高分。用《不再掩饰》在致敬中国的摇滚之父"崔健"，居然排了第七，我没有觉得《不再掩饰》要表现的比《无地自容》差，两个都很优秀。

"曾感到过寂寞，也曾被别人冷落，却从未有感觉，我无地自容！"
------《无地自容》

"我的自由也属于天和地，我的勇气也属于我自己" ------《不再掩饰》

周晓鸥说："坦白说上一场比赛最后一名对我来说压力是蛮大的，但我还是希望替摇滚把这个位置给留住"。他很努力，他也做到了，感谢他。

其实对于最后一场选歌，他选择郑钧的《天下没有不散的筵席》，我感觉很不合适。谭维维表现的很出色，她第一嗓子出来，我很震惊，这个小姑娘好牛逼。周的声线和郑钧差距很大。如果要我给周晓鸥选一首郑钧的歌的话，我会选择《长安，长安》，相信从周口中喊出"长安，长安"会是另外一种不错的风味。不过，无所谓了，享受他自己就可以了，摇滚不该是这样吗？

辛晓琪，她让我感觉真诚、感性、善良、还有几分纯真可爱的一个女人。她没有很在乎过自己在我是歌手中的位置，只是用自己的歌声传达着自己想传达的东西。

对于黄琦珊，我只能说我不懂她的音乐，可能没有她的经历，所以不懂。

好吧，谈一谈羽泉和林志炫。

羽泉，下了一盘很大的棋。在整个过程中，他们都在一个安全的位置，没有特别的嘲讽，没有成为别人的集火点，一步一步的奠定自己的位置，可能观众朋友们也没有想到他们最终可以夺冠。

1. 羽泉实力很强，有几个点可以表现出来。首先一点就是他们的歌曲改编能力，每一首歌都让你感觉到和原唱近乎不同，但是又别有一番风味；其次，这个组合是一个很好整体，高低和低音部分配合近乎完美；还有，他们的舞台表现能力，他们的演唱无一不带动观众的节奏，让现场沸腾。
2. 羽泉很喜欢音乐，这句话有些废话，相信每一个参加到我是歌手的歌手，都很喜欢音乐。我能感受到他们的不同，别人在台上都很享受，但是羽泉的享受中夹杂了一些玩音乐的心态。
3. 羽泉很努力，每一次现场表演都可以看出他们在背后花费了很大的精力在改编歌曲上，做了很多的准备工作，做到了自己的最好。
4. 羽泉很聪明，从选歌上可以看出来，对比一下几位歌手的选歌你就会发现了。羽泉所有选择的歌都是大众特别耳熟的歌，《男人哭吧不是罪》、《大中国》、《再回首》、《热情的沙漠》、《心似狂潮》。选歌没有一次冒险，即便是效果差，也绝对不会到淘汰的份上。他们很懂得观众需要什么，其实普通大众对音乐的要求仅仅在于好听，朗朗上口。表达情感非常丰富，让人哭的稀里哗啦的或者另类的歌曲大众可能很少去深入的研究。仅仅这一点上，羽泉做的很好。他们在别人听烂的歌上，让人感到很多的不同，而那些不同又做的很好。
5. 最后一点是羽泉得天独厚的优势，就是这些所有歌手里面传唱度最高的歌手就是他们。他们的一部分人气在这个比赛开始之前就有了。

如此的组合，怎能不赢？

林志炫，我想林志炫的出现打破了我是歌手的格局，他的出现也为我是歌手增加了非常多的亮点。我不说什么，那我上面列过羽泉的很多点和林志炫相比，你会发现林志炫和羽泉还是有一些差距的。林志炫能跟他们抗衡只因为他别人更真诚的去做自己喜欢的音乐，他的音乐很单纯，没有加入任何世俗的成分。他做，完全是因为自己非常喜欢。

1. 林志炫在谈及加盟《我是歌手》的初衷时表示："我之前入围过7次金曲奖，但从来没有得过奖。可是我的父亲告诉我，更重要的是入围的次数，这代表那一段时间内是被大家所认可。我觉得这一辈子最重要是两件事，一个是好歌，一个是知音，到了《我是歌手》的舞台上，我是带着好歌来求知音来的，人生如得到这两样，夫复何求。"------百度百科
2. 我觉得我来这边就是唱歌给大家听，大概我排了有八首想唱给大家听的歌。当然我不确定我能够唱多少首，但
   是总是一份诚意。 ------林志炫谈参加《我是歌手》的意义
3. 我其实今天是来开“耳界“的，我觉得透过这样一个节目跟大家交流，然后我可以从各位的身上了解各位的拿手绝活，真的是一个很好的学习的机会！加油！------林志炫谈空降《我是歌手》赛后感受
4. 其他

   - 我一直觉得自己是歌手，不是明星。
   - 我只為自己做唱片，我只挑自己喜欢的歌，我有感觉的歌，我爱的歌，这个出发点很自私.
   - 我做唱片的过程，不但自私，而且笨。
   - 我爸其实很担心我，我只要一做唱片，他就會去關心我存款的數字。基本上就像是坐雲宵飛車，往上爬的速度慢，往下直接一滑到底。
   - 我觉得一辈子一个歌手求兩件事。一个是好歌，一个是知音。
   - 我有一個很大的缺点就是：我只要跳到音乐裡面，就會太忘我。可能會忘記某人的生日，忘記打電話給誰，甚至于提前跟別人越好事情也会忘記。
   - 我到现在一直觉得自己幸福到不行。

他做音乐初衷别别人简单的多，当我听到/看到他的演唱，无论心理有多乱，总让我可以瞬间静下来听他唱完那首歌，让我静静的感受他音乐中讲述的故事，这就是他的音乐感染力。林志炫没有拿到最终的冠军是因为不是每个人都能感受到他的音乐的魅力。

林志炫和羽泉，虽然他们采用的方式方法不同，但是他们都是非常棒的歌手。
站在我个人的角度，我更喜欢林志炫，可能是我性格的原因吧，他说过的有些话引起了很多的共鸣。
我也非常自私，我做东西往往不会太多考虑别人的因素，完全按照自己的想法来去做。我一直坚信："如果一个东西做的自己都不喜欢，凭什么要求别人去喜欢"。

总结：我给林志炫用卓越来评价，给羽泉用合适来评价。在卓越和合适之间，选择合适的人更多一些，毕竟不是每个人都懂卓越的东西，而合适大伙的东西都很容易懂。（"卓越"和"合适"用的不恰当，但是没有更好的替代词）

PS:
第一届的我是歌手应该说湖南卫视做的很成功，但是我预测继续做下去会越来越差，哪有那么多好的"歌手"。
