#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 逃离 Wordpress，拥抱 Jekyll
#+DATE: 2013-10-20 00:00:00

早觉得 Wordpress 不爽，对于一个技术博客来说，太过庞大了，发布文章太耗时，不支持 Markdown 。
但是仍旧没有到非换不可的程度，毕竟用了一两年了，积累了几十篇文章。

直到上上周的某一天，我写了一篇文章，也就是刚才发布的 [[http://www.perfect-is-shit.com/programming%20language/2013/10/20/talk-about-c-and-cpp-base-input-output][C和C++基本输入输出小谈]]，在 Wordpress 上提交了半个多少时，都没有提交上去，
出现的问题是提交后的文章莫名其妙的被截断了(也就是总是提交一部分文章)。不知道大家有没有遇到这个问题，我两个网站都遇到类似的问题，非常蛋疼。
于是我在微博上非常愤怒的喷了两句，但是这并不能解决问题。

第二天，我有了不再使用 Wordpress 的想法，转而使用静态博客。类似的博客引擎有很多，为什么使用 Jekyll？

- Pelican 也是一个好的选择，不过，我的[[http://www.errpad.com][ErrorPad]]已经用过了，博客继续使用就没有新鲜劲了。Pelican 的主题和 Jekyll 主题相差太远，长的很丑。
  另外，Pelican 用的人相对 Jekyll 用的人，还有提供的资料都要少很多。
- 在 Jekyll 和 Octopress 都不了解，我选择 Jekyll 只是因为 Tanky 使用了 Octopress，那么我一定要用他没用过的。嘻嘻

总共耗时有两周左右吧，遇到了一些问题，不过总归解决了。这也是使用 Jekyll 的好处，用的人多，一旦遇到了问题，很快就能找到解决方案。
如果是 Pelican 的话，相对要麻烦很多。

现在写文章就非常方便了： =Github + Ubuntu + Emacs + Markdown= ，打开 Emacs 就可以干完所有的事情了，非常爽！一切都是可控的！

给想要转用 Jekyll 的朋友一点建议：

如果你文章多的话，不如直接重新用 Jekyll 搭建一个新博客，导文章成本太高了。如果你和我一样是个细节控的话，成本就更高了。
虽然有一些工具可以从 wordpress xml转成 Jekyll post格式，但是转移之后的 post 细节上要做很多调整，基本上我每一篇文章都过了一遍。
比如，在我之前的文章分类有一类是 =C/C++= ，Jekyll 认为这是一个层级目录，所以所有的文章都无法正常显示。

评论丢失的可能性很大，因为很多文章的 URL 都变了，第三方的评论系统基本上都是依赖文章的 URL。我搬过来以后，基本上所有文章的URL都发生了改变，
也就是说，我的评论都没了。

更多的细节就不赘述了，网上一搜一大片。
