#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: Github page build failed 可能的解决方案
#+DATE: 2013-11-25 00:00:00

前几天博客修改了一些东西(把部分英文改成了中文，以及主题上的一些精简)，本地测试没有问题，但是提交到
Github 以后，邮件警告：

#+BEGIN_QUOTE
  The page build failed with the following error:

  page build failed

  For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

  If you have any questions please contact us at
  https://github.com/contact.
#+END_QUOTE

因为没有提供更多信息，我多次尝试性的修改，网上找了相同经历的人的解决方法，还是没能搞定。无奈之下，给
Github 发了一份邮件，回复的很快，大体意思是让我按照 Git Pages
的测试方法再进行本地测试：

#+BEGIN_QUOTE
  https://help.github.com/articles/using-jekyll-with-pages

  Also note that you should be using the --safe switch or be setting
  'safe: true' in your _config.yml so that pages are built in safe mode
  locally when testing. Note that Jekyll plugins currently aren't
  supported when you deploy to GitHub Pages.

  More info on that here:

  http://jekyllrb.com/docs/plugins/

  If you follow those instructions you should be able to reproduce any
  errors locally.
#+END_QUOTE

我按照提供的方法再折腾了一段时间，问题依旧没有解决，然后回邮件希望他们可以把详细的错误日志可以发给我。今天收到邮件，错误提示为：

#+BEGIN_QUOTE
  No submodule mapping found in .gitmodules for path
  '_theme_packages/mark-reid'
#+END_QUOTE

网上找到一个帖子：[[http://stackoverflow.com/questions/4185365/no-submodule-mapping-found-in-gitmodule-for-a-path-thats-not-a-submodule][No
submodule mapping found in .gitmodule for a path that's not a
submodule]]，使用：

#+BEGIN_EXAMPLE
  git submodule update --init
  git rm --cached _theme_packages/mark-reid
#+END_EXAMPLE

然后再次 update, 提交到Github，问题得到了解决。

我回复邮件建议他们在 Github Pages build error
的时候邮件提供更多的错误信息，这样方便我们快速的定位问题。

没想到另外一个博客提交的时候也遇到了类似的问题，用这个方法得到的解决，我想遇到的人应该不是少数，所以就简单整理了一下(如果build
error，可以尝试一下 submodule
update)，希望可以帮到大家。当然，最根本的解决方法还是我上面说的，编译错误之后，有一些错误提示就好了。

非常感谢 Github
的工作人员，他们的回复速度很快，而且也很有耐心(就俺那个英语)，我们都希望能有个很好的平台供大家来使用。

btw，最近 Github 是否做过一些改动?
博客这只是一方面，这两天提交文章也提交不上去，需要修改
=.git/config=的=url=链接。
