#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 2017~2019 个人总结
#+DATE: 2019-12-28 15:14:52

从 2013 年开始就有了写个人总结的习惯，连续写了四年：

- [[file:../2014/2013-personal-review.org][2013 个人总结]]
- [[file:../2015/2014-personal-review.org][2014 个人总结]]
- [[file:../2016/2015-personal-review.org][2015 个人总结]]
- [[file:../2016/2016-personal-review.org][2016 个人总结]]
- [[file:2018-personal-review.org][2018 个人总结]]

最近 3 年都没怎么认真写，2018 年草草写了几句，负面的比较多，本来准备删了的，后来想想时好时坏都是当时的心境，这也是记录的目的。
马上 2020 年就要来了，本文补一下这三年的空缺 ~

在此之前把之前写的总结都过了一遍。感触还是挺深的，像以前那样简单纯粹，敢打敢拼的时光已经不在了，
2017 和 2018 是个过渡期，今年开始走向人生的下一段旅程。

和以前一样，按照几个大方向分别 review 一下，然后写一写对未来的期望。

* 职场
** 换工作

在 [[file:../../youth/in-hefei-s15.org][再见七行]] 中说明了离开七行的原因，后来又在 [[file:../../youth/in-hangzhou-s0.org][在杭州-序]] 中说明了后续面试和入职挖财的事情，这里不再赘述了。
离开一个环境之后再看待之前的事情会更加客观一些。在 2018 年里，花了很多的时间在反思在七行的两三年时间里，
哪些事情做对了，哪些事情做错了；甚至是离开七行来挖财是一个对的选择，还是错的选择。 /当然对错都是相对的。/

过去 2017 之前的几年里，自己的不足有很多，究其根源是： *永远是一个技术人的心态来做事，来看待事物* 。
在七行的时候本以为自己可以产品或者工程的角度来思考问题，在做事。现在来看自己还是太局限了，始终是一个技术人的思路。

而最近两年里，我更多思考的是，当下或者未来该如何做，得到的结论是： *以目标/结果来驱动自己做事，不论过程* 。
这两年职场上的纠结，都是自己内心之间的斗争，这也是诸多痛苦的源泉。

** 挖财

离开七行之后，我想着再也不用写前端了，没想到到挖财之后逐渐成了一个专职的前端，不愿但又无可奈何。
在快乐的做事与能拿结果之间，以前总是会选择前者，而现在我要慢慢的选择后者。

*不用在意自己做什么，而关心事情本身的意义。* 这也是我来挖财之后琢磨出来最重要的东西，其它的都不值一提。

** 技术

在上周部门内部做了前端开发的分享（也就是 [[file:intro-frontend-dev.org][前端开发从入门到放弃]] 和 [[file:intro-to-umi.org][基于 umi 构建中后台前端项目入门]] 这两篇文章的内容）。
这个过程中顺便把自己这么多年零零散散的前端开发做了一次全面的复盘。再努努力应该就可以说自己能写前端了。

每个做技术的人，都有自己的舒适区，这种舒适区也是程序员偏执的源泉，每次跳开都会给自己找一堆借口，然后快速回到自己的舒适区继续待着。
在入行不久就发现很多人喜欢给自己打标签，直至现在遇到的人大都如此，比如 Java，C++，Go，Linux，开发，运维，产品等。
所以我很讨厌这一点，但后来发现自己也不自己觉得陷入了标签中，然后为自己的不擅长找借口。

直到这次对前端的复盘，我才意识到一个人深入多个领域是有可能的。 *不应该去关注技术本身，而去关注技术所能带来的东西。*
一旦有了这个思路的转变，就不会再去抗拒学习新的东西了。

到现在，所有的技术对我来讲才变成了真正意义的工具化了，只是实现目标的手段。从入行就知道的道理，经过七八年的历练，才彻底的想明白。

*从此以后，再无技术。*

* 阅读与写作

这 3 年读过的书，应该是不足前面 4 年的四分之一的，后来不想读书的原因在以前的文章里提过，不再赘述。
现在想来是自己对于读书的功利性太强了，太着急了。追求物质金钱的东西应该目标明确，而精神领域的东西，本来就是一个很慢的过程。
*这样不好。*

这 3 年写的东西，并不比以前少，但是质量上差了许多。我记得 2013 左右的时候，写一篇技术文章最多花过八九个小时；
这一点放到现在是做不到的，不会有这么多整块的时间。但是这些都是正常的，也是之前文章中所说的，写作能够带给我的东西，已经带来了。
现在写东西不会去关注质或者量，只是一个记录，对自己有意义就行。

另外，今年把 blog 和 wiki 等都通过 org-mode 整合到一起，然后丢到 github 了，以后不用在为博客工具和云托管商操心了，可真爽（Emacs 大发好）。

* 家庭

订婚，买车，买房，结婚是这三年的主题，各种曲折只能说人生不易，但好在都过去了，而且越来越好。

前几天跟冯飞聊天，感叹人生的所有弯路都是必经之路，该面对的问题迟早都是需要面对的。前面的四五年，除了没挣到钱这个客观事实之外，
其它的都是顺风顺水的：父母年轻且健康，家里也不需要我操心；每份工作也算是有领导赏识，自己想要做的大多也都做了；对于生活，自己年轻，一切都挺好。

到了 30 岁左右的年龄，自己的角色不再那么单一：是父母的儿子，是妻子的丈夫，肩上的责任也越来越重。
以前有人说，工作和家庭应该分开，现在觉得挺扯淡的，无论怎么分你都只有一个脑子，只有一份精力，同时只能思考一件事情。

对我来说，最大的收获在于逐渐的认清了自己：工作、生活不可能兼顾，你不可能把所有的事情都做到让自己满意。

* 未来

明年就 30 了，前些日子想明白的一事是：人的一生可能只能做几件事情。工作不可能一直换下去，换到满意为止；
工作城市也不可能一直换下去，总要有一个归宿。很多梦想也不会再去想，这样挺好。

*对于未来，不必想的太长远，不必想的太多，心态开放，不辜负每一天就好。*

------------------------

* 别人的 2019 年

- [[https://overreacted.io/my-decade-in-review/][My Decade in Review]] Dan Abramov 的 10 年经历，这哥们是 Redux 作者，貌似比我小 1 岁；
  不算什么传奇经历，倒是各种心酸的经历... 2010 年高中毕业，没上大学，自学编程，2014 年之前都一直没有稳定的工作；
  没有 2014 年搭了 React 的顺风车，后来自己写了 Redux，2015 年后去了 Facebook，目前在 Facebook 做 React 技术栈相关的东西
- [[http://www.yinwang.org/blog-cn/2019/12/31/2020-new-year][2020新年寄语]] 王垠离开 Intel，十年挣扎路
- [[https://mp.weixin.qq.com/s/xVjV3JmpUzkL0OARYLp5Fw][我的 2019 年个人总结]]：Fenng，有一天有许多话要说出的人，常默然把许多话藏在内心
- [[https://mp.weixin.qq.com/s/JLOU4YyiX685hcfa-L9a1A][悲观者往往正确，乐观者往往成功]]：池建强
