#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 2019 年春节
#+DATE: 2019-02-11 11:32:00

今天是年后上班第一天，随便写写春节这一周时间的一些流水事件，以及感悟。

** 回合肥过年
   :PROPERTIES:
   :CUSTOM_ID: 回合肥过年
   :END:

前年春节（2017 年）在合肥过的，因为年前的 11
月份订婚，父母从陕西过来了一趟，想着就不回去过年了，来回折腾。

原计划今年春节（2018
年）回老家过年，和老婆自相识、订婚到现在还没去过老家，需要见见长辈亲戚。没成想去年房子的事，一再折腾，到年底又跑回去了一趟，担心末了还需要回去，这是其一；再者距离实在太远了，两个人回去无论是高铁还是飞机，钱是一方面，时间也是一方面。去年因为买房子的事情，借了不少钱，压力也是很大。加上自己心里也懒，不想来回奔波，所以和父母商量，过年就不回去了，五一前后再回去吧。

这些年，陪伴父母的时间实在太短了，仔细想来自己很不孝顺，以后定居合肥了，回家过年也是个大问题，只能走一步看一步。

** 拜年
   :PROPERTIES:
   :CUSTOM_ID: 拜年
   :END:

合肥的民俗与老家（延安）大不相同，无论是饮食习惯还是礼节都相差甚远。

我们老家那边，拜年都是在年前拜的，而且礼数比较随意，要紧的亲戚，带点烟酒吃喝年前走一趟，陪亲戚寒暄几句即可。年夜饭晚上吃，也有熬夜的传统，就算睡觉也会开着房灯。大年初一早上是一定吃饺子，而且大年初一是不出远门走亲戚的。

合肥则不同，拜年都在年后，礼数就正式一些，送礼烟酒都要双数，拜年一般要去吃早饭（鸡蛋、卤菜、面条等），比较奇怪的是，拜年一般是全家人都去，这与我们老家不同，也没有大年初一吃饺子这种传统。给长辈拜年是相约同辈兄弟姐妹，子女，能去的全去，一起做饭一起吃，图个热闹。不仅是过年，正月十五、中秋节等也是如此。做「女婿」的这一年多，我参与过三四次，几十号人，好不热闹。

不光如此，包红包也不相同，老家那边就相对随意一些，包的大小全看亲疏程度，在我印象中，100、50
面额也是有的，意思到了就行了。而合肥这边不同，红包讲究比较多，基本上都是
200 起。

这一年跟老婆有过多次争吵，很多时候根源都在于南北方民俗历史导致人的观念理解不同。我认真想过这个中缘由，除了老祖宗留下来的传统之外，还有很重要的一点是经济发展相差太大，北方发展相差南方甚远，利益纠葛不同。放到
20
年前，我们那边的穷可能是吃不上馒头，只能吃窝窝头，而这种情况同比放到南方，可能是四五十年前才有的。我跟岳父岳母聊过这个话题，我六七岁的经历，是他们那个年代的经历。经济资源的不同，导致了亲戚之间相处的模式全然不同，资源受限的情况下，兄弟姐妹难免出现争抢会比较明显，关系自然就疏远了。

** 年味
   :PROPERTIES:
   :CUSTOM_ID: 年味
   :END:

不管是北方还是南方，年味都在逐渐淡薄，经济发展至今日，「年货」早就没有了意义，逢年过节才能吃的上穿的上的东西，现在随手可得。

除此之外，这一代的年轻人（90 后、95
后等）随着互联网的快速发展，社交主打线上，线下的关系维持逐渐淡薄。在未来，传统的礼节可能会消失，越是发达的地方越是如此，上海当地很多人过年就是出去旅游，不会这么复杂的拜年。

不知道是好是坏。

** 一部电影：飞驰人生
   :PROPERTIES:
   :CUSTOM_ID: 一部电影飞驰人生
   :END:

过年无事，跟老婆一起看了「飞驰人生」，挺好看的。虽然各种段子拼凑到一起不免尴尬，但是整体还是挺好的。

#+BEGIN_QUOTE
  我这个人啊，没什么故事，初中、高中、没人喜欢我，我也不喜欢别人，父母身体一直很好，没发生过任何的意外，车祸什么的都没有，没考过研，没打过仗，没在
  KTV
  里唱哭过小姐，没有逼良为娼，也没有劝妓从良，只有坐在赛车里的时候，我才觉得自己活了一次。
#+END_QUOTE

笑着笑着就哭了，永远热爱。

** 归程
   :PROPERTIES:
   :CUSTOM_ID: 归程
   :END:

到舒城拜年之后，就下大雪了，气温也骤降。在车上的积雪，没多久就结冰了，南方的雪跟北方差距也很大···。原计划初五、初六走都行，初四下雪、初五就匆忙走了，因为初六天气预报也有大雪。

开春开车本来就有压力，加上积雪就更麻烦了，路上打滑不说（励志得买个好车），开车开到高速口才发现高速因大雪封了。沿着省道各种绕就罢了，谁知道也遇到了走着走着没路了的尴尬情况，眼看都搁到三不靠的大马路上了。最后在芜湖找了一个汉庭酒店住下来，初五开了七八个小时，实际距离走了相当于
150
公里左右（全都绕路了）。睡了五六个小时，初六早上五点就出发了，好在高速解封了，尽管还下着不小的雨夹雪，早上十点总算开到了杭州。

一个人开长途也的确不行，我不会开车···，老婆几次发飙，当忍也就忍了。2019
年得考虑考虑学驾照了。

** 承启
   :PROPERTIES:
   :CUSTOM_ID: 承启
   :END:

2018 年依旧没有写年终总结，只是在微博上写了一段话。2017-2018
年折腾的事情比较多了，但是都不顺，也算是一种磨练吧。

以前为了实现自我价值而折腾的情况逐渐变成了养家糊口，这个过程有些难，这两年当是过度年了，没有办法，人生逐渐的到了尽责任、尽义务的阶段了。这几年的主要目标是攒钱还贷，不宜大折腾，稳中求变。
