#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 博客主机被迫迁移到腾讯云香港
#+DATE: 2019-06-26 21:40:00

2019-06-21 收到工信部的"关于ICP备案信息中注销网站的通知"，内容如下：

#+BEGIN_QUOTE
  尊敬的用户张杰
  ，您备案信息中的网站闲言碎语已被注销，该网站的备案号皖ICP备16000446号-1已被收回，注销理由为其它（空壳网站（无接入信息）），特此通知！

  工业和信息化部网站备案系统
#+END_QUOTE

收到这个通知，说实话我一脸懵逼，网站一直在运行状态，竟然告知我这是个空壳网站？！然后我快速给腾讯云提工单确认问题，腾讯云说他们这边一切正常，让我打电话问工信部。工信部的电话谁打谁知道，基本上不会得到什么有效的信息，所以我就继续让腾讯云的查一下具体原因，最后得到的结论是这个网站一直没在腾讯云备案，我就更懵逼了。

我有几个网站，最初都是在阿里云备案的，后来不太想用阿里云的
ECS，所以就购买了腾讯的云主机。这里面有个很蛋疼的问题：

- 腾讯云的域名是可以正常解析到阿里云的
- 阿里云的域名是不可以解析到腾讯云的，这个是腾讯云单方面限定的

在七行的时候，曾经把阿里云的服务全部迁移到
UCloud，就遇到过域名迁移，我问过 UCloud
的客服，其实原则上来讲，只要域名备案，不管是哪个云厂商，都应该可以正常解析到不同的云厂商，因为他们只是接入商，而真正负责备案的是工信部。

所以，这种不同厂商不允许相互解析，是不是一种恶性的竞争？比较蛋疼的是，阿里云的域名解析到腾讯云，并不是直接告诉你不行，而是过了一段时间后，网站不能访问了，告诉你需要备案（我估计是定期扫描的）。这块具体的政策我也不是很清楚，反正就是很恶心。

于是，我就将域名全部转移备案到腾讯云了，我有印象是因为提交的时候腾讯云的人给我打电话确认过网站名称之类的。但是现在看来是没有转移成功。我不是很确定是不是因为几个域名我搞混了。

在此之前，阿里云的客服曾经给我打过多个电话，说我账户信息需要更新，否则会影响自己的业务。由于历史原因，我在阿里云有两个账号，一个账号是当初这几个域名，一个账号是用云存储和
ECS
的。打电话的时候，我没太在意，因为我想的是域名全部都迁移到腾讯云了，加上很长时间网站运行都没遇到备案问题。

就这么机缘巧合之下，网站备案被注销了。注销了之后我快速的登录阿里云，确认域名备案是否正常，更恶心的事情出现了，因为之前预留的手机号已经不用了，账号登录不了，只能申诉更换手机号。按照流程申诉之后得到的回复是：

#+BEGIN_QUOTE
  您好，经核实，您的账号信息注册过于简单，未进行实名认证且账号下无业务，您该账号当前的情况是无法修改信息的
#+END_QUOTE

确认再三，也是说账号下面是没有域名的，我想既然登录不进去，那我申请注销吧，得到的回复是：

#+BEGIN_QUOTE
  您好，这个账号无任何信息，注销账号需要您登录上这个账号，由于您现在无法登录，账号无信息和业务也不会影响您的，您可以重新注册新账号使用的。
#+END_QUOTE

What the Fuck？
换句话说，反正账号也没信息，就放着吧，不影响你也不影响我。还有这种操作？！不巧的事，当天阿里云给我的邮箱发了一封推广邮件，我当时就怒了，就跟他们讲，要注销，不然你们会给我发推广邮件。得到的回复是：

#+BEGIN_QUOTE
  您好，这边会和后端核实一下，给您带来不便请谅解
#+END_QUOTE

然后，就没然后了。这几天都没有得到任何通知，这事估摸着就不了了之了，这就是阿里云，需要续费的时候，短信邮件各种催，最后欠费了电话催，遇到这种事就是反正不影响你，就这么放着吧。

--------------

没办法，域名还是要继续用的，在与阿里云、腾讯云沟通的时候，同时把服务（博客、Wiki）迁移到了香港（腾讯云），还想着这是一个临时方案。

最后得知域名确定注销，没有回旋的余地，那就只能重新备案了。一看，备案的先决条件是网站不能开启，得，完蛋。备案至少要两三周，网站关上两三周，我还不如直接换一个域名呢，备案也就毫无意义了。那就不备案了吧，以后统一用香港的主机就行了，只是希望后面因为没备案引发一些问题就好。

--------------

对于博客的折腾，可以看一直在维护的
[[file:blog/about-blog][关于博客]]，我最早用的域名不是这个（zhangjiee.com），而是
=keepsimply.org=，我挺喜欢这个域名的，这也是我申请的第一个域名。

2011-11-13 ~ 2013-01-18 一直用的是
keepsimply.org，后来因为网站信息有误，让我提供证明（类似证明我是我），我没有办法证明，跟运营商扯了好久，也是没办法就放弃了。用的时间不算长，但是那段时间是我更新文章最频繁的时候。那几年的还在博客时代，写博客的人很多，已经有了一些固定的圈子，访问量还挺高的。从那个时候换域名就把网站换废了（一个域名对于网站的意义懂的人自然懂）。再后来连续换了两个域名，=perfect-is-shit.com=
和 =zhangjiee.com=，网站就更废了。

到现在博客的访问量我已经不 care
了，写作能带给我的已经带给我了，网站只是我自娱自乐、记录和成长的一个地方。所以，我只求的不要再出这种幺蛾子，*真的折腾累了*
。
