#+SETUPFILE: ~/site/tpl/wiki-tpl.org
#+TITLE: Ubuntu
#+DATE: 2018-09-10 21:39:56

系统版本： =Xubuntu 18.04=

* 设置国内源

手动设置：

1. [[https://mirror.tuna.tsinghua.edu.cn/help/ubuntu/]]
2. =apt update=
3. =apt upgrade=

自动选择：

软件和更新 -> Ubuntu 软件 -> 下载自 -> 选一个国内的镜像源

* 代理
** SS
*** 客户端

1. 命令行：[[https://github.com/shadowsocks/shadowsocks-libev]] =sudo apt install shadowsocks-libev=
2. GUI：[[https://github.com/shadowsocks/shadowsocks-qt5]]

GUI 版本很不稳定，不如直接使用命令行（ =ss-local= ），配合 =systemd= 设置服务开机启动。

*** ss-local 配置

配置文件在 =/etc/shadowsocks-libev= 目录下。文件内容改为：
  #+BEGIN_SRC
  {
  	"server":"",
  	"server_port": xx,
  	"local_port":1080,
  	"password":"",
  	"timeout":60,
  	"method":"chacha20-ietf-poly1305"
  }
  #+END_SRC

systemd unit 名字为： =shadowsock-libev= 直接重启即可。设置开机启动 =systemctl enable shadowsock-libev= 。

*** Chrome 浏览器代理

因为鸡生蛋，蛋生鸡的问题，需要手动安装 [[https://github.com/FelisCatus/SwitchyOmega][SwitchyOmega]]，新版本的 Chrome 不允许安装第三方的插件，会报错。一个投机取巧的办法是将 crx 后缀改为 zip，打开开发者模式，然后拖入，经测试可行。

规则列表网址： =https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt=

*** 终端代理

Sock5 proxy：[[https://www.irif.fr/~jch/software/polipo/][Polipo]]

1. 安装: =apt install polipo=
2. 修改配置文件: =/etc/polipo/config= ，添加：
   #+BEGIN_SRC
   proxyAddress = "0.0.0.0"

   socksParentProxy = "127.0.0.1:1080"
   socksProxyType = socks5
   #+END_SRC
3. 重启: =system restart polipo=

设置代理（polipo 的端口是 8123）：

#+BEGIN_SRC
export http_proxy="http://127.0.0.1:8123" export https_proxy="http://127.0.0.1:8123"
#+END_SRC

测试是否生效: =curl ip.gs=

** SSR

1. https://github.com/shadowsocksrr/electron-ssr 设置订阅源，然后更新
2. 开启全局代理
3. Chrome 安装 SwitchyOmega 并设置，规则列表网址： =https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt=
4. 关闭全局代理

* 软件列表

- 搜狗输入法
  + 先安装 fcitx =apt install fcitx=
  + 安装 [[https://pinyin.sogou.com/linux/?r=pinyin][搜狗拼音输入法]]
  + 重启电脑即可生效，如果没生效，通过 fctix 配置，添加搜狗输入法
  + 设置快捷键为 =Ctrl+Space=  切换激活/非激活输入法 改为 =Ctrl+Space= ，启用输入法之间的切换给禁掉。（配置设置挺蠢的，要研究半天）
- 邮箱客户端：Thunderbird，说他丑，说他重度，可是只有他最稳定啊
- 截图工具：[[https://github.com/lupoDharkael/flameshot][flameshot]]
  1. =apt install flameshot= 安装
  2. 将 =flameshot gui= 绑定到 =Ctrl+Alt+A= 快捷键上
- 视频播放器：[[https://www.videolan.org/vlc/download-ubuntu.html][VLC]] =apt install vlc=
- gif 录屏：[[https://github.com/phw/peek][Peek]]，这个很好用，视频录制也有人推荐 [[https://github.com/hzbd/kazam][Kazam]]，就我个人而言 Peek 满足需求了
- +网易云音乐+ ：经测试 Ubuntu 下的网易云音乐比较吃资源，就不用了
- SNS
  + Telegram =apt install telegram-desktop=

[[file:~/site/org/wiki/growing/programmer.org][技术人]] 有补充，重复的软件没有在这里体现。

* 几种桌面对比
   :PROPERTIES:
   :CUSTOM_ID: 几种桌面对比
   :END:

常见的 4 种桌面：

- GNOME 3，Ubuntu 18.04 之后默认的
- [[https://kde.org/][KDE]]
- [[https://www.xfce.org/][Xfce]]
- [[https://lxqt.org/][LXQT]]

资源消耗和 UI 体验成正比，GNOME 3 和 KDE 差不太多，其次是 LXQT，Xfce 体验最差，但是占用资源的确少，而且快。

<2020-03-08 13:13:22 日>

GNOME 太不稳定了，换到了 Xubuntu，世界顿时清净了。

* Xfce

快捷键：

|------------------+----------|
| 快捷键           | 描述     |
| =Ctrl + Alt + D= | 显示桌面 |
| =Alt + F4=       | 关闭窗口 |
| =Ctrl + ESC=     | 打开菜单 |
|------------------+----------|

http://xahlee.info/linux/linux_xfce_keyboard_shortcuts.html

如何移动 panel：https://forum.xfce.org/viewtopic.php?id=7310

* FAQ
** 安装 xfce 之后，卸载不干净怎么办？

- 卸载 =xfce4-*=
- 卸载 =xubuntu-*=

网上教程很多，但是有一点要注意：zsh 不支持 =apt remove xfce4-*= 这种语法，要切换到 bash 才行。

** 系统设置被卸载掉了，如何安装回来？

#+BEGIN_EXAMPLE
  sudo apt-get install gnome-control-center
#+END_EXAMPLE

** 如何启动 ROOT 用户

默认的 root 是被锁定的，要先指定一个密码： =sudo passwd root= ，Ubuntu 默认禁用 root ssh，需要打开：

1. =vim /etc/ssh/sshd_config= 将 =PermitRootLogin= 的 =without-password= 改为 =yes=
2. =restart ssh=

** 启动速度慢调试

- =systemd-analyze=
- =systemd-analyze critical-chain=

via: [[https://www.dedoimedo.com/computers/ubuntu-beaver-slow-boot.html]]

** 18.04 蓝牙每次重启之后不会自动连接

使用 bluetoothctl 添加设备 TRUST：

控制台输入 bluetoothctl， =devices= 查看设备列表，找到蓝牙对应的 MAC 地址，然后 =trush <mac-addr>= 即可。

** fcitx + 搜狗拼音经常会出现某一个核 CPU 占 100 的情况

网上说在 fctix 输入法配置 -> 附加组件 -> 高级 -> 然后把 "搜狗云拼音" 去掉就可以了。

不确定是否可行，先试试。后面不行的话就不用搜狗拼音了。<2020-03-21 13:46:58 六> 确定可行。

** 重启 fcitx 之后，Emacs GUI 无法进行输入法切换

=Ctrl+Space= 默认被认为了 Emacs 中的文本 Mark Active，解决办法是重启 Emacs 。

** 使用 wine 安装微信、企业微信等

deepin-wine 确实可行，但是问题挺多的，体验很差，还是算了。
