#+SETUPFILE: ~/site/tpl/wiki-tpl.org
#+TITLE: Ubuntu
#+DATE: 2018-09-10 21:39:56

目前在用 Ubuntu 22.04 LTS 版本。

*多次被迫重装的教训告诉我：既然选择了 Ubuntu 就要专注于开发和学习。不要随便升级系统或者库，遇到问题时，不要随便找一段自己不知道干了什么事情的指令就执行了！*

* 软件源

- 自动选择：软件和更新（Ubuntu 软件 -> 下载自 -> 选一个国内的镜像源）
- +手动设置+ 找清华、阿里源替换 =/etc/apt/sources.list=

* 代理

** SSR

1. 安装 [[https://github.com/shadowsocksrr/electron-ssr][electron-ssr]] 设置订阅源，然后更新（没代理可能无法打开 github，最好平时自己缓存一份）
2. 开启全局代理
3. 系统设置->网络->网络代理：设置成与 ssr 中相同的 socket 和 http 地址
4. Chrome 安装 SwitchyOmega 并设置，规则列表网址： =https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt=
5. 关闭全局代理

*注意* ：electron-ssr 是用 Python 写的，最近几个版本的 Ubuntu 发行版默认只安装了 Python3，所以需要手动安装一下，否则将无法正常使用。
具体操作：

#+begin_src sh
  sudo apt install python2
  sudo ln -s /usr/bin/python2 /usr/bin/python
#+end_src

可以参考这个安装教程：https://github.com/qingshuisiyuan/electron-ssr-backup/blob/master/Ubuntu.md， 较新版本的 Linux 发行版，
systemd 自己运行了一个 DNS server（127.0.0.53, =systemd-resolved= 这个服务），这会导致全局代理不生效（PAC 也更新不了），
参考文档中的“系统设置”修改之后即可解决这个问题。

** +Ubuntu Server+

安装 shadowsock-libev, =apt install shadowsocks-libev= ，客户端连接只需要 =ss-local= 。先停掉无关的服务：

#+begin_src shell
  systemctl disable shadowsocks-libev.service
  systemctl stop shadowsocks-libev.service
#+end_src

配置文件在 =/etc/shadowsocks-libev= 目录下。文件内容改为：

#+BEGIN_SRC js
  {
    "server":"",
    "server_port": xx,
    "local_port":1080,
    "password":"",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
  }
#+END_SRC

systemd unit 文件是： =shadowsocks-libev-local@.service= ，把其中的配置文件路径修改成实际的配置文件。

- 重启 ss-local =systemctl restart shadowsocks-libev-local@.=
- 查看服务运行状态 =systemctl status shadowsocks-libev-local@.=
- 查询运行日志 =journalctl -f -u shadowsocks-libev-local@.=
- 设置开机启动 =systemctl enable shadowsocks-libev-local@.=

shadowsocks 是一个 socks5 代理，想用 http 代理需要做一层转换。

Sock5 proxy：[[https://www.irif.fr/~jch/software/polipo/][Polipo]]

1. 安装: =apt install polipo=
2. 修改配置文件: =/etc/polipo/config= ，添加：
   #+BEGIN_SRC yaml
     proxyAddress = "0.0.0.0"
     proxyPort = 8123
     socksParentProxy = "127.0.0.1:1080"
     socksProxyType = socks5
   #+END_SRC
3. 重启: =systemctl restart polipo=

设置代理（polipo 的端口是 8123，可以换成其他的）：

#+BEGIN_SRC sh
   export http_proxy="http://127.0.0.1:8123" && export https_proxy="http://127.0.0.1:8123"
#+END_SRC

测试是否生效: =curl ip.gs=

* 软件列表

- 输入法：
  + 搜狗输入法，按照官方的 [[https://shurufa.sogou.com/linux/guide][安装指南]] 即可
  + +rime 输入法+
    - 安装： =sudo apt-get install fcitx-rime=
    - 默认是繁体的，设置成简体：
      - =~/.config/fcitx/rime/build/luna_pinyin.schema.yaml=
      - 找到 =switches= 在 =simplification= 下添加 =reset: 1= 即可
- [[https://albertlauncher.github.io/][albert]] Linux 下最好的 Laucher 工具，类似 macOS 下的 alfred
  - [[https://software.opensuse.org/download.html?project=home:manuelschneid3r&package=albert][下载安装]] =sudo dpkg -i=
  - 绑定快捷键：将 =albert toggle= 绑定到 =F2=
- 截图工具：[[https://github.com/lupoDharkael/flameshot][flameshot]]
  1. =apt install flameshot= 安装
  2. 绑定快捷键：将 =flameshot gui= 绑定到 =F1=
- Telegram =apt install telegram-desktop=
- 邮箱客户端：Thunderbird
- 视频播放器：[[https://www.videolan.org/vlc/download-ubuntu.html][VLC]] =apt install vlc=
- gif 录屏：[[https://github.com/phw/peek][Peek]]，这个很好用，视频录制也有人推荐 [[https://github.com/hzbd/kazam][Kazam]]，就我个人而言 Peek 满足需求了
- 思维导图 =sudo snap install xmind=

[[file:~/site/org/wiki/growing/programmer.org][技术人]] 有补充，重复的软件没有在这里体现。

* FAQ

** ifconfig not found [fn:1]

- https://serverfault.com/questions/458628/should-i-quit-using-ifconfig
- https://askubuntu.com/questions/1031640/ifconfig-missing-after-ubuntu-18-04-install

简单来说， =ifconfig= 不推荐使用了，改为 =ip= 。

** Dell 安装 Ubuntu 找不到硬盘问题

进 BIOS 设置硬盘，将 raid on 改为 ahci。

** 安装 xfce 之后，卸载不干净怎么办？

- 卸载 =xfce4-*=
- 卸载 =xubuntu-*=

  网上教程很多，但是有一点要注意：zsh 不支持 =apt remove xfce4-*= 这种语法，要切换到 bash 才行。

** 系统设置被卸载掉了，如何安装回来？

#+BEGIN_EXAMPLE
  sudo apt-get install gnome-control-center
#+END_EXAMPLE

** 如何启动 ROOT 用户

默认的 root 是被锁定的，要先指定一个密码： =sudo passwd root= ，Ubuntu 默认禁用 root ssh，需要打开：

1. =vim /etc/ssh/sshd_config= 将 =PermitRootLogin= 的 =without-password= 改为 =yes=
2. =restart ssh=

** 启动速度慢调试

- =systemd-analyze=
- =systemd-analyze critical-chain=

via: [[https://www.dedoimedo.com/computers/ubuntu-beaver-slow-boot.html]]

** 18.04 蓝牙每次重启之后不会自动连接

使用 bluetoothctl 添加设备 TRUST：

控制台输入 bluetoothctl， =devices= 查看设备列表，找到蓝牙对应的 MAC 地址，然后 =trush <mac-addr>= 即可。

** 重启 fcitx 之后，Emacs GUI 无法进行输入法切换

=Ctrl+Space= 默认被认为了 Emacs 中的文本 Mark Active，解决办法是重启 Emacs 。

** 使用 wine 安装微信、企业微信等

deepin-wine 确实可行，但是问题挺多的，体验很差，还是算了。

** 笔记本合屏之后，阻止自动休眠

=/etc/systemd/logind.conf= 中的 =HandleLidSwitch= 打开，并且值修改为 =ignore= 。然后 =service systemd-logind restart= 。

** Dell 笔记本 Ubuntu 触摸板右键

触摸板双击等于右键，点击右下角还是相当于左键点击。解决办法，命令行执行：

#+begin_src
   gsettings set org.gnome.desktop.peripherals.touchpad click-method areas
#+end_src

via [[https://www.dell.com/support/article/zh-cn/sln316799/ubuntu-%e5%9c%a8-ubuntu-18-04-lts-%e5%ae%89%e8%a3%85%e5%90%8e-%e8%a7%a6%e6%91%b8%e6%9d%bf%e5%8f%b3%e9%94%ae%e5%8d%95%e5%87%bb%e5%81%9c%e6%ad%a2%e5%b7%a5%e4%bd%9c][Ubuntu：在 Ubuntu ® 18.04 LTS 安装后，触摸板右键单击停止工作]]

** APT 单独更新一个 package

=sudo apt-get --only-upgrade install <package_name>=

* Footnotes

[fn:1] https://askubuntu.com/questions/1031640/ifconfig-missing-after-ubuntu-18-04-install
