#+SETUPFILE: ~/site/tpl/wiki-tpl.org
#+TITLE: Ubuntu
#+DATE: 2018-09-10 21:39:56

* 设置国内源

1. [[https://mirror.tuna.tsinghua.edu.cn/help/ubuntu/]]
2. =apt update=
3. =apt upgrade=

* apt-get update 和 apt-get upgrade 的区别

先运行 =update= ，然后再运行 =upgrade= 。它们两个没有包含对方的功能，各自做的事情不同。

- =apt-get update= 更新可用包列表和他们的版本，但是不安装和升级任何版本
- =apt-get upgrade= 升级你已有包的到最新版本，更新列表之后，程序包管理器将会了解你已经安装的软件的可用更新。
  这就是为什么首先你需要 =update=

还有一个命令是 =dist-upgrade= ，它跟 =upgrade= 的区别：

+ =upgrade= 是对当前已经安装的包升级到最新版本（你首先要 =update= ），升级的规则是：在任何情况下安装的软件包都不会被删除，或者未安装的包被检索和安装。如果更新对你很重要，要使用 =upgrade=
+ =dist-upgrade= 除了执行 =upgrade= 之外，还会智能的处理包的依赖关系，所以说 =dist-upgrade= 可能会移除一些包。如果你想事情「正常工作」，可能要使用 =dist-upgrade= 来确保解决依赖关系

来自：

+ [[https://askubuntu.com/questions/94102/what-is-the-difference-between-apt-get-update-and-upgrade]]
+ [[https://askubuntu.com/questions/194651/why-use-apt-get-upgrade-instead-of-apt-get-dist-upgrade]]

* Ubuntu 18.04 快捷键

- =Super= 打开活动菜单，然后可以搜索应用程序、查看正在运行的 GUI 程序、切换工作区
- =Super + L= 锁屏
- =Super + D= 显示桌面
- =Super + A= 显示应用程序菜单
- =Super + Tab= 在运行的的应用程序之间切换， =Super + `= 在实例之间切换
- =Super + 箭头= 移动窗口位置，左分屏，又分屏，全屏幕等
- =Super + M= 切换到通知栏
- =Super + 空格= 多种输入法切换

* SS 代理
** 客户端

1. 命令行：[[https://github.com/shadowsocks/shadowsocks-libev]] =sudo apt install shadowsocks-libev=
2. GUI：[[https://github.com/shadowsocks/shadowsocks-qt5]]

GUI 版本很不稳定，不如直接使用命令行（ =ss-local= ），配合 =systemd= 设置服务开机启动。

*** ss-local 配置

配置文件在 =/etc/shadowsocks-libev= 目录下。文件内容改为：
  #+BEGIN_SRC
  {
  	"server":"",
  	"server_port": xx,
  	"local_port":1080,
  	"password":"",
  	"timeout":60,
  	"method":"chacha20-ietf-poly1305"
  }
  #+END_SRC

systemd unit 名字为： =shadowsock-libev= 直接重启即可。设置开机启动 =systemctl enable shadowsock-libev= 。

** Chrome 浏览器代理

因为鸡生蛋，蛋生鸡的问题，需要手动安装 [[https://github.com/FelisCatus/SwitchyOmega][SwitchyOmega]]，新版本的 Chrome 不允许安装第三方的插件，会报错。一个投机取巧的办法是将 crx 后缀改为 zip，打开开发者模式，然后拖入，经测试可行。

规则列表网址： =https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt=

** 终端代理

Sock5 proxy：[[https://www.irif.fr/~jch/software/polipo/][Polipo]]

1. 安装: =apt install polipo=
2. 修改配置文件: =/etc/polipo/config= ，添加：
   #+BEGIN_SRC
   proxyAddress = "0.0.0.0"

   socksParentProxy = "127.0.0.1:1080"
   socksProxyType = socks5
   #+END_SRC
3. 重启: =system restart polipo=

设置代理（polipo 的端口是 8123）：

#+BEGIN_SRC
export http_proxy="http://127.0.0.1:8123" export https_proxy="http://127.0.0.1:8123"
#+END_SRC

测试是否生效: =curl ip.gs=

* 软件列表

- 搜狗输入法
- 网易云音乐：经测试 Ubuntu 下的网易云音乐比较吃资源
- 终端：[[https://gnometerminator.blogspot.com/p/introduction.html][terminator]] =sudo apt-get install terminator=
- 邮箱客户端：Thunderbird，说他丑，说他重度，可是只有他最稳定啊
- 截图工具：[[https://github.com/lupoDharkael/flameshot][flameshot]]
  1. =apt install flameshot= 安装
  2. 将 =flameshot gui= 绑定到 =Ctrl+Alt+A= 快捷键上
- 视频播放器：[[https://www.videolan.org/vlc/download-ubuntu.html][VLC]] =apt install vlc=
- gif 录屏：[[https://github.com/phw/peek][Peek]]，这个很好用，视频录制也有人推荐 [[https://github.com/hzbd/kazam][Kazam]]，就我个人而言 Peek 满足需求了

[[https://getmailspring.com/][Mailspring]] 只是看起来漂亮，Bug 太多了。

* 几种桌面对比
   :PROPERTIES:
   :CUSTOM_ID: 几种桌面对比
   :END:

常见的 3 种桌面：

- GNOME 3，Ubuntu 18.04 之后默认的
- [[https://kde.org/][KDE]]
- [[https://www.xfce.org/][Xfce]]
- [[https://lxqt.org/][LXQT]]

资源消耗和 UI 体验成正比，GNOME 3 和 KDE 差不太多，其次是 LXQT，Xfce 体验最差，但是占用资源的确少，而且快。

/不想再尝试桌面版了，还是老老实实的用 GNOME3，后面有了本子玩玩其它发行版。/
* FAQ
** 安装 xfce 之后，卸载不干净怎么办？

- 卸载 =xfce4-*=
- 卸载 =xubuntu-*=

网上教程很多，但是有一点要注意：zsh 不支持 =apt remove xfce4-*= 这种语法，要切换到 bash 才行。
** 系统设置被卸载掉了，如何安装回来？

#+BEGIN_EXAMPLE
  sudo apt-get install gnome-control-center
#+END_EXAMPLE
** 如何启动 ROOT 用户

默认的 root 是被锁定的，要先指定一个密码： =sudo passwd root= ，Ubuntu 默认禁用 root ssh，需要打开：

1. =vim /etc/ssh/sshd_config= 将 =PermitRootLogin= 的 =without-password= 改为 =yes=
2. =restart ssh=
** 启动速度慢调试

- =systemd-analyze=
- =systemd-analyze critical-chain=

via: [[https://www.dedoimedo.com/computers/ubuntu-beaver-slow-boot.html]]
