#+SETUPFILE: ~/site/tpl/wiki-tpl.org
#+TITLE: Ubuntu
#+DATE: 2018-09-10 21:39:56

系统版本： =Ubuntu 18.04=

* 设置国内源

手动设置：

1. [[https://mirror.tuna.tsinghua.edu.cn/help/ubuntu/]]
2. =apt update=
3. =apt upgrade=

自动选择：

软件和更新 -> Ubuntu 软件 -> 下载自 -> 选一个国内的镜像源

* Ubuntu 18.04 快捷键

- =Super= 打开活动菜单，然后可以搜索应用程序、查看正在运行的 GUI 程序、切换工作区
- =Super + L= 锁屏
- =Super + D= 显示桌面
- =Super + A= 显示应用程序菜单
- =Super + Tab= 在运行的的应用程序之间切换， =Super + `= 在实例之间切换
- =Super + 箭头= 移动窗口位置，左分屏，又分屏，全屏幕等
- =Super + M= 切换到通知栏
- =Super + 空格= 多种输入法切换

* 代理

** SS
*** 客户端

1. 命令行：[[https://github.com/shadowsocks/shadowsocks-libev]] =sudo apt install shadowsocks-libev=
2. GUI：[[https://github.com/shadowsocks/shadowsocks-qt5]]

GUI 版本很不稳定，不如直接使用命令行（ =ss-local= ），配合 =systemd= 设置服务开机启动。

*** ss-local 配置

配置文件在 =/etc/shadowsocks-libev= 目录下。文件内容改为：
  #+BEGIN_SRC
  {
  	"server":"",
  	"server_port": xx,
  	"local_port":1080,
  	"password":"",
  	"timeout":60,
  	"method":"chacha20-ietf-poly1305"
  }
  #+END_SRC

systemd unit 名字为： =shadowsock-libev= 直接重启即可。设置开机启动 =systemctl enable shadowsock-libev= 。

*** Chrome 浏览器代理

因为鸡生蛋，蛋生鸡的问题，需要手动安装 [[https://github.com/FelisCatus/SwitchyOmega][SwitchyOmega]]，新版本的 Chrome 不允许安装第三方的插件，会报错。一个投机取巧的办法是将 crx 后缀改为 zip，打开开发者模式，然后拖入，经测试可行。

规则列表网址： =https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt=

*** 终端代理

Sock5 proxy：[[https://www.irif.fr/~jch/software/polipo/][Polipo]]

1. 安装: =apt install polipo=
2. 修改配置文件: =/etc/polipo/config= ，添加：
   #+BEGIN_SRC
   proxyAddress = "0.0.0.0"

   socksParentProxy = "127.0.0.1:1080"
   socksProxyType = socks5
   #+END_SRC
3. 重启: =system restart polipo=

设置代理（polipo 的端口是 8123）：

#+BEGIN_SRC
export http_proxy="http://127.0.0.1:8123" export https_proxy="http://127.0.0.1:8123"
#+END_SRC

测试是否生效: =curl ip.gs=

** SSR

1. https://github.com/shadowsocksrr/electron-ssr 设置订阅源，然后更新
2. 开启全局代理
3. Chrome 安装 SwitchyOmega 并设置，规则列表网址： =https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt=
4. 关闭全局代理

* 软件列表

- 搜狗输入法
  + 先安装 fcitx =apt install fcitx=
  + 安装 [[https://pinyin.sogou.com/linux/?r=pinyin][搜狗拼音输入法]]
  + 重启电脑即可生效，如果没生效，通过 fctix 配置，添加搜狗输入法
  + 设置快捷键为 =Ctrl+Space=  切换激活/非激活输入法 改为 =Ctrl+Space= ，启用输入法之间的切换给禁掉。（配置设置挺蠢的，要研究半天）
- 终端：[[https://gnometerminator.blogspot.com/p/introduction.html][terminator]] =sudo apt-get install terminator=
- 邮箱客户端：Thunderbird，说他丑，说他重度，可是只有他最稳定啊
- 截图工具：[[https://github.com/lupoDharkael/flameshot][flameshot]]
  1. =apt install flameshot= 安装
  2. 将 =flameshot gui= 绑定到 =Ctrl+Alt+A= 快捷键上
- 视频播放器：[[https://www.videolan.org/vlc/download-ubuntu.html][VLC]] =apt install vlc=
- gif 录屏：[[https://github.com/phw/peek][Peek]]，这个很好用，视频录制也有人推荐 [[https://github.com/hzbd/kazam][Kazam]]，就我个人而言 Peek 满足需求了
- +网易云音乐+ ：经测试 Ubuntu 下的网易云音乐比较吃资源，就不用了
- SNS
  + Telegram =apt install telegram-desktop=
- Docker

微信：

http://www.ubuntukylin.com/applications/24-cn.html

* GNOME 美化

安装工具：

#+begin_src shell
sudo apt install gnome-tweaks
sudo apt install gnome-tweak-tool
sudo apt install chrome-gnome-shell
#+end_src

https://extensions.gnome.org/ 比较实用的几个扩展插件： Dash to Dock、OpenWeather、Netspeed

重启 GNOME tips： =Alt+F2 -> r=

* 几种桌面对比
   :PROPERTIES:
   :CUSTOM_ID: 几种桌面对比
   :END:

常见的 4 种桌面：

- GNOME 3，Ubuntu 18.04 之后默认的
- [[https://kde.org/][KDE]]
- [[https://www.xfce.org/][Xfce]]
- [[https://lxqt.org/][LXQT]]

资源消耗和 UI 体验成正比，GNOME 3 和 KDE 差不太多，其次是 LXQT，Xfce 体验最差，但是占用资源的确少，而且快。

/不想再尝试桌面版了，还是老老实实的用 GNOME3，后面有了本子玩玩其它发行版。/

* FAQ
** 安装 xfce 之后，卸载不干净怎么办？

- 卸载 =xfce4-*=
- 卸载 =xubuntu-*=

网上教程很多，但是有一点要注意：zsh 不支持 =apt remove xfce4-*= 这种语法，要切换到 bash 才行。

** 系统设置被卸载掉了，如何安装回来？

#+BEGIN_EXAMPLE
  sudo apt-get install gnome-control-center
#+END_EXAMPLE

** 如何启动 ROOT 用户

默认的 root 是被锁定的，要先指定一个密码： =sudo passwd root= ，Ubuntu 默认禁用 root ssh，需要打开：

1. =vim /etc/ssh/sshd_config= 将 =PermitRootLogin= 的 =without-password= 改为 =yes=
2. =restart ssh=

** 启动速度慢调试

- =systemd-analyze=
- =systemd-analyze critical-chain=

via: [[https://www.dedoimedo.com/computers/ubuntu-beaver-slow-boot.html]]

** 18.04 蓝牙每次重启之后不会自动连接

使用 bluetoothctl 添加设备 TRUST：

控制台输入 bluetoothctl， =devices= 查看设备列表，找到蓝牙对应的 MAC 地址，然后 =trush <mac-addr>= 即可。
