#+SETUPFILE: ~/site/tpl/wiki-tpl.org
#+TITLE: WSL2
#+DATE: 2020-11-21 11:40:19

* 简介

WSL[fn:3]，Windows Subsystem for Linux。允许开发人员在 Windows 下运行 GNU/Linux 环境。
包括大多数命令行工具，实用程序和引用程序。

比较牛逼的一个点在于，安装一个 Linux 发行版跟安装普通软件一样，但却能拥有近乎原生的 Linux 系统
（真正的 Linux 内核），而不需要安装虚拟机。

* 安装指引

https://docs.microsoft.com/zh-cn/windows/wsl/install-win10

安装报错[fn:4]：

#+begin_src sh
  Installing, this may take a few minutes...
  WslRegisterDistribution failed with error: 0x800701bc
  Error: 0x800701bc WSL 2 ?????????????????? https://aka.ms/wsl2kernel

  Press any key to continue...
#+end_src

[[https://docs.microsoft.com/zh-cn/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package][下载 Linux 内核包]]，安装即可解决。

* Windows Terminal

https://docs.microsoft.com/zh-cn/windows/terminal/get-started ，直接在商店搜索 Perviews 版本使用。

Windows terminal 快捷键跟 Emacs 快捷键冲突很多，索性直接禁用掉：

#+begin_src js
  {
      "command": "unbound",
      "keys": "ctrl+v"
  },
  {
      "command": "unbound",
      "keys": "ctrl+c"
  },
  {
      "command": "unbound",
      "keys": "ctrl+shift+f"
  },
  {
      "command": "unbound",
      "keys": "alt+shift+d"
  },
  {
      "command": "unbound",
      "keys": "ctrl+shift+space"
  },
  {
      "command": "unbound",
      "keys": "ctrl+comma"
  },
  {
      "command": "unbound",
      "keys": "ctrl+shift+comma"
  },
  {
      "command": "unbound",
      "keys": "ctrl+alt+comma"
  },
  {
      "command": "unbound",
      "keys": "alt+space"
  },
  {
      "command": "unbound",
      "keys": "alt+enter"
  },
#+end_src

重新绑定页签切换快捷键：

#+begin_src js
  {
      "command":
      {
          "action": "switchToTab",
          "index": 2
      },
      "keys": "alt+3"
  },
  {
      "command":
      {
          "action": "switchToTab",
          "index": 0
      },
      "keys": "alt+1"
  },
  {
      "command":
      {
          "action": "switchToTab",
          "index": 1
      },
      "keys": "alt+2"
  },
  {
      "command":
      {
          "action": "switchToTab",
          "index": 3
      },
      "keys": "alt+4"
  }
#+end_src

* 使用

*禁用光标闪烁* 配置没有办法直接禁用，只能在系统全局设置。 ~控制面板 => 键盘 => 更改光标闪烁速率~
这个设定有点坑，估计后面会优化。

在 WSL 系统中使用宿主 Windows 系统的代理：

#+begin_src sh
  export ALL_PROXY="http://$(cat /etc/resolv.conf |grep "nameserver" |cut -f 2 -d " "):7890"
#+end_src

取消代理： =unset ALL_PROXY= 。

主机使用 ClashX 作为代理时，注意打开 =Allow LAN= 选项。

*远程连接到服务器上，中文乱码* =/etc/default/locale= 中 LANG 改为 =zh_CN.UTF-8= 。

*WSL 不支持 systemd* ，那就严重依赖 Docker 安装服务了。好在 Docker 和 WSL2 融合的似乎很完美[fn:1]。
只要安装 Windows 版本的 Desktop 之后，开启 WSL2 即可。

*设置启动目录* ="startingDirectory" : "//wsl$/Ubuntu-18.04/home/<Your Ubuntu Username>"= [fn:2]。

*ssh-add 报错： =Could not open a connection to your authentication agent.=* 根源是 ssh-agent 没起来，使用： ~eval $(ssh-agent -s)~ 解决。

*与宿主机（Windows）之间相互拷贝文件：* Windows 系统目录被挂载在 Linux 的 =/mnt/= 目录下，拷贝文件超级方便。

* Footnotes
[fn:4] https://github.com/microsoft/WSL/issues/5393

[fn:3] https://docs.microsoft.com/en-us/windows/wsl/

[fn:2] https://docs.microsoft.com/en-us/windows/terminal/troubleshooting#set-your-wsl-distribution-to-start-in-the-home--directory-when-launched

[fn:1] https://docs.docker.com/docker-for-windows/wsl/
