#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 一如年少模样
#+DATE: 2017-06-25 00:00:00

上周公司立项了一个新项目，确切的说算不上新项目，是之前产品的精简版。从预案到讨论，再到立项，再接下来就是吸取线上产品的经验教训，重新做更轻量级的架构以及技术上的简单选型（对于小公司来讲，更低的开发成本和线上运营成本是至关重要的）。

15 年 10 月份到七行的时候，已经是我工作 2.5
个年头了，也是我第一次可以独自去做技术选型和架构，胆战心惊不至于，但是小心翼翼还是要的。我认为，评价一个软件工程师的关键标准是：在限定的资源下，他可以做的有多好。什么
title、技术、工具都是虚的，唯有在特定的情况下，快速权衡，做出对于最好的方案才是水平的体现。

现在回看以前的架构以及技术选择，有些过度设计和臃肿，有很多的因素：技术不成熟大家都没有经验、频繁的需求改动等等，更重要的是当时所有人对产品和市场没有整体的理解。但是，好在平稳运营的这一年多的时间里，几乎没有出过大问题。其实过程中遇到了很多问题，这些问题不光是技术上还有产品和工程上，有一些个人理解。只不过现在很多想法都是零散的点，很难整理成面来分享给大家，再熬几年吧。

实实在在的又写了一周的代码，之所以用又，是因为这已经记不得是第多少个周，基本上没有什么沟通，都是一个人在搞。困的时候，中午多睡一会、效率高的时候，晚回去一会，总之就是没人管。当初是谁特么喜欢自由来着？！要说一个神枪手是拿子弹喂出来的，那么一个优秀的程序员就是拿各种乱七八糟的代码写出来的，写到吐。

昨天来公司打了一天刀塔，中午饭都没吃。提起游戏，好气！特么的，各种打不过，被人喷，对喷还喷不过。这要隔以前，虽然我打不过，但是我至少能喷的过啊。现在感觉精力严重不足，很难像以前一样全身心的投入到游戏中，都不知道自己在玩什么。心里不服，但是也没啥办法，打到下午三四点的时候，整个人都是迷糊的。仔细想想，也是应该的，可以随意支配的打游戏的时间越来越少了，水平难免下滑。万事万物的道理都是差不多的，哪有不劳而获的事情？

停下来的时候，要么疯狂的打游戏，要么就想一个人静静的待着，或者走一走也好，总之就是不想说话，尤其不想解释。工作累加上赶上心态不好的时候，我常常会想我特么过的这是什么日子：几乎把所有的精力都花在工作上，做着可能重要也可能不重要的事情；费劲心思做出来的东西，还总有人煞有介事的全凭感觉的评头论足；几乎永远都是用着陈旧的技术、平常的技巧解决新的问题；这真的是我想要日子吗？

后来才逐渐的明白了：生活就是 遥不可及的理想 和 碌碌无为的现状
两个矛盾不断被激化所得的东西，所以你会为前途迷茫而焦虑、所以你会为人生得意而兴奋、所以你会放弃了自己放弃了生活、所以你会重新拾起心情上路。不管你承认与否，最终我们都会走向「碌碌无为」，然后你才发现生活从来都没改变过多少，变的只是历尽世事之后的心态。

高晓松在有一期晓说里说过：四十不惑，说的不是人过四十之后什么事都想明白了，而是过了四十之后，想不明白的东西也就不想明白了。

其实表达的东西差不多，就像我上篇文章里写的：「人到了一定阶段之后，一些曾经执着的问题，就失去了再执着的意义。」。不是曾经的选择或者付出对了或者错了，而是不再有意义，你需要去面对新的问题。

尽管如此，我一直信奉的观点是：许多事我要懂，但是我不一定会去做，我会一直按照自己认为对的思路去做事，哪怕别人不理解也不会这么做。如果最终都要走向无为，那么我也会坚持初心，坚持到不能坚持为止，哪怕为这份坚持付出了更多。

「一如彷徨，一如年少时模样。」
