#+SETUPFILE: ~/site/tpl/weekly-tpl.org
#+TITLE: 2018-11, 2018-12

** 2018-12-26 11:43

https://blog-1252349778.cos.ap-beijing.myqcloud.com/2018/wujinguangmang.dpg

有些经历，我不愿回头。有些记忆，却永远在心里。

** 2018-12-25 16:28

时光难熬

** 2018-12-23 21:40

11-6 开始写 qwerty 代码，今天发布了第一个版本

** 2018-12-22 12:59

微信升级个大版本，互联网就跟发生个小地震一样，产品做成这样，夫复何求。

** 2018-12-22 09:18

http://microblog-1252349778.picsh.myqcloud.com/2018/2018-12-22.jpeg

OK, let's go.

** 2018-12-21 11:35

antd 算是一个很良心的产品了，迭代很快。同时希望别被 KPI 冲昏了节奏，做到一半又放弃了。

** 2018-12-19 16:08

气大伤身，淡定。

peace & love .

** 2018-12-19 10:53

千万不要跟这些个国企、政府部门打交道。

** 2018-12-19 10:50

工程和产品，本质上，都可以数据化。

** 2018-12-18 10:21

https://stackoverflow.com/questions/16647069/should-i-use-vagrant-or-docker-for-creating-an-isolated-environment

#+begin_quote
@Solomon Hykes

Vagrant is for managing machines, and Docker is for building and running application environments.
#+end_quote

最简单的讲 VM 和虚拟机的区别，就是 VM 是针对的虚拟机环境，而 Docker 针对的是应用的构建和运行环境。 也就是说前者针对的是 OS，Docker 针对的是 App。

** 2018-12-18 10:09

在公交车上当然是可以看书的，只不过看的记不住而已··· 刷书本个数是可以的，想要获得知识，我看还是算了吧。

** 2018-12-17 11:14

学习任何东西，实用任何工具，都要研究其不变的东西（本质）。

** 2018-12-15 22:02

当然国内外做技术的环境差距也是导致产品国内技术普遍不如国外的原因。国内如果在某个技术领域内做到顶尖，可选的公司也就那么几家了。在商业模式驱动下，技术永远只是解决问题的手段而已。

所以，这也是我有的时候会质疑自己做技术到底有什么用原因。

** 2018-12-15 21:28

不得不佩服过国外这些搞技术的表达能力，https://stackoverflow.com/questions/16047306/how-is-docker-different-from-a-virtual-machine 看了这个帖子对虚拟化了解清晰了好多，包括对 Docker 的两大核心技术 Namespace 和 CGroup 的理解。

之前看陈皓博客里将的 Docker，看的我云里雾里的。相比之前我们的技术大神跟别人的差距大的太多了。

突然对 Linux 充满了浓厚的兴趣。

** 2018-12-10 10:50

任何时候都谨记：结果导向，而非过程导向。如果一件事情可能不会有结果产出，或者产出的结果没有太多的价值，那就不要去做了。

** 2018-12-09 13:11

http://microblog-1252349778.picsh.myqcloud.com/2018/xiaxue.jpeg

** 2018-12-05 22:22

“ 每个人的生命里，都有最艰难的那一年，将人生变得美好而辽阔。”

—— 《岛上书店》

** 2018-12-05 20:47

不能在 qwerty 上花费更多时间了，毕竟只是一个工具，还有更重要的任务要去完成。

** 2018-12-04 21:17

努力的意义在哪里？

** 2018-12-03 23:26

写代码还是得靠周六日啊，平时晚上时间太少了。能抽两个小时整块的时间都是难上加难了。

** 2018-12-03 20:45

=git log --help=

原来这么牛逼，还有原理介绍！

** 2018-12-03 11:25

RGB Color Codes Chart： https://www.rapidtables.com/web/color/RGB_Color.html

Tag 可选颜色。

** 2018-12-03 11:17

周一还是照常的困，周末还是不能打游戏，但是不打游戏，还能干个啥呢

** 2018-12-01 11:59

总算把博客和 wiki，还有 prometheus 和 grafana 迁移到 阿里云了

** 2018-12-01 10:58

已经习惯了周末早上和老婆一起吃早饭，去菜市场买菜，然后回来她做饭，我看看东西，写写代码。 以前这些事情是不敢想象的，这可能就是生活本该有的样子吧~

** 2018-11-30 21:14

1. 三天的新人培训可算结束了，没有想象的那么遭，还是学到不少东西的。接下来要休息~
2. 阿里云的域名还是不能解析到腾讯云，第二次抱着侥幸心理，还是失败了。这个设定不是很理解，本来打算后面一直用腾讯云，看来不靠谱，转备案又很麻烦

** 2018-11-27 16:02

这一年里快把我身上的所有东西都快磨没了，好的和坏的。
