#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 写文字的那些事儿
#+DATE: 2016-04-17 00:00:00

虽然是个理科生，但是我从小就特别喜欢语文，见到一些美好的、有趣的文字，总会收藏下来。在朋友圈故作深沉和忧伤，这些文字可算是立了大功了。

自从逐渐开始写一写零零碎碎的事情之后，发现写技术文章毫无乐趣，而且没什么写作技巧而言。技术文章的核心点在于把问题描述清楚，思路清晰、直截了当通常是评判一篇技术文章是否合格的第一要素，解决用户的痛点嘛。

而非技术类的文章是有些不同的，如果要直截了当的描述问题，几百字的文章，几句话就说清楚了。所以，我以为这种碎碎念性质的文章，看似简单，实际很难。技术文章，需要技术功底，做一番调研和验证即可；闲扯类的文章需要你对周遭的事物有自己的理解，并且需要一定的社会经历。

有了写东西的习惯以后，发现在一段时间内不写东西总感觉少了点什么，一些新的想法总想一吐为快。

时间长了，我很快就发现了另外一个问题：自己对自己的行文表达手法越来越厌恶。记得在写在西农系列的时候，很多精力都用在如何把前后两句话连接起来，比如：「其实」、「也许」、「可能」、「说真的」、「发现」、「感觉」
... 类似的词汇都用烂了，自己也不想用，但是想不出更好的表达手段。

古龙，应该是我看过的最多的书的作者了，有些东西已经深深的成为自己的性格的一部分。比如，快意恩仇的江湖、以酒为伴的流浪、生而为人，那种深深的孤独。在写
[[/in-xinong-s12.html][在西农-S12: 陈东坡]]
这篇文章的时候，我刻意的模仿了一下古龙的写作手法，比如下面这一段：

#+BEGIN_QUOTE
  陈东坡。

  确切来讲，我们不算同学，没一起做过事，聊的也不多。

  但是他是我的朋友，老朋友。
#+END_QUOTE

现在看看也挺好玩的，但是我发现写这样一篇文章太难了。对我来讲，偶尔矫揉造作一两句还可以，毕竟，装逼这种事情，我个人还是很擅长的。通篇这样玩，自己看了也会恶心。

我平常看的公众号，MacTalk 和 小道消息 应该是最多的了。MacTalk
早期文章写作风格，我还是挺喜欢的，最近一年左右的的技术周边类的文章，我越来越不喜欢了。文字过于华丽，让我感觉很多地方都在套字，看完之后文章到底说了一件什么样的事，反倒没啥印象了。相比，Fenng
的文章则不同，始终如一，言辞犀利，恰到好处。

我认为每个文章的写作者都应该有自己的风格，我所追求是真实厚重的文字，宁愿爆粗口也不愿隐晦婉转，更不愿意哗众取宠，逗众人一笑。

路还很长啊~
