#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 在博客上的又一些折腾
#+DATE: 2016-01-17 00:00:00

*一*

在开始写「绝版青春」系列文章的时候，重新在 VPS 搭了一个 Wordpress
博客，本来感觉还不错。后来不知道是机房出了问题，还是线路有问题，一到晚上网站速度卡的打不开。每次发文章都要卡很久，很费时间。

一直用国外的、香港的主机线路总是时不时的抽风，香港的稍微好一些，几年前用美国的虚拟主机，一个月有几天访问不了都是常事。国内的主机需要域名备案，听说备案要邮寄资料、审核什么的很麻烦，所以一直拖来拖去。最近实在扛不住了，问了问别人人备案相关的事情，然后在阿里云（全称:
[[http://beian.gein.cn/order/index.htm][阿里云ICP代备案管理系统]]）申请了域名备案。

流程比想象的要简单的多，在阿里云层面上只需要填一些资料、拍个照片上传上去就可以了，效率挺高，2个小时左右就审核通过了；剩下的就是交管局了，可能是元旦放假的缘故，我的花了
12 天时间才审核通过。总之，还是挺方便的，提交了资料，等就行了。

比较蛋疼的一个地方是在阿里云申请代备案，必须要选择一个阿里云主机，提供「备案服务号」。

*二*

目前挂在我身上有四个域名:

- genglema.com : Dota视频更新的一个网站
- m1983.net: 音乐博客
- perfect-is-shit.com: 技术博客
- zhangjiee.com: 主页

除了最后一个，其他几个都不打算用了。现在觉得没有那么多的精力折腾了，得把时间花在真正有价值的事情上。前博客:
perfect-is-shit.com，当时申请的时候是因为最早的域名: keepsimply.org
因为不明原因不用了，就申请了 perfect-is-shit.com
做临时域名。没想到用了快3年了。

技术博客的所有文章都已经迁移到目前这个博客了，明天我就给丫关了。以后只有一个博客：blog.zhangjiee.com，不瞎折腾了。

*三*

昨天基于 Bootstrap
重写了一下博客主题，适配了一下移动端，少了一些条条框框，更简单了一些。也就是你现在看到的这个样子，细节上还有很多小问题，以后慢慢调整吧。

*四*

我不记得我在文章里吐槽（pen）过多少次国内的社会化评论系统了，今天再来一次。但是我保证这是最后一次了，因为我自己写了一个。

几年前，我有了个人博客以后，就开始尝试使用各种第三方的评论系统，尤其是在使用了
Jekyll
这样的静态博客工具以后，必须要使用第三方的评论系统。多说、友言、搜狐畅言、评论啦等评论，我试了个遍，甚至有过几轮切换。越用越失望。随便打开这几个评论系统的官网，都是看起来叼炸天，牛逼吹的一个比一个响。实际上用户体验渣的一B。前段时间我试用了一下多说，琢磨着都几年过去了，也该打磨的差不多了吧，实际上并没有，感觉他们完全跑偏了方向。

CoderZh
写过一篇关于多说评论系统的文章：[[http://blog.coderzh.com/2015/09/18/holy-shit-duoshuo/][坑爹的多说评论]]，我摘录几句：

#+BEGIN_QUOTE
  运用了各种奇技淫巧的黑科技手段，终于把之前旧页面的多说评论全部转过来了。如果再来选择一次的话，我绝不选多说。之后有时间，全部转移到disqus吧。

  多说简直就没人维护啊有木有，居然还那么多人用着。罗列一下多说评论的各种不人性:

  1.残废的评论通知功能
  简直就收不到任何通知啊，有木有，别人回复了根本没有邮件通知，页面右上角的弹框通知也木有啊。直到上周实在不能忍了，在我的VPS上跑了一个多说实时邮件提醒脚
  ...
#+END_QUOTE

就这个收不到评论通知的问题，几年前就有了，这算是评论系统最基础的功能了吧，到现在还没解决？

为什么我会持续吐槽这些产品？因为本质上这些根本不算是技术上的难题，就是他们没有用心去做产品。几个人的团队，只要用心去做，根本不需要几年的时间就可以把核心功能做的很完善了。

在我看来，这几个评论平台的通病在于：光顾着去做「社会化」了（也就是社交），而没有把最核心的「评论系统」做好。产品太中国化了，我他妈一篇文章的评论，需要你关联QQ、微博、豆瓣、微信干嘛啊？输个昵称，一个邮箱不就
OK 了？有别人的回复，直接邮件发给我就行了。

评论的关键在于评论内容本身，其他乱七八糟的功能做好了就是锦上添花，做不好就是画蛇添足。我发现好多产品做着做着都做成了大而全的产品，别人有的，我也要有，大家相互抄，抄到最后最核心的东西都没做好。

[[https://disqus.com/][disqus]]
倒是很不错的，但是国内访问速度太慢了，基本上用了和没用一样。在很长一段时间，我的博客都是没有评论系统的。

这两天有时间写完博客主题，顺手写了一个评论系统。目前输入昵称和邮件就可以评论了，安全性的因素完全没有考虑，先用着吧，有问题再解决问题，慢慢优化。等后面自己用爽了，核心功能都有了，再考虑公开给别人用。

试听了一下徐佳莹的歌，感觉还不错，推荐几首：《大雨将至》、《绿洲》、《不难》。
