#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 不做井底之蛙
#+DATE: 2016-09-20 00:00:00

1) 我初中的时候，分好赖班，我是平行班，物理成绩一直处于 70 分左右。直到初三的时候，分到了好班(2班)，说也奇怪，我并没有比之前努力多少，
   但是成绩上突然比以前高了 20 分；
2) 初三的时候，1班有个同学姓马，就叫马同学吧。学校附近有一个街机厅，马同学经常中午去打街机，上学、考试从无例外，据说在街机厅已经近乎无敌。
   不仅如此，马同学的理科成绩处于全校的佼佼者，一时成为学校的传奇人物。

   和初中差不多，我高一依旧是平行班，高二分文理班，我又被分到了一班，马同学在一班。

   那个时候，我有个同桌，叫穆怀斌，我常叫他"老穆"，也打街机。

   有一天，我突然想起来了，就问他，有没有和马同学切磋过 97(拳皇)，他说打过。那我就接着问，打的怎么样啊，那可是我们初中街机的王者啊。
   他说"一般吧，没感觉有多厉害"。

   我心里琢磨，这不科学啊，一定是老穆太厉害了。我继续问，那你的水平是什么阶段呢？他的回答却是："我自己也一般吧"。

3) 从高一到高二，换班，有些事情我非常不理解。总觉得这好班成绩都想对好一些，那一定比平行班的同学更努力更聪明一些吧。
   直到换班以后，我才感觉到完全不是这么回事。平行班中小部分的努力程度要比好班的大部分人高很多。

   好班中叛逆的孩子也很多，谈恋爱的不比平行班少。以老穆为例，很多课上都是睡觉，晚上下课以后踢球一直能踢到上晚自习，然后在晚自习上吃饭。业余生活很挺丰富。

   我看到很多人都和他类似，一天吊儿郎当的，但成绩一样前50、前100。要知道，当时平行班中，要有一个人能进前 100 都很不错了。
4) 高三转学到陕西老家，同样是平行班，我见到了纯正的农村出生的孩子，他们之中肯努力的人，远比之前高中的人高太多了。

   转学之后，我第一次模拟考试，考了年级第一。再之后的考试一直基本上都是第一、第二的。在之前的学校我考的最好的成绩也就是年级三四十。

   我非常的不理解，为什么付出更多的努力的人，没有得到应有的成绩。他们的学习方法有问题？不见得，不够聪明？更不可能。

--------------

*你所处(选择)的环境，将决定你的视野和格局，进而决定你上限，无论你怎么努力都不可能超越的上限。*
