#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 在合肥-S8: 这一年多(下篇)
#+DATE: 2016-12-06 00:00:00

上篇文章[[/in-hefei-s7.html][在合肥S7：这一年多(上篇)]]，是在状态不好略带发泄的情况下写出来的，没想到的是看的人比之前的文章要多一些，有些朋友还在朋友圈转载了，惭愧。东坡还赞一个大包，搞的我不太好意思。

写微信公众号一年多了，刚来合肥的时候日子难熬，连续写了十几篇的《在西农》，没多久被开通了原创功能(可以评论)和赞赏，完全是意料之外。因为公众号关注的人比较少，后面的文章便开了赞赏，只是为了好玩，赞赏的也都是一些朋友，每次写完文章都微信上喊磊磊「早饭给加个蛋」。于是，早饭便有了蛋！后面的文章还是会继续开赞赏，建议大家多留言和点赞，少分享，少赞赏(如果要赞赏，最小额度也是极好的)。

最近三四年，工作之外，我折腾了很多事情，大部分都是一时兴起，没什么价值，也没什么东西坚持了下来，好坏参半。写博客也是这样，平台和工具一直在换，csdn->博客园->wordpress->jekyll->github->微信公众平台...。到合肥这一年的时间里，不知道是工作比以前忙了，还是疲倦了，又或者是年龄大了操心的事情多了，感觉精力真的不够用了。而且，前几年的折腾除了多了一些茶余饭后朋友闲扯的时候吹嘘的资本，水平并没有得到实质性的提升。但是没有评判以前所做的事情和选择正确与否，毕竟，没有以前也不会有现在的转变。

这半年里文章的更新频率低了很多，以前都是一两周一篇文章，现在差不多要一个月左右，这和年初的计划相差甚远，今年很快就要结束了。频率低是有原因的，我不想把情绪不断的写在文章里，又或者是写一些无关痛痒的回忆录打发时间，需要面对自己的心性，不再去逃避生活给予我的一切。后续不会再写上一篇那样的文章。

今天是我生日(如果能赶在明天之前发布的话)，嗯，26岁了(此处应该响起起BGM，许巍的漫步:「很多事来不及思考，就这样发生了」)。下面这句话送给
13~16 这三年的自己：

#+BEGIN_EXAMPLE
  短短几年里，自己，不愤青了，话少了，沉默了，开始想家了；
  短短几年里，父母，不吵架了，变唠叨了，开始真的变老了；
  短短几年里，朋友，联系少了，买房了，结婚了，生娃了，开始养家了；

  你想留住过往，追赶明天，却发现越追越远；
  你觉得这社会、朋友、家人变化太快，其实是你变化的太慢了，慢的离谱；

  就这样，没有什么可以坚持的，投降吧;
  就这样，没有什么可以坚持的，投降吧;
  就这样，没有什么可以坚持的，投降吧!
  (重要的事情说三遍~)
#+END_EXAMPLE

在 13 年初去上班的时候，我给了自己三个关键字:
程序、音乐、游戏，这三个词频频出现在我的很多网络帐号的签名里(知乎、QQ、网易云)，不断的提醒自己。仅从这三项来上说，我执行的还是不错的：

1. 每天都在写代码，大量的写代码
2. 每天都在听歌，大量的听歌
3. 空闲的时间，几乎都在打游戏

15
年做游戏的时候，游戏系统翻来覆去的写，一个版本忙起来忙的要命，闲起来闲的蛋疼。忙的时候，一写代码写一天，很多机械性的代码，我都开始烦
C++ 了(要知道曾经我是多么的热爱 C++ 啊)。

到了合肥之后，嘿！忙成了常态，写代码写到吐。上个版本优化 Web
订单业务，3个功能，一个功能 4 个
后端API(增、查、删、改)，前端跟着每个功能封装 5 个 JS 函数，也就是光函数
3*(4+5)=27 个，加上 Web
页面的设计，表单，只用了两天半的时间。你感受一下，毫无技术含量的东西，但是必须要在限定的时间内完成，而类似的事情成了常态。

游戏也打不动了，没人跟我玩了。刻意的戒
Dota，从大学就开始戒，戒了几年越戒打的越猛；前段时间，突然就不想打了，感觉没意思。

倒是音乐从来没有间断过，她依旧是这最美好的事物之一。

10 月份，我意识到该做一些改变了。这里要插几句：

#+BEGIN_EXAMPLE
  其实人在做一些事情的时候，需要「笃信」。首先，你要给自己信念，说我能行，你就可以开始做了；剩下的事情就是不断的给自己洗脑，每天都对自己说，我能行，我能行，一旦你养成了习惯，它成了你生活的一部分，也就没那么困难了。
  以前我做了很多规划，写的特别细，可是每次坚持几天就坚持不下去了。后来我找到原因了，计划的复杂了，让我觉得压力太大了。想要做一件事情，只需要一个明确的目标，然后不断的重复把这个目标深深的刻在自己的意识里。这么简单的道理，我竟然到现在才明白。
#+END_EXAMPLE

在未来的三年时间里，我给自己的关键字改成了：产品、音乐、学习。

把「程序」改成「产品」，在我最近的文章中，基本上可以体现出来了。我想再往上走走，不再执着于技术，而是花精力去研究产品形态，研究数据，研究用户。

音乐依旧保留，后面我会写一系列的关于音乐的文章，但愿这次不搁浅，嘿嘿。

「学习」一词是我抄李笑来老师的公众号「学习学习再学习」，看过他的《把时间当成朋友》、《七年就是一辈子》；以及购买了他在
得到APP
上的《通往财富自由之路》，李笑来老师写的东西对我的影响很大。。在以往的经历中，每当我觉得自己很不错的时候，再向前走一走就会发现自己才刚刚开始。到上海有这样的感觉，到合肥更是这样。所以，持续学习，「Stay
Hungry, Stay Foolish」.
