#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 公众号开通了原创保护
#+DATE: 2016-03-19 00:00:00

昨天有两件很开心的事情:

- 第一件是早起发现许巍发了新的单曲:
  [[http://www.xiami.com/song/1775751240?spm=a1z1s.6843761.1478643741.1.dCMcLR][生活不止眼前的苟且]];
- 第二件是下午 3
  点半，微信推送给我一条服务通知「微信邀请你使用公众号原创保护功能」。

许巍的这首新歌对于我(可能包括杨溪)来讲，歌的本身所表达的含义、歌是否好听都已经不那么重要了。每次听到他的声音，就像一个老朋友在诉说一样，满满的都是过去的那些欢笑、那些纯真、那些迷茫。

引用一下杨溪最近的一条说说：

#+BEGIN_QUOTE
  听许巍已经十年了，从迷茫、彷徨、嘶吼和愤怒，到平静、温暖、安详又充满希望。虽然已经渐渐听的越来越少了，但是他的歌对于我来说，就像那些朋友一样，即便再久不去碰触，听到依然是那么熟悉。
#+END_QUOTE

这可能是杨溪发的最好的一条说说了。

回到第二件事情上，原创保护这件事情我从未想过，更新频率不高、文章价值一般，粉丝量更是少的可怜，所以很惊喜。有些触动：「这好像是我第一次坚持一件事情一年左右，得到的肯定」。

我是一个想法很多的人，但同时又是一个没有耐心的人，所以很多尝试最后都半途而废了。这一两年，有意识的让自己少一些折腾，培养一些好的习惯，多一些坚持，公众号写文章算是一个体现吧。

去年(2015)的
4月26日，我在「张杰de闲言碎语」这个公众号上发布了第一篇文章:
[[http://blog.zhangjiee.com/stop-update-blog.html][博客停更，转做公众号]]。说一些统计数据吧:

到现在为止一共发布了 47 篇文章( 45 篇原创，2 篇照抄)，一共写了 123,711
个字。其中已完结的系列在西农一共 15 篇，51,365
个字。看着这些数据，还是有一些成就感的。

然而，粉丝只有 188 个，这 188 个中有 30
个左右是一些认识的朋友(现实生活中的，网络中)。再努努力，文章数量就可以赶上粉丝数了，哈哈。

很多喜欢写文字的人，通常都有一个纠结的心里状态:
一方面嫌弃自己写的东西太矫情怕太多的人看到，另外一方面又希望有一些人看到，希望能得到更多的认可和理解。在一开始写纯技术文章的时候，希望被更多的人看到，又怕自己写的不够好；从
14 年下我开始写这种碎碎念类型的文章，就出现了前面那种纠结的心态。

到现在，我已经很少有哪些顾虑了，写东西对我来讲是一种享受：看到的想到的都会写下来，长文章会写到公众号，短文章记录到
once
，偶尔还会发个朋友圈。以至于一个朋友说：「你的故事里有太多的忧伤」，其实不全是，只是我太矫情，抑郁青年，也因为「开心的事情，有太多的人可以分享，而一些患得患失，文字是最好的表达方式」。所以，朋友圈的你们，受苦了。

微信原创保护最主要的一个功能是增加了「用户留言」，以后你们可以留言啦。最近一个月事情比较多，已经攒了很多想法，可以写好几篇了。在后面还是会平均一周一篇文章，期待吧。

最后，

- 感谢你们一直愿意听我念叨，也随时欢迎你们取关；
- 感谢微信公众平台，希望可以越做越好。

--------------

微信扫描二维码关注我的公众号:「张杰de闲言碎语」


