#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 上海一周，一切顺利
#+DATE: 2014-03-10 00:00:00



接上一篇 [[file:../blog/2014/leave-beijing.org][离开北京，去上海]]，到上海一周了，房子找好了，工作找好了，一切顺利。
明天就要去上班了，写一写这一周的一些感悟。

* 时间线
   :PROPERTIES:
   :CUSTOM_ID: 时间线
   :END:

- 4 号过来先找锋子，在虹口区蹭了一下锋子的宾馆，晚上还去网吧 Happy 了一下。
- 5 号投奔超超(浦东，张江)，当天晚上把房子搞定。不得不说这边比北京那边住房要便宜一些，
  1400 的房子(空调、电视、洗衣机、冰箱、厨房、卫生间和一些家具)和北京 1500 的房子(15平米，卫生间、空调)比要强太多了，
  上海是在浦东，北京在西苑。同时把简历给[[http://kumu-linux.github.io/][枯木]]，内推给[[http://www.123u.com/][江游]]。
- 6 号签住房合同、搬家、熟悉周边环境。同时收到江游的面试通知(7 号下午)。
- 7 号下午江游面试(两面)，并安排下一次面试。之前枯木让我去江游，我只是抱着拿个 offer 的心态，并没有多少期待。
  通过技术面试和一些了解，让我真的想进入这个团队。江游的团队规模和安排我的职位以及公司的氛围都比较符合我的要求。
- 8 号和上海的小伙伴们一起吃了个饭，唱了个K，恰好小宝也到上海出差。
- 9 号超超带着熟悉周边环境。
- 10 号再去面试(两面)，拿到了江游的 offer。

* 上海印象
   :PROPERTIES:
   :CUSTOM_ID: 上海印象
   :END:

去年来过一次，前年也来过一次。印象一直不错。今年过来一如既往吧，可能是和北京的对比，天气上落差太大，侧面增加了我对上海的好感。

不过人文方面不如北京，总感觉本地人说话比较冷漠(问路，买东西)，不过也无所谓了，没啥交集。

* 技术成长
   :PROPERTIES:
   :CUSTOM_ID: 技术成长
   :END:

相信每个喜欢技术的人，都深深的了解自己的优势和劣势，我也不例外。只是这次面试让我理解的跟深刻一些，
这里我想告诉大家的是一定要 *有一个自己的擅长的方向，然后深入的挖掘* 。尤其对于刚入职场的技术人员来说。
不要在工具和语言上花费太多的时间。以我为例，这些年，乱七八糟的技术和工具玩过很多，
但是当面试官问我你觉得你的擅长什么？真的有些不好回答，我不能告诉他我 C++ 学的不错，
毕竟那只是一门语言并不是一个方向。这次找工作，主要依靠之前折腾过的东西，和扎实的 C++ 功底。
但是下一次，这些东西不再有那么大的优势了。难道一个工作了三四年的程序员，还要告诉别人我会 C++ 么？谁不会？

*要注重计算机基础* ，操作系统、数据结构算法、编译原理、计算机组成原理等。我问了一下技术面的面试官（广宇），
在熟练的技术和扎实的基础必选其一的话，会选哪个，他选后者。我也同意这一点，在这一行干的时间越长，你就会发现语言、工具都没什么，
而这些当年逃过的课却是最最重要的。

* 加入江游
   :PROPERTIES:
   :CUSTOM_ID: 加入江游
   :END:

选择江游有几个原因:

1. 对做的事情感兴趣，手游本身前景不错。另外用到的技术(网络编程、数据库)恰好都是我不擅长的，对我来说也是一种历练和挑战。
2. 技术氛围，虽然没有工作，但是通过几次面试可以感受到面试官的技术功底，交流期间也可以感受到公司的企业文化。属于我喜欢的那种类型。
3. 薪酬待遇，待遇挺不错的，薪资小伙伴们感觉我要的少了，我感觉还可以，不是很在乎薪资(我也就那么回事，不是不自信，而是我很了解我自己的技术水平)，
   还是注重个人技术成长吧。

* 无形的资产
   :PROPERTIES:
   :CUSTOM_ID: 无形的资产
   :END:

靠谱的朋友比什么都重要，如果没有他们，我也不可能在这么短的时间租房、工作。感谢。

--------------

*2014.03.11 更新*

1. 所有曾经逃避过的东西，总有一天需要去面对。软件开发如此，技术成长如此，生活也是如此；
2. 所有曾经付诸努力的东西，总有一天会用到。这一点是针对技术学习而言的，学过的东西，当时可能没有用到，但是以后肯定会用到的；

因此，珍惜工作、生活中每一个可以提高自己的机会，珍惜身边的每一个人，不要再逃避遇到的问题，勇敢的面对。

*2020-01-01 更新*

没想到在挖财还是磊磊内推的。
