#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 关于理想
#+DATE: 2014-07-02 00:00:00

本来打算以"理想"作为本篇博客的标题，后来想想"理想"实在过于宽泛，而且容易让人误以为这是一篇"洗脑"式的文章。
于是就改成了"我的理想"，其实想来全文也必定不是谈个人理想，而是一个人的成长过程。从这个角度来看，以"我的理想"作为标题也不太合适。不过也都无所谓了。

有一个半月了没有正式的写文章了，倒是有很多想法可以写，不过很凌乱，不成熟。也就拖来拖去，一直拖到现在。

今天公司"五周年"庆，其中有个活动是让大家都写一下自己的梦想，然后用瓶子封起来，塞到梦想墙里面。我所填的东西，也就是我想写篇文章的缘由。

其实我们每个人都是有自己想法的、有自己的理想的，只不过大部分选择的沉默，不去向别人表达你对事物的看法，说自己以后想做的事情。
这也就是我和大部分人的区别，我喜欢把自己所看到的、所想到的一切美好的东西（音乐、生活、技术）分享给身边的朋友，
可是通常得不到别人的一个很好的反馈，或者说得不到任何反馈。久而久之，我产生一些质疑，以前我总是希望我趟过的坑，走过的弯路别人不再去趟，
不再去走。然后告诉别人什么是好的，什么是不好的。现在不会了，因为我深深的明白，他们根本就不会去思考我在说什么，因为他们没有经历过。

就拿超超来说，他总是习惯给自己贴上一些标签，比如 Java、Android 前端。不光是超超，很多人都是这样的，喜欢给自己贴各种标签，C++? Java?
.Net? Web? 运维? 再举个吴磊跟我说过的例子，很多开发人员不会用生成 ssh 公钥/密钥，而且会质问运维人员这不是你们应该做的么？

就技术人员贴标签这本身是没有什么大的错误的，标签从一定程度上可以说明某个人所擅长的技术/方向。但是标签所带的最大的问题是：被标签所束缚。
超超和锋锋都告诉过我说: 我们搞前端不需要去理解什么操作系统，不需要去理解你们底层的东西。真的是这样吗？！开发人员就不应该去理解一下 ssh 原理？

我个人觉得，技术人员不要给自己贴那么多的标签，关注更高层次的一些东西，所使用的技术真的不是那么重要的（这个观点我跟很多人都说过，
但是貌似从来都没有用）。没有人规定你该学什么不该学什么。就拿 gy 来说，我们后端的主程，自己写后端框架，在项目前期，还兼前端程序。
写各种 shell, python 工具，用 django 搭建内部协作平台。比较逗的是，前段时间，还自己改前端的编码问题，解决起名字不能有中文的问题。
我也没感觉他有多累，可能会有人说他有多年的积累啊。没错，积累很重要，但是我感觉更重要的是对待技术的态度。如果在你不会的同时，
你还告诉你自己这件事情应该别人去解决，那么，这件事情对你来说就无比的艰难。

以后，我会做积累然后的去写想法和感受，但是不会轻易的向别人表达（因为没有人会真正的思考）。

我大一的时候理想很简单：就是在大四找工作的时候，找份 5k+ 工资的工作（当然大四的时候实现了，不到 5k 估摸着北京是难活下去了）。

到大二、大三的时候，很多人都想着以后创业，去改变世界。我也想过，我的理想是有自己的工作室，去做自己喜欢做的时候。几个原因：
短小精悍的小团队，创造性的工作、自由（类似 37signal）。

曾经在大学里组建过自己的团队FREESPACE，和郑媛她们一起做乐魂，后来和 TankyWoo 一起做论坛（cppleyuan.com），组建Sib9（博客墙+cpp1x.org）。
虽然没有做成过什么大事，但是这几年我能有的想法基本上都已经实现，收获颇多：技术只是附属品（好吧，我其实技术很渣），
重要的是对不同事物的理解（产品、团队、论坛和博客的趋势、音乐），也体会到自身的缺陷（瓶颈）。

折腾让我觉得很疲惫，也可能是工作的时间稍微长了一些吧，生活环境（人/物）也在变化。很多人被这个社会所扭曲，太盲目的选择，明知道改变不了什么，
还是会勉强自己，有点像飞蛾扑火，活着总是被各种事情束缚。

这一切，致使我更加对真正的自由的渴望。我一直是"自由"的，到上海的工作以后，可以是说相当自由。可是我却一点都感觉不到自己是自由的，反而觉得很痛苦。
因为小半年了，技术上没有什么成长，在北京一年我好歹也看了好几本书、做了些事情的。我才明白以前的追求的自由的是有些偏激的。

有一天我在知乎上，看到一个帖子说，真正自由的人首先是"自律"的，我感觉很有道理。我渴望自由，但是"自律"能力太差，这应该是这段时间非常浮躁的问题所在。

自由这个词，可以涉及到很多方面：思维，生活，财富，工作等等。做到真正的自由，这就是我的理想。现在，从"自律"开始。
