#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 离开北京，去上海
#+DATE: 2014-03-03 00:00:00

好久没有写思绪飘零式的文章了，今天是时候来一篇了。

在北京的最后一夜，作为一个 Bloger，当然要做的最后一件事是Blog，写写经历，发发感慨。

过年的时候，我打算在风行踏实的再干一年，后来的离职我只能用五个字来形容：万万没想到！连我自己都被自己吓了一大跳。
周一晚上想好的辞职，没到一周时间就 GG 思密达了。

回忆我在风行的一年，算是过的比较轻松，也学到很多知识。武师傅去往武汉以后，正式的接收了工作，我自以为还是做了很多事情的。
虽然解决问题的速度上是慢了一些(业务逻辑不熟)，但是经过我手的每一件事情，我都尽自己能力做到了最好，从来没有从心里上应付过事情。

在我的手上，Task 模块除了与直播有关的代码没有动过，其他代码基本上都进行了修改，尤其是的最基本的编码规范(缩进，命名、风格等)。
写过的脚本，不管是小或者大，被自己重构过很多次了，而且都用Git做版本控制。周四看的时候，离开风行对折腾过的代码依旧恋恋不舍。

直接促使我离开的原因只是一次不足 10 分种的谈话，我想一起的工作的小伙伴大体也能猜出来了，离开很仓促。我也就不必隐瞒什么了。
这是一个导火索，但并不是离开的唯一原因，只是它让我开始思考这个团队是否真的适合我。如果不适合，我为什么要继续待下去？

之前所处的客户端内核组团队，我以为它是一个很好的整体，一个优秀的团队，每个人的责任心都很强(这是非常难得的)，在协调配合、
业务沟通上可以说畅通无阻，非常和谐。这是我非常喜欢这个团队第一个理由；第二个理由是在经理的领导下，不用背着很多 KPI，工作氛围好，比较轻松；
第三个理由是里面的我喜欢里面的小伙伴，人与人之间沟通不用考虑太多，每周三的台球活动将是我在北京这一年最好最快乐的回忆。

对于大家的一些话，我在离职的最后一封邮件里面都说了。前面我写到了如果不适合，会离开团队，这里写一下我觉得不适合我的原因，反正已经离职，
写出来也就无所谓了：

1. 工程师文化不强，或者说很弱。例子很多，比如编码风格不统一(这个问题我纠结过太多次了，甚至起过争执)，到现在为止，仅缩进上，还是没有统一。
   再如，业余时间的除了业务上的交流，基本上不会交流与其他技术相关的东西。再如，不写博客、不玩 Github、不怎么逛社区等，我觉得要求所有人是没有多大意义，
   但是基本上没有人不科学吧！这些东西可能大家从潜意识里面觉得不重要，我觉得这是一个程序员最基本的素养，不谈是否重要，尤其是编码规范，
   这是最基本的要求了吧。
2. 不愿意表达自己的观点/想法。对于会议上的讨论，其实一些人是有自己的想法的，除非问到被问到，否则什么都不愿意说。就拿我们小组来说，
   八九个人的团队，会猜与讨论的不超过个(包括我和主管)。我觉得一个当你脑子里面有一个好的想法的时候，尽快表达出来，然后付诸实践，
   否则你就真的什么想法都没了。
3. 科研味重。在开源和论文之间，选择了论文，难以置信的是真的把论文作为季度目标了。让外人了解团队，我觉得开源和博客是很好的两个选择，而论文，
   真的不敢苟同。

基于上面 3 条，我离开了风行，并不是那一次谈话。而且，这只是我觉得团队不适合我的 3 条原因，并不是团队的缺点。

为什么要去上海？

也许这些都是缘分吧，

1. 我有了离开风行的想法;
2. 马上工作满一年;
3. 锋子跟我说他3月初要去上海，我本身也对上海有很对期待;
4. 北京连续一周的雾霾。

去年和前年各去过一次上海，对上海印象还不错。所以，去上海！

请允许我最后说一次，晚安，北京！

如果可能我再也不回来了，再见！

-----------------------------------------------

*2020-01-01 15:59:33 更新*

看到 6 年前离开北京的文章，想起一些事，感觉自己应该向周总道个歉…… 很多看法现在想起来都是偏见，纵使看到我很多怨念的情况下，
还是可以拍着我的肩膀说：以后做事还是不要太浮躁，有点耐心。这份心胸是我比不了的。

刚毕业的时候感觉职场的同仁都应该是特别专业的，拥有专业的技能、责任心以及自我驱动。

但后来发现差异化才是常态，职场最重要的能力应该是包容心，细节上存异，大方向上求同。
