#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 重来
#+DATE: 2014-01-18 00:00:00

[[http://www.amazon.cn/%E9%87%8D%E6%9D%A5-%E6%9B%B4%E4%B8%BA%E7%AE%80%E5%8D%95%E6%9C%89%E6%95%88%E7%9A%84%E5%95%86%E4%B8%9A%E6%80%9D%E7%BB%B4-%E8%B4%BE%E6%A3%AE%E2%80%A2%E5%BC%97%E9%87%8C%E5%BE%B7/dp/B0048EKQS0/ref=sr_1_1?ie=UTF8&qid=1390186254&sr=8-1&keywords=%E9%87%8D%E6%9D%A5][《Rework》]]这本书是这几年我读过最好的一本书，整本书一直都是频频点头，看完之后大呼过瘾。看了几遍了，决定写篇博客分享一下里面的观点，以及自己的一些想法。加粗部分为原书摘录，剩下为个人理解，不代表书上观点。

#+BEGIN_QUOTE
  「现实世界」并不存在，那只是一个借口，只是某些人为了开脱自己的无所作为，跟你一点关系都没。
#+END_QUOTE

「现实世界」这个词充斥在我们的周围，尤其毕业到现在，从同学、朋友的聊天过程中，这个词也是高频出现。经常会拿理想和现实做比较，而这些往往就成了我们不去实现、不去努力的借口。反思一下，我们真的尝试了吗？努力了吗？因为别人尝试的失败、别人的无所作为，所以我们也就没有希望了吗？显然，这是不成立的。

#+BEGIN_QUOTE
  逗留在过去的失败中是无法进化的，进化是建立在成功的基础上的。
#+END_QUOTE

失败能得到的是失败的经验，然而我们需要是成功的经验。如果一开始就想着失败，那么永远不可能成功。

#+BEGIN_QUOTE
  计划即瞎猜。
#+END_QUOTE

算一算我们从小到大做过多少计划，有多少坚持做完了呢？没有人会知道一个月以后，半年、一年以后会是什么样的。你不知道你下一刻想什么、要什么。不要动不动就制定计划说明书，做事情吧！

#+BEGIN_QUOTE
  小公司并不只是一块跳板。小公司本身就是一个伟大的目标。
#+END_QUOTE

#+BEGIN_QUOTE
  工作狂不是英雄。他们没有力挽狂澜，不是是浪费时间而已。真正的英雄早就想出办法、搞定一切，然后回家了。
#+END_QUOTE

#+BEGIN_QUOTE
  挠自己的痒处。想创造一个伟大的产品或者卓越的服务，最简单直接的办法就是做你自己想要的东西。
#+END_QUOTE

这一点我非常赞同，以前在博客中说过一句话：「如果一个东西做的自己都不喜欢，凭什么要求别人去喜欢」。评价产品做的好或者不好，最直接的方法就是自己做用户，如果你是用户，你会知道哪些才是真正需要的。

#+BEGIN_QUOTE
  在你人生中真正有意义的的是你做什么，而不是你想过什么或者计划过什么。
#+END_QUOTE

做个实干主义者，不要空想。只有你把你的想法做到了，你的想法才是有意义的。

#+BEGIN_QUOTE
  你的需求没有想象的那么多，伟大的公司基本上都起于微末。
#+END_QUOTE

不要妄想一下子做一个完美的产品出来，把握住产品的核心是什么。假如你要做一个音乐播放器，你首先要做的是“播放“功能，一旦可以播放了就可以上线让别人使用了。绚丽的界面，播放频频崩溃，一样没有人用，用户需要的是实用有效的产品，不是花瓶。

#+BEGIN_QUOTE
  在你高唱"始终不够"的悲观论调之前，请试试看自己利用现有的资源能走多远。
#+END_QUOTE

#+BEGIN_QUOTE
  与其做个半成品，不如做好半个成品。
#+END_QUOTE

#+BEGIN_QUOTE
  从核心出发。如果有些东西即使没有了，你也能把事情干下去，那这些东西就不是事业的中心。
#+END_QUOTE

#+BEGIN_QUOTE
  不要过早的关注细节。
#+END_QUOTE

#+BEGIN_QUOTE
  项目周期过长会打击士气。项目开发时间越长，成功的可能性越小。只要有足够的动力和士气，就要趁热打铁，积极决策，果断推进，现在就把事情做出来。
#+END_QUOTE

#+BEGIN_QUOTE
  要记住，时尚会凋零。只有你聚焦于长久的功能时，你才会发现自己把握了永不落伍的东西。
#+END_QUOTE

产品如此，技术如此。时尚会凋零，而实用的不会。

#+BEGIN_QUOTE
  人们总忍不住执着于工具，而不关注要用这些工具要做的事情。
#+END_QUOTE

小伙伴们有多少次想要写代码，却最终把时间花在编辑器的选择和配置上？

#+BEGIN_QUOTE
  立马就上线。
#+END_QUOTE

《黑客与画家》中提及的创业哲学：搭建原型 -> 上线运营(别管Bug) ->
收集反馈 -> 调整产品 -> 成长壮大。

#+BEGIN_QUOTE
  退出的理由。为什么要做？你的解决什么问题？这真的有用吗？你加上去的东西有价值吗？这种改变真的会起作用吗？这种方法简单吗？有其他更值得做的事情吗？这样做值吗？有的时候放弃其实是一步好棋，即使为之投入很多努力，也不要继续把大好的时间浪费在不值得做的事情上。
#+END_QUOTE

#+BEGIN_QUOTE
  会议有毒。
#+END_QUOTE

#+BEGIN_QUOTE
  预估的都是垃圾。
#+END_QUOTE

#+BEGIN_QUOTE
  人在变，环境也在变，你不可能满足所有人的要求。公司要对某一类型的客户全情投入，而不是对某一个善变的用户唯唯诺诺。
#+END_QUOTE

#+BEGIN_QUOTE
  家用便利就是好。广告做的好不如产品做的好。产品和宣传做的好，也无法弥补一次糟糕的客户体验所带来的损失。
#+END_QUOTE

#+BEGIN_QUOTE
  培养自己的拥趸。在过去的 10 年里，我们通过 Signal vs. Noise
  博客，培养了超过 10
  万名的每日浏览用户，这就是一个庞大的观众群体。他们每天都回来看看我们在说什么。我们的话题面向设计、业务、软件、哲学、易用性，或针对整个行业的宽泛讨论。不管我们聊什么，这些人都兴致勃勃的回来倾听。如果他们喜欢我们的观点，也很可能会喜欢我们的产品。
#+END_QUOTE

#+BEGIN_QUOTE
  你大可直言不诲，畅谈那些别人不愿意讨论的东西。直面你的弱点，向别人展示你最近的工作状况，即使你还没完全搞定它。不完美没关系，也许你看起来不专业，但你却很真实。
#+END_QUOTE

#+BEGIN_QUOTE
  放弃牛人。牛与不牛没有任何意义，不需要就是不需要。
#+END_QUOTE

不要本末倒置，在农场拖拉机比法拉利更有用，更不要为了开法拉利，在农场造一条公路。

#+BEGIN_QUOTE
  多年无关经验。一个具有 6 个月经验的应聘者和一个具有 6
  年工作经验的应聘者相比，其差别小得让人吃惊。真的差别来自于个人的努力程度、性格差异以及智力水平。
#+END_QUOTE

看似不靠谱，真实情况确实是这样的，刚毕业的学生和公司几年的老员工的差别在于业务逻辑的熟悉程度，技术上差距小也是很常见的事情。

#+BEGIN_QUOTE
  现实世界中的人才库要远远大于高分、上大学的那一波人。不要忽略了这些人，虽然他们的
  GPA 分数不高、毕业于社区大学，甚至只读过高中。
#+END_QUOTE

#+BEGIN_QUOTE
  速度改变一切。
#+END_QUOTE

当收到客户的问题的时候，应该第一时间给予答复，一旦你快速答复了，即便问题没有立刻得到解决，用户也不会因此放弃你的产品。而且，如果用户的问题最终得到了解决，用户将会更忠诚你的产品。

#+BEGIN_QUOTE
  在生意场上有些词汇永远不要使用。它们不是那些不文明用语，而是"得"、"必须"、"不能"、"简单"、"只要"、"只有"以及"赶快"。这些词会损害交流。
#+END_QUOTE

不只是在生意场上，在一个团队中也是如此。对于”简单"这个词，我印象深刻，非常反感这个词。当别人说这个功能很"简单"的时候，意味着这个功能很容易实现，如果可以快速解决当然好。可是，通常不是如别人所说的那么快捷，通常会花费很长时间才能做完。花了很长时间搞定别人认为"简单“的事情，让当事人如何想？

#+BEGIN_QUOTE
  灵感是个奇妙的东西，是效率放大器，是推进器。但是它不会停下来等你。灵感转瞬即逝，当它来找你时，要立即把它捕捉，将其投入工作中。
#+END_QUOTE

/later or
never/，回头去做，明天再去做，可能就是永远不会做。当你的有一个好的想法的时候，写下来，去做。

#+BEGIN_QUOTE
  是时候从头来过了，让我们整装出发了！
#+END_QUOTE

看完这篇文章的你，不要说明天或者明年要如何如何，从现在开始，别等了！

扩展阅读：[[http://coolshell.cn/articles/9156.html][《Rework摘录与感想》]]。
