#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 新的开始
#+DATE: 2014-05-06 00:00:00

ki 的时候，突然意识到拥有的网站，做过的东西有些乱，没有精力(兴趣)再去折腾一个新的网站，也意识到应该有所取舍，
作出一些改变。这其中也有一个很大原因是做过的网站之间没有关联，尤其是域名。

仅技术上从 cnblogs/chinazhangjie 到 keepsimply，再到 perfect-is-shit.com ，以及去年新建的 errpad.com
，真是有些累。正如我前面说的，享受个人想法的实现，而没有考虑更多。想到了就会立即去做。

在软件开发过程中改变一个产品形态，一般有两种方式，一种是增，一种是减。事实上，我们知道减比增要难的多。
我的想法是做一次整合，不再做向前兼容，重新开始。从 keepsimply 到 perfect-is-shit.com ，再加上从 Wordpress 到 Jekyll，
折腾过的人都会有很深的体会，基本上之前做过的所有积累就废了(url失效)。

折腾是一个很揪心的过程，有种痛并快乐的感觉。成长也是如此，每一次改变都是一个揪心的过程，因为改变意味着你要扔掉以前一些觉得美好的东西，
而去接受以前觉得很肮脏无味的东西。想起致青春里的一句话："我们终将会变成我们自己曾经讨厌的那种人"。

星星沙最新的一篇博客：人，最先老去的，从来都不是容颜，写的内容和我前面说的内容大体相同，难得的是竟然在同一时刻有了相同的想法。
我在想统一网站的时候(上周)，思考过第一篇文章应该表达怎样的主旨，后来的想法就是我前面写到的东西。内容想法相似，
但是我想表达的主旨不是无奈，不是感慨世事和人的成长。

我想表达的是，人在不同的阶段所追求的东西不一样，对于之前做的事情，无谓对错，对将来要做的事情也无谓无奈。
所谓世事、所谓现实只是不断的矫正你的方向，让你更接近你追求的东西的本质。我们总是会对未来有很多幻想，很多期待，
可是当你真正拥有的时候，往往会发现想要的是另外一样东西，也许是截然不同的东西。你能责怪现实吗？其实你根本都不知道你到底想要的是什么？
这一点董正荣应该感触很深。

以前的技术博客不再更新维护，errpad.com 也不会再使用，替代的是 blog.zhangjiee.com 和 wiki.zhangjiee.com，全都挂在 zhangjiee.com
这个域名下面方便以后扩展，而且 blog.zhangjiee.com 不会写与技术文章，技术相关的全部会放到 wiki。唯一不变的是写作的热情。

新的开始，对我来说，换网站的只是一个标志。真正要做的是一个3～5年的技术沉淀、生活积累，注重本质，忽略过程。

这个决定不一定是绝对正确的，但是我知道之前关注的方向，做的事情不再是我想要的。

同时，这篇文章也写给和我一同毕业的朋友们，毕业两年对于很多人都是一个瓶颈(技术和生活都是如此，我和一些人聊过，情况都差不多)，
不要抱怨，作出决定去尝试改变就是进步。

--------------

*2020-01-01 16:22:57 更新*

文章最开始的内容，经过博客的几次折腾，没了... 现在不知道写了个啥，就这样吧。
