#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 技术人的积累和整合
#+DATE: 2014-09-01 00:00:00

一个月没更新博客了，突然开始写有点不知道怎么开始。写本文的想法有一周之余了吧，精神状态不好(失眠)，也就一直拖到现在。

写这样一篇文章主要是因为在个人发展上遇到了问题，文章的一些想法可能不成熟，有待验证，不过我还是选择写了出来，毕竟想法这种东西稍纵即逝。

记得和峰子聊天的时候，我开玩笑的说过：

#+BEGIN_QUOTE
  从以后看现在的话，现在所有的想法都是错的，所以，所谓的正确都是相对的，而错误都是绝对的”。
#+END_QUOTE

当然这是一句玩笑话，有点装B的成分在里面，而且也过于绝对，毕竟不是所有的东西都是非错即对的。然而，这句话给我这几年的很多想法做了一个总结，现在看来以前的很多想法确实是幼稚的，不成熟的，这些成熟体现在我的各种折腾上，最简单的例子就是在博客的纠结上了.

反之，也这是因为这些幼稚的、不成熟的想法让我成长。我们策划诠释过他理解的完美:

#+BEGIN_QUOTE
  完美不是在每一个细节都做到了极致，而是在每一件事情上在可控的范围内做到最好，

  假如有个二维坐标，在y轴最高点与x平行的线理解为极致(完美)，把你以前做的每一件事情上都评估为一个坐标点，如果你把每一件事情都在可控的范围做到最好，把所有的点连接起来应该是一条优美的弧线，无限趋近于极致，但它永远到不了。
#+END_QUOTE

我觉得很有道理，人的一生应该是一条线，最终成什么样子，完全取决于你做每一件事情的态度。这其实就是"积累"，是每一个人的积累。谈人生积累，恐怕我还不够格，所以本文仅仅谈的是技术和做技术的人。

*技术人*

字面理解，做技术的人，但是我的理解远不止此。第一、对技术的热爱与激情(能做事)，这是基本保证(事实上很多人远达不到)；第二、职业素养(会做事)，职业素养包含的东西很多，但是我觉得最重要的是责任心，态度，只有你想做好，你才有可能真的做好。这两点是我所理解的技术人的基本要求，也是核心点。

*积累*

积累在以前的博客里面说的比较多了。什么叫积累？就是你有个目标(想法)，然后付诸努力的过程就是我认为的广义意义上的积累。

技术上的积累(侠义)就很多了写代码，调试，重构，软件测试，自动化这些都是与工作息息相关的东西，只要你用心去做，干上个一年半载基本思想有了，后面基本上就是良性循环了。能真正意义上把工作做好，我觉得也挺不错的。这些积累虽然是有限的(仅仅对工作上用的技术和工具熟悉)，但是是非常有效的。

另外一种技术上的积累就是工作之余的积累，《黑客与画家》中有这么一个观点，看一个程序员是否优秀不是看他在工作上做过什么，而是在工作之余做过那些事情。你是否有一个个人主页/blog，是否做过一些好玩的/实用的工具，是否有个Github帐号来开源/管理你的代码，是否给开源项目提交过bug？......

这些额外积累的无限的，兴趣所致，不知疲倦。一个优秀的程序员，不应该是仅仅的做完工作上的事情，而是用自己的能力创造出实际有效的价值，造福大众。我们今天用的
Linux，Git，开源的框架无一不是利己又利人的体现。

*整合*

整合:
把零散的东西彼此衔接，从而实现信息系统的资源共享和协同工作。------[[http://baike.baidu.com/subview/57967/8058650.htm?fr=aladdin][百度百科]])。

前几天在想自己的职业生涯规划，查了一些资料，但是卡住了。究其原因是对自己没有一个正确的认知，不知道自己做过哪些东西，擅长哪些东西。以前从来都是想学什么学什么，想做什么做什么。比如，很快我就忘了自己曾经还做这个
[[http://cpp1x.org/][cpp1x.org]]，去年在北京和 TankyWoo
一起搞的，因为离开了北京而且也不怎么用 C++11 ，所以就淡忘了。

整合的价值在于：

- *把自己做过的所有东西整理到一起，一目了然。*
  在做规划时，明确的知道自己擅长的东西和不擅长的东西；在找工作的时候，明确的告诉别人自己做过的事情。
- *不重复造轮子。*
  大学有个老师曾经跟我说过："你遇到的所有的问题，99%在网上都可以直接找到答案了"。不得不承认，工作中遇到的绝大部分问题都是通过搜索引擎解决。有些问题别人已经做了很详尽的解释了，你是否需要再重新整理一份出来了？如果是在大学时我的答案是肯定的，自己折腾过一遍印象要深刻的多。现在，则不会了。两个原因：第一，没有那么多精力；第二，技术基础比以前好了，大部分问题都是一点就透的，能解决当前的问题就好。如果有现成的文档，我会直接引用，如果有错误，我宁愿去帮他完善，而不是重新整理一份。把相关的资料放到一起，没事的时候看一看，这种提高是很恐怖的。
- *做目的性更强的积累。*
  就好像上面讲到的做的任何事情都可理解成一种积累，人的精力是有限的，且做技术总需要有些侧重。在整合技术时，势必要搭建一个框架，也就是在做计划，而基于这个框架上做事情，无疑就是一种针对性的积累。

比较抽象，可能还是不理解我想表达的是什么。恰好我在最近做整合：

- 主页: [[http://www.zhangjiee.com/][www.zhangjiee.com]]
- 服务器开发技术 wiki: [[http://sd.zhangjiee.com/][sd.zhangjiee.com/]] :
  列出了一些现在开发用的到的技术，然后把相关的资料都放到分类放好。这也就是
  *做目的性更强的积累*。
- 音乐博客: [[http://blog.zhangjiee.com][blog.zhangjiee.com]] :
  前身是乐魂。
- 技术博客:
  [[http://www.perfect-is-shit.com/][www.perfect-is-shit.com/]]
- ...

虽然还在完善中，但是我感觉比以前清晰的许多，通过主页把所有的东西联系到了一起，一眼就可以看清楚我拥有的东西，当不知道该干什么的时候，总会在这个圈子里面找点事情做的。

相信在未来几年量的积累，终会达到质的飞跃。
