#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 对技术和博客的思考
#+DATE: 2014-05-06 00:00:00

来上海这段时间不管是生活还是工作上都比较浮躁，也一直在思考将来的发展，有的时候会比较烦。我有个毛病：心静不下在的时候什么都不想干。在北京的时候晚上回到房子里还会看一个小时左右的书，到了上海以后基本上没有看过。

关注过我之前博客的朋友应该大体了解我是一个什么样的人，比较依赖旧的生活环境，同时对新的环境排斥心里比较强。

记得大学时候，常开玩笑说自己比较专一，现在想想当时的一句玩笑话，在我身上真的应验了。善于折腾，但是不善于做改变，很多东西放不开，很多东西尝试也不愿意去接受。技术如此，生活习惯、交际圈也是如此。

最近一件挺有意思的事情，感触很深。我回复了 V2ex
上的一个帖子应届毕业生的编程能力，怎样才算合格呢？得到一个哥们（或者是妹子）的回复:

#+BEGIN_QUOTE
  @JerryZhang
  我已经不记得是第几次看到你对在校计算机专业的大学生此类建议了，其实你说的很对，基础的东西往往不被在校大学生看重，比如数据结构、操作系统等，他们想要学的是根据现在一些招聘网站看到的一些要求而对应学习的，比如Java
  web
  或者Android。同时也很容易理解此行为，对于大部分学生来说，做出一个"酷"的app比啃数据结构有成就感多了？
#+END_QUOTE

看到这句话以后有些吃惊，没想到有人还关注过我...
剩下的就是思考了，其实我很长一段时间都没有在社区、论坛等地方回答过任何技术非技术的问题了。现在基本上不逛社区，微博和
Twitter 上的多一些。主要是对国内的社区形式的东西彻底失望了，CSDN,
ChinaUnix, 博客园，再到后来的
cppleyuan，混了有四年左右，对国内的技术氛围和社区的运营非常失望。这一点相信
Tanky
也深有体会。现在的知乎相信也会走他们的老路，这个观点我在去年下半年的时候就说过了。

就做技术的人来说的话，做了 5~10
年技术的人，一部分转行，一部分做了管理，剩下的安心做技术。前两类人我相信都是不混论坛的，安心做了那么多的年技术的牛人，更不会混国内的论坛。最纠结是在于
3~5
年左右的技术人，大部分到了结婚的年龄，赚钱买房娶媳妇。生活压力大，不混论坛其实还好，混论坛的话发表的消极言论较多。最后剩下的一批人大学生和刚毕业不到两年的人，技术底子差，但是富有激情，论坛社区大部分都是这样的人。就拿上面的这个帖子来说的话，回帖的人中我相信有一部分是还没毕业的大学生，或者刚毕业没多久的人，你真的觉得有资格来回答这个问题么？太不负责任了吧。

还有个非常让人吃惊的事情是，一些还没有毕业的学生经常以程序员自居，抱怨苦啊，累啊。看这个帖子就明白了：大三程序员的一点困惑，求前辈们解答（非技术）。「最近不知道怎么的，觉得越来越不适应这个圈子了。」说真的，你进入这个圈子了吗？

去年我的技术博客去掉了评论系统，一方面是因为没有合适的评论系统，另外一方面评论系统真的不能得到应有的交流的效果，最多就是搞技术的朋友之间相互吹捧一下。以博客园今天首页的最多评论文章「财神爱欢乐------手表的故事」，有效的评论没几条。类似「沙发」、「顶」、「感谢」对一篇技术文章来讲一点用都没有，有的只是让博主自信心爆膨。

吐槽多了，回到刚才的那个帖子。两年前我战战兢兢的写了一篇如何学习 C++
的文章，还找 Tanky
和杨溪审校，他们虽不是大牛，但我相信他们一定是很负责任的看完每一个字，在他们那一关是没有问题的。当时我写了我个人近几年技术上理解的精华：基础的重要性，因为我是踩着坑过来的。后来在人人网和一些论坛上有被人转载过，现在想想其实这是一篇废文。经历过的人已经明白了如何去做，而没经历过的人不会在意这些东西的。包括我在上面那篇帖子的回复一样，我相信不会对发帖者和看到回复的人起到任何作用。

以前经常建议很多人去写博客，现在来看，不好说。
