#+SETUPFILE: ~/site/tpl/wiki-tpl.org
#+TITLE: 一日三省
#+DATE: 2019-07-24 09:55

* 2020-04-06 14:44:48 一

这些年做的最差的事情恐怕就是没有好好的经营自己。

总是狗熊掰棒子，摆一个扔一个。

* 2020-03-26 21:55 四

要深深的明白这样一个道理：

在你没有取得任何成就之前，是没有人会尊重你的想法的，无论是别人，还是自己的亲人。
所以，受到挫折的时候，无非是爬起来坚持走，没必要祈求别人的理解。
大家在意的只是结果。

最近也总结出了另外一个道理：

在工作中，做事不能做的过于完美，要适当的留有瑕疵，偷偷懒。
每件事情都默默的做的妥妥帖帖，以至于别人都不知道你的存在，直到离开了才知道你的重要性。
这种结果怪不得别人，只能怪自己蠢。而我已经这么蠢了六七年了。

* 2020-03-10 14:06 Tue

刚毕业的时候，挺讨厌那些给自己贴标签的人，像什么编程语言了：Java、C++；工具了：Vim 党；还有系统：Linux，喜欢折腾就写个 geek。

以前总感觉程序员应该不应该受语言、系统、工具的限制，随用随学。

坚持了这么多年，自己好像快失业了... 而那些贴标签的一条路走到底，都成专家了...

语言、平台只是工具可能是这个行业最大的谎言了，就像皇帝的新衣，大家都知道靠一种语言和一个平台一直吃饭的人是越吃越香，但是嘴上还会告诉别人语言只是工具。

* 2020-02-21 09:33 Fri

从业七八年，见的人越多，了解的越多，就会对这个行业越来越失望，想要离开。

令人沮丧的是，待过的团队，协作过的同仁，能达到「尽职尽责」的不在多数，而能达到「优秀」的更是寥寥无几。
每次都让我质疑自己，是否对待工作太过「认真」，为什么不能成为沉默的大多数；久而久之就会对这个行业不再报什么希望。

以前想着可以做一个 PM 或者 PO，等有这个能力之后，发现能安安稳稳的做好技术，一直写代码一直到退休也是极好的一件事情。

所以开始反思：我也本可以，拿着不错的工资，安稳的度日。

即日起，给工作以及工作相关的技术学习减少投入精力，而把一些精力投入到自己「喜欢」干的事情上；或者开始投资自己的第二职业也不错。

* 2020-02-11 23:42 Tue

无论何时、无论处于何种目标，人生中总要有一些事情并不是因为必须要做而做，而是因为喜欢；否则，人生的意义又在哪里？

* 2020-02-11 23:36 Tue

大部分技术人安身立命的资源永远是扎实的技术；不管是试图转型到产品或者项目管理，在短长期内技术都是至关重要的。

无论是小的转型还是大的转型，都需要一定的机遇和能力储备，而且还是失败的可能性；脱离现有的东西越远，风险就越高。

所以任何时候都要使自己的技术能力保持一个不错的水平。

* 2019-11-07 16:13
不能因为第一印象或者简短的了解就否定一个人。
* 2019-11-01 10:06

我很反感很多人给我提「意见」，经常会引发一些情绪化的争执，并不是因为我不是一个「和善」的人，不能够接收「别人想法」的人，只是我有的时候会默认以为他是一个专业的人，他本不该与我讨论看起来如此低级的问题。
我希望得到的是他们在专业领域的「建议」，而不是一些浮于表面的我已经了解的问题。但是往往我所期待的人，并没有提出我所期待的建议，所以情绪化的争执就开始了~

如果是以前，我可能会说出我的期望来解决类似争执的根源；但是现在，我明白让别人成长并不是我的责任，而且不是每个人都会理解我的「善意」。
所以，我只能改变自己，尝试把别人当成一个小白，循循善诱，「友善」的接受别人的「意见」。

* 2019-07-24 09:55
  木秀于林，风必摧之。任何事情都要给别人留有余地。
* 2019-07-15 17:23

一旦更深一步的了软件工程之后，使我陷入了一个误区：一切都是权衡利弊。

权衡本身是没有错的，做工程本质上就是在做选择题，其实人生也是这样。

误区是什么呢？从结果上看，是需要权衡的，人生中的大部分事情都是通过结果来评判的，但总有一些事情是看意义的，并不是看结果的。

也就是说，理性更容易出结果，结果往往意味着可以提高人的物质水平。对于人生来讲，生活的质量，物质水平是非常重要的一部分，但并不是人生的全部，你还有家人、爱人、朋友，你还有自己的热爱与梦想。

如果说理性更容易出结果的话，感性则是让自己更舒适。理性做事往往会伴随着些许的残酷，而感性则不用违背自己的内心，做一些让自己觉得舒适的决定。

这是这么长的时间，为什么自己一直在与自己对抗的原因。我知道怎么样做事更能成事，只不过我没有办法面对自己的内心（这太不摇滚了），我太想做成事了。

最近一直在看乐队的夏天，悟到了一些东西。

我需要做一些权衡，权衡理性与感性。不能所有的事情都按照做成功那一套东西来，对于生活，要少一些理性，多一些感性。相比 2015 年之前，这几年的状态是因为没有了之前的坚守，没有之前的热爱，功利性太强了。

所以今后，工作是工作，结果导向没什么问题；但是私下的学习和生活，不必要结果导向，热爱一件事情，做一件事情，本身就具有意义。

*2019-07-16 21:20:47 更新*

究其原因是少了死磕的精神，太追求短期的成效，一会干这个，一会干别的。

* 2019-05-25 16:37

不管别人是怎么做的，怎么想的，我始终不能放弃自己，要坚持自己。

* 2019-03-18 11:27

永远不要想着主动的改变一个人，或者影响一个人，这是不可能的。

与其花这个精力投资别人，不如投资自己。

* 2019-03-17 12:30

古之成大事者必须要有的：

- 健康的身体（如司马懿），只有健康的活着才能有时间实现自己的梦想
- 忍耐（如司马懿）
- 胸怀（如孙坚、刘备）
- 资源（当然包括钱），没有充足资源的人是不配追求梦想的，所以有的时候需要委屈一下自己，积累资源
- 能力，这是自然

* 2019-03-07 15:52

每次想要抱怨的时候，就多一分的努力。

* 2019-03-01 19:52

所有对现实的不满，都是因为自己不够努力，水平太低。

* 2019-02-13 10:59

我算是想明白了，这些年中自己身上明显的一个缺陷，但是又一直逃避的一个事实：不着眼于眼下的局势，而盲目追求远方；这会导致喜欢埋怨眼下，期待远方，而实际上眼下没有那么的糟糕（糟糕又能怎么样呢），远方没有那么的美好。

这也是为什么自己付出的并不比别人少，然而结果总是差强人意的原因之一。

在工作上，以后还是 80% 的时间夯实眼下所需的技能，20% 或者更少的时间丰富技术栈。

在其位，谋其政；任其职，尽其责。
