#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 读书笔记
#+OPTIONS:  ^:nil

* Entry

|   ID |         读完时间 | 书名                                   | 作者                           | 评价 |
|------+------------------+----------------------------------------+--------------------------------+------|
|      | <2022-02-19 Sat> | 秦汉史（上、下）                       | 林剑鸣                         | 优秀 |
|    3 | <2022-02-19 Sat> | 人类简史：从动物到上帝                 | ［以色列］尤瓦尔点·赫拉利      | 神作 |
|    5 | <2023-07-09 Sun> | 万历十五年                             | 黄仁宇                         | 神作 |
|    6 | <2023-07-22 Sat> | 魏晋南北朝史                           | 王仲荤                         | 优秀 |
|    7 | <2022-11-14 Mon> | 大秦帝国（6 部 11 本）                 | 孙皓辉                         | 优秀 |
|    9 | <2023-06-14 Wed> | 汉家儿郎冠军侯：霍去病                 | 觉明堂主                       | 一般 |
|   16 | <2022-02-19 Sat> | 庆余年                                 | 猫腻                           | 尚可 |
|   17 | <2023-07-18 Tue> | OKR：源于英特尔和谷歌的目标管理利器    | 保罗                           | 一般 |
|   18 | <2022-02-19 Sat> | 将夜                                   | 猫腻                           | 尚可 |
|   19 | <2023-06-04 Sun> | 这就是OKR                              | 【美】约翰·杜尔（John  Doerr） | 优秀 |
|   23 | <2022-02-19 Sat> | 绝对坦率：一种新的管理哲学             | [美]金•斯科特                  | 一般 |
|   24 | <2023-08-12 Sat> | 有效管理的5大兵法                      | 孙陶然                         | 神作 |
|   26 | <2023-08-11 Fri> | 万古江河                               | 许倬云                         | 神作 |
|   27 | <2023-08-15 Tue> | 说中国                                 | 许倬云                         | 优秀 |
|   28 | <2023-06-29 Thu> | 显微镜下的大明                         | 马伯庸                         | 尚可 |
|   30 | <2023-07-13 Thu> | 风起陇西                               | 马伯庸                         | 尚可 |
|   31 | <2022-08-13 Sat> | 舍不得看完的中国史：秦并天下           | 渤海小吏                       | 神作 |
|   32 | <2022-05-11 Wed> | 楚汉双雄                               | 渤海小吏                       | 神作 |
|   35 | <2023-06-21 Wed> | 秦崩：从秦始皇到刘邦                   | 李开元                         | 尚可 |
|   38 | <2023-06-29 Thu> | 楚亡：从项羽到韩信                     | 李开元                         | 优秀 |
|   40 | <2022-05-11 Wed> | 汉瓦：西汉王朝洪业启示录               | 刘三解                         | 优秀 |
|   42 | <2023-05-13 Sat> | 两京十五日                             | 马伯庸                         | 尚可 |
|   45 | <2023-07-31 Mon> | 金瓯缺                                 | 徐兴业                         | 优秀 |
|   53 | <2023-06-18 Sun> | 亚马逊逆向工作法                       |                                | 一般 |
|   55 | <2023-08-09 Wed> | 武则天                                 | 蒙曼                           | 尚可 |
|   62 | <2023-05-31 Wed> | 大汉帝国                               | 萧然                           | 尚可 |
| 1154 |       2023-06-19 | 三国史话                               | 吕思勉                         | 优秀 |
| 1262 |       2022-05-17 | 长安十二时辰                           | 马伯庸                         | 尚可 |
| 1278 |       2023-05-09 | 细说宋朝                               | 虞云国                         | 优秀 |
| 1390 |       2023-07-27 | 流血的仕途：李斯与秦帝国               | 曹昇                           | 尚可 |
| 1411 |       2023-05-21 | 乡土中国                               | 费孝通                         | 优秀 |
| 1421 |       2023-07-06 | 嗜血的皇冠                             | 曹昇                           | 尚可 |
| 1516 |       2023-07-21 | 品三国                                 | 易中天                         | 优秀 |
| 1587 |       2023-05-28 | 易中天中华史：魏晋风度                 | 易中天                         | 尚可 |
| 1594 |       2022-07-17 | 易中天中华史：南朝，北朝               | 易中天                         | 尚可 |
| 1597 |       2022-07-28 | 大隋兴衰四十年                         | 蒙曼                           | 尚可 |
| 1663 |       2023-06-24 | 大唐兴亡三百年（全7册）                | 王觉仁                         | 一般 |
| 1705 |       2022-08-04 | 曾仕强说情绪管理                       | 曾仕强                         | 优秀 |
| 1716 |       2022-08-16 | 人际的奥秘                             | 曾仕强                         | 尚可 |
| 1783 |       2023-08-02 | 中国式管理                             | 曾仕强                         | 尚可 |
| 1813 |       2023-08-03 | 小米创业思考                           | 雷军                           | 一般 |
| 1863 |       2023-08-16 | 红顶商人胡雪岩                         | 高阳                           | 尚可 |
| 1876 |       2023-07-19 | 中国文化的精神                         | 许倬云                         | 优秀 |
| 1908 |       2023-06-07 | 中国是部金融史：透过金融读懂中国三千年 | 陈雨露                         | 优秀 |
| 1941 |       2023-07-03 | 曾仕强经典语录                         | 曾仕强                         | 优秀 |
| 2000 |       2023-08-06 | 中国人的智慧                           | 易中天                         | 尚可 |
| 2157 |       2023-07-15 | 唐玄宗                                 | 蒙曼                           | 尚可 |
| 2172 |       2023-06-04 | 太平公主和她的时代                     | 蒙曼                           | 尚可 |
| 2433 |       2023-06-12 | 胡雪岩的启示                           | 曾仕强                         | 优秀 |
| 2552 |       2023-08-08 | 三国的奥秘                             | 曾仕强                         | 尚可 |
| 2783 |       2023-08-13 | 长安的荔枝                             | 马伯庸                         | 优秀 |
| 2802 |       2023-08-12 | 五代十国全史. Ⅰ, 黄巢起义              | 麦老师                         | 尚可 |
| 2866 |       2023-06-23 | 五代十国全史. Ⅱ, 万马逐鹿              | 麦老师                         | 一般 |
| 2990 |       2023-08-17 | 五代十国全史. Ⅲ, 朱温称霸              | 麦老师                         | 一般 |
| 3025 |       2023-01-01 | 五代十国全史.Ⅳ,大唐末路                | 麦老师                         | 尚可 |
| 3131 |       2023-06-14 | 五代十国全史. Ⅴ, 后梁帝国              | 麦老师                         | 尚可 |
| 3514 |       2023-08-13 | 文治帝国                               | 艾公子                         | 尚可 |
| 4599 |       2023-06-23 | 三国争霸（上、中、下）                 | 渤海小吏                       | 尚可 |
| 4975 |       2023-06-11 | 大宋国士·北宋卷                        | 陈启文                         | 尚可 |
| 5277 |       2023-07-12 | 大宋国士·南宋篇                        | 陈启文                         | 很差 |
|      |       2023-08-26 | 明朝那些事儿                           | 当年明月                       | 神作 |
|      | <2023-09-09 Thu> | [[https://book.douban.com/subject/1463256/][大明王朝的七张面孔]]                     | 张宏杰                         | 尚可 |

* 人类简史

2020.04.06 读过一遍，当时读起来没什么感觉，但每次总能想起里面的一些片断。于是决定重新认真的拜读一遍。

人类语言真正最独特的功能，并不在于能够传达关于人或者狮子的信息，二是能够传达关于一些根本不存在的事物的信息。

大规模的人类合作是以虚构的故事作为基础。只要改变所讲的故事，就能改变人类合作的方式。

«人类以为自己驯化了植物，到其实是植物驯化了人» 这是非常让我记忆犹新的一段故事。

其实人类在历史上一直不断的重蹈覆辙，道理都相同：因为我们无法真正了解各种决定最后的结果。

人类一心追求更轻松的生活，于是释放出一股巨大的力量，改变了世界的面貌，但结果并没有任何人料想的到，甚至也不是任何人所乐见的。
并没有人在背后操纵农业革命发生，或者意图让人依赖谷物为生。一开始只是各种小事，主要就是希望吃饱一点、生活安全一点，
但最后累积引起的效应，就是让远古的采集者开始花上整天的时间，在烈日下挑水务农。

每当人类的整体能力大幅度增加，似乎大获成功的时候，个人的苦痛也总是随之增长。

在现代晚期之前，总人口有九成以上都是农民，日出而作、胼手胝足。他们生产出来的多余粮食养活了一小撮精英分子：
国王、官员、战士、牧师、艺术家和思想家，但历史写的几乎全部都是这些人。
于是，历史只告诉了我们极少数的人在做些什么，而其他绝大多数人的生活就是不停的挑水耕田。

如果人们希望某个由想像构建出的秩序能维持久远，大部分的人（特别是精英分子）就必须真正相信它。

身为人类，我们不可能脱离想象所建构出的秩序。每一次我们以为自己打破了监狱的高墙、迈向自由的前方，
其实只是到了另一间更大的监狱，把活动范围稍稍扩大了而已。

阿拉伯数字，其实是印度人发明的。阿拉伯攻打印度的时候，发现这套实用的系统，加以改良再传到中东。

每一种由想象构建出来的秩序，都绝不会承认自己出于想象和虚构，而会大谈自己是自然、必然的结果。

全球人民逐渐同意“自由”和“平等”都是基本的价值观。然而这两者根本就互相抵触！想要确保“平等”就得限制住那些较突出的人；
而要人人都能“自由”，也就必然影响所有人的平等。

如果人真的无法同时拥有互相抵触的信念和价值观，很可能所有的文化都无从建立，也无以为继。

合久必分只是一时，分久必合才是不变的大趋势。

金钱并不是物质上的现实，而只是心理上的想象。

历史的铁则就是：事后看来无可避免的事，在当时看来总是毫不明显。

究竟为什么要学历史？历史不像是物理机学或者经济学，目的不在于做出准确预测。我们之所以要研究历史，不是为了要知道未来，而是要拓展视野。
要了解现在的种种绝非“自然”，也并非无可避免。未来的可能性远超过我们的想象。
举例来说，研究欧洲人究竟是如何控制了非洲人，我们就知道种族歧视绝非自然或无可避免，而且知道世界大有可能是完全不同的样貌。

如果要在过去 500 年间挑出一个最重大、最具代表性的一刻，一定就是 1945 年 7 月 16 日早上 5 点 29 分 45 秒。
就在这一秒，美国科学家在新墨西哥州的阿拉莫戈多引爆了第一颗原子弹。从这时开始，人类不仅有了改变历史进程的能力，更有了结束历史进程的能力。

科学革命并不是“知识的革命”，而是无知的革命。真正让科学革命起步的伟大发现，就是发现“人类对于最重要的问题其实毫无所知”。

现代科学是一套独特的知识体系，独特之处也就在于公开承认这“整套体系”都对一些“最重要的问题”一无所知。

郑和下西洋比哥伦布发现新大陆要早快一百年，但是对国家的影响远远比不上哥伦布，当时的科技，人数规模远超哥伦布。为什么呢？书中说：
是欧洲人的无与伦比又贪得无厌、不断希望探索和征服的野心。
但其实我觉得是政治文化的原因，中国人一直遵从儒家孔孟，不争不抢。直到现在，中国人相比欧洲美洲人少的其实是探索精神。

帝国资本主义的奇妙循环：信贷资助新发现，新发现带来殖民地，殖民地带来利润，利润建立起信任，信任转化为更多的信贷。

人类的历史从来不是洁白无瑕

工业革命的核心，其实就是能源转换的革命。

有钱人的最高指导原则是-“投资”，而我们这些其他人的最高指导原则则是-“购买”。

我们比较容易体会个人的辛酸，而不是人类整体的苦难。

生活有意义，就算在困境中也能甘之如饴；生活无意义，就算在顺境中也能度日如年。

从我们所知的纯粹科学来看，人类的生命本来完全就没有意义。人类只是在没有特定目标的演化过程中，盲目产生的结果。

我们对与生活所赋予的任何意义，其实都支持错觉。

佛教认为，快乐既不是主观感受到愉悦，也不是主观觉的生命有意义，反而是在于放下追求主观感受这件事。
苦真正的来源不在于感受本身，而是对感受的不断追求。

历史一再让我们看到，许多以为必然会发生的事，常常因为不可预见的阻碍而无法成真，而某些难以想象的情节，最后却成为事实。

第二遍 DONE

* OKR：源于英特尔和谷歌的目标管理利器

目标要被设定的富有挑战性，及时员工或者组织竭尽全力，也只有一半的成功机会。

OKR 是一套严密的思考框架和持续的纪律要求，旨在确保员工紧密协作，把精力聚焦在能促进组织成长的、可衡量的贡献上。

OKR 的定义：
- 目标：我们想要做什么
- 关键结果：我们如何知道自己是否达成了目标的要求

OKR 能给你带来哪些收益？
1. 易于理解，增强了接受度和使用意愿
2. 更快的开展节奏，提升了敏捷性和快速应对变化的能力
3. 把精力聚焦在最重要的事情上
4. 通过公开透明促进跨部门间的横向一致性
5. 能促进沟通并提升敬业度
6. 促进前瞻性思考

更好的沟通、敏捷、聚焦、公开透明、自下而上、前瞻性思考。

高管支持是实施 OKR 过程中至关重要的一环。
高质量 OKR ，创建目标时，应该具备的标准：

- 鼓舞人心
- 可达到的
- 以季度为周期
- 在团队可控范围内
- 有商业价值
- 定性的

目标是定性的，代表一个期望的方向；而 KR 则应当是定量的，因此可以用数字去衡量我们是否达成了目标。

content: 打分标准：
- 1.0 几乎不可能实现
- 0.7 虽然很难，但最终是可以达成的
- 0.3 通过正常的努力就可以完成

OKR 制定流程 CRAFT
1. Create 创建
2. Refine 精炼
3. Align 对齐
4. Finalize 定稿
5. Transmit 发布

OKR 应该是“松耦合”，而非“紧耦合”。 同你上级主管的 OKR 联接过程应该是一个沟通协商的过程。

用 OKR 进行日常管理：

关键动作：周例会、季度中期审视、季度评估。

制定 OKR 前应注意的关键事项：

1. 帮助大家理解为什么你们要实施 OKR
2. 得到高管的帮助
3. 提供 OKR 培训
4. 确保存在一个清晰的战略

制定 OKR 时应注意的关键事项：

1. Objective 应定性而非定量
2. 避免所有 OKR 都是自上而下制定的
3. 解决 KR 上出现的一系列问题
   - 条目过多
   - 质量差
   - KR 全是里程碑类型
4. 使用一致的评分系统

制定 OKR 后注意的事项：

1. 避免制定后就束之高阁现象
2. 联结 OKR 确保同上层组织对齐一致

如何确保你的 OKR 反映组织的战略，以便让大家专注于做正确的事情？

- 首先，建议你得花足够的时间在这上面
- 其次，倾听也非常重要。OKR 至少应部分地自下而上的方式去开展。
- 最后，让人们充分的辩论。

* 这就是 OKR

想法很容易，执行最重要

OKR 四大利器∶ 聚焦、协同、追踪、延展。

- 对优先事项的聚焦和承诺： 高绩效组织应该聚焦重要的工作，同时清楚什么是不重要的。
- 团队工作的协同和联系： OKR 具有透明性，自上而下，自下而上，每个人的目标都是公开的。
- 责任追踪： OKR 是由数据驱动的。定期检查、目标评分和持续的重新评估可以让 OKR 充满生机——所有这一切都是基于客观、负责的精神。
- 充分延展进而挑战不可能：OKR 激励我们不断超越之前设定的各种可能，甚至超出我们的想象力。

健康的 OKR 文化的本质是绝对诚实、摒弃个人利益和忠于团队，这也是格鲁夫思想的核心。

以下是我在英特尔公司工作的时候，从从……学到的：

- 少即是多。
   每个周期最多只需制定 3 到 5 个 OKR 。
- 自下而上设定目标。
   各占一半。
- 共同参与。
   在公司目标已经确定的情况下，关键结果仍然是可以商谈和调整的。
- 保持灵活。
   如果大环境发生变化。既定目标看起来不切实际或难以实现，可以在执行了期间修改甚至放弃某些关键结果。
- 敢于失败。
- OKR 是工具，而非武器。
- 耐心、坚定。
   一个组织可能需要 4 到 5 个季度才能完全适应这个系统，而构建成熟目标往往需要更长的时间。

当你不厌其烦地多次强调的时候，团队成员可能才真正开始听你的话。

管理的艺术在于能够从看似同样重要的选择中选择一个、两个或三个能充分发挥杠杆作用并让你专注于此的活动。

当一个关键结果或目标变得过时或者不切实际时，就要当机立断的结束它。

总结：清零与重复

总结包含三个部分：客观评估、主观自我评估和反思。

谷歌评分标准：
- 0.7-1.0 分 绿色 目标完成
- 0.4-0.6 分 黄色 有进展，但没有完成
- 0-0.3 分 红色 目标失败

谷歌将他们的 OKR 分为两类，一类称为承诺性目标，另一类称为远景型（或挑战性）目标，二者有着本质的不同。

持续性绩效管理是通过一种叫做 CFR 的管理工具来实现的:

- 对话（conversation）：经理和员工之间真实的、高质量的交流，旨在对绩效提升起到驱动作用。
- 反馈（Feedback）： 同事之间面对面进行双向沟通或通过网络进行交流，以评估工作进展情况并探讨未来的改进方向。
- 认可（Recognition）： 根据个体所做贡献的大小施以对等的表彰。

一旦人们经历过成功的变革，他们就再也无法拒绝变革带来的益处了，他们会继续推动变革不断进行下去。

* 有效管理的 5 大兵法

领导和你工作的关系只有三个：

1. 帮你把握方向和目标，这确实不是你能够决定的
2. 在你做不到的地方给你支持，作为你的增援部队
3. 帮你协调你协调不了的资源

其他的事都是你的事。


四环方法论：先问目的、再做推演、亲手打样、及时复盘。

先问目的：想不想 该不该 值不值

再做推演：画蓝图 横分解 纵分步 配资源 里程碑

打样要慢，要细致，考虑方方面面，一旦打样成功之后要快速复制。

我们可以为一块骨头打的头破血流，如果骨头上有肉而我们又非常饿的话，但是如果骨头上没有肉，或者我们已经吃的很饱了，还是和别人为了一块骨头打的头破血流，我们就有毛病了。

复盘四步法∶
1. 目标结果：做事先设定目标
2. 过程再现
3. 得失分析：好和不好
4. 规矩总结：认知和实践两个方面

执行四步法，是中层管理者管人的方法。

1. 设目标 SMART 原则
2. 控进度
3. 抓考评
4. 理规范

设目标：向上思考，先长期再短期；书面确认，可追踪；要进取，有挑战；符合 SMART 选择。

控进度，就是盯着下级一步步接近目标并随时准备帮助下级达成目标。
1. 管一层看两层
2. 亲撰周报
3. 该出手时就出手

赢家必备的四个心态：自信、自主、自强和自嘲。其中自主最重要，把命运把握在自己手里，按照自己设定的目标坚持努力，才有可能达到期望的终点。

为我们创造 80% 效益的是卓越的 20% 的人，我们应该把更多的关注、更多的关心、更多的资源都给予这 20% 的人，这才是管理之道。

管理三要素：建班子、定战略、带队伍。

领军人物必须具备三大素质两大能力：

- 三大素质：志存高远，心力强大，胸怀宽广。
- 两大能力：战略能力，学习能力。

实战中的战略就是四件事：目标、打法、资源和激励。

员工有责任心、中层干部有上进心、核心高管有事业心，这是基本的选人标准。

用文化带队伍，把企业文化：提出来、天天讲、以身作则、融入业务。

三有人才观：有态度、有能力、有素质。

* 万古江河

文字和王权的出现，是中国文化发展的里程碑，也是史前文化进去历史时代的分界线。

唐代藩镇割据，军人拥兵自重、分裂国家。宋代惩于唐代的前车之鉴，政府致力于重文轻武，大将不得据地佣兵，南宋的大将岳飞、韩世忠等，即使忠心耿耿，仍遭迫害。

广义的中原包括今日所谓北五省: 河南、陕西、山东、河北、山西。狭义的中原是黄河中游以洛阳为中心的地区。

在南北朝之前，中国最富庶的地区是中原。但是自从唐中叶以后连年战乱，北方逐渐凋敝，南方战乱较少，气候温和，发展农业较佳，于是在人口和财富两方面都超越了北方。

#+begin_quote
昨晚读完了，很不错的一本书，说不出哪里好，反正就是好……

搜了一下许倬云，发现经历类似黄仁宇，历史学家，准备接下来把他写的书都看看。

应该是从大秦帝国系列小说开始看历史的，后面就是秦汉史、魏晋南北朝史和正在看的隋唐五代史。

起初有趣，看着看着有点看不下去，很枯燥，硬着头皮看。

直到看《冠军侯》这种小说的时候，才发现还是更喜欢严肃的谈历史。

再到看《万古江河》的时候，从文化的角度看中国历史，仿佛把之前看的断代史都连接起来了。

再去看隋唐五代史，好像突然变得很有趣，以前看政治、经济、文化、民族关系这几部分也看到下去了。

总结出一个很简单的道理：一个体系的东西，需要切换不同的视角，会相互促进，由点到面。
#+end_quote

* 说中国

因能容纳，而成其大；因能调适，而成其久。

在一个大的人群体系之中，我打算以文化理念、政治权力、社会力量和经济制度为研究视角，以这四个方面作为考察的基本变量。
中国历史观念中的朝代，毋宁代表的是政治权威：可是，任何政治权威都无法独立运作，政权必须倚仗经济、社会和文化理念三个方向的维系，

1. 从九千年开始，大概经过一两千年，水稻耕作的技术已经扩散到更为广大的地区（东方的人类）。
2. 离现在一万年左右，黄牛第一次被驯养为家畜，牧养文化也出现了。牧养可以作为食物，食物来源从渔猎变成了人类自己可控性的食物生产。
3. 七八千年左右，太行山东边延伸到渤海冲积平原的山坡地，人类发展了栗（小米）种植。很快，在中纬度的北方，耕作小米成为了最为普遍的农业活动。

这三种生产方式构成了三种形态的文明。

人类族群的分野，往往并不是以血统为基本要素而是以生活方式当做认同的文化基因。

“中国”并不是没有边界，只是边界不在地理，而在文化。

及至韩、赵、魏三家分晋：赵国拥有山西东半边和河北的土地和人口；魏国的领土则稍微偏南和中央，具有晋国的核心部分；韩国的地域则是偏西的一块。

儒家的祖宗崇拜。行之于制度，就是慎终追远：这是对生命的关注发展来的信仰。道家的自然崇拜，则是对于各种自然力的崇敬。

世界乱序之时，人心不安，常常必须找到依靠。儒、道两家，是由知识分子经过学习、研究，建构起一定的价值观念系统，进而形成法律与制度。对于一般庶民，这些大道理不足以抚慰惊惧不安的心灵。
于是，外来的信仰颇有垫补不足的空间。最晚不会晚于东汉初年，佛教就进入了中国。

儒道两家的宽容和包含，中国对于外来的宗教并无抵制。

中国“分久必合”的观念，就靠经济的交换网，维持全国一盘棋的构想。

辽（金）和西夏，与宋代中国时战时和。这两个国家和宋国的关系，并不同于匈奴、突厥和中国的关系，他们并不志在侵入中国、取得土地，他们主要的要求是中国赠纳丝帛和银钱。

有宋一代，实在是中国历史的转折点：两汉的坚实基础，隋唐的宏大规模，转变为中国文化的稳定结构。从此以后，中国两度面对外族的完全征服，还可能重新站起来。
可是，在面对活力充沛的西方近代文明时，这一稳定的中国文化系统，不再能有接纳和适应的能力。

明代人固然恢复了中国人自己的统治，却丧失了天下国家的包容气度，也没有消除征服王朝留下的专制统治。

自从安史之乱之后，黄河以北数百年来都是战场，因为长期战乱，中国的核心转移到了南方。

核心地区南移之后，丧失了所有产马之地。在冷兵器主导的战争中，马匹是非常重要的力量。于是，宋代的中国成为列国之一，再也不能统治原来中国的全部疆域。
* 显微镜下的大明 @马伯庸

长久以来，历史在我们脑海中的印象，是烛照万里的规律总结，是高屋建瓴的宏大叙事。这虽然是正确的，但视角实在太高了，高到没有什么人情味。
即使有些讲述者有意放低视角，也只停留在庙堂之上、文武之间，关心的是一小部分精英，再往下，没了，或者记录很少。

在一个庞大的官僚机构里，政策的执行是有惯性的（比如说大明）。政策一旦形成惯例，即使周围情况发生变化，官员依旧会机械地继续执行，
不会主动求变，甚至畏惧变化。所谓“祖宗成法”，就是这么来的。

明代的科举分为三级：乡试、会试、殿试。
1. 乡试是行省一级的考试，三年一次大比，考试时间是在八月，因此又称“秋闱”。通过乡试的士子，成为举人。
2. 次年年初，全国举子赶赴京城，参加礼部举办的会试，称“春闱”。会试通过的考生，叫做贡士。
3. 接下来，皇帝会亲自主持一场殿试，没有淘汰，只为这些贡士排个名次，分三等。
4. 一甲有三人，赐进士及第，即我们所熟知的状元、榜眼、探花；二甲若干人，赐进士出身；三甲若干人，赐同进士出身。

何不食肉糜，贬义词，指不了解事物的全部。

官员的办事原则是：拿住首犯，略施薄惩，以吓阻压制为主，不求根治问题，只要别在我任内出事就好。仔细回想一下，历任知县——除了赵昌期之外——对待保龙的态度，实际上都未曾偏离过这条主线。

中国老百姓历来要承担两种义务：一种是赋税，要么交钱要么交实物；还有种是徭役，要出人力。兴修水利，运送军需粮食，地方官府迎来送往、日常修葺的琐事，都要征掉人力来做。
这些活都是白干的，没有工钱，服役者往往还要自备干粮。

黄册里甲制锁住了人口相关的税数和徭役，鱼鳞图册和粮长则掌控了田地租赋。黄册，鱼鳞图册以及里甲制三位一体，构成了一道又一道纵横铁索，
牢牢地把百姓钉在了士地之上，动弹不得，化为稳固税基，源源不断地为朝廷输血。
大明凭借着这三样工具，将控民之术提升到前所未有的新高度。历数前朝，还从未有一个政权对民众的控制能做到如此深切细致。

赋役黄册、鱼鳞图册和里甲制所构成的体系，对民众的管束和禁锢达到了前所未有的严密，是不折不扣的“张密网以罗民”。明清两代被称为中央集权的巅峰，其根源，就在洪武始建的这套底层设计里。

读史有一个很重要的原则，就是不要轻易把古人当白痴。我们今天可以看到的历史，和当时人的视角不同，获得的信息亦不同。如果设身处地的去想，就能明白，很多看似愚蠢的举动，自有其逻辑和动机。

大明官场有个特点：上头重视什么，下面未必会重视。往往得三令五申；但上头如果不重视什么，下头立刻心领神会，迅速废驰，堕落速度之快，令人咋舌。

* 舍不得看完的中国史：秦并天下 @渤海小吏

东周分为两个阶段，春秋和战国。春秋的主旋律是“争霸”，而战国的主旋律是“兼并”。

韩赵魏三家分晋，这里的晋就是山西，才反应过来。当然，当时晋不止包含现在的山西全境，还有河北，河南， 陕西，山东部分。

晋有多强大？强大到解体之后的三个国家依旧位居“战国七雄”之列。

三个国家地处天下之中，所以成为后面战国历史上最重要的战场。

所谓战国的历史主线，就是“三晋扛强秦”。

庞涓,孙膑
- 当一个人害你了，你可以原谅他，但是一定要从此远离他
- 永远不要被情绪左右自己的头脑，永远也不要得罪了解你的人

孙子兵法有云：主不可怒而兴师，将不可愠 yun 而致战。

儒家五伦：父子有亲，长幼有序，夫妇有别，君臣有义，朋友有信。

八德：孝、悌、忠、信、礼、义、廉、耻。孔子高度提炼后总结为“仁爱”。

天不生仲尼，万古如长夜。这句话原来是孔子说的。

时来天地皆同力，运去英雄不自由，成败有命，国运在天。

我们要学会分清轻重缓急；要学会在事物的本质关键点上使劲；要分清什么是平庸的机会，什么是千载难逢的机会。如何分辨。则是我们一生要去修炼的本事。
寻常之人要么一辈子在一个问题上辗转反侧，要么对于每一个机会都等闲视之。功业成就之人则往往把握住了人生中的好机会，并尽己所能的扩大战果，

看一个人有没有出息，要看他怎样对待人生的前几次成功。成功是个好东西，有时会激励人，但有时也会毁了人。

恩要等着他人主动报，千万别去要！如果你对某人有大恩义，千万要闭紧嘴，并争取忘掉此事，否则你很可能会遇到奇祸。千百年来，无不如此。

做好人，要积阴德，啥叫阴德？干了好事不让别人知道，帮了别人不让他心里有压力，永远不提这茬。总结起来就是，施恩不图报。

两千多年中，只要是商人掺合政治，最终下场都很惨。吕不韦，桑弘羊，胡雪岩。

* 楚汉双雄 @渤海小吏

人生中的好多事情都可以运用这个道理：不怕慢，就怕迟。

见识这东西，其实说到底，就是大量的理论和实际结合融汇贯通之后，明白了事物发展、运行的规律。
换句话说，就是可以根据现有的情况，准确的判断出来事情未来的走势。

人要在成功面前保持敬畏、保持谦和，很多时候我们成功了，虽然有自己努力的成分，但我们更要感谢命运。

成功越大，运气占的比例越高，自身水平占的比例越低。

科技无论怎么发展，人性的进化都是很慢的。

都说以史为鉴，咋为鉴呢？骄、奢、淫、逸、贪、妒、怒、傲，每一项都是终生的课程。

上升到国家层面这种大牌局，低层次的人往往不知道该怎么玩。

在中国历史中，有一种很神奇的现象，那些干出一番大事业的人，在最初起步的时候，上天总是给他在周边配备了一套相当牛的班底，文武俱佳。

别琢磨细枝末节的各种战术。定好人生的大战略，做好自己的基本功，然后踏踏实实的践行。人生是长跑，时间会把你们筛选掉绝大多数竞争者，复利会帮我们达到人生的巅峰。

将侥幸的概念从脑子中删除，取而代之的是计算概率。

做任何事情，成功的概率越大，越是我们要努力的方向。

长江的源头是潺潺小溪，但并不耽误它最终奔腾成海。

人生最重要的还是赛道的深度和广度！

战争是政治的延伸。

天予不取，反受其咎。时至不迎，反受其殃。

上天赐予的东西不接受，反而会受到惩罚；时机到了不行动，反而会遭受祸殃。其意思是让人把握时机，当仁不让，为所当为，不要犹豫、妇人之仁。

* 秦崩：从秦始皇到刘邦 @李开元

富贵多士，贫贱寡友，不过是人间的冷暖常情。

人处卑贱之位而不思变，正如圈养禽兽，只能张嘴等食，不过徒有一张人脸，两腿可以直立行走而已。所以说，卑贱是人生最大的耻辱，贫穷是人生最大的悲哀。
长久处于卑贱的地位、贫穷的境地，反而讥讽富贵、厌恶利禄，以自托于无为来自我安慰和解脱，不过是无能而已，绝非士人应有的情怀。
@李斯

* 楚亡：从项羽到韩信 @李开元

秦末兵锋突起的时代，韩信不是带头起事的领袖人物，他只是想找一个可以施展自己抱负才能的平台，成就统帅百万之兵战必胜、攻必取的伟业。

所以在各种机遇的选择上，才与众不同，同样也导致了没有善终的悲剧。

刘邦真正意义的角色转换是从鸿门宴之后。

社稷，社是土地神，稷是谷神。

在秦汉，能够指挥六十万大军的将领，一个是王翦，另外一个是韩信。六十万似乎是领兵的极限，非军事天才不可以。

彭城之战，是项羽军事生涯的顶峰，三万楚军破六十万刘邦统帅的联军。

项羽的军事才能被他强悍的个人武力所掩盖，感觉是个莽夫，其实恰恰相反，他是个顶尖的军事天才，比肩白起，甚至要强于韩信。

一位当代的名人曾经说过，生命中最伟大的光辉不在于永不坠落，而是坠落之后总能再度升起。

韩信、英布、彭越，史称“灭楚三杰”

期待高，失望大；失望大，怨恨深。

飞鸟尽，良弓藏；狡兔死，走狗烹；敌国破。谋臣亡。

人生无常，万物有主。慎之敬之，留名于世。

* 汉瓦：西汉王朝洪业启示录 @刘三解

江湖，就是人情世故。其实就是社会关系，也就是“家族传统”“原生家庭”“成长环境”“婚姻”“交友”“工作”等因素交织在一起，构成的关系集合。

前对于刘邦和项羽最大的误解在于：
- 刘邦是和个混子，不知兵
- 项羽是个莽夫

而真实的刘邦，佩剑，会武，长的也是一表人才。而军事水平，在韩信出山之前，是汉家军独一档。放在同级别的首领上，可能仅次于项羽和章邯。

项羽非但不是个莽夫，而且是个顶尖的军事天才。与白起是一档的。只是武力值太多强悍，让大家忽略了军事才能。

项羽的缺陷是他是个政治白痴，而刘邦是这方面的天才。

看一个人，不能听他说什么，而是要看他做什么。

我们知道，过程的顺遂，往往不是运气的加持，而是绝对实力的碾压，杀鸡用牛刀，则意外就少。

付诸阙如，即付之阙如。指欠缺本应具有之物。

汉高祖的“布衣将相”并非是说出自“社会底层”，或者说“劳动人民”。恰恰相反，他们只是属于统治者的“边缘群体”，也就是距离“富贵”“权力核心”较远的“社会精英”。

我们所了解的韩信在项羽那里不受重用，理解上有偏差，重用的反义词不一定是不收重用，而可能是重用但不达预期。按照史书上记载，韩信在项羽的官位升迁比樊哙在刘邦的升迁很快。

只不过，他可能看到了项羽重视“自己人”而自己没有大的机会，也恰恰是项羽的分封比较守规矩，或者说比较保守。

反观刘邦，“不讲规矩”，像韩信、曹参、张耳、英布等人，真正需要的，就是不讲规矩，否则，他们在秦朝也是普通公务员，混年资也可以过得很好。
究其原因，还是“王侯将相宁有种乎”。

韩信的悲剧结局，看似是轻信主君、重情重义，实则是短于治下，没有能够托付机密和生死的铁杆下属。

最终究竟是体制塑造了人，还是人塑造了体制，已经纠缠在一起，无从厘清。

毕竟，历史就在那里，不容许假设。

公共行政学的最主要的创始人之一，马克斯·韦伯认为，任何组织的形成、管治、支配均构建于某种特定的权威之上，适当的权威能够消除混乱、带来秩序；而没有权威的组织将无法实现其组织目标。

在刘邦时代，根本没有什么普惠全民的所谓“休养生息”政策，只是在照搬秦政、恢复秦朝编户齐民体制的基础上，对“自己人”进行肆无忌惮的照顾，进而换取他们的忠诚。
这并不是“历史学”，而是“成功学”逻辑。

一个鲜为人知的事实是，所谓“文景之治”，根本不是政策、制度的连贯时代。

秦汉时代所谓的“法律”，并不是现代意义上的“法律”，其本质的立法原则，并非是规定你什么不可以做，而是规定你应该怎么活，如果你不按照这个“法”来做，你违背的就是“天”的意志，也就不必活了。

所谓的文景之治，展示的“清静无为”的真正背景，是西汉初年的律令制度体系完全是对秦代的继承，只是根据汉朝的政略调整，略做修正。
表面上崇尚黄老之学，其实汉文帝很看重刑法。某种意义上来说，只是一种社会宣导或者洗脑，而各种史学家不敢戳破而已。

看完了，有些枯燥。但是很多视角颠覆了对这段历史的理解，比如说“文景之治”的背后原因。
一些书都是照着史记等各种历史典故来把时间线、故事凑的丰满，但是没有自己独特的理解，比如正在看的大汉帝国。想必而言，这本书就好太多了，观点独特，论据充足。

* 明朝那些事儿 @当年明月

张士诚的特点是器小，陈友谅的特点是志骄；器小无远见，志骄好生事。如果我进攻陈友谅，张士诚必然不会救他；
而进攻张士诚，陈友谅就一定会动员全国兵力来救，我就要两线作战，到时就很难说了。

诸位可以借鉴，遇到恨透一个人、想要拿刀去砍人的时候，用张定边的事迹勉励一下自己，不要生气，修身养性，活得比他长就是了。

人生最痛苦的地方不在于有一个悲惨的结局，而在于知道了结局却无法改变。

这个世界上最坚固的堡垒往往都是从内部被攻破的。

自古以来，最可怕的事情并不是死，而是每天在死亡的威胁下等死。不知何时发生，只知随时可能发生，这种等死的感受才是最为痛苦的。

滚滚长江东逝水，浪花淘尽英雄，是非成败转头空，青山依旧在，几度夕阳红。白发渔樵江渚上，惯看秋月春风，一壶浊酒喜相逢，古今多少事，都付笑谈中！
原来是杨慎写的，杨慎何许人也，他爹是内阁首辅杨廷和。

徐尚书对人一贯和气，而且越是深仇大恨，越是和蔼可亲。

你还很年轻，将来你会遇到很多人，经历很多事，得到很多，也会失去很多，但无论如何，有两样东西，你绝不能丢弃，一个叫良心，另一个叫理想。

人生很漫长，但关键处只有几步。相信这句话很多人都听过，但是许多人并不知道，其实历史也是如此。

十六年前，年轻官员王锡爵大摇大摆地迈进了张居正首辅的住所，慷慨激昂，大发议论后，扬长而去，然后声名大噪。
十六年后，年轻官员赵南星向王锡爵首辅发起攻击，名满天下。
当年的王锡爵，就是现在的赵南星，现在的王锡爵，就是当年的张居正。有趣，很有趣。

因为批评总是容易的，做事总是不容易的。

这个世界上，所有的爱都是为了相聚，只有母爱，是为了分离。

有人曾对我说，原来，历史很有趣。但我对他说，其实，历史很无趣。因为在绝大多数情况下，历史没有正邪，只有成败。

其实我们这个国家的历史，一向是比较复杂的，所谓你中有我，我中有你，能凑合就凑合，能糊弄就糊弄。向上追溯，真正执著到底、决不罢休的，估计只有山顶洞人。

懂得暴力的人，是强壮的；懂得克制暴力的人，才是强大的。

张牙舞爪的人，往往是脆弱的，因为真正强大的人，是自信的，自信就会温和，温和就会坚定。

共患难者，不可共安乐，世上的事情，大致都是如此吧。

换句话说，崇祯上台以后，是很想干事的，但有的事，干了也白干，有的事，干了不如不干，朝廷就是这么个朝廷，大臣就是这帮大臣，没法干。

*成功只有一个 —— 按照自己的方式，去度过人生。*
* 大明王朝的七张面孔 @张宏杰

忧患之来，常始于宴安者。明者能灼于未形，昧者犹蔽于已著，事未形，犹可图也，患已著，则无及矣。

中国社会和西方社会本质上的区别是组织方式的区别。西方社会的统治者的权力总是或多或少产生于契约关系。在封建时代的君主制下，
国王只能对他的直属附庸的封地享有契约规定的某些权利。所以，“你的附庸的附庸就不是你的附庸”。而在以希腊为代表的民主制下，
权力的产生基于这样一种假设，即每个公民都是平等的，公民们在一个国家之内共处，要通过公开的竞争，组织起政府，把权力自下而上赋予它，
使它合法地为众人服务。所以西方行政权力的表情有点像一个雇工，毕恭毕敬，一副被选票所操纵的窝囊样。

在中国的政治传统里，规划设计帝国人民的生活是专制君主应有的权利，《周礼》反复说：“唯王建国，辨方正位，体国经野，设官分职，以为民极。”
每一代伟大的政治家，面对刀剑征服来的天下，都有一种要在上面画最新最美的图画的冲动。他们把自己当成天才的艺术家，
殚精竭虑在这片被他删成白纸的土地上进行美轮美奂的艺术创作。然而由于这种创作以理想主义为指导，这种冲动造成的结果往往是
“先造成理想上的数学公式，以自然法规的至善至美，向犬牙交错的疆域及熙熙攘攘的百万千万的众生头上笼罩着下去，... 行不通的地方，
只好打折扣，上面冠冕堂皇，下面有名无实

其实，真正的英雄人物，做大事并不需要认真的借口，有借口要做，没有借口制造借口也要做。做成之后，自有人来擦屁股。

在中国，做事一定要在真实的意图外包上一层光明正大的道德外衣。

在海瑞的身体里，在历代中国知识分子身体里，总是汹涌着激进主义的热血。他们总是认为，有那么一种终极真理，可以解释整个宇宙，
可以解决一切问题。如果你找到了这种真理，坚定不移，大刀阔斧，就可以粉碎一个旧世界，换来一个光辉灿烂的新世界。所以，
他们做起事来，总是那么唯我正确，总是那么激烈绝对，总是那么一步不退，总是那么缺乏建设性空间。
而他们的失败，也总是脆败。王安石如此，海瑞如此，康有为也如此。
* 两京十五日 @马伯庸

这人如果面临纷乱的局势，一时难以措手，不妨先从做完一件小事开始。一个个麻烦由先及大，逐一解开，你不知不觉便进入了状态了。
古人临事钓鱼，临战弈棋，都是这个道理。

自古能搞起乱子的，都得是揣着明白装糊涂，真糊涂的成不了事。

* 金瓯缺 @徐兴业

生命好像一丸墨，放在科举的、宗教的、诗酒的、节日的砚台上磨，很容易就把这一生磨完了。他们用消竭的生命来换取这些光荣的记录，多看几出戏，多喝几杯酒，多逛几处庙宇，多过几个节日，也就感到不虚此生了。

们衡量别人的幸福，常常根据别人已经被满足了的欲望，那是一望可知，人人清楚的。他们衡量自己的幸福，却常常根据自己曾经设想过、希望过、作过努力或尚未努力过而还没有得到满足的潜在欲望，那只有他本人知道得最清楚，别人未必能够完全了解。正是由于这两种不同的尺度，他们觉得别人常常是幸福的，而自己却常常不幸。

一切形式上的区别都是低级的区别，只有从本质上来区别才是高级的。

计划没有被精确地执行，而且事后证明，被临时修改的计划的大部分都比上级原来规定的更加符合实际，更加具有实施的可能性，但它毕竟是自发的，不是出于领导者的统一意志，没有经过全面平衡。

在政治上，很少有完全紧密的团结与绝对无间的和谐。有之，则是表面上的团结与和谐。表面上的团结与和谐犹如包着硬壳的核桃，透过厚厚的外壳，内部仍有掩盖不住的“磊落不平”

他看起来固然绚烂夺目，却是一株草本的芍药，只是一种观赏的植物，给人看一看，欣赏一下，称赞几句，如此而已。至于它是否顶得住严霜寒雪、急风暴雨，却要待事实来证明了。刘鞈与他十分不同，他们是完全不同的两种人。他却信任刘鞈，把他比为木本的白山茶花，看来很朴素，没有妖艳的姿态，没有夺目的色彩，开足了花也只是一朵朵结结实实、笨头笨脑的重瓣花，花瓣儿挨得密密，包得紧紧的，似乎不愿让人看到它的底蕴。

抄家是暴行的集中，是罪恶的渊薮，是杀人犯、盗劫犯、偷窃犯、贪污犯、强奸犯、侮辱女性犯、诈骗犯的培养所，是贪欲狂、虐待狂、喝血狂的大暴露，也是还没有脱离兽性范畴的“人性”的大展览。特别当这些罪行是在合法的外衣之下进行的，人们就可以借用法律的名义，随心所欲地干一切他们愿意干的事情而无所顾忌，无所约束。

这个马子充好像是一只扑火的飞蛾，多少次，他往理想的火焰中扑去，扑得身焦肉烂，化成灰烬。只要得到一次再生，他还是要向这个理想的火焰中扑去，不到最后陨灭，决不停止。扑呀扑呀！他的生命就是在这样的扑灭、再生、再扑灭的反复过程中消耗尽的。永远不失去理想的光芒的人，就难免成为一个悲剧的角色。

一切斗争，与敌人作政治或军事的斗争，与自然界作生产建设或抗暴的斗争，最痛心的一个现象莫过于力量内耗，在自己内部的矛盾中把力量消耗殆尽

一座城市被毁灭，一个朝代被灭亡，都不是轻而易举就可以做到的事情。首先它并非单纯地亡于外来的暴力，而亡于内部的溃烂以及本身不断造成的错误。人们要花多少气力才铸得成这样一个足以毁灭一座京城、一个朝代的大“错”。

任何一个征服者都要从被征服者中间挑选出一部分代理人来帮助他们治理广大的被征服者。用通俗的话来说，征服者是主子，被征服者是奴隶，中间的代理人就是通常所说的奴才。这是历史的规律。奴才虽然也带着一个“奴”字，但究竟也是“才”，它非同小可，常常要起承上启下的作用。统治者的统治术是否高明，很大程度上取决于他们怎样使用奴才，怎样对待奴才，要从奴才身上取得什么，他们给了奴才什么。

譬如病危之人，非用重剂劫药不足挽救，医生开了方子，病家迟疑低回，唯恐一剂而死，不敢服用，这是所有庸懦迟缓的病家的通病，他们宁愿慢慢地去就必死，而不愿冒一下险以求万一的生存。

那漫漫长夜啊！要何年何月何日何时才盼得到金瓯无缺、日月重光的好日子？马扩手抚着那只骨灰坛，不觉茫茫然起来。

* 大汉帝国 @萧然

两汉共历二十四帝，四百零六年。西汉 210 年。

富贵不归故乡，如衣绣夜行，谁知之者！
不敢相信这是项羽在大火烧完咸阳之后说的话，足以证明在他的内心并没有想做皇帝，还是小农思想，有本事之后就要向家乡人炫耀。

彭城就是现在的江苏徐州

权力争战到特定阶段，有可能成为未来胜利者的便会滋生一种特别的心里：希望分享成果的人越少越好，少到最好只剩下他一个人。

大凡由暴力产生的政权，为着长存下去，总得渐渐从武将统治过渡到文官统治，由武力至上转变为文化至上，即所谓“偃武修文”，社会才得以逐步趋向稳定和安宁。这应是一个规律。

时来天地皆同力，远去英雄不自由。

时运来时，连天地都鼎力相助你，时运没有了，即使是再多智的英雄也会壮志难筹。

狡兔死，良狗烹。高鸟尽，良弓藏。敌国破，谋臣亡。这句话不一定是韩信说的，但却是韩信要死的时候感慨的。

大风起兮云飞扬，威加海内兮归故乡，安得猛士兮守四方。 - 刘邦

中国人一向安土重迁，即使年轻时走遍了天涯海角，到老了还是希望重归故乡，所谓落叶归根。

周亚夫原来是周勃的次子。

一死一生，乃知交情；一贫一富，乃知交态；一贵一贱，交情乃见。

终武帝之世，所施行的思想路线，其实还不是“罢黜百家，独尊儒术”，而是“外儒内法”，或者叫做“霸王道杂之”。霸道指法家刑治；王道指儒家德治。其后昭帝、宣帝也大率如此。
元帝继位后，颇为全面的贯彻了“罢黜百家，独尊儒术”的制度。从汉代元帝开始，中国掀开了一部总体上有言必称孔孟的历史。也从此之后，慢慢的汉帝国走向了黄昏。

诚如徐复观先生所言：“通观古今中外，学术与现实政治，必有一相当距离，使其能在社会上生根，学术乃有发展可能，政治乃能真得学术之益。”（两汉思想史）

对于一种学说，思想家关注的是它的真理性，是它的普遍价值；政治家感兴趣的则是它的工具性，是它的使用价值。

出塞
唐·王昌龄

秦时明月汉时关，
万里长征人未还。
但使龙城飞将在，
不教胡马度阴山。

一战封侯，说的是霍去病。初次作战被封为冠军侯。

霍去病最大功劳在于打通河西走廊，武帝先后设立了酒泉、敦煌、张掖、武威四郡，开辟了从玉门直达西域的重要通道。

究天人之际，通古今之变，成一家之言。《史记·太史公自序》。
司马迁因为为李陵说了一句话，被汉武帝处以宫刑。而后作下：人固有一死，或重于泰山，或轻于鸿毛，用之所趋异也。太上不辱先，其次不辱身，其次不辱理色……

盖西伯拘而演《周易》；仲尼厄而作《春秋》：屈原放逐，乃赋《离骚》；左丘失明，厥有《国语》：孙子膑脚，《兵法》修列；不韦迁蜀，世传《吕览》；韩非囚秦，《说难》、《孤愤》。《诗》三百篇，大民！通“抵”）贤圣发愤之所为作也。

苏武壮年出使，归来须发尽白，羁胡凡一十九年。这个世界上至今还没有发现一种困难，可以击垮一个真正具有人的尊严的人！

张而不驰，文武弗能也；弛而不张，文武弗为也：一张一弛，文武之道也。 《礼记·杂记》
解释：只拉紧而不放松弓弦，即使是文王和武王也做不到；只放松弓弓弦而不拉紧，却是文王和武王不会做的；有时拉紧，有时放松，这才是文王、武王治理国家的办法。

《太初历》的施行时间为西汉武帝太初元年（公元前104年）至东汉章帝元和二年（公元85年），近二百年。但它的一些基本法则，如以正月为岁首，每年有24节气以及闰月的设置等等，一直延用了两千余年，至今正月初一仍是中华民族最重要的传统节日。

人的认识不能超越特定的时间空间。

汉承泰制，皇帝的正妻一人称皇后，妾可有多人通称夫人。此下还有十四等。前十三等是：昭仪、婕妤、经娥、傛华、美人、八子、充衣、七子、良人、长使、少使、五官、顺常；最后第十四等叉分六种称号：无滑、共和、娱灵、保林、良使、夜者。

北方有佳人，
绝世而独立；
一顾倾人城，
再顾倾人国。
宁不知倾城与倾国，
佳人难再得。

这是李延年写的，说的是自己的妹妹，也就是后面的李夫人。他们还有个兄长就是贰师将军李广利。

武帝之后昭帝刘弗陵，在位十三年。然后是刘病已，是为宣帝，在位二十五年。二帝共在位三十八年，史称“昭宣中兴”。

汉世衰于元、成，坏于哀、平。 《汉书·佞幸传》

“断袖之癖”的典故说的是哀帝和董贤的故事。

平帝继位的元始元年，即现在世界多数国家采用的公历的元年。

看完了，评价不好说。自然比不上专业的史书，类似李开元，刘三解写的。但还是帮助我串联了整个西汉的历史，“尚可”。
