#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 2014 年个人总结
#+DATE: 2015-01-03 00:00:00

一转眼，2014 年已经结束了。本来打算 31 号晚上写这篇文章的，打游戏耽搁了。
前天和小伙伴们聚了一下，喝多了，以至于影响了昨天，所以只能逼到今天了。

这几天微博上对于总结了规划性的文章大佬们"嘲讽"的比较多了，在这样浮躁的社会中，我认可这种嘲讽存在的合理性。
所谓梦想、所谓规划，感觉越来越遥不可及。不是因为我们不够努力，而是我们永远不知道明天究竟会怎么样，尤其是在二十五六这样想法多、变数多的年纪。

但是，我依旧认为应该写一写，一则是对自己一个交代，二则给自己一些坚持下去的希望。
如果认真的思考、总结一下，还是会有一些收获的，毕竟每个人的成长也就是这么折腾着过来的（无所谓好、坏，只是一种个人经历而已）。

看了一下去年写的 [[file:../2014/2013-personal-review.org][2013 年个人总结]]，有些惭愧。整理一下 14 年的一些经历，对比一下两年以来的变化，并对今年（15 年）有个期待。

* 换工作

14 年对于我最大的事应该是换工作、换城市，具体的原因我在 [[/leave-beijing.html][离开北京，去上海]] 这篇文章中说过了。这里说一下自己的一些想法:

换工作要慎重，离职可以冲动（因为不喜欢嘛，老子就不干了，这是可以理解的），但是要选择另外一家公司要先做一些调研，
千万不要因为自己主观意愿上的期待和薪资盲目的选择一家公司，否则就是从一个坑掉了另外一个坑。

选什么样行业? 视频、电商、金融、游戏等，考虑自己的喜好是一方面，更重要的是职业生涯规划，千万不要因为自己的内心中对某份工作的期待或者因为薪酬等就选个一个行业。
最好的办法是问问在在相关行业的开发人员、测试人员，他们的看法，也可以找一些文章。比如看 [[http://blog.codingnow.com/][云风]] 的文章，就可以发现他的文章大多是如何做技术和游戏，
而基本上不谈工程文化，但是看 [[http://timyang.net/][Tim Yang]]、[[http://www.raychase.net/][四火的唠叨]]、[[http://coolshell.cn/][酷壳]]，就相对综合一点，有工程管理、有技术、工程师文化等。
这里并不是评判谁的博客好或者不好，这几个人的的博客，我基本上是常客。
我想表达的是，从博客的内容上可以客观的看出在不同的行业中、工程师的侧重点差距还是很大的，你到底要成为什么样的工程师，多考虑一下吧。

选择什么样的企业，以及他有什么样的团队文化，是不是符合你的气息，这个也要考虑一下。
其实这个更侧重于个人的一个感受、很难调研出来的、除非自己去工作一段时间。
在《重来》中说过实习的重要，不过他是站在公司的层面讲的。以前我比较讨厌实习这个词、总感觉这是公司对你的不信任，
也下意识的觉得如果实习结束后公司没要会很没面子，但是仔细想想，实习不只是公司对个人的一个认可、也是个人对公司团队文化的认可。
可惜的是国内的很多公司实习基本上也就是走个样子，时间到了自然就转正。

具体所在职位、所做的事情也要考虑下，很多公司招人都是临时需要填坑，就招过来了，半年、一年以后事情搞定了，随便给你安排一个新的职位。
这样的公司不管是对员工、还是对公司就极不负责任的。面试的时候多问问吧，如果有朋友在那家公司可以问问具体的工作环境等等。

我一直觉得找一份工作对于做技术的人来讲，是很简单的（只要你不是菜的过分），谁的身边基本上都会有一些人，虽然技术水平不怎么样，但是公司待遇也都不错的。
但是我现在对换工作，多多少少有些害怕了，不是怕找不到，而是换到一个更不切合的环境，
毕竟不管多么优秀的团队/公司，总会有自己的一些问题，找一个合适的环境还真的不如意。

总之，换工作，别冲动，须谨慎。

* 放弃乐魂

12 年四月份开始做一个关于音乐的网站叫 "乐魂"，到现在快 3 年了，到现在 548 篇文章，后来没有坚持的做下去。倒也不是完全放弃了，只是从
http://www.yuehun.in/ 搬到了 [[http://zhangjiee.lofter.com/]]，也不再是一个公众的网站，更私人了而已。

很多人不懂，我会对这样一个网站赋予什么样的感情，总体来说就是过去几年的一个寄托、一个念想吧，毕竟那些音乐、那些人、那些事总是值得回忆的。
其实不再继续做是希望自己不要沉浸在过去中，直接删掉又感觉有些可惜，就放到 Lofter 了。

* 技术成长

从 Windows 底层开发转到服务器开发，从视频行业转到游戏行业，跨度还是有点大的。就服务器开发，我挺喜欢的。
从风行离职以后，就想着要么做服务器开发，要么做 Python，绝对不做 Windows 下的 C++ 开发了。
后来面试的时候其先生就推荐我去热血项目组，基本上两方面都有了，服务器开发（C/C++），接入用 Django（Python），还经常需要用 Python 写一些小工具。
但是真的不喜欢现在所处行业，也可能是公司本上的问题吧，没有任何企业/团队文化，我在另外一篇私有博客中分析过为什么是这样，这里就不给链接了，
毕竟牵扯到公司了。

14 年没写纯技术文章，以前文章也说过了近几年不写纯技术的文章了。倒是折腾了一个 [[http://wiki.zhangjiee.com/][Wiki]]，涉及到编辑、调试、编译、调优、编程语言等方面，内容不深，
只是一种积累，需要的时候查阅一下。

两篇思考性的文章：[[/thinking-tech-and-blog.html][对技术和博客的思考]]、[[/tech-person-accu-and-intergrate.html][技术人的积累和整合]]。

相比 13 年，虽然表面上看 14 年学的技术更全面一些，但是心里上总觉得 14 年并没学什么东西，没什么意思，没有以前充实。
在北京的时候每天晚上各种折腾技术，虽然没得到实质性的技术提升，但是真的很开心，很兴奋，总觉得有很多事情可以去做。

反观 14 年，有的时候很忙，那是在忙工作，不是忙自己的事情；当闲下来的时候，总想打个游戏，睡会觉，放松一下。
久而久之，感觉日子过的很快，把握不住，但又无可奈何。

离职以后我一直在反思自己在风行中所做的事情，究竟自己是对的还是错的。后来的结论是，我有很多地方是不对的。
不是我做的不够好，而是我做的事情对于一个团队来讲并意义并不是那么大的。这也是很多新人常犯的一个错误（可能我犯的更过分而已，跟性格有关）:
盲目的追求完美，而忽略的事情本身的价值。很多道理真的是只有经历过才能真正的明白，
关于离职之后的反思（站在我的角度，站在经历的角度，站在不同类型团队的角度），回头单写一篇文章总结一下（不过可能不会公开了，毕竟涉及到公司层面了）。

分享两篇文章:

[[http://weibo.com/laruence][@Laruence]]，[[http://weibo.com/p/1001603794538257899132][一个程序员眼中的价值]]:

#+BEGIN_QUOTE
  如果你真正做出了真正有价值的贡献, 那么你就可以得到于价值相当的肯定.
  或多点, 或少点, 或早点, 或晚点.

  也许你会自认为得到的不是你期望的, 或者得到的少于付出得, 但,
  那应该不会差太远.

  而如果只追求你得到的价值, 并且要追求各种价值, 而忽略了你付出的价值,
  那会活的很幸苦..
#+END_QUOTE

不能同意再多了，真的。不管是我的博客还是我和别人谈技术的时候，总是会谈到四个字: "职业素养" 。而 Laruence 谈到的价值，也就是职业素养的一个导向。

我一直认为，成为优秀、追求卓越不是一个结果，而是一种日常习惯，应该融入到自己每做的一件事情上（在有限的范围内把事情做到最好）。
这也是我一直坚持的东西，不管干的开不开心，与你配合的是什么样的人，只要是该自己做的，就做好，也因此获益匪浅。

[[http://timyang.net/][Tim Yang]]，[[http://timyang.net/tao/thoughts-2014/][一个技术从业人员眼中的2014]]:

#+BEGIN_QUOTE
  刚接触第一门编程语言时候，对每一个细节充满了好奇心，发现一种新的语法糖也会兴奋不已。当使用这些技能之后，慢慢的发现工作中只会重复的使用其中20%左右的领域，就这样月复一月的过着。当然学习的习惯还继续保留，工作之外的东西也会去看看其他一些东西，比如花一周学习媒体炒得火热的Swift语言。

  但较常见的情况是，大家学的这些新潮技术工作中一般不会立即使用，几个月之后Swift怎么写可能一点也不记得了。几次类似经历之后，当再有新的某项技术出来，如果看不到有使用的需要，你已经不打算再学了。毕竟花很大力气学会某项东西，又注定在几个月后会忘记，这种做无用功的感觉很不好。因此最终学习曲线会停滞在某个点。
#+END_QUOTE

其实这也是我现在的体会和面临的问题，11 年的时候 TankyWoo 劝我学 Python，我学了几个月，到工作的时候再用，发现自己全忘了。后来在风行要用
lua 做单元测试，学了一段时间，也可以熟练使用了，但是你让我现在用 lua 写个 =Hello, World!= 我估计都够呛能写出来。
我写 C/C++ 程序写的有 4 年了吧，C/C++ 的书经典的基本上都看过了（[[http://www.zhangjiee.com/books.html][books]]），玩各种 C++ 奇淫技巧。但是在风行一年中，用到的不过 20% 左右，
到了现在服务器框架到是用了很多技巧（大量的模板、模板特化、宏、用内存布局实现部分反射），可是大部分时间还是在写游戏逻辑，也不过用到 C++ 20% 不到。
试想，我花了多大的精力玩 C++ ，到最后发现工业开发根本用不到。其他的例子也比比皆是，如果有人问我，你 Python 用过吗，我回答:
「用过」。但是如果他再问水平如何，我真的不知道怎么回答。大部分时候用 Python 都是写一些小工具，做一下数据分析。
不是不知道一些高深的语言特性，而是不需要知道啊，用现有的知识完全可以解决问题了。

也因此，这种情况多了，就会感觉的很疲惫。一次两次靠的是热情，时间长了，完全是看应用场景。现在做技术选择真的需要慎重，这也是我面临的一个问题。

* 个人生活

没有在北京时候的规律，和工作有关、也与个人有关。

入手两款机械键盘（家里青轴、公司茶轴，用过机械键盘真的感觉普通键盘就是渣渣...）、一个显示器（以前的 19 寸显示器实在太小了，换了个 24 寸的）、
一个桌子（房东给配的桌子实在太渣了）、一个 iPad mini（感觉把自己坑了，不怎么用）。年底要买个 MBA ，没有本子回家不方便。

入手一辆自行车，本打算没事骑着玩，但是只玩过一次...

看了几本书:

1. 《暗时间》，大部分内容很棒，不过内容比较零散;
2. 《把时间当做朋友》，推荐最后两章;
3. 《软件随想录》，这本书绝对是过誉了;
4. 《Remote》，一般吧，跟《Rework》没法比;
5. 《黑客与画家》，不同时间段看总会有不同的感受, 推荐一看。

身体素质变差了，懒得出去锻炼，有一个月失眠了一个月，生活节奏太差了。

* 总结

13 的总结，给自己打了 7 分。写这篇文章之前，我觉得 14 年最多也就 5 分，感觉没什么大的收获。
但是写完之后，发现自己也并不是那么差，没有直观的知识收获，但是有一些理解和思考也是不错的。不好也不坏，打 7 分吧，也就刚及格。

身体又变差了，扣一分。

13 年关键字是 "沉溺"，14 年关键字是: "执行力、专注"，事实上由于换工作环境、换城市等，这一点目的远没有达到。所以这里扣一分。

没怎么看技术书籍、没怎么做额外有趣的事情，扣一分。这里应该扣 2 分的，因为毕竟是做技术的，最应该做好的确没做好。

* 2015 的期望


1. 按时休息，注意身体;
2. 多看书，越来越觉得书真是个好东西。一个月一本非纯技术书籍，技术书就不强求了;
3. 多写博客，写东西真的需要坚持，放一段时间就不好怎么下手了;
4. 多交流;
5. 做一些好玩的事情.

关键字：坚持。
