#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 白日梦蓝 【豆瓣乐评摘抄】
#+DATE: 2015-06-27 00:00:00

白日梦蓝，这首歌是前年吧（忘记了）看阿川的 Dota
视频找到的，后来一直听刺猬的歌，沉沦了一段时间。在豆瓣上有几篇乐评，感觉很赞，就收藏了。

原贴链接：[[http://music.douban.com/subject/3566567/]]

--------------

*生活本是如此*

by [[http://music.douban.com/review/1775954/][汽水儿]]

在写这篇也许算不得评论的评论之前，我删除我之前所写的所有的关于音乐的评论，因为那其实就是在装逼，那根本不是我的生活。

其实在写这个的时候，我甚至还没来得及完完整整的听过一遍这张专辑，所以，请各位文艺青年各位大师乐评可以尽情的鄙视我，我只不过是一个普通的青年而已。

我没生活在纽约，没生活在伦敦，没生活在那些浪漫或者宿醉的梦里，生活没让我活不下去，爱情也没夺走我的所有，仅仅是这样普普通通的活着，我活过了
20 年。

从第一首歌开始，我就在无数的回忆我所谓的青春，我曾为我那弱小而苍白的青春期添加了许多文艺或者离奇的情节，就像我们在所有的小说里看到的那样，但当我们站在所谓的青春的尾巴上的时候，才发现，其实那些我曾感到骄傲或者痛苦的青春也不过就是那么平淡的度过了而已，在学校里，在家里，在上学和放学的路上，在那些金色的幻想里。

或许这世界上一万种活法，但是我正在经过的以及以后也会经过的，也只不过是这样的一种而已，耳机里响起的这些歌儿让我感到温暖，因为他们在经过着和我一样的生活，他们在说着和我一样的话。

#+BEGIN_QUOTE
  那些金属相信这世界上一切都是噩梦，那些朋克相信这世界上一切都是虚无，那些中年大叔相信这世界上一切都是金钱女人和人情，我该相信什么？

  我尽量不让自己矫情，尽管这本身就是一件很矫情的事，其实这世界上的一切我们都该相信，因为它们确实是发生了，就在我们的生活里，而不在那些小说或电影里。
#+END_QUOTE

我们经过的是我们的青春，只不过很多时候我们把它当成了小说里写的那些而已。

#+BEGIN_QUOTE
  关于青春，关于爱情，关于未来，我们曾有着那些无限单纯无限傻逼的理想，这在那些高高扬起头的岁月里是说不出来的，因为那一点都不文艺，一点都不深刻，尽管那就是真实的，但是你得学会说谎，虚假的文艺生活。
#+END_QUOTE

大白菜才是生活，燕京和青岛才是生活，京酱肉丝和拍黄瓜才是生活。没碴过架没飞过叶子没割过腕上过吊没退过学，这难道就不是青春了么？正视自己的青春吧，把拯救世界的任务还给超人，把启迪人类的任务交给艺术家，我们只不过是些忧郁青年而已。但是我们真实的生活过，把传奇还给小说，生活本该是这样而已。

说了很多其实无关音乐，似乎也跟刺猬无关。无关就无关吧，至少那些唱着的歌是真实存在的。我们的身体不是最硬的金属，所以我们只能在人群里想象着把自己撞散，用汗水和喊叫去热爱我们所热爱的音乐和梦想。那些不可能实现的梦想如此可爱，那些平淡的生活如此可爱。

--------------

*这里生死花开*

by [[http://blog.sina.com.cn/s/blog_6f39a41c0100s4qf.html][素葉的博客]]

自开始听这张专辑开始，就以平均每天起码一遍的频率听《白日梦蓝》这首歌，其次便是《金色年华，无限感伤》。一直固执地认为，在华语摇滚乐中，直指人心的歌词比起直击人心的旋律更有力量。相比上一张几乎全英文歌词的《噪音袭击世界》，《白日蓝梦》似乎更有寓言性质地在向成人世界发起挑衅。当然，后海大鲨鱼，或者，重塑雕像的权力，他们似乎在用模棱两可的英文词挑战一种暧昧的界定。但也不能说，中文词就有失尖锐了。

「青春是青涩的年代，社会是伤害的比赛」

每一张新专辑里都隐含着这个乐队许多成长的痕迹，虽说做专辑不是非得像写论文那样要主题先行，但毕竟一张专辑就像开一家独立品牌的专卖店一样，需要有自己的独得的概念和态度。并不是说他们的编曲制作在慢慢变得成熟，而是能看到总有种包含着思考的果实在其中，而是能听到在把噪音这个撞击的概念偷换成抨击。

总觉得一首感动死人的歌，却又在你想描述它的时候一时语塞，久久语塞，只能一遍一遍重复地把自己丢进去，一旦白日梦蓝那个前奏响起，整个人就止不住要颤抖，不停得对自己说，生活不就如此么，有什么了不起的呢。说被感动也许并不恰当，而是真心觉得到有人在和你并肩作战，就算没有明天，也什么都不用怕了的感觉。

「24 小时摇滚聚会，搭最后一班车回家」

一些歌，因为它作为记忆体所承载的青春而被我留下；而一些歌，因为它本身所携带的青春留恋和迷幻而让人欲罢不能。越来越觉得摇滚乐本质上是诗意的，这种诗意可以在一张有连带关系的专辑里被无限放大和纵深。其实任何东西，被当作一种工作的时候，是很容易变俗气的，音乐虽然永远带着理想主义的气息，但也不免在技巧和专业的磨砺中变得规矩，就好像大多数的人生一样，遵循社会的一般轨迹，是最容易存活的方式。一年365个24小时，只抽出一个24小时，人生会不会因此而不同呢？坐在呼啸的夜班车上，满载着一副副疲倦的面具，彼此显出陌生，尽管几分钟前，在party尚未结束前，我们都彼此心领神会地对望。但，是不是人生不会因为这一个晚上，这一场聚会而改变，我们就不用尝试了呢？

「全部的爱都已回来，全部的恨都已离开」

音乐最大的动人之处就是它的包容。我们这些忧郁青年，把纷繁世界锁在里面。他们唱着，对于理想的故事，不再有感觉。也许，就是那种没有感觉，才让我有力气面对明天。我才能够一边听着白日梦蓝，一边恨不得用力捶打自己的胸口，一边还理智地告诉自己，不算太坏，至少还剩下一点点色彩和一点点废弃的优越感。起码我还和它相遇了。在这个病毒蔓延的社会里，起码，还有一点点爱和感念在。

--------------

*我终于成了一个无可救药的理想主义者*

by [[http://music.douban.com/review/2713730/][苏不西]]

甜蜜的蓝色。固执的蓝色。

听他们的音乐总是很愉悦的。刺猬的音乐就像一个率真的小孩子，坦白着他的欢喜和拒绝。我能感到音乐里有一些和我理想一样的东西在那里。于是心里就很开心，和着节奏，打着拍子，摇头晃脑，热泪盈眶。

比如，我们都拒绝长成一个庸俗的成年人。我们都拒绝和这个有点格格不入的社会妥协的机会。我们都还拥有摇滚的梦想，不管我们在什么位置，心里也许会有着同样的感动。

【白日梦蓝】长长的前奏很美，跳跃的，有力的，歌词有些忧郁"青春是青涩的年代，我明白，明天不会有色彩。社会是伤害的比赛，当我醒来时才明白"。但是我们的梦境总是色彩斑斓，姿态鲜活，它让现实的生活不那么单薄，不那么疲软。于是我想我还有力可以过好明天。

这张专辑里每首歌都是一种态度。一种对青春的宣誓。【告诉他们我爱你】是真实和坦诚。【Christmas
Ends】有些迷醉。【树】是固执。【假象】是尖锐。

我最喜欢的是【电影】。"故事最后留下悬念 青年们睁大双眼
耳畔响起音乐留下沸腾画卷 这里并不只有音乐
这里有梦也有鲜血"。听到这一句，总是特别感动。

刺猬的歌词很简单。旋律很动听。我想我能明白他们想要表达的是什么。就像一个固执的小孩子，坦白着他的欢喜和拒绝。

如果那个小孩，喜欢一切能够飞翔的东西，那他这一生，一定会用尽力气去尝试。
