#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 在合肥-S2
#+DATE: 2015-11-23 00:00:00

今天早上看到 OurDearAmy
的新文章「时光难熬」，确切来讲不能算一篇文章，只不过是比较感伤的碎碎念，可能这也就是生活吧。我喜欢她的文章，并不是文采有多好、价值有多高，而是写的很真实，不做作。

经常看的几个公众号，「小道消息」、「鬼脚七」、「caoz的梦呓」、「MacTalk」等等，他们其实算的上一种很彻底的自媒体了，文章比较有价值，看完之后收获也很多，但是感受到的只是一些冷冰冰的东西，感受不到一个人在诉说。内容价值放为第一位的公众号，坚持去做，一定会有很多的粉丝，也可能会赚一些钱。但是对于很多人来讲，当他们更新一篇文章的时候，看和不看其实区别不那么大的，并不会有太多的期待。反之，我更喜欢
OurDearAmy
这种类型的公众号，每篇文章都是诉说，有开心的也就不开心的，有有价值的，也有碎碎念的，让你觉得你多了一个无形的朋友。

其实，我一直想做的是第二种类型的公众号，一个有个人灵魂的公众号。尽管如此，很多不成熟、消极的、叛逆的、希望得到别人认可和赞赏的想法，我还是不能写出来给大家看，这无关矫情。

举个例子吧，去年前半年和前女友分手了，因为在一起的时间有点长了，有一年多的时间才逐渐走出来。经常晚上十一二点把
zc
叫出来，两个人喝酒，喝到凌晨两三点，他知道我为了分手的事心烦，但是到现在为止他对我和我前女友之间的事还是一无所知。不是关系不够铁，不是我不想说，只是我真的说不出来，不知道为什么。

小的时候，我好像很喜欢哭，很容易被感动，看电视剧会看到哭。上大学的时候，我告诉自己在任何时候都不能哭，不知道什么时候，我真的做到了。直至现在，我发现自己心里再不爽，不开心，只会很压抑很难受，却怎么都哭不出来。心里有事想不明白的时候，我会一直想一直想，直到想通了为止。现在想想，这真不是一个坏习惯。

以前说过，我写文章基本上不是为了写而写，而是某种程度的"发泄"。我的习惯是写完文章自己看一到两遍，主要是检查一下语句是否通顺，标点符号等。一旦文章发出去，我自己从来不看自己写的文章，也许你们不相信，我自己看了恶心，真的。

昨天看了吴磊写的「一些片段[北京] 1、启程去北京」、「一些片段[北京]
2、帝都初体验」，有了写「在西农」「在北京」「在上海」
这样一系列的文章的冲动，再加上
「在合肥」，多年以后，至少是一份记忆。当然这很有可能只是冲动！

我在彻底决定来合肥之前，是先在合肥这边体验了一周的，看看这边的环境等等。当时我已经肯定要来了，但是感觉
wuxf 似乎比我还要犹豫，他当时跟我提到了一个人生活的难处，担心我扛不住。

现在看来，他的担心是有道理的，我严重的高估了自己一个人生活的能力。这些日子的生活和经历的一些烂事用一句话文艺的总结：

「我曾以为我知道那种感觉，但其实我并不知道」。

说实话，我现在很迷茫，很多事情想不清楚。这几年我有很多次迷茫，都是和职业生涯相关的，只有这次是和生活相关，而这次我该怎么做呢？

困了，下篇文章继续聊吧。
