#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 在合肥-序
#+DATE: 2015-10-12 00:00:00

从江游离职以后，写了上篇文章《离开热血》，大体写了在江游的一年半时间的经历和收获以及离开的原因。

之后很多朋友问我去哪儿的问题，当时已经有来合肥的想法，但是并没有定下来，所以也就没跟大家说，感谢大家的关心吧。目前已经来合肥这边上班几天了，算是稳定了下来，写篇文章谈谈自己的选择与感受。

从风行到江游，都算是创业型公司，工作近三年了，技术基础打的也都差不多了，也做了一些事情。去一家大公司涮一涮，不管是从个人发展、成长空间，乃至薪资，无疑是最好的选择。反之，在这个时候从一线城市到二线城市，从中小型创业公司到一个更小的创业团队，看起来是最差的一个选择了。当时有一些朋友不理解或者直接反对，我都理解并且挺感谢他们的。

每个人的成长环境不一样，毕业以后所承受的压力也是不一样的，我家里虽然不富裕，但是他们并有给我多少压力，要求我一年上缴多少钱，什么时候结婚，买房等等。这可能是我和很多人不同的地方，也是我能够做一个自己认为对的选择的前提。

离职换一家大公司，拿更高的工资，更好的待遇，过两年可能会升职，可能能有更多的财富。这些是我能够想象的到的，所以我不愿意去做。就好像跟着一款游戏过来以后，仿佛就能看的到的是过几年乃至10年之后的自己，无非是钱多了而已。

毕业以后，第一次意识到自己在逐渐老去，不是感觉自己成熟了，而是过年回去发现父母真的变老了，不怎么吵架了，变的唠叨了。那个时候我才意识到年轻和时间就是最好的资本，时间的流逝让我感觉真的很慌，这不是给你多少钱，给你多好的物质生活能够弥补的。如果三年五年后，面临现在的选择，我一定会选最稳妥的那一个，而现在我只想选择自己喜欢的那一个，什么都没有，也就什么都不怕，给自己几年的时间去尝试去折腾大不了得不到什么，也至少不会失去什么。

在风行的时候，和丁亮聊的比较多，离职的时候跟他说，现在工作太平淡了，我想去一个小公司，看看小公司是怎么运作的，最好能跟着一个项目一起走过来，他说你看来你以后想自己单干。比较幸运的是，后来还真的跟着热血这个项目一起走了过来，最后离开。

年初的那些想法，我在以前的文章里大部分都写过了，七八月份的时候，忘了是因为什么事了，和武师傅聊了几句。后来断断续续的聊了一个月，大体知道了他们在合肥这边创业的情况，我感觉对于我可能是一个机会，一拍即合，所以就过来了。这边的团队比我想象的还要小，二线城市自然比不了一线，但是价值观至少是正的（有多少公司是做不到这一点的）。

最后，用陈东坡曾经用的一个签名来结尾吧：低头做事，莫问前程。
