#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: M1983.NET
#+DATE: 2015-09-16 00:00:00

[[http://m1983.net][M1983.NET]] 是我一个第二个音乐网站，可以称之为
乐魂2.0（关于乐魂这篇文章就不絮叨了，经常看我文章的人，应该都知道是怎么回事，不过话又说回来，除了我比较亲近的几个朋友之外，也没几个人知道完整的故事，可能会写，但一定不会发出来），已经"运营"了2个多月了，按照惯例，该写篇文章，一拖再拖，拖到现在。

正文:

在网易云音乐和虾米之前，我一直使用 [[http://www.duomi.com/][多米音乐]]
来听歌的，6月份的时候正好在做一些整理工作，出于好奇，就写了一个脚本把自己在多米音乐的收藏的歌都抓下来，然后生成这样一个网页:
[[http://www.zhangjiee.com/music-memory-in-duomi.html][音乐回忆 -
在多米音乐的那些日子(某年某月某日~2014-06)]]，点击即可播放。

于是我把这个网页发给了yx，他的回答是"你还是这么能折腾啊"，而我的回复是"生命不息，折腾不止啊"。当然，这是聊天而已，实际情况是我不想折腾了，感觉没激情了。

从大三开始吧，一直想做一个自己的音乐网站，当时一方面是不知道怎么做，另外一方面的是不知道自己到底想要的什么。人总是这样，越迷茫，越渴望。大四下学期实习的时候，买了
yuehun.in 这个域名，尝试去折腾，只是没想到一折腾就是两年多。

现在来看的话，虽然花了很大的精力，但是仍旧做的很渣。原因有很多:

1. 没明白自己想要做的是什么，这个也是核心原因。自己想法太多了，如果少点折腾，可能会好很多。
2. 技术角度的，[[https://cn.wordpress.org/][Wordpress]]
   框架不适合做音乐类的网站，当能也没有能力自己开发，所以也没的选择。
3. 音乐源始终是一个很纠结的问题，百度音乐、虾米、音悦台，真是优酷等。因为版权的原因，很多歌后来都没办法播放了。

众多原因吧，实在是心累，今年3月份备份到 Lofter 以后，关门大吉了。

大众的、小众的音乐播放器，我基本上都体验过了，从去年开始用网易云音乐以后，就再也没有换过。对于音乐，和其他人不同的是，我喜欢的音乐歌词和旋律必须有一个让我特别中意。喜欢摇滚是因为摇滚的歌词一般都比较写实，离那些情情爱爱的都比较远，音乐背后的灵魂，这也是当初"乐魂"名字的由来。不过听的多了也会腻，后来就更喜欢旋律，于是开始喜欢后摇、纯音乐等。到了云音乐之后，我发现云音乐的评论真的很有才，很多时候都能够打动你的内心。举几个例子:

[[http://m1983.net/m/4005825/][Без макияжа (dub version)]] 的评论:

#+BEGIN_QUOTE
  @微笑的鱼a

  看清一个人又何必去揭穿；讨厌一个人又何必去翻脸。活着，总有看不惯的人，就如别人看不惯我们。人的成熟不是年龄，而是懂得了放弃，学会了圆融，知道了不争。有些苦衷不言痛，不是没感觉，而是知道说与不说都一样；那些暗伤，不是不在乎，而是懂得了慢慢修复。
#+END_QUOTE

[[http://m1983.net/m/28038055/][爱着爱着就永远]] 的评论:

#+BEGIN_QUOTE
  @酒瓶盖子: 人常常都是这么误会自己的 以为自己恋旧 以为自己长情
  其实只是现在过得不好而已

  @sosoli: 她割破了手指 他紧张得疯掉 飞奔去替她买创可贴 但是 他是个哑巴
  比划了一阵子 服务员也不知道他究竟想买什么 他心急如焚 后来索性拿出小刀
  在自己的手上割一道口 我很喜欢这个故事 如果爱情只是靠说说而已
  那哑巴怎么办。
#+END_QUOTE

念想这个东西很奇怪，虽然乐魂做的磕磕绊绊，但是总是想有这样一个网站，可以放自己喜欢的音乐。如果就这么放弃了，始终不甘心。有了上次的经验以后，我并不着急撸起袖子开始写代码，而是花精力想明白要做哪些事情，而不是漫无目的的瞎折腾，等想明白了以后，也就成了现在的
M1983.NET。面对以前的存在问题的应对策略：

1. 定位是:
   纯粹的存放音乐和听音乐的地方，不会设置评论系统，不会设置分享。
2. 网站后端基于 Django 框架，不会有以前的 Wordpress 那么多的限制。
3. 内容上完全依托于网易云音乐网页播放器和热评（脚本爬的）。

M1983 这个名字的由来，M for music，1983
其实只是为了好记......，没有什么特殊的含义。

就这样吧，这可能是关于乐魂相关的最后一篇文章了，借此对曾经帮助过乐魂的
zy, cx, lb, yx, dzy ... 表示感谢。
