#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 对技术和博客的思考2
#+DATE: 2015-04-26 00:00:00

从大二（2009 年）的时候开始写博客，到现在差不多 5 年左右了。平台从 csdn
到博客园，再到独立博客; 工具上从「虚拟主机 + Wordpress」的方式到 「VPS +
Github + Jekyll + Markdown + Emacs」,
一路走来，对博客的理解随着个人的生活、工作经历一直再变。过程中杂七杂八的技术顺带就学了，基本上都是边用边查的，虽然功力不怎么深厚，但是够用了。

依稀记得，第一次用 Wordpress 搭建博客的时候，LAMP 差点折腾死我，对
Apache（后来换用Nginx） 和 MySQL 一点概念都没有。第一次写主题，HTML、CSS
相关的问题问的 Tanky
都烦了，最后都不管我了，好在那个时候他也是菜。折腾几次之后，就再也没怕过这些东西，后来的几个博客主题都是我自己写的。

13 年，大家都崇尚像黑客一样写博客，开始折腾静态博客工具:
Octopress/Pelican/Jekyll ，后来选择了 Jekyll 。也是那个时候开始 Git +
Markdown + Emacs
这个组合的。到头来，技术博客没写几篇，到时把工具玩的很熟了。现在想想虽然有些本末倒置，但是这些工具的使用，对现在的影响还是很大的。

时至今日，没精力再去折腾那些东西，也觉得没啥意思了。

作为结束，谈一下这些年写过来，对博客这种形态的几点理解，也有可能是这些略微偏激的理解，让我不再想去写博客了。

** 一篇博客应该有一个观点（或者主旨）
   :PROPERTIES:
   :CUSTOM_ID: 一篇博客应该有一个观点或者主旨
   :END:

仅仅「提出问题、解决问题」这种问题记录式的文章的不应该算作一篇合格的博客，应该加上通过这些问题得到了什么，超越问题本身的解决问题的思路和方法才是重点。而且，这种类型的文章也并没有多大的价值。不知道大家有没有这样的感觉，当遇到问题的时候，我们用谷歌去搜，一般答案都在官方文档或者像
stack overflow
这样的论坛中，找到的答案一般都很准确，基本上就是我们想要的。反之，假如我们用百度搜，很多时候都会从
CSDN 或者 博客园去检索，很旧的一些技术(比如汇编、C
等)，答案还可以，但如果是 Django, Ruby
这种相对新一些的技术，答案坑的概率很高，要么版本陈旧，要么理解的太片面了。

所以个人以为问题式的文章，即便写的再好，价值也没那么大。其实这种「文章」，我也写过不少，比如：[[http://blog.zhangjiee.com/differences-between-std-cpp11-and-std-gnu11.html][differences
between -std=c++11 and
-std=gnu++11]]，[[http://blog.zhangjiee.com/the-most-vexing-parse-in-cpp.html][the
most vexing
parse]]。一篇合格的博客，应该像这样：[[http://coolshell.cn/articles/10217.html][加班与效率]]，有观点，有论据；我以前写的：[[http://blog.zhangjiee.com/cpp-vtable.html][C++虚函数及虚函数表解析]]、[[http://blog.zhangjiee.com/analyse-new-delete-malloc-free.html][再谈
new/delete/malloc/free]]，这两篇文章花了我至少 8
个小时以上去研究，整理成文。

/一篇好的技术博客，有争议是很正常的一件事情，如果大家读完都说好，那这篇文章估计也没多大价值，搞技术的这个群体就是这样的。/

** 博客是严肃的，不是笔记，更不应该碎碎念
   :PROPERTIES:
   :CUSTOM_ID: 博客是严肃的不是笔记更不应该碎碎念
   :END:

我见过很多人博客非常的「充实」，产量高的吓人，一天一篇或者更高。文章内容基本上都是从书上拷一段，把课后习题实现了等等。还有一种博客，就是所谓碎碎念的形式，写的时候很开心，怎么发生的，甚至谁说了什么都会写的清清楚楚，洋洋洒洒上千字，很简单的一个问题，非要写的异常复杂。但是我以为：只有经过一段时间的积累、思考才有可能写出一篇高质量的博客，很少有人能一天一篇，除非他真的是憋了很多年。笔记应该以
Wiki 的形式来表达更合适一些。

btw，上大学上的的很多人不会说话，不知道怎么和别人有效的沟通；
不会文字表达，做个简历做不好，写封邮件事情都表达不清楚，说实话大部分毕业生的个人素养真的太低了（工作一年年还是这样的大有人在）。

** 博客不只是写给自己看的
   :PROPERTIES:
   :CUSTOM_ID: 博客不只是写给自己看的
   :END:

博客既然自己花了很多的精力写出来了，就应该让更多的人看到，分享给别人，如果可以帮到别人，那再好不过了。顺便可以吸引更多志同道合的朋友相互学习，沟通一起玩技术也是很棒的一件事情。

扩展：[[http://book.douban.com/subject/5320866/][Rework]]中培养自己的拥趸，强烈建议大家去看看这本书。

** 并非每个技术人都应该有一个博客，但是每个技术人都应该写作
   :PROPERTIES:
   :CUSTOM_ID: 并非每个技术人都应该有一个博客但是每个技术人都应该写作
   :END:

写作的好处自然不用说，锻炼思维、思考总结、但是博客只是写作的表达方式之一。

我遇到过的一些能力不错的人，他们从来不写博客，但是都有写作整理的习惯。上面说的三种：写书籍笔记、问题记录、写东西只给自己看，都是很好的几种学习总结方式，但是很显然笔记本（比如印象笔记、有道云笔记）更适合做这些事情，博客并不适合。

以前总是太执着于这些「炫酷」的技术和工具，现在才想明白一个道理：*用最简单的方式能解决问题就可以了*。
