#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 周末闲聊
#+DATE: 2015-08-16 00:00:00

从博客转到公众号写文章有段时间了（三个月，时间过的真快），粉丝也逐渐地变的多了起来，然而这并没有让我变的多开心（稍微有些开心），而是一种焦虑，
更是一种责任。

粉丝虽不多，但也基本上可以分为三类：

1. 认识的朋友，刚申请完公众号的时候，碍于情面就关注了，也因为碍于情面，也不太好取关
2. 不认识的老朋友，粉丝里面有一些人（不多），应该是从博客和新浪微博过来的，有些人的
   ID 好多年前就见过了
3. 不认识的新朋友，这个不用解释了吧

对于这个公众号而言，第二类是最重要的，其次是第三类，最后是第一类。原因用 rework 书中的一句话表述:

#+BEGIN_QUOTE
  培养自己的拥趸。在过去的 10 年里，我们通过 Signal vs. Noise 博客，培养了超过 10
  万名的每日浏览用户，这就是一个庞大的观众群体。他们每天都回来看看我们在说什么。我们的话题面向设计、业务、软件、哲学、易用性，
  或针对整个行业的宽泛讨论。不管我们聊什么，这些人都兴致勃勃的回来倾听。如果他们喜欢我们的观点，也很可能会喜欢我们的产品。
#+END_QUOTE

rework 不管是在博客还是公众号文章中出现的频次都挺高的，再次推荐给大家。

坦率来讲，我写东西越来"自私"了，上一篇 [[/Smells-Like-Teen-Spirit.html][少年心气]] 就是一个典型的例子，不管是内容上还是表达方式上，个性都太强了。
如果分成几篇来写效果可能会好一些，理论上来讲，的确是这样的。很少有人会喜欢这样冗长的文章，大家喜欢简单而又励志的故事（我也喜欢）。

对于分享这件事，我的想法从来都没有变过。举个例子来讲，一个人站在讲台上做分享，100 个观众在听分享，原则来来讲，
只有 20% 的人（或者更少）能真正明白分享人在说什么，这 20% 中的 20% 的人（毋庸置疑，道理明白，真正愿意去做的人又有几个呢）才有可能去实践，去尝试。
=100 * 0.2 * 0.2 = 4= ，从普遍意义上来讲，「你写的东西，真正受益的人，只是极少数的一部分人」。
所以当我明白了这个道理以后，就不再特别在乎基数有多大，而更在乎受益的那一部分人，他们的想法是什么，因此上面的第二类人才是真正最重要的人。

公众号在统计方面，确实要比博客强的很多，明确可以送达的人数，沟通也仅仅是读者和博主之间的私聊，不需要让别人看到(事实上的确不需要)。
体验下来，公众号更私人一些，我感觉和 QQ 空间写东西差不多。当然，公众号有几点上目前存在问题：

1. 过于简单，这是优势也是问题所在，单从某一篇文章上来讲，是没有问题的。但是个人维护的时候，文章不能分类，不能加标签。文章多的时候，不方便维护。
2. 不能被搜索引擎检索。
3. 基于数据库的存储，备份和迁移比较麻烦。这是非静态文章的通病，以前用 Wordpress 也有这个问题。静态博客，
   我只需要维护 Markdown 文件就可以了，不管引擎用 Jekyll, 还是 Octopress，或者是 Pelican。极端一点自己写一个博客工具，都是一样的。

因为这几个问题，我把所有公众号上的文章，都备份到我的个人博客了，万一那天公众号让我的觉得不爽了，也有条退路（同时也建议刚开始写东西的朋友，
一定要做好文件备份，今天流行的平台，说不定明天就被淘汰了）。

前段时间把公众号的介绍改了，觉得以前的介绍有些官方了，而实际上我并写不了「技术、工程」方面的高质量文章，现在就简单的多了:「真实的、美好的」。
这几年，唯一没有变的是对美好事物的追求。亢奋的、平静的音乐，美好的文字，图片，程序等等，当你突然看到一些自己喜欢的东西的时候，那种身临其境的感觉真的难以言表。以后会多给大家分享一些好的东西，可能不是原创，就像以前的两篇:[[/talk-china-rock.html][这是一个亡命徒死绝的时代，不知道这是不是谈中国摇滚]]
和 [[/bai-ri-meng-lan.html][白日梦蓝【豆瓣乐评摘抄】]]。大家要有好的东西，可以私信给我。
