#+SETUPFILE: ~/site/tpl/weekly-tpl.org
#+TITLE: 2020 Q1

* 2020-03-03 11:17:16 Tue

再也不乱升级 Emacs package 了，一早上时间没了。全部回退到 stable 版本了。

* 2020-02-21 15:43:43 Fri

不能每天都完全做一些重复性的事情，没人愿意做这样的事情，如果非要做那么大多是与钱有关的事情，「不得已」而为之。

但是每天都要有所进步，无论是大是小，无论是哪个方面的：技术成长、生活感悟，又或者是一句有意义的话。

把这些成长用文字记录下来，这也是记录的意义所在。

* 2020-01-21 16:55:14 Tue
翻老的文章翻到一句话感觉收获颇多：

#+BEGIN_QUOTE
不要花太多时间在防御性的工作上。
#+END_QUOTE

* 2020-01-20 15:48:28 Mon

#+BEGIN_QUOTE
每一个机构，每一个部门每一个岗位都有自己的游戏规则。不管是明是暗，第一步学会它，不过好多人还没有走到这一步就已经死了，知道为何？自以为是。
第二步，就是在这个游戏里面把线头找出来，学会如何不去犯规，懂得如何在线球里面玩，这样才能勉强保持性命。
#+END_QUOTE

--- 寒战

* 2020-01-20 14:22:00 Mon
有时候觉得看别人荒废时光想说两句，但是慢慢的就忍住了，自己的日子还过不好呢，一天天的担心别人。
而且，一个装睡的人，你怎么叫的醒。
* 2020-01-18 10:32:56 Sat

从今天开始，开始微服务和 Kubernetes 学习周期。

* 2020-01-17 15:11:42 Fri

#+BEGIN_QUOTE
There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies. The first method is far more difficult.
— C. A. R. Hoare
#+END_QUOTE

翻译过来就是：「软件设计有两种构建方法：一种是简单到明显没有错误，另外一种是复杂到没有明显的错误」

C. A. R. Hoare 也比较厉害，是快速排序的发明者，也是哲学家就餐问题的提出者，具体见：https://zh.wikipedia.org/wiki/%E6%9D%B1%E5%B0%BC%C2%B7%E9%9C%8D%E7%88%BE

* 2020-01-17 14:52:02 Fri

1. 从 Go v1.11 升级到 v1.13，顺便研究了一下 =go mod= ，比 govender 好用一些；
2. 又整理了一次 Emacs Go 的配置，每次版本升级，工具链都要跟着折腾一次；

* 2020-01-16 17:05:13 Thu

现在经常突然闲下来之后，有点茫然，少一个学习的主线；
要理一下当前用到的技术栈和相关的学习进阶资料，区分优先级，然后空闲的时候慢慢巩固。

* 2020-01-07 17:04:54

创业公司解决现下的问题才用的野路子方法，是逼不得已的，并不是万能钥匙。

「现下」本身就是一个难以界定的，满足今天明天的可以叫现下吗？满足今年以内的可以叫现下吗？

立字据，一年后内见分晓。

* 2020-01-01 16:27:40

人生啊，从懂得道理到落地实践该有多难。

* 2020-01-01 11:10:42

hello, 2020.
