#+SETUPFILE: ~/site/tpl/youth-tpl.org
#+TITLE: 在合肥-S3
#+DATE: 2015-12-08 00:00:00

我基本上是两周一篇「日志」的节奏，本应该上周末写的，周六和几个朋友开黑打Dota，周日写「职业生涯规划」去了（职业生涯规划，这可能是个悲伤的词汇，哈哈，你们懂的），今天补上。

接上篇，「在合肥-S2」写的时候有些迷茫，最后也抛了一个很大的话题，就是如何去生活的问题，这个问题可能要穷尽每个人的一生才能回答，所以我并没有解决，只是暂时有了答案。

*项目上线测试*

确切来讲，还没有正式开始使用，上周五打了一个 tag，预示着第一个发布了功能相对完善的版本。来「[[http://www.qixinginc.com/][七行]]」（我司
，以后的文章不在赘述）已经两个月了。代码写了只有一个月，主要是搞需求分析，前一个月除了一个版本，后一个月改动比较多，基本上和重写差不多了。

其实过来压力挺大的（似曾相识，以前说过了？！）：

- 从技术层面上讲，我以前是做手游服务器开发的（C++），虽然游戏接入和数据分析都是用的是（Django，Python），但是当时确实偷了很多懒
  Django 文档都没怎么细看过。虽然也经常在线上操作，但是对 Linux
  系统（及命令）、负载、调优，以及数据库备份、恢复等都只是一知半解。我以前文章里说过，我很讨厌几样基础：网络、数据库、UI相关的。一方面讨厌不想做，另外一方面自视甚高，觉得有问题哥搜搜资料也就搞定了。当然，最重要的一方面原因是后
  广宇 这个坚强的后盾，实在搞不定还有 广宇
  来救火，不怕。过来之后，做了纯 Web
  服务器开发（终于告别了C++，赞！），Python
  还好，虽然没有正儿八经的学过，但是也毕竟用了好几年了；Django，Linux，MySQL，Nginx，uwsgi，web前端（html/css/js）......这些都用过但都很不熟，所有这些这可不可控的因素都是我压力所在，这和个人有关和自信无关。这两个月的让我想起了我大二的时候，刚对程序有了感觉，感觉自己每天都在面对未知的东西，不断的尝试，不断的验证自己的想法。那个时候是我很兴奋，也是我大学成长的最快的一段时间了。这两个月应该是我工作以后，过得最充实的一段时间了，有些累，但不辛苦，很爽。
- 非技术层面上，在过来之前武师傅应该对我当时的技术水平是不了解的，两年左右没有怎么联系了，这两年我做了那些事情他也不了解。而且，过来之后，只是让我看看工作和生活环境，一个简单的面试也没有。对于这份「信任」，我只能尽自己所能把事情做到最好。

现在，这些压力（似乎压力这个词之后最近才在我的日志中出现的）
都烟消云散了，工作、技术都顺手了，剩下的只是一往无前。

我很幸运，在江游能有机会跟着一个游戏、一个团队一起成长，现在又可以跟着一个初创公司一起成长。在七行除了项目相关的事情，我有几件额外的事情想去做，一个是把公司自己的技术栈（technology
stack）逐渐的搭建起来，我认为 互联网企业
的技术根基和工程师文化是公司可持续发展的保证，产品失败了没有关系，只要这批人还在；另外一件事情是想做公司的
数据分析和监控平台 ，一方面这基本上是每一个 互联网
刚需，另一方面是我在上家公司的念想（当时和广宇想着做自己的 BOSS，只可惜
BSS 最后不了了之，现在也不知道怎么样了），总想把它实现。

*写作、写作体验*

11月28日的时候，我又新开了一个博客
[[http://blog.zhangjiee.com/][张杰de闲言碎语]]。

「技术做的不咋地，工具研究了一大堆；文章没写多少，平台换了一大堆 」

好悲伤啊！

就写作而言，不同的阶段，需求是不一样的。以前和「丁亮」吃饭的时候，我问他你怎么不写博客啊？他的回答是：不是我不愿意分享，只是觉得太麻烦了，没时间折腾，要记个什么东西直接印象笔记多方便啊，如果印象笔记可以直接挂域名的话访问的话，我选择这种方式。我现在有同感。

以前追求「酷」，Linux + Emacs + Markdown + git
+Jekyll，「像黑客一样写作」。现在基本上没有这方面的需求，也不写技术文章了，只想有个
「所见即所得」的平台。我现在写东西，基本上都是写在我的印象笔记的，然后拷贝粘贴到其他平台发布就
OK 了，也不需要几级标题，所以也不存在排版的问题。

微信公众号
是一个很好的阅读体验极佳的平台，最新一次改版，后台编辑体验也更好了。但是，这毕竟是人家的平台，控制权不在自己，「霍矩」的新文章称：

#+BEGIN_QUOTE
  我个人认为微信有一个相当不错的团队，和一位非常优秀的掌门人。但很遗憾，个人品质和团队品质不能保证一个这样规模公司做的事情都是正确的。
#+END_QUOTE

同样，按照公众号的发展趋势来讲，我相信他们他们以后可以做的更好，但是我不相信
商业操作 和 Go-vern-ment，这些因素是不可控的。

所以我还是自己用 Wordpress 搭建一个博客，让我惊讶的是，这些年的发展
Wordpress
已经很赞了，手机上的阅读体验不亚于公众平台。以后「日志」会首发到
个人博客 中，部分日志才会在公众号发布。

*没事，别随便思考人生*

这个标题其实
「鬼脚七」的新书名字（我给加了一个断句）。前段时间生活上有些迷茫，我看到这个题目的时候，想了一下突然就明白，我特么就是思考人生思考多了。

我经常在晚上睡觉之前、一个人走的时候、早上睡醒的时候想过去的经历、想未来、想理想、想人生，有的时候会莫名的悲伤，觉得干什么事情都没意义，生无可恋。我承认，很多道理都是靠这些时候想明白的，想透彻的。但是大部分时候真的是杞人忧天。

自打我想明白了这个道理，生活质量倍感舒畅和充实：

1. 想好了要做一件事情，就去做，立刻！马上！不要等到明天，不要等到下午。
2. 如果是定好某一天要去做的事情，但是时间过了没有做，以后再也不要想这件事情了，也不要做了，也不要去想自己为什么没有做！因为那件事情本身可能本来就无所谓的。

当你的个人实力赶不上你的想法的变化的时候，就先不要想了，干点实事去提升实力吧。

*成长*

「所谓成长，就是自己不断颠覆自己想法的的过程，迷茫过了，痛苦过了，就成长了。」

再过几天就 25 岁了，再过 2 个月就 26 岁了！

不想说什么时光荏苒、岁月如梭的话，只想说 周杰伦 结婚了；科比退役了；前几天关于陈冠希的记录篇，突然发现「艳照门」过去已经 8 年了！

上周末写的「职业生涯规划
」，主要是针对接下来的三年（26、27、28），也是我最后能够挥霍的极限了，整个规划是围绕这几个关键字展开的：

1. 健康 本来没加的，这几天病了才意识到身体的重要性！「世人最大的愚蠢莫过于为了诸如金钱、晋职、学问、声名、甚至为了肉欲和其他片刻的欢娱而献出自己的健康------叔本华」
2. 成熟 从大学到现在一直在逃避的一个问题，知道现在，才意识到自己真的该改变了
3. 自律 养成良好的习惯，优秀和追求卓越是习惯，而不是目标
4. 专注（坚持）：Stay hungry,Stay foolish！
