#+SETUPFILE: ~/site/tpl/youth-tpl.org
#+TITLE: 在合肥-S10: 年后
#+DATE: 2017-04-02 00:00:00

清明放假，身边的朋友们都回家了，我也想回，可是太远了。

我很少会谈到家，因为我一直对家都没概念，倒不是家里人对我不好，只是因为从小跟父母在外面奔波，高中、大学都不在父母身边，工作之后更是到处漂，手指头掰一掰也十几年了吧。前几年也没觉得什么问题，反而觉得自由自在。可最近一年多的时间里，停下来的时候，觉得酸酸的。

了解我的朋友都知道我看过「古龙」几乎所有的小说，经典的小说，比如小李飞刀系列，看过很多遍。我向往那样的江湖：一人、一剑、一壶酒、行事洒脱、快意恩仇。可后来书中的故事逐渐成为现实的时候，才明白全然不是那么回事，各种酸楚，只有自己明白。原来不知不觉，我好像已经成了一个浪子，四处飘荡、居无定所。从此，不敢再看古龙。

此处应该有手动BGM：「曾梦想仗剑走天涯，看一看世界的繁华，年少的心总有些轻狂，如今你四海为家」。

距离上一篇「在合肥」已经有快 5
个月了，迟迟不写原因有很多。过完年之后心态不好，有段时间一直处于崩溃状态，身上负能量太多，写出来东西恐怕又是发泄式的东西。前段时间(几周前？一个月前？忘了...)
zhengyuan 问我为啥不更新文章了，我说就写，后来一拖也好久了。
写文章就是这样了，如果你隔三差五的就写一篇，觉得没什么；但是，放下一段时间之后，就很难再开始写了。

过年之后的这几个月，仿佛过了很长时间，周围人事还是照旧，只是感官上的差距太大了。权当碎碎念捋一捋，没什么主旨，有些是个人的，有些是公司的，都写写。

--------------

杨溪在过年期间，回国待一段时间，年前就合计着聚聚。所以过完年之后，在西安我们几个人聚了一下(杨溪、疯子、张超、阿龙)：台球、喝茶、吃饭喝酒、KTV
一条龙。一起唱歌时候，仿佛回到了大学小东门外的拿个小 KTV
里。我、杨溪、bird、x 四个人，我和杨溪是任何歌都可以唱出摇滚的感觉，bird
则是各种伍佰，而 x 是向天再借五百年...一个唱摇滚可以左右摇的男人。

那一晚唱了好多许巍和郑钧，竟然还被杨溪找到了「镜子中」，唱的疯子默默的点起了烟。很久不见，一首「浮躁」还是那么的有感觉，如果磊磊在的话，一定会跟着嗨起来...，这可能是毕业之后的四五年里最开心的几个小时了。

散场之后，第二天各奔东西，飞机的飞机、高铁的高铁，上班的上班。

--------------

回到合肥之后，有些「冷场」。年前和肖峰聊过公司年后的部署，我也只是提提建议，吐吐槽，毕竟只是公司研发的一员，能决定的事情不多。可能这也是我的「毛病」吧，操太多的心，闲不下来。年前因为马上就过年了，也就没怎么较真，随便聊了聊。但终会有年后的！过完年之后很短的时间里，如我所料，每个人都是迷茫状态，不知道该干什么。

在我整个职业生涯的四五年时间里，非常讨厌这种毫无目标的状态。在酱油的最后那段时间就是这种状态，没多久就离职了，所以我心里上有些担忧。这种担忧夹杂了很多复杂的东西，譬如回了一次家，感觉又不一样了，身上的担子又大了；譬如工作几年了，依旧没什么作为；譬如对行业、对公司人事的失望；譬如一颗越来越安逸的心；譬如一大推复杂的人际关系等等乱七八糟的东西。

在闲的那两周里，我异常的浮躁，做几个小程序或者说看看文档做一些技术沉淀，但没过两天就搞不下去了。因为我深深的明白，这不是我应该做的事情，无非是浪费时间和精力而已。

一个产品在不同的阶段短板不一样，同于木桶原理，如果短板不提高，最长的板再增长也没有意义。在风行的那段时间让我明白了，如果做的事情没有产生实际的价值那么做的事情是毫无意义的，不管你付出了多少。「爱车店」这个项目到这个阶段，瓶颈已经不再研发这块，我再怎么努力也解决不了整个产品的问题。

印象中年后的第一个版本是很维和的，像是在凑数一样的加了几个功能，我做的毫无感觉。很多想做的事情，但觉得做了毫无意义，所以也就不想做了。年后的第一个月的事情，我到现在想已经完全想不起来了，唯一留给我的感觉是做任何事都无意义。

后来销售定各种计划，去跑南京市场，合肥的售后也逐渐搞起来了。销售、售后进入良性循环之后，研发是永远停不下来的，所以二三月份里，还是各种研发任务。南京市场势头还不错，我还是挺开心的。坦白说，如果慢一点，我可能已经不在合肥了，因为人的一生中没有几年可以浪费，我希望在我牵挂最少的几年时间里，全力的奔跑，不浪费青春。

加入七行之后，我技术成长最快的应该是前 8 个月的时间里，除了 App
之外的整个架构全都是我一个人做的，前端、后端、部署，自动化等等。在后来的时间里，尤其是今年，技术上基本上没有任何的成长，一部分的时间都在写毫无技术含量的
Python/Javascript
代码，还有一大部分时间是在琢磨用户体验、优化交互，琢磨新功能应该做成什么样等等。可能公司的人觉得我喜欢做类似的事情，其实恰好相反，我非常讨厌类似的事情。我努力去做，只是因为公司没人去做，才必须主动的去做，相比于其他，我更希望产品的用户拥有更好的体验，而不是一边骂着娘一边不得已用你的产品。

在我的规划，我还需要 3
年左右时间的技术方向的历练，现在做产品远远不是我想要的。我很担心两三年后，陷入一种尴尬的境地，技术拿不出手，产品更拿不出手。在最近的半年多里，做技术我很少有那种兴奋的感觉了(做技术的都懂)，说明做的事情出现了大量的重复，也说明我在不断的变菜。所以，我很焦虑了很长一段时间，自己和自己纠结。

可能没有人会给我答案，没有人能告诉我现在我应该怎么做，继续像现在这样做下去，还是说应该把侧重点偏向技术，我不知道。所以我唯一能做的就是全力以赴，努力的做好手头上的每一件事情，争取...变的更好、更优秀。

不想写了，睡觉！

--------------

年长些就会发现，记忆是非常不靠谱的，脑子里的能装的东西就那么多。以前我能清晰的记得大学里发生的很多事情，但现在一两个月发生的事情都已经完全记不清了，可能是大脑的选择性遗忘吧。这一系列文章我还是会继续写下去，尽管写的时候会有诸多不适，但，愿多年以后，想回忆起这段经历，还可以有文章可翻。
