#+SETUPFILE: ~/site/tpl/youth-tpl.org
#+TITLE: 在西农-S10：摇滚(2)

** 启蒙（续）

在听了许巍以后，和杨溪聊的就有了更多的话题，了解之后，我才发现他是一个无比真诚的人，很多想法都很原始、很纯真。

聊的多了，才发现喜欢的音乐竟然如此的一致，从周杰伦到张宇、伍佰、王杰、beyond 都有很多话题可以扯等等。你会发现，真正喜欢音乐的人，对音乐类型都是很包容，而不是非黑即白。但是，有一些人不是的：比如说喜欢摇滚的人，鄙视流行和民族音乐；
喜欢小众音乐人，鄙视所有大众被商业包装的音乐人；喜欢古典的人又鄙视摇滚。在各种风格里都很优秀的音乐人，优秀的作品，如果给自己加了标签，相当于固步自封，这个话题，后面谈。没多久，我接触到另外两个歌手：郑钧和朴树。

许巍、郑钧、朴树，这三个应该就是我摇滚音乐的启蒙。什么？他们也能叫摇滚？滚犊子。

杨溪是很喜欢朴树和许巍的，而我对朴树其实并没有太大的感觉。虽然许巍的音乐、许巍这个人我都很喜欢与敬佩，但是风格和嗓音上我更喜欢郑钧一些，更直接。我觉得郑钧比许巍更燥、洒脱一些，那个时候的我需要这个。尤其是在家养病的那段时间，听郑钧的沉溺的一塌糊涂。

*喜欢一首音乐、喜欢一本书、一句话或者一个人都是一样的，不是她本身有多少优秀（也许在别人眼里一文不值），而是在你最需要时候，她恰如其分的出现在了你面前，她能懂你的开心与落寞。于是：她影响了你，而你，被她改变了。*

** 90 年代的摇滚

#+begin_quote
梦 缠绕的时候

在我眼中

昨日的痛楚如音符

静静地飘过心中

像烟雾弥漫

想回味坚强的渴望

你能否感到这迷惘

让我痛楚让我欢畅

让我的双眼蒙上

尘封的幻想

超载《梦缠绕的时候》
#+end_quote

这应该是我听超载的第一首歌，感觉真的好棒。从这以后，开始逐渐找各种摇滚音乐听的旅程。国内搞摇滚的人的嗓音，我最喜欢的有两个：一个是超载的主唱 高旗，另外一个是达达的主唱 彭坦。尽管后来遇到了各式各样的乐队，我依旧觉得他们两个嗓音是最干净的。

超载乐队，成立于 1991 年 10 月 31 日。高旗担任主唱兼吉他手，李延亮担任主音吉他手。得特别介绍一下：李延亮，他号称中国吉他的第一人，中国早期的摇滚音乐他都担任吉他手，也是许巍演唱会的御用吉他。
当时还有一个很厉害的吉他手，唐朝老五（刘义军）。不过国内的摇滚毕竟时间太短了，和国外的吉他大师相比还是差的太多了。

代表作品：《梦缠绕的时候》、《每次都想拥抱你》、《低下头是人间》 等。

高旗的唱功在圈里算是很优秀的，05 年的不插电摇滚就是最好的证明（没几个人歌手敢这么玩的）。大学的时候在优酷上看过，当高旗把手一挥的时候，台下的观众都燃起来了。我找了几个视频（还有些找不到了）留作纪念吧。高旗超载乐队 不插电（05年）视频：

+ http://v.youku.com/v_show/id_XMjUxMTc3Mjk2.html?f=6037153&from=y1.2-3.4.2
+ http://v.youku.com/v_show/id_XMjU3NDM4MTIw.html?f=6037153&from=y1.2-3.4.3
+ http://v.youku.com/v_show/id_XMjU3NDU5MzIw.html?f=6037153&from=y1.2-3.4.4
+ http://v.youku.com/v_show/id_XMjUxMTkxNTUy.html?f=6037153&from=y1.2-3.4.5

中国的摇滚在 90 年代的时候是萌芽时期，这也是为什么国内的摇滚乐队一直都很难区分出具体的风格的原因，发展时间太短，大部分还在尝试风格当然定不了。然而90年代的出现了很多优秀的摇滚乐队，也是中国摇滚最鼎盛的时期。

杨溪在大学的时候偶尔会买《我爱摇滚乐》，我听过几次，感觉他们真的是「为了摇滚而摇滚」，这句话用来形容当前的摇滚现状再合适不过了。现在的摇滚乐队差不多都是伪摇，无病呻吟。如果你想反驳的话，麻烦在你喜欢的摇滚乐队的作品挑出 10 首传唱度高一点的音乐，
10 首算多了，5 首？不说别的，迷笛、草莓压轴的那几个乐队，痛仰算不错的了吧，好听的有手指头都可以数出来了。唱来唱去就那么几首歌，甚至好多歌手、乐队几年里都唱那么一首歌。

国外有个成就奖叫摇滚名人堂（Rock and Roll Hall of Fame），其中一个标准是：被提名的时间必须距离首张专辑发行 25 年以上。 Green day 都 10 来张专辑了，我们连 10 来首歌都凑不齐。我们比国外晚了有 50 年左右，我感觉再有个 50 年也追不上人家。
一方面是因为文化的差异太大了，Green day 可以出 《American Idiot（美国白痴/美国傻逼）》这样的专辑，赤裸裸的抨击政治，还大卖，在中国这种事情，我不敢想······；另外一方面，我们搞摇滚的人的素养太低了，现场就是一群地痞流氓，装B、耍酷。
赚不到钱算了，还非要标榜自己小众，玩音乐，没钱还搞个P啊，国外哪个摇滚乐队不是赚的盆满钵满的。Linken park 今年来中国开演唱会，随便哪一场不是爆满。给我们自己的乐队开个演唱会，就算人满了，你都唱不了 2 个小时啊。
温饱问题都解决不了，不无病呻吟才怪呢。恶性循环。

地下摇滚这次词本来就是病态，我感觉除非有一天大部分乐队都从「地下走到地上」，赚了钱，有了更好的创作环境，才有可能做出更优秀的音乐。也就是说当我们的摇滚乐队停止在自己的圈子里意淫的时候，当更多的人开始了解接纳了他们的时候，我们才能真正的开始。
不是我刻意抨击，而是我爱的深沉啊。

下篇文章介绍几个 90 年代的乐队。

文章里所有提到的乐队以及他们的音乐，我会整理成专辑：

+ 中国摇滚丶许巍（壹）：http://music.163.com/#/playlist?id=138165255
+ 中国摇滚丶许巍（贰）：http://music.163.com/#/playlist?id=139572583
+ 中国摇滚丶超载：http://music.163.com/#/playlist?id=141984836

张杰

2015-12-25
