#+SETUPFILE: ~/site/tpl/youth-tpl.org
#+TITLE: 在西农-S16: 毕业碎语

以前承诺要一天更新一篇把这一系列写完，然而过程没有我想的那么简单，回忆并不是一件让人很痛快的事情。不管怎么说吧，总算是把在学校的这段经历写完了，这篇 [[http://www.cnblogs.com/chinazhangjie/archive/2012/07/01/2572092.html][文章]] 是我毕业的时候写的，全文引用。

另，后面的在北京和在上海，只会更新到博客，不会更新到公众号了；公众号，我争取写一些职场和技术类的文章。

** 毕业碎语

+ 作者：独酌逸醉
+ 时间：2012.07.01

早就想写写最近这一个月的，一直在忙着毕业，事情繁杂，静不下心来。到家了好几天了，今天连上网了，决定随便写写。

我 5 月二十几号从公司回到学校，具体时间什么时间忘了。原本计划回到学校好好毕设，顺便学点技术。想必很多人和我的想法是一样的吧，呵呵！回到学校之后，基本上就天天打游戏去了（dota），天天开黑。宿舍胖子和祥子都没回来，胖子是开学还没回来，祥子是在北邮研究生复试之后回家了。只有锋子淡定的一个人在学校打 dota，冲 1500 ，不过我回去他就不寂寞了。我回去很多人还在公司，班里面没几个人，打球也就没啥人。月底大部分人就都回来了，WM 还坚持在公司到五月中旬。

每天和 YX ，DZR, WM 他们吃吃喝喝，打打篮球。日子过的还算挺快，等学院开始催毕设论文的时候，我才有些急了。氛围就是大家嘴里天天喊论文，也没什么人行动。到最后，我也不知道论文怎么来的，就已经开始天天改格式了。大一学的排版，现在都忘的差不多了，排版遇到的问题要比写论文还要多。

转眼就答辩了，原本在我心中神圣的毕业答辩，等我知道真相后，彻底颠覆了。这就是传说中的坑爹啊！答辩结果是怎么样的，都已经不重要了，只关心的过于不过。其实大家心里都明白，学院都会让过的，事实上也是如此，好的未必分高，差的最后也都让过了。

最后几天时间过的飞快，不知不觉一天就过去了。送书、卖书、卖东西。吃饭，喝酒，吃饭。转户口、转档案。体检。我想着，这一切顺顺利利的结束，我拿我的毕业证、学位证去公司报道，开始我的职场打拼生活。

天意弄人啊，体检的时候照了个 x 光，照完之后那么医生MM问我得没得过结核，我说没有啊，我都不知道结核为何物。她让我去示范区医院做个胸部 CT，随后的几天我就一直奔波在学校和示范区医院之间。具体过程我就不说了，结果是我确诊得了肺结核！每天的生活让我有种，拿起来一个啤酒瓶然后找一块大玻璃使劲砸去。现在的医生 TM 是看病的吗？！毛 TM 都不懂，就知道去做这种化验，也不跟你解释为什么。最让我郁闷的是，我身上不痛不痒，怎么就病了呢？！肺结核不是传染的么？为什么我们宿舍人都没事，大家都很正常？！我怎么就病了呢？！我一直不明白！

校医院找我谈话，大体就两点：1.赶紧治病；2.少和别人接触，别传染给别人。这两点，都让我很纠结。第一，治病。医生说病很好治（坚持吃药就好），但是需要至少半年时间。半年意味着什么？工作怎么办？FUCK ！第二，少接触。要毕业了，少不了聚，以后大家在一起的时间越来越少了。聚一次少一次，我怎么能不去呢？我怎么可以不去呢！那段时间我很烦躁，但是又不能和别人说，因为我也不知道到底会不会传染给别人。临近毕业了，搞的人心惶惶，不好！后面的两次班级聚会我都没去，以及后面的散伙饭，我也没去。我想对大家负责一点比较好，都是要出去工作的人了，万一传染给别人，后果很严重。每次晚上想想，眼泪不自觉从脸颊划过，我一直以为自己很坚强，没想到，等真正遇到事了，原来自己这么脆弱。

28 号我就走了，27 号和我们宿舍人还有剩下的一些人一起吃了饭，喝了很多。我心里不痛快，很不痛快。可以看出来，大家心里都不是很舒服。吃完饭，WLB叫上去喝酒，我们都过去了，玩了一会，决定去唱K。没几个人有心情唱K的，本来打算唱通宵的，唱了一会，都困的不行了。几个人喝多了，都躺着睡了。晚上两点多的时候，都回去了。我早上 8:30 的火车，还没收拾东西。加上蚊子咬的受不了，第二天不到六点就起来了。上了会网，收拾了收拾，时间差不多就走了。祥子送的我，给 ZQ 打了个电话，就走了。走到门口，回头看看西农的大门，感慨万千。

一路上的火车，怎么都提不起精神来。病+毕业季，很难让人开心起来。稍微想想，总想哭，从没感觉自己如此脆弱过。什么都来得及买，加上酒喝的胃里面干的很难受。真是揪心啊！还好有我妈，有ZQ，有CX。聊着天，时间会过的快一点，谢谢她们。

在家待了两三天了，心情稍微好了平复了一些。偶尔想想，还是觉得有些不爽。这半年时间，我需要好好规划一下，怎么去度过。不写了吧！

今天看了一篇文章，里面的一段话说的很好，分享给大家看：

「每一次深刻的认知，都意味一次痛苦的洗礼。当时身处其中的滋味，正如炼狱一般的折磨，本能的痛恨自己的无知、无能，更加剧了生不如死的感觉。可是，一旦意识到错误在哪里，重新确立生的方向，我就要毅然决然的和过去的自己挥手道别，选择重生。恰如曼德拉说起获释出狱当天的心情：“当我走出囚室、迈过通往自由的监狱大门时，我已经清楚，自己若不能把悲痛与怨恨留在身后，那么我其实仍在狱中。」
