#+SETUPFILE: ~/site/tpl/youth-tpl.org
#+TITLE: 绝版青春-序

#+begin_quote
他们总说 年少轻狂 一切都像走马看花 ——信《我记得》
#+end_quote

**WHY**

快过生日了，其实我每年是不过生日的，甚至对每个节日都不怎么感兴趣，我不喜欢热闹。今年不一样，特别想给自己一个交代。

往年对这些日子没感觉，可能是自己不在乎自己的年龄，年少无畏。到了今年，我突然觉得很多事情都变得急躁了起来，也许是因为自己年龄到了，24 岁和25 岁的感觉真的是不一样的；又也许是工作近 3 年了，依旧一无是处的彷徨；
又也许是一起毕业的同学，周围的人，都在忙碌，都在改变自己，想方设法的「适应」着这个社会。而我，一直迷茫，一直彷徨，心里却又不知道坚持着什么东西，自己和自己生活的犟，和周围的人犟。个性也好、叛逆也罢，有的时候甚至我自己都不明白自己在执着着什么。

13 年的 7 月份，我写过一篇文章 [[http://www.perfect-is-shit.com/yuehun-upcasting.html][乐魂转型]]，最可能代表自己这些年的心境:

#+begin_quote
杨溪不再摇滚了，不再亢奋了，不再是那个惆怅和愤青的少年了。我心里有些矛盾，总归是该开心还是不开心？有些青涩的酸酸的感觉，不知道该怎么形容，也许你们不会懂的。
...
如果有一天我也被同化，不再愤青，那将是多么可怕的一件事情。
#+end_quote

2 年以后的今天，我对很多事物有了新的认知，不那么「亢奋」，心里也不像当时那么「愤青」，并没有觉得多么可怕，而是欣然的接受了这一切，没有无奈，没有悲伤。
这之前和这之后的区别在于，以前我与社会环境抗争，与周围的人抗争；现在我只想与自己抗争，让自己变成一个优秀的人，做自己喜欢做的事情，让自己的生活乃至人生变的更有趣、更有价值、更有意义。

我记得，大学有个心理学老师，说过这样一句话：“女人的成熟，可能需要很长一段时间；而男人的成熟只需要那么一瞬间“，我跟很多人讲过这句话，只到这段时间才真正的懂了这句话的含义，可谓后知后觉。

我真的很感激能到合肥有这样一段经历，能让自己想明白了很多事情，以前我觉得自己生活、工作做的还不错，现在觉得自己才刚刚开始，因为只有方向正了，才算开始。我也尝试着去改变一些自己的性格，改变自己一直以来的习惯等等。
我想每个人都会有这样一个过程，从彷徨、迷茫到了有了方向，只是我比较笨，花了7年的时间才逐渐了找到了自己的可能的人生方向。

今年 10 月份到合肥之后，在公众号写了一篇「在合肥」的日志，后来觉得还不错，每隔两周更新一篇在合肥（系列），目前为止一共四篇。

我喜欢写东西，有一天我突然就想为什么不早点做这些事情呢？！如果把自己的思考，自己的生活经历写成一部小说，10 年，20 年，一辈子……也是一件很赞的事情。

于是，我觉得我需要把之前七年的欠的先补上，作为这部小说的第一部，在合肥以及在我结婚之前作为第二部。

**HOW**

7 年我打算拆分成 3 个系列，在西农（4年）、在北京（1年）、在上海（近两年）。

其实在做这个决定之前，我很犹豫。时间长了，很多事情都忘了，怕自己写不到自己想要的效果，这是其一；
我们周围的一些人，总有一些是自己的喜欢的，有一些是自己不喜欢的，写出来总会涉及到个人隐私，这是其二；
回忆是一件很累的事情，有些事情我不想去想，更不想写出来，这算是其三吧。

后来，我和郑媛聊过自己想写一系列大学生活的文章，并说了自己的顾虑，她表示支持，说我想想怎么写就怎么写，不要想那么多。其实，想想也是，只少一根主线，否则真的就乱写了。

我曾经有一个念想，是把自己喜欢的所有音乐全部收集起来，想什么时候听就什么时候听，后来这个想法在一番挣扎之后破灭了；我曾经有个念想是把为中国摇滚写一部历史，到现在都没有实现过……

看我文章时间长的人，应该知道我是很喜欢音乐，喜欢摇滚。其实我这几年的变化完全符合自己对摇滚的不同理解（这让我想起了许巍和杨溪），这三个系列我会穿插很多中国、国外摇滚以及摇滚人，也算是实现了自己的念想。

文章的几大配角，我已经挨个征求了同意，所以出现有很多真名，真实地故事。涉及到的人，我会用拼音或一些外号代替，尽量不扯别人的隐私，故事和音乐为主，人为辅。

张杰

2015/12/13
