#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 思绪飘零：我羞涩的写了一款主题，MusicSoul
#+DATE: 2012-12-02 17:21:17

在给我的技术博客写一个 wp 主题以后（确切的说是改的），想着给音乐博客也写一个主题。怎奈期间思想扭曲变异程度令人发指！

萌生写主题这个想法在乐魂建初就有了，在技术博客之前就想做了，毕业之后学 HTML, CSS 也完全为了乐魂的新主题，当时有了很多想法，
也有千百种想象飘荡在脑海中。后来发生了一些不开心的事情，我几度颓废，持续了长达几个月。把乐魂也交给了星星沙同学，我找不到坚持下去的理由。

几个月之后吧，我不舍得放弃，又开始构思主题，又怎奈...大脑空白，原先想过的种种瞬间消失了。就这样写一半扔一半，怎么说呢，
还是没有一个很好的想法。不想做的时候就去打 DotA 了。这种日子持续了好久吧（将近一个月的样子）。

我记性很差，但是敏感度很强，也就说有一些事情一旦记住了，很难忘记；但是通常大部分是记不住的。
忘了是哪一天了，应该是上上周吧，我翻了翻博客，看到了以前写的一篇文章：[[http://www.perfect-is-shit.com/2012/07/27/zzjxzd/][做自己想做的]]，突然有一种莫名的想抽自己的感觉（只是想，没有实施），
然后眼睛湿润了。于是乎，我就硬起头皮开始为 [[http://www.yuehun.in/][乐魂]] 写主题。

* 思维定式
   :PROPERTIES:
   :CUSTOM_ID: 思维定式
   :END:

一时间没有想到自己想要的感觉，但是我强迫自己一定要写。wordpress 主题的架构不外乎就那么些文件（这次的主题和上次不同，
这次是完全一行一行代码敲出来的）从 =index.php= 和 =style.css= 一步一步的来，很快架子就出来了。
那么面临的问题就是我要什么样的感觉？总想着音乐博客、音乐博客，陷入了自己给自己的一个囹圄，难以自拔。因为 wordpress 就是为博客而存在的。
一直思考，应该用两栏、三栏还是单栏？一直难以下手。

后来我把侧重点放在音乐二字上，而弱化了博客。我想别人来这个网站，是来听歌的。网站一直存在一个很大的问题就是想听一首歌需要不断的点啊点，
连续播放是实现不了的，至少对我来说。不过放一个背景音乐倒是可以的。就抱着这个想法，我开始慢慢的构思。

* 设计
   :PROPERTIES:
   :CUSTOM_ID: 设计
   :END:

一直在我的眼里，想永远要比做要重要的多。这个社会从来不缺乏劳动力，乃至高执行力的人也不是不缺的，缺的是好的想法、好的创意。
请不要跟我辩证这个问题，因为毫无意义（注意我的措辞就好）。

一开始我想的是主页要有 背景音乐一栏，最新发布音乐，随机音乐。当然博客题目，副标题，菜单栏，sidebar，footer等等。
颜色的设计也考虑许久，选择了一套视觉效果不错的色系。就这样我去做了，整合到一起，我瞬间就感觉做这个主题开发是多余的。之后我就在考虑那些是不必要的，
那些是必须的。不是必须的就直接删除，后来发现只剩下背景音乐、随机音乐、最新发布音乐。其他的都让我删了，我的原则是音乐，与音乐有关的留下，
其他的全部删。越删越看着舒服。再后来就没什么了...都让我删了。

最后首页剩下四栏，一栏背景音乐，一栏最新发布音乐，一栏随机文章，一栏 footer 。布局完之后配色，按照色系配色。期间费了很长时间，这里一笔带过。
之后上传 ftp，看了一下效果。我只能说平淡无奇。下面是效果图：

/图丢了/

整体感觉太平庸，没什么亮点，也没有视觉冲击。我记得刚写完 keepsimple 这款主题的时候，我有些 crazy，可是这次没有。
于是我就明白了，这不是我想要的。每当我遇到我自己特别喜欢的东西，或者突然灵感一动的时候，我会不知所措的开心，开心好久（尤其是对好听的音乐）。

* 再设计
   :PROPERTIES:
   :CUSTOM_ID: 再设计
   :END:

再设计是几天之后的某天下午（好像是前天吧），我可以说是想了一个下午，想到头疼。网站的标题区我是模仿这个网站的：http://designlol.net/
感觉还不错。我不喜欢平庸，喜欢走极端。背景使用黑色算是一个表现吧，其他颜色的选择都是缘分，很巧我用美图秀秀偶然间觉得挺不错的，
放上去感觉还真的是挺不错的，嘿嘿。总体的格局算是一个突破吧。整体的感觉有了以后，后面的硬编码就很简单了。下面是效果图：

/图丢了/

上传到 ft p以后，看效果之后，我发了一条微博说："从现在看，才觉得乐魂像是一个听音乐地方"，也确实，有了一些音乐气息。
这不能算一个好的设计，但对我个人来说，算是一个突破。

灵感很重要，大胆的尝试很重要，缘分也很重要。

* 技术
   :PROPERTIES:
   :CUSTOM_ID: 技术
   :END:

为什么文章的最后才提到技术呢？不重要吗？不是的，但是我想说技术始终是一个工具。这次开发过程中，技术点是有的，但是我想说的不多。
技术不懂可以学，可以查资料，可以咨询别人。但是设计的灵感呢？

--------------

现在已经是 2012.12.03 凌晨 1:03 了，我喜欢晚上，晚上的头脑会清晰些。零零碎碎写了不少了，可是还有很多东西没有写出来，那就不写了吧。
思绪飘零一系列文章我已经写了不少了，今后还继续写。出于这两个目的吧，首先是记录，记录自己曾经的一些想法和经历过的往往；
同样希望当你看到这些文章以后能给你一些不一样的启示和灵感，这样我也不枉我玩命的扯淡了。

好了，本文到此结束，今天送上一首好听的歌曲：[[http://www.xiami.com/song/1769324580][Space Cowboy - Banaroo]]。晚安！
