#+SETUPFILE: ~/site/tpl/site-tpl.org
#+TITLE: 至简的 wordpress 主题：keepsimple
#+DATE: 2012-09-29 12:19:00

给我自己博客写主题这个事情蓄意已久了，从去年申请域名买空间的时候就想做，转眼快一年了。换了很多主题，都太过花哨了，我不喜欢花哨，尤其不喜欢什么功能都有主题。之前的主题
[[http://www.neoease.com/inove/][inove]]
其实是一款很不错的主题，很多人都在用，适合技术博客，但是达不到我想要的效果。今天上半年就开始折腾HTML，后来学了点CSS，但是没怎么上心。我始终觉得写博客主题需要了解的东西有些多（HTML,CSS,PHP,Mysql），以至于不敢下手，算是一种逃避（太繁琐，我非常不喜欢数据库）吧。

有些兴奋，所以文章可能有些言语胡乱，请见谅。我做事、说话不愿意循规蹈矩，不喜欢走套路，喜欢直截了当，喜欢随性而为。

我想要的博客主题应该具有哪些特点呢？简单，嗯！这是首要条件。作为一个博客，尤其是技术博客，首先应该做的就是把文章（技术）的内容完全展现给读者，所以展现博文的时候就不应该有其他的。其次，紧凑，不能松松垮垮，看不到主旨。再次，颜色选取，有一些博客看第一眼觉得很不错，但是文章内容看不了，看一会眼睛会非常累，感觉很不舒服。所以一款好的主题应该让读者看内容时不会眼睛疲惫。最后一点，是针对我们IT行业而言的，宽度不能太宽，也不能太窄。太宽或者太窄代码列出来都会非常不舒服。

我看过很多技术博客，很少有上眼的主题，没有我想要的效果。但是，有一个，[[http://blog.codingnow.com/][云风的博客]]，完全符合我的要求，和我想要的效果几乎一样。大家可以看到我这个主题和他的主题非常类似（其实只是看起来像，细节差距还是很大的）。

昨天花了一天时间，终于搞定了，在颜色选取上费了很长时间，尤其是背景色（现在这个背景色是
EMACS
一个主题的背景色），一开始想做一个单栏主题，把文章目录、归档、声明等放到菜单栏里面，后来发现放上去之后，显得顶部很臃肿。后来还是用了两栏，但是点开文章之后，是一个单栏的，我很喜欢这种方式看文章，没有杂项打扰视觉。颜色选择我没有用亮色，因为我感觉亮色看着很累，文章字体颜色是接近黑色的一种颜色，我发现这种颜色和背景放到一起很舒服。

不得不说的是，主题不是我手写出来的，是我改的。这个主题的原型是 wordpress
default 主题。我做了两件事情：

- 改 CSS，之前的 CSS 构造很奇怪，我重新调整了一下位置。CSS
  基本上每块都改了。
- 删 php 代码。我删了很多 php
  代码，一些看起来很强大的东西，在我看来我根本不需要，我就删了。比如在主页显示每一篇文章的归档、标签，我觉得没用，加上之后感觉主页东西很杂。我不懂
  php，但是可是猜出来大体。

我在主题里面说了，keepsimple depend on kubrick, changed by Jerry Zhang.
不敢居功，因为这是别人的劳动果实，我唯一能够做的就是在此声明，然后把主题免费送给喜欢的人。

关于主题的名字，我选 keepsimple 的原因是：

- 这是我设计的理念，simple；
- 这是我为 http://www.perfect-is-shit.com/ 专门打造的主题；
- 时刻告诫我自己，要 keep simple，切忌繁琐。

顺便说一点，改主题不需要很多技术，我以前就处于这个盲区。懂些 HTML 和 CSS
就可以搞定的，下载一个 =xampp-win32-1.6.2-installer.exe=

可以本地测试。网上也有教程可以参考，果断去改吧，没那么复杂。

** 2018-11-19 22:03:18 更新**

Github repo 地址在：[[https://github.com/zhangjie2012/keepsimple]]

现在做技术用 Wordpress
搭建的不多了，这是我五年前的折腾，今天把相关的几篇更新日志的博客给删掉了，这篇留着当做回忆吧。
