#+SETUPFILE: ~/site/tpl/weekly-tpl.org
#+TITLE: 2019-01

** 2019-01-31 14:18

这么多年了，听着音乐，写着代码，依然是我最喜欢的时刻。

** 2019-01-30 15:40

文档这种东西，真是个双刃剑。以前对公司文档化比较推崇，现在不这么觉得了，那些文档要写那些不要写，还真不好界定。

说这些是基于：写文档是比较简单的，但是文档维护是比较难的，维护成本很高。文档的价值在于说明，但是如果说明不能实时的跟着变化走的话，意义也就不大了，造成的困扰很不小。

** 2019-01-30 11:15

QQ 音乐 Mac 版本做的真的是垃圾，各种 Bug，估计产品的产品经理自己都没在用。相比网易云音乐真的弱爆了。不相信腾讯没有能力做好，这是态度问题。

btw，不知道腾讯内部 QQ 和 微信 是不是存在很严重的政治斗争，很多产品设计到 QQ 和 微信双账号的地方做的都很差。

** 2019-01-29 18:02

嘿嘿

** 2019-01-29 10:52

相比 Ant Design Pro，antd 就克制的多了，希望可以坚持。

** 2019-01-28 09:35

连续过去三辆 193 ，智障啊

** 2019-01-25 09:47

今天去看病，不知道是遇到庸医还是神医，一句话没问，把脉听诊，开药了…

** 2019-01-24 16:54

测了几年了，性格测试一直是 INTJ，?

** 2019-01-24 14:38

花了一个下午和一个上午的时间，总算把 Pro 无关的代码删干净了，把权限这块搞明白了。

shit。

** 2019-01-24 10:50

Ant Design Pro 似乎更新从来不考虑兼容的···

每次 clone 下来都是一个崭新的项目，我尼玛。

** 2019-01-23 17:23

阿里的 Ant Design Pro 权限认证这块代码写的跟屎一样，或者说屎都不如，没见过这么晦涩的代码。
使用 Pro 从 0 到 1 搞过 3 个 Project，每次都在这块费很长的时间。

** 2019-01-23 09:43

感冒了?

** 2019-01-22 14:33

做技术有什么好玩的，做产品好玩，折腾数据才好玩

** 2019-01-21 17:46

http://app.programmingfonts.org/

这个网站不错啊！

** 2019-01-21 16:45

是不是应该没有任何功利性的学点、做点事情？

BTW，当然是业余时间。

** 2019-01-21 15:31

说点什么呢？

** 2019-01-21 13:14

http://microblog-1252349778.picsh.myqcloud.com/2019/wuzhen.jpeg

** 2019-01-18 14:33

如果有个程序员疯狂的按键盘，发出咔咔的声音，他其实可能没做什么，只是在保存（ Vim :w）。

** 2019-01-18 08:47

恭喜马良，真不容易啊。

** 2019-01-16 22:44

混着也挺好?

** 2019-01-15 15:42

一开始写爱车店的时候，我也没咋用过 Django，没写过 Web server，现在想想很多地方设计有些想的复杂了。

** 2019-01-15 11:32

看来我要尽快做手机适配了！

** 2019-01-15 11:31

我擦，Django admin 手机端适配的很不错啊，省事了。

** 2019-01-15 11:27

新专辑 心中的歌谣，一副弹起我心爱的土琵琶的既视感···，醉了。

还是只有爱好听。

** 2019-01-15 11:27

是不是要写一个手机端的服务，用来发布微博？

** 2019-01-14 11:02

昨天看了张小龙 2019 微信公开课，简述微信 8 年。将近四个小时，视频略长，但是对于一个经历 8 年的公司来说，四个小时还是太短了，相信张小龙是意犹未尽的。

我不想说明从视频那里得到了什么，而想说另外一个事情：做产品、做技术的价值观。

我记得 2015 年 10 月份去七行之前，跟肖峰说过：作为一个做技术的，应该做一些真正有价值的，方便大众的事情出来。那个时候，我一直坚信这个观点。

可是经历了七行两三年的时间的经历，加上离职后一年的思考，我发现我已经不再抱有之前的那些想法。更加的注重结果，而不是过程；更加的关注于利益的得失。因为我曾经想把用户当成人看，想要做好的产品出来，却处处碰壁，以至于我开始质疑自己是不是对的，而业内的大部分产品也是不把用户当人看的，比如今日头条，抖音，百度等产品，或者说大部分产品都是这样的，注重流量，注重变现，而没有职业道德，所以不得已我也变成了他们。

现在想来，我很庆幸，我并没有依靠这些捞到一桶金。如果真的依靠这些捞到金了，那我们自然而言会觉得这么做的对的。

看了张小龙的演讲，我才知道了，原来我的思路是没有错的。互联网是用来方便人的，为人提高效率的；是人来利用互联网产品，而不是互联网产品来驾驭人。

万物之中，希望至美。

** 2019-01-14 10:46

相比而言，我更喜欢微博的方式表达，而不是博客。微博让人觉得轻松，而博客则「非要表达出什么」让 人感到压力。

** 2019-01-12 15:09

上手容易的语言，通常很难更近一步，大家都会写，但是高手很少。比如 Python，Go。

上手难的语言，掌握也就掌握了，门槛高，针对语言特性的介绍和使用场景也就多，比如 C，C++。

** 2019-01-11 22:32

http://microblog-1252349778.picsh.myqcloud.com/2019/20190111.jpeg

感谢 磊磊 赠书。

看完 SRE 就看这本。

** 2019-01-11 14:09

在没有能力改变的时候，还是应该做好自己的本职工作，做好每一件小事。

** 2019-01-11 11:47

想清楚再写有多么重要

** 2019-01-08 14:51

打游戏时间过得真快，什么都没干，很空虚，但是过程可真快乐啊。

-- 元旦三天假

** 2019-01-02 22:56

2019 年要对自己狠一点，也要对别人狠一点。少说话，多思考，多做事。
