#+SETUPFILE: ~/site/tpl/weekly-tpl.org
#+TITLE: 2019-02

** 2019-02-28 21:48

在来回合肥的途中，看完了 上瘾: 让用户养成使用习惯的四大产品逻辑，在亚马逊 9.9 买的电子书，所以不知道薄厚程度，花三四个小时就能读完的书想必不会厚的。

内容很不错，举的的例子都是我们所熟知的公司，谷歌、Facebook、苹果、instagram 等，所以比较好理解。看完之后，今天又在京东上买了纸质书，这本书值得收藏，并定时翻阅。

btw，路途中带个 Kindle 体验还不错，虽然我更喜欢阅读纸质书一些。

** 2019-02-28 18:29

剑未佩妥，出门已是江湖。千帆过尽，归来仍是少年。

** 2019-02-28 18:32

是谁来自山川湖海，却囿于昼夜 厨房与爱。

——万能青年旅店《揪心的玩笑与漫长的白日梦》

** 2019-02-28 17:24

用 kubectl 手动删掉了一个空间，好紧张~

** 2019-02-28 16:58

每次用 mongodump 和 mongorestore 都能惊出一身冷汗，设计太不人性化了。

** 2019-02-28 09:55

努力不是为了攀比，不是为了证明什么，只是为了让自己变强。


** 2019-02-26 20:18

我们通常会以为互联网的优势在于花样翻新，但其实人们只想在网络上继续做自己熟悉的事情。

伊万·威廉姆斯

** 2019-02-26 19:52

值得注意的是，尽管一些人会将“习惯”和“成瘾”混为一谈，但它们是截然不同的两码事。成瘾 指的是长期且被动地依赖某种行为或是某个东西。依照定义，成瘾最终会使人走向自我毁灭。因此，生产让用户成瘾的产品是不负责任的表现，因为这等同于蓄意伤害。

相反，习惯可以对一个人的生活产生积极的影响。习惯有好有坏，而你的每一天都有可能重复一些有益身心的习惯。

《上瘾》

** 2019-02-25 14:17

睡了好长的一觉，仿佛经历了很多事情一样疲惫

** 2019-02-24 17:34

眼界生于 2018-01-17，卒于 2019-02-24。

** 2019-02-22 08:55

已识乾坤大，犹怜草木深。

马一符

** 2019-02-21 16:30

悸动的心该平复些了。

** 2019-02-21 09:58

完了，要迟到了

** 2019-02-20 15:48

现在听后摇，真的脑袋疼

** 2019-02-20 15:19

写前端大部分时间都花在等待编译上了，艹。

** 2019-02-17 20:55

QWERTY 做了一个手机适配，现在可以在手机上完美的阅读了，棒棒哒。

** 2019-02-14 23:25

时间和经验一再证明，系统不但一定会出问题，而且会以没有人能够想到的方式出问题。

读 SRE - P137

** 2019-02-14 18:58

https://microblog-1252349778.cos.ap-shanghai.myqcloud.com/2019/IMG_20160422_171214R.jpg

那个时候真年轻。


** 2019-02-12 15:51

写了一年多的 Go，再回看 对 Go 语言的综合评价 可谓中肯。

Go 优雅比不上 Python，说工程比不上 Java，开发效率比 C 高，但是跟 Java 还有有距离的。

Go 更像是约束版本的 C，而不能类比 C++。不知道这算是一种进步，还是倒退。

** 2019-02-11 23:00

如果天空是黑暗的，那就摸黑生存； 如果发出声音是危险的，那就保持沉默； 如果自觉无力发光的，那就蜷伏于墙角，但不要习惯了黑暗就为黑暗辩护； 不要为自己的苟且而得意； 不要嘲讽那些比自己更勇敢热情的人们； 我们可以卑微如尘土，不可扭曲如蛆虫。

** 2019-02-11 10:38

2019 年开工第一天！

** 2019-02-10 17:29

开车回来上班，经历了现实中的人在囧途，走到高速口高速被封了，走着走着没路了，从下雪走到了下雨。

** 2019-02-06 23:03

飞驰人生，看着看着就哭了

** 2019-02-06 10:00

过年真无聊
