#+SETUPFILE: ~/site/tpl/weekly-tpl.org
#+TITLE: 2019-03

** 2019-04-28 10:03

https://microblog-1252349778.cos.ap-shanghai.myqcloud.com/2019/rock-category.jpeg

** 2019-04-19 14:44

在配色网站：https://mzohaibqc.github.io/antd-live-theme/

** 2019-04-10 14:24

GiB 和 GB 的区别？

GB 是十进制的容量单位（10^3=1000），GiB 是二进制的容量单位（2^10=1024）。

一般厂商的单位是 GB，用来形容内存，硬盘等容量，所以经常看到的硬盘容量比实际使用的容量要小，也是这个原因（其实本来就没那么大）。

** 2019-04-04 11:59

曾经我心中的执剑少年，此刻也混迹于市井之间。

** 2019-04-01 21:26

React Interview Questions & Answers

[[https://github.com/sudheerj/reactjs-interview-questions][sudheerj/reactjs-interview-questions]] 翻译：[[https://github.com/sudheerj/reactjs-interview-questions][semlinker/reactjs-interview-questions]]

** 2019-03-31 15:41

Every new Go developer should read http://talks.golang.org/2012/splash.article. It’s important to understand where the language is coming from, so you can work within that philosophy, rather than fight it.

via https://blog.rubylearning.com/best-practices-for-a-new-go-developer-8660384302fc

** 2019-03-31 14:56

相比做技术，我更喜欢做产品；相比沉浸在技术实现的快感，我更喜欢通过数据琢磨背后的原理和人性。

** 2019-03-31 09:57

成年人的幸福竟然是可以舒舒服服的睡一觉。

** 2019-03-30 09:07

早。

** 2019-03-29 17:11

使我有洛阳二顷田 安能佩六国相印

--苏秦

** 2019-03-29 09:47

每一刻都是崭新的。

** 2019-03-27 17:26

一生要走多远的路程 经过多少年 才能走到终点

梦想需要多久的时间 多少血和泪 才能慢慢实现

** 2019-03-26 14:10

To B or Not To B

** 2019-03-22 12:08

常与同好争高下，不与傻瓜论断长

** 2019-03-22 12:04

看，聪明人可真多啊

** 2019-03-18 17:51

费了半天劲给 Go 的 mongo-driver 提了一个 issue，结果发现是自己没重新编译，还不知道咋删除 issue，极度尴尬···

话说 MongoDB 为啥不用 Github 的 issue 做问题跟踪呢？

** 2019-03-15 11:36

迪克牛仔，真带劲。

** 2019-03-10 20:54

生活就是挣钱，买菜，做饭，洗锅，睡觉，如此周而复始，无趣至极。

** 2019-03-10 16:51

本想写一个 qwerty 的小程序客户端，想想还是算了，写这样一个小程序没什么技术含量，一两天的时间差不多就可以上线了。

时常忘了建站的目的是什么······应该把时间花在更有意义的地方。

** 2019-03-10 11:25

昨天两事记：

1. 喜欢吃的一家面馆倒闭了，尴尬
2. 看了电影《绿皮书》，好看，推荐

** 2019-03-07 15:53

这周末我要写一个小程序的 qwerty 客户端。

** 2019-03-07 11:09

突然还有点怀念在 热血 写 C++ 的日子。

** 2019-03-05 22:27

原文打算看完《SRE》就去看《原则》的，今天想了一下，还是先抓时间搞一下 Docker 和 K8s，毕竟吃饭的家伙事比较重要。

** 2019-03-05 10:44

昨晚把 SRE: Google运维解密 看完了，从去年的12月10日看到今年的3月4日，进度很慢，甚至后面都有点不想看了。简单评价这本书：

内容比较零散，前后衔接不大，是由谷歌内部的一些文章或者论文拼凑而成，像是一本工具书；阅读的时候不用从顺着看（从前往后），可以直接看自己关心的技术点；
书涉及到的面比较广，偏向于运维和工具，扩展视野是一本很好的书；也可以运维系统搭建的参考书，没事的时候翻一翻；
谷歌是一家牛逼的公司，从 实践 -> 方法论 -> 实践 这个严谨的过程值得让人尊敬。

个人感觉，SRE 理念或者说 DevOps 理念是非常好的，但是落地还是有些堪忧，一个是 Dev 和 Ops 技能和理念的差异导致本身就有些水火不相容的感觉；另外一个是 DevOps 收益自然是很大的，但是对于很多公司的成本是无法接受的，像谷歌这种规模的自然没话讲；还有一个是国内外 IT 企业差异导致了国内的很多 DevOps 徒有其表。所以，整体来看，DevOps 的推行还是有很长的路要走。

** 2019-03-03 14:25

新技能 get， =docker exec= 中的 =--rm= 和 =-d= 选项不能同时使用：

--rm 是启动之后立刻删除，可用于测试容器启动
-d 是指 daemon 运行容器

** 2019-03-02 10:58

已经为 Emacs 的 plugin 们提了不少 issue 了，好佩服它们的效率，人家的开源项目做成那样，我们的开源项目做成那样，啧啧。

有一说一，国内的大环境不好，且不说制作者怎么样，社区也不咋地。

不谈了，继续写 QWERTY，Let's Go。

** 2019-03-01 14:59

我为啥要一直较真呢？因为希望他们可以做的更好，有期望。

现在木有了，我继续做的「非专业前端」了，开心就好。

** 2019-03-01 14:57

Pro 觉得他们很大的一部分用户是专业的前端，但是让我有「专业前端」技能，我是不会用 Pro 的。

当然，专职前端 != 专业前端。

** 2019-03-01 14:54

看了 [[https://github.com/ant-design/ant-design-pro/issues/3143][Pro: V4 Next Big Version]] 的讨论，再一次对阿里做的开源项目有些失望（见之前的 [[https://github.com/ant-design/ant-design/issues/13848][彩蛋事件]]）。

不说阿里，就说 Pro 做产品的思路。说 KPI 可能他们会不爱听，但是「主题」这样的功能真的有这么重要吗？就说这两个回复：

#+BEGIN_SRC
这些范例是 Pro 的重要部分，主要是给中后台开发一些代码化的设计资产和设计参考，让那些没有设计师的产品也能做出水准上的设计品质。

切换主题是非常重要的特性，否则后台产品样式千篇一律，估计不会有人爱用。
#+END_SRC

我的天，看到这种回复，我惊呆了！

「没有设计师的产品也能做出有设计水准的设计品质」，把自己想的也太牛逼了，咋不去开学校呢！难道我用了 Pro 我就有设计水准了吗？几层关系都搞不清楚：

1. 脚手架和范例完全可以分离开，为什么非要做到一起呢？我没见过哪个框架是直接集成了丰富的范例，然后剥离花费了大力气，且不说你 1.x 和 2.x 还不兼容呢···
2. 脚手架的职责跟「设计水准」扯不上半点边，UI 库才是负责「设计水准」的

#+begin_quote
切换主题是非常重要的特性，否则后台产品样式千篇一律，估计不会有人爱用。
#+end_quote

产品样式跟切换主题有多半毛钱关系吗？难道换一换菜单位置和网站主色就会有很大的差距了吗。爱用不爱用产品难道是根据主题样式来决定的吧，搞不清楚产品的定位，把产品想的太伟大了。

不想跟他们争论了···，放弃了，不能对他们抱有太大的期望了···

反正我就是一个二流前端，我能怎么样呢，怎么设计怎么用呗。
