#+SETUPFILE: ~/site/tpl/weekly-tpl.org
#+TITLE: 2019-06

** 2019-06-30 12:22

Ubuntu 18.10 Emacs =javascript-eslint config file: missing or incorrect=

将 =flycheck-javascript-eslint-executable= 设置为包自己的 eslint，比如：

#+BEGIN_SRC
(setq flycheck-javascript-eslint-executable "/home/jerryzhang/qwerty-client/src/node_modules/eslint/bin/eslint.js")
#+END_SRC

环境相关的东西，真的太恶心人了

** 2019-06-29 23:00

看来不学 LISP 是不行了，不然 Emacs 配置上很多自己的想法实现不了。

** 2019-06-27 23:11

Error: npm ERR! write after end:

https://stackoverflow.com/questions/49148753/error-npm-err-write-after-end

** 2019-06-25 22:50

自己选的 Ubuntu，含着泪也要用下去。一天天净吓折腾了，一点正事都没干，正事不断的 delay 。

** 2019-06-24 18:41

排队上车这个事，有三四个人开始排队，大家都会排队，有一个人开始抢，大家就都会抢。

道理就不讲了，都明白。

** 2019-06-23 23:02

因为备案问题，网站迁移到香港了，明天写篇文章记录一下，

** 2019-06-21 10:20

你大爷，还是你大爷：

https://lkml.org/lkml/2019/6/13/1892

** 2019-06-20 15:22

晚上想把 gnome3 切换到 KDE，玩一玩

** 2019-06-17 21:47

Ubuntu 设置被我不知道咋给删掉了，安装回来：

#+BEGIN_SRC
sudo apt-get install gnome-control-center
#+END_SRC

** 2019-06-17 21:43

https://microblog-1252349778.cos.ap-shanghai.myqcloud.com/2019/elisp-first.png

写了一段 elisp，不同的系统不同的字体，可把我牛逼坏了，哈哈哈

** 2019-06-17 21:25

Ubuntu 启动速度慢调试：

- =systemd-analyze=
- =systemd-analyze critical-chain=

看了一下 docker 启动速度有点慢。

via： https://www.dedoimedo.com/computers/ubuntu-beaver-slow-boot.html

** 2019-06-17 11:42

ES6 遍历对象成员

via: https://gomakethings.com/the-es6-way-to-loop-through-objects-with-vanilla-javascript/

#+BEGIN_SRC javascript
var lunch = {
    sandwich: 'ham',
    snack: 'chips',
    drink: 'soda',
    desert: 'cookie',
    guests: 3,
    alcohol: false,
};

Object.keys(lunch).forEach(function (item) {
    console.log(item); // key
    console.log(lunch[item]); // value
});
#+END_SRC

** 2019-06-16 11:35

Ubuntu 上的一些小工具，真好用啊。比如 Peek。

** 2019-06-15 14:50

Ubuntu 好用的截图工具，flameshot，稍后整理文档。

** 2019-06-15 12:04

Ubuntu 下随机更换壁纸：variety 真不错。

#+BEGIN_SRC shell
sudo apt-get install variety
#+END_SRC

可惜网站都是墙外的，尴尬～


** 2019-06-14 17:18

工作到五年之后，也就是我这个年份，能在公司学习到的东西越来越少了。

刚毕业的学生，公司招你进来是看潜力，看没有培养价值，所以在公司会有人带你，会给你相对充足的时间让你去学习历练。

然而，有一定工作年限的人，公司找你进来的意图很单纯，就是创造价值，所以不会再给你充足的时间学习新的东西，最多给你一段时间熟悉代码，仅此而已。

所以，根据我这几年的经历，总结下来，单方面比较深入的人才，比通才要吃香的多，因为他们只需要对口就可以工作了，通才比较吃环境，如果环境没有发挥的空间就很难混下去。

另外一个角度是，毕业的前几年太重要了，越往后面留给自己学习技术的时间越来越少，也难怪很多人在公司混工资。其实也没什么办法，随着技术的积累，突破自己本来就越来越难，加上时间精力又远远不够。

拿我自己来说，以前工作之余想看花多少时间就能有多少时间，除非自己懒；现在呢，一天能抽出来一个小时看看书就很不容易了

** 2019-06-14 12:04

Go is the number one language on developers’ list for 2019, report shows

语言：

1. JavaScript 是 2018 年最大赢家，超越了 Java（Java 是 2017 年最流行的语言）
2. TypeScript 相比之前从 15% 上升到了 24%
3. Go 成了 2019 年开发者最期望学习的语言，除此之外是 Kotlin 和 Python

框架：

1. Angular 依旧是第一，紧随其后的是 Spring 和 React
2. 33% 的人表示想要在 2019 年学习 React
3. 招聘者最希望要的是 React，而应聘者拥有最多的是 Spring 技能

** 2019-06-13 10:34

Ubuntu mono 和 M +1m 也是一个中英文等宽的字体，可惜不等高。

** 2019-06-12 18:00

我发现 YouTube 上拍摄 Emacs 视频大都是使用 Ubuntu 或者 Linux 发行版的，而不是 MacOS，没见过用 Windows 的。

** 2019-06-11 22:36
用 ace-window 替换了 emacs-winum，emacs 可真好玩，哈哈。

快用上 ado-ado 全家桶了，ado-ado 牛逼

** 2019-06-10 18:08
#+BEGIN_SRC python
# 一个简单的方法将 django 变成一个 restful api framework
# 路由配置：
#   url(r'^res$', Resource())

from django.http import JsonResponse


class Dispatcher:
    def not_match_resp(self, req):
        return {
            'code': 1,
            'error': 'not match handler function, method={0}'.format(req.method)
        }

    def __call__(self, req):
        if req.method == 'GET':
            data = self.get(req)
        elif req.method == 'POST':
            data = self.post(req)
        else:
            data = self.not_match_resp(req)
        return JsonResponse(data)

    def get(self, req):
        return self.not_match_resp(req)

    def post(self, req):
        return self.not_match_resp(req)


class Resource(Dispatcher):
    def get(self, req):
        return {
            'code': 0,
            'data': 'hello, resource get'
        }

    def post(self, req):
        return {
            'code': 0,
            'data': 'hello, resource post',
        }
#+END_SRC
** 2019-06-10 10:21

文泉驿，在 Mac 下虽然丑了一点（其实也没丑多少，主要是我外接显示器是 1K 的，分辨率太低了，看着更丑）。但是中英文做的真的好，其它的字体：Source Code Pro，Fira Code，Hack，Monaco 等等宽没问题，等高都有问题，英文中文切换的时候，总会有跳跃的感觉，文泉驿没有这个问题。

** 2019-06-07 07:08

avy 跟 ace-jump 差不多

2019-06-11 21:22:52 update

已经用 avy 替换了 ace-jump，abo-abo 真是个牛人啊，开发了很多 emacs 插件，要不是我已经用 emacs-winum ，差点都想用 ace-window

** 2019-06-06 21:07

2018 年 8 月份到 2019 年 6 月份，房子总算搞定了。

** 2019-06-05 11:22
折腾了几天 Emacs，工作流切换了一下，感觉使用上比以前上了一个档次。总结下来：

心态很重要，不能固守残缺，要拥抱新的东西。
还是那句话，被很多人追捧的东西，一定有其独到的地方，要先尝试，再下定论。

** 2019-06-03 19:45

Ubuntu 下 wunderlist，https://github.com/edipox/wunderlistux

nice job。

** 2019-06-03 17:56

https://wiki-1252349778.cos.ap-shanghai.myqcloud.com/2019/TV21DgN.jpg

来自：http://i.imgur.com/TV21DgN.jpg

选择最适合你的发行版

** 2019-06-03 12:38

房子终于放款了，不容易。
