#+SETUPFILE: ~/site/tpl/weekly-tpl.org
#+TITLE: 2019-07

** 2019-07-31 17:17

真讨厌程序员写代码炫技，妈的，明明很简单的逻辑，非要搞的那么高大上，看起来费劲，写起来费劲

** 2019-07-30 16:27

我可真棒呀

** 2019-07-30 11:22

https://microblog-1252349778.cos.ap-shanghai.myqcloud.com/2019/wttr.png

emacs 天气插件 wttrin，不错

** 2019-07-27 19:43

最好的时光，老婆已经睡着了，我听着朴老师，写着代码，等待乐队的夏天。

** 2019-07-26 13:20

听故事的人可以感动，可以落泪，但是一定要记住那是别人的人生，不是你的。

告诫自己。

** 2019-07-25 22:36
#+BEGIN_SRC shell
export LSCOLORS=ExFxBxDxCxegedabagacad
#+END_SRC

让 ~ls~ 显示的颜色更舒适。

** 2019-07-23 23:03

http://getqwerty.org/ 上线了。

想做一个小程序的客户端。

** 2019-07-23 14:34

啥歌都不想听了，听过的听来听去没意思，没听过的都感觉不好听。


** 2019-07-21 15:31

昨天在桐庐：

https://microblog-1252349778.cos.ap-shanghai.myqcloud.com/2019/20190720-1.jpeg

https://microblog-1252349778.cos.ap-shanghai.myqcloud.com/2019/2019-07-20-2.jpeg

** 2019-07-18 09:32

三篇文章可以读：

- [[https://medium.com/@teivah/the-top-10-most-common-mistakes-ive-seen-in-go-projects-4b79d4f6cd65][The Top 10 Most Common Mistakes I’ve Seen in Go Projects]]
- [[https://medium.com/@teivah/the-top-10-most-common-mistakes-ive-seen-in-go-projects-4b79d4f6cd65][Allocation efficiency in high-performance Go services]]
- [[https://go101.org/article/value-copy-cost.html][Go Value Copy Costs]]

** 2019-07-16 22:05

iterm2 Emacs 快捷键经常打印出特殊符号，比如 =M-b= 会输出 =∫= ，解决办法是：

=Preferences -> Profiles -> Keys -> Left Key/Right Key= 改成 =Esc+=。

** 2019-07-15 17:55

依旧做个 Rocker

** 2019-07-15 09:15

我倒下后，不敢回头

** 2019-07-12 09:48

101 Tips For Being A Great Programmer (& Human): https://dev.to/emmawedekind/101-tips-for-being-a-great-programmer-human-36nl

TODO: 简单翻译一下


** 2019-07-12 09:41

https://microblog-1252349778.cos.ap-shanghai.myqcloud.com/2019/networking-tools-poster.png

via Every Linux networking tool I know

** 2019-07-09 10:07

世界上有两种程序员，一种是用百度的，一种是用谷歌的

** 2019-07-09 09:29

今天走过最难走的路是天目山路。

** 2019-07-04 09:20

昨晚试了一下 LUbuntu ，就使用方便上来讲，都是不如 gnome 的，Ubuntu 是不打算再折腾了，后面有笔记本了，玩玩 debian ，fedroa，archlinux 之类的

** 2019-07-02 23:28

- qwerty 把所有的 API 都改成了 RESTful 方式（当然本身就很少）
- 删掉了从 jekyll 导出的 API，这些应该集中到 tools 中来通过调用 server 的 API 来实现，职责要分清
- 买了一个 getqwerty.org 的域名

星期二，90min

** 2019-07-01 23:13

- 验证之前的把 Django 简单改造成一个 RESTful API framework 的方案可行
- qwerty-server API 改成 RESTful 风格，完成 20%

工作日晚上写代码不太行，时间太短了，一两个小时看看书还行，写代码刚进入状态就结束了，难受。

星期一，90min

** 2019-07-01 21:47

更好的使用 RESTful API 的 10 个最佳实践

1. Use nouns but no verbs => 使用名词，而不是动词
2. GET method and query parameters should not alter the state => GET 方法不应该修改资源状态
3. Use plural nouns => 使用复数（不要混用单数和复数，简单点全部用复数就行）
4. Use sub-resources for relations => 使用子资源进行关联
   #+BEGIN_SRC
   GET /cars/711/drivers/ Returns a list of drivers for car 711
   GET /cars/711/drivers/4 Returns driver #4 for car 711
   #+END_SRC
5. Use HTTP headers for serialization formats => 使用 HTTP 头部标示序列化格式
   Content-Type 定义请求格式，Accept 定义可接收的回包格式
6. Use HATEOAS
   Hypermedia as the Engine of Application State is a principle that hypertext links should be used to create a better navigation through the API.
7. Provide filtering, sorting, field selection and paging for collections => 为集合提供过滤、排序、分页和字段选择
8. Version your API => 为 API 设置版本
9. Handle Errors with HTTP status codes => 使用 HTTP 状态码处理错误
10. Allow overriding HTTP method => 允许覆写 HTTP 方法

来自：https://medium.com/@mwaysolutions/10-best-practices-for-better-restful-api-cbe81b06f291
