#+SETUPFILE: ~/site/tpl/weekly-tpl.org
#+TITLE: 2019-09


** 2019-09-22 11:44:41

装个 Windows 系统装成了 32 位了，难怪打个 Dota 各种调节分辨率还是那么卡。

** 2019-09-20 20:52:44

彻底不用云主机了，一个月节省了几十块钱，最主要的是不用再操心这些事情了，真的听烦的。

** 2019-09-20 20:49:47

慢慢去做，坚持去做，该学习学习，该打游戏打游戏。不想再刻意了。

** 2019-09-18 21:43:05

写了个脚本把 qwerty 里所有的文章都转成 org-mode，所以博客都迁移过来了，哈哈。Python 真牛逼啊。

btw，还是要花精力学 Python 啊，一直边查边写效率真的挺低的。

** 2019-09-17 14:21:31

腾讯云要到期了，不想续期了，尽快把博客迁移过来。

** 2019-09-16 17:49:31

我后来想明白了，事情是要做的，同事的利益也是要兼顾的。

** 2019-09-16 13:03:58

突然还挺喜欢谭维维的声音。

** 2019-09-16 11:12:51

跟老婆讨论买房子的事，起初觉得很麻烦，很难，过来了之后也就觉得没什么。

人一辈子就那么几件大事，买房、买车，结婚生子。

没经历的时候，觉得特麻烦。经历完之后就不会那么觉得了，一件大事了了之后就不用再想了，反而是放松。

以前感觉那些早结婚生娃的人，会很不幸福。但是看别人过的也挺好的。。

** 2019-09-12 11:21:11

你所了解的未必就是全部。

** 2019-09-11 22:39:48

这主题有点帅，

本想随便搞一个主题，怎奈按耐不住就随便写了写。

** 2019-09-10 17:38:40

#+begin_quote
Bad programmers worry about the code. Good programmers worry about data structures and their relationships.
#+end_quote

/via Linus Torvalds/

** 2019-09-10 12:31:23                                              :twitter:

东野圭吾《恶意》里面说：有些人的恨是没有原因的，他们平庸、没有天分、碌碌无为，于是你的优秀、你的天赋、你的善良和幸福都是原罪。有种恶意不需要理由，而且可以深刻到赔上自己以致对方于死地。

/via Zannmuling/

** 2019-09-03 19:44

~(org-publish "project-name" t)~ 清发布缓存

** 2019-09-02 10:29

准备开始用 Emacs org-mode。

每一次做选择总是好奇心和惰性之间徘徊，一方面觉得这个挺好，另外一方面觉得，没了它好像也挺好。

以前总是考虑短期内的收益，后面做决定要长期收益比重要增加。毕竟人生的路还很长呢。

** 2019-09-02 10:15

九月了，该努力了。
