#+SETUPFILE: ~/site/tpl/weekly-tpl.org
#+TITLE: 2019-10 ~ 2019-12

* 2020-01-01 11:08:56

Bye 2019.

* 2019-12-29 10:33:29

工作日认真工作，回家看看书。周末拓展视野，总结总结，这样也挺好。
不然压迫感太强了。

* 2019-12-23 14:16:21

总是很容易跟别人起争执，这样不好。

* 2019-12-29 12:06

#+BEGIN_QUOTE
人们总是把慢和快对立起来，似乎慢生活就要扔掉手机，辞退工作，满世界寻找自己……

其实慢很容易。读一本书，安静的看一场电影，写一篇不追求阅读量的文章，写一份能被对方收藏的邮件，看窗外的风景，走在落叶纷飞的大地……

这就是慢生活，但不妨碍你随时起飞。
#+END_QUOTE

via [[https://twitter.com/sagacity/status/1208780758652833795][@池建强]]

* 2019-12-20 14:11:15

昨天突然想起来很早以前博客的副标题：

#+BEGIN_QUOTE
make it run, make it right, make it better.
#+END_QUOTE

我一开始理解的本意是：避免做完美主义，先把事情做出来，然后一步一步的优化。

昨天觉得，也可以通过这句话把人划分成三类：

- 现实中能独立把事情做出来的人，已经不是多数；
- 能把事情做出来的人，就少了一点了；
- 能够做好的人，则少之又少，至少我从业几年中遇到的也没几个。

* 2019-12-19 16:18:02

认真做事的两个条件：

1. 有产出
2. 自己非常喜欢

自己喜欢做的事情，同时也有产出的话，那是最好的；自己喜欢的事情，可能产出少，但至少自己是开心的；
不喜欢做但是不得已做的，产品很明显的，至少付出了会有收获；又不想做，又没产出的的，就没有做的意义了；
也就是说，两个条件至少要占一个。

* 2019-12-03

祝自己生日快乐。

* 2019-12-01 14:33:25

看到了 StateOfJS 之后，我在想别的技术是不是也有类似的统计分析。后来发现确实是有的，只要谷歌搜索： =xx in years= 即可，比如： =Go in 2018= =Python in 2018= 就可以看到该年份相关统计数据。

现在才知道，我是不是孤陋寡闻了？

* 2019-11-12 23:07:17
每次做决定都要找最当前的最优解，不用考虑的过于长远。可实施性才是最重要的。
* 2019-11-12 14:09:27
再折腾一次 Pro ，感觉对前端技术理解又加深了一点，有点膨胀，哈哈。
* 2019-11-11 10:34:37

最近目标有点混乱，今天整理一下。目标首先要聚焦于当前最重要的事情，短长期的可先不考虑。

* 2019-10-21 14:40:19

这么多年的过去了，我到今年才逐步的意识到：原来人的一生只能做好几件事情。

做技术也差不太多，哪有什么真正意义上的全栈，能做好一个方向就已经很厉害了，而且往往混的好的都是在一两个方向上坚持下去的人。

这个道理真是后知后觉，要是前三四年我能明白这个道理该有多好。

* 2019-10-10 17:04:02

有一部分人看待问题永远是批判的眼光看的，提出自己的「真知灼见」，然后洋洋得意，觉得自己多么了不起。

我以前也是这样的人，还好我及时刹住车了。
